### ISSUE TITLE
Why don't you know the Chinese developers cannot visit amazon servers? So we cannot download git

### ISSUE THREAD

**Issue by leotsai** [git-for-windows/git#1010]

**Comment by PhilipOakley** [comment]
> Why don't you know the Chinese developers cannot visit amazon servers? So we cannot download git (#1010)

Hi Leo,

Is this for the installer, the Portable Git, or the SDK?

I don't believe it was in any way deliberate. The AWS is a widely available service, so is a convenient host. 

I wasn't aware, specifically, that the AWS GfW uses was not accessible in China, do you have a suitable suggestion for a host?

How accessible is GitHub? (Capacity limits and serving binaries also to be considered)

If there is a suitable hosting service then (in a catch 22 way) a patch to (the github code) offer an alternate host would be welcome.

--
Philip
(contributor, rather than developer)

**Comment by dscho** [comment]
@leotsai. It would be good of you to present options how to improve the situation.

**Comment by leotsai** [comment]
This is the download link:
https://github.com/git-for-windows/git/releases/download/v2.11.0.windows.1/Git-2.11.0-64-bit.exe

It reredirects to an amazon server.

You can put part of your resources on a Chinese server, i.e. https://www.aliyun.com

In China, all kinds of sub-domains of AWS are prohibited by GFW.

**Comment by Jimmy-Z** [comment]
As a programmer in China, I can confirm that link works, anway I can understand why you need that mirror though, it's extremely slow.

But very site without a CDN in China suffer from the same problem. Do you really expect all foreign resources you need to provide a Chinese mirror?

**Comment by hkdennis2k** [comment]
I believe you've report the issue to a wrong project.

You should report the problem to the great-firewall project.

I really don't think the git-for-windows project have enough funding and resource to setup many mirrors around the globe.

**Comment by dscho** [comment]
> If there is a suitable hosting service then (in a catch 22 way) a patch to (the github code) offer an alternate host would be welcome.

This. If there it is made easy for me to upload the binaries to a site that is more accessible to mainland China, I will do it.

**Comment by Jimmy-Z** [comment]
This is some quick search results:
http://git.oschina.net/
http://www.hwclouds.com/en-us/devcloud/
These two are github like sites with English UI. the most popular github clone I've heard is coding.com, which doesn't support English.

For the record, I've never used any of them.

**Comment by NewBie1993** [comment]
I also came from China and I can confirm his statement is true. In fact, strictly speaking, the link is unstable. We all know why it is and it is not the responsibility of everyone here.

**Comment by leotsai** [comment]
Aliyun has an english version: https://intl.aliyun.com

**Comment by dscho** [comment]
@leotsai again, if you make it easy for me (so far, that has not been the case), I will upload future releases to a site that is more accessible from mainland China.

**Comment by leotsai** [comment]
Here is the Alibaba cloud CDN page(in English):
https://intl.aliyun.com/product/cdn

You can purchase one and upload future releases there. That would be much faster for Chinese users.

**Comment by leotsai** [comment]
github must be a targeted client of aliyun. Quote from aliyun cdn page.

> China CDN

> Due to its vast geographic size, population and lack of peering points, China can be a challenging market for overseas companies to deliver their online content. Variable load speeds, availability and sudden spikes in traffic are all major challenges to operating in China.

> With Alibaba Cloud’s 500 nodes in China you can dramatically minimize your website response time and manage potential spikes in traffic. As Alibaba Cloud maintains full control over its infrastructure in China we are also able to provide a one-stop CDN service without exposing your website and data to other parties.

> In order to access a China-based Content Delivery Network you will need to first apply for a Chinese ICP license. Alibaba Cloud provides a dedicated team of bilingual experts to help guide you through the ICP license application process. The Alibaba Cloud team successfully submits ICP applications on a daily basis and can flag problems early in advance or avoid delays in order to fast-track your application.

**Pay special attention to the last paragraph.  **
> Alibaba Cloud provides a dedicated team of bilingual experts to help guide you through the ICP license...

**Comment by Jimmy-Z** [comment]
Fire this issue to github then, you should understand it's not git-for-windows but github paying AWS for it's hosting service.

**Comment by liuge9466** [comment]
good




在 2016年12月30日，15:58，"Leo" <notifications@github.com<mailto:notifications@github.com>> 写道：


github must be a targeted client of aliyun. Quote from aliyun cdn page.

China CDN

Due to its vast geographic size, population and lack of peering points, China can be a challenging market for overseas companies to deliver their online content. Variable load speeds, availability and sudden spikes in traffic are all major challenges to operating in China.

With Alibaba Cloud’s 500 nodes in China you can dramatically minimize your website response time and manage potential spikes in traffic. As Alibaba Cloud maintains full control over its infrastructure in China we are also able to provide a one-stop CDN service without exposing your website and data to other parties.

In order to access a China-based Content Delivery Network you will need to first apply for a Chinese ICP license. Alibaba Cloud provides a dedicated team of bilingual experts to help guide you through the ICP license application process. The Alibaba Cloud team successfully submits ICP applications on a daily basis and can flag problems early in advance or avoid delays in order to fast-track your application.

**Pay special attention to the last paragraph. **

Alibaba Cloud provides a dedicated team of bilingual experts to help guide you through the ICP license...

**Comment by dscho** [comment]
> Here is the Alibaba cloud CDN page(in English):
https://intl.aliyun.com/product/cdn
>
> You can purchase one and upload future releases there. That would be much faster for Chinese users.

So let me clarify: you want to use a decade of work of others without paying even a red cent or contributing anything back, and then expect me to go through some license issues with bilingual experts and pay my own money to make that software available to you?

Let me think about that.

Okay, I thought about it and decided to decline.
