### ISSUE TITLE
Right click menu to add Git Pull Button

### ISSUE THREAD

**Issue by chinglinwen** [git-for-windows/git#1026]
- [*] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 1.9.5.msysgit.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Windows 7 64 bit
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601] 
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
_TODO_

Can't find the file, install with default option
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Right click within a git repo directory
```
 - What did you expect to occur after running these commands?

 Show a pull button

 - What actually happened instead?

 No pull button

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 it's general, not to a specific repository

 - Extra info

https://github.com/msysgit/msysgit/issues/267

**Comment by dscho** [comment]
> git version 1.9.5.msysgit.1

Please note that you are suffering *multiple* security problems: https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version

> Right click within a git repo directory

I assume you refer to right-clicking on a file in a worktree in Windows Explorer?

We only have a very rudimentary Explorer integration in Git for Windows. This is by design: for a couple of years, we tried to ship a more complete solution, but there was so little interest in contributing to the project that we had to drop it (remember: this is Open Source, if too many people volunteer requests and not enough people contribute patches, the project dies).

If you want a more complete Explorer integration, you will most likely be served better using either [TortoiseGit](https://tortoisegit.org/) or [Git Extensions](http://gitextensions.github.io/).

**Comment by chinglinwen** [comment]
Thank you for your note, so I installed "git version 2.11.0.windows.1"

> I assume you refer to right-clicking on a file in a worktree in Windows Explorer?

I think it doesn't need to right-clicking on a file, but click on any space (for a git repository directory) in Windows Explorer

Also I realized while I install "git version 2.11.0.windows.1", the "Git Branch" button is gone from the menu 

![git_issue](https://cloud.githubusercontent.com/assets/16344129/21791667/6c642558-d71f-11e6-9c2e-697cdb4d2c1b.png)

And thank you for your suggestion about "TortoiseGit and Git Extensions", I have take a look, I think I still favorite the simplicity of "git-for-windows", Great works.
