### ISSUE TITLE
parameters not correctly parsed

### ISSUE THREAD

**Issue by codingdave** [git-for-windows/git#1031]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64

```
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
Plink Path: C:\Program Files (x86)\PuTTY\plink.exe
SSH Option: Plink
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

MINGW64

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
```
git fetch --al
```
 - What did you expect to occur after running these commands?

```
$ git fetch --al
Unknown option: --al
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

 - What actually happened instead?
```
$ git fetch --al
Fetching origin
l
```

**Comment by codingdave** [comment]
It would be nice if git is able to detect wrong parameter input. Lets e.g. consider 

```
$ git commit --ammend
error: unknown option `ammend'
usage: git commit [<options>] [--] <pathspec>...
```
which is nice. **The trick may be to check for double hyphens (--)** because afaik after it (without spaces) only options can appear. Since the set of options is known it would be easy to check for a valid/invalid input.

A related problem is 
```
git commit -ammend
```
where I see the chance to check for a space after -am and the commit message "mend" (please see http://stackoverflow.com/questions/41287891/git-commit-amend-is-dangerous for details here). I can create an individual bug report for that if required.

**Comment by dscho** [comment]
Did you realize that `git fetch --al` is treated as if you typed `git fetch --all`?

The reason is that Git comes with logic *specifically* designed to detect unambiguously-abbreviated options. So this is a feature.

Please note that this is *not* a Windows-specific issue. A better place to report platform-independent bugs is [the Git mailing list](mailto:git@vger.kernel.org).

> A related problem is
> 
> git commit -ammend

Please note that

1) this is not a Windows-specific issue,
2) there are *two* problems: the missing `-` *and* the repeated "m"; if you had typed `git commit -amend`, Git would have errored out with "error: did you mean `--amend` (with two dashes ?)"

If you want to report this as a bug, please feel free to send a mail to [the Git mailing list](mailto:git@vger.kernel.org) (you may want to avoid simply sending a link, instead summarizing the issue and *also* mentioning the link, a bare link sending developers to StackOverflow may just get ignored).

**Comment by codingdave** [comment]
Thank you @dscho for this helpful clarification and suggestions.
