### ISSUE TITLE
git bash crash on fresh git install 

### ISSUE THREAD

**Issue by Magneticmagnum** [git-for-windows/git#1052]
When launching git with right-click menu "Git Bash Here", the git bash (minTTY) doesn't launch. Instead, a mintty.exe.stackdump file gets created with the following:

Exception: STATUS_ACCESS_VIOLATION at rip=001800BE66B
rax=000006FFFC9F9EF8 rbx=00000000000C9EE8 rcx=1FFFFFFFFFFD0000
rdx=FFFFFFFFFFE80000 rsi=000006FFFC6F9EF0 rdi=000006FFFC879EF0
r8 =0000000000180000 r9 =0000000000000000 r10=0000000100000000
r11=000000010040F5C4 r12=000000000000869F r13=000000000000869F
r14=0000000000010000 r15=0000000000000000
rbp=FFFFFFFFFFFF0000 rsp=00000000FFFFC568
program=C:\Program Files\Git\usr\bin\mintty.exe, pid 10176, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B

I have tried reinstall 32-bit and 64-bit windows.

There have been several users who had the same issues online, but their resolutions didn't solve my issue.

Windows 7, Git 2.11.1 package.

**Comment by dscho** [comment]
Could you verify that [Cygwin](https://cygwin.com/) and/or [MSYS2](https://msys2.github.io/) display the same issue?

**Comment by Magneticmagnum** [comment]
Cygwin and MSYS2 launch fine on my system.  

Running mintty.exe will still stackdump in whatever directory I try to launch it from.

**Comment by dscho** [comment]
Does it work if you select ConHost instead of MinTTY as the terminal backing Git Bash?

**Comment by GrosvenorGrowGe** [comment]
I meet this question (cannot fork ....)also. I tried almost all ways searched from google, but was not effective. My base information: Windows7 64bit, Pro, pack 1, git 2.12.0. install and uninstall many times (when uninstalling, I will delete Program Files\git  ProgramData\git )!
I have installed the lower version(such as 2.9) on OTHER 3 computers, they are all works OK. the current computer is newly installed OS, and I resize the C partition's size by using windows7's "disk manager tool-compress volume". I can only think of this different point from other's computers except for difference between their hardwares and driver softwares. Isn't would really the "compress volume" cause this question?
Today morning, I get the new git-scm release information, it says that resolve git bash “cannot fork...” question。But it‘s so regret that the question computer is now not here, otherwise , I can try new version
.  also, it not fit my question :(

**Comment by Magneticmagnum** [comment]
@dscho sorry, i totally missed your reply.  I'm currently using git 1.9.4 as a workaround, I'll let you know if ConHost still breaks when I can get around to installing git 2.6.x+

**Comment by dscho** [comment]
@GrosvenorGrowGe it is possible that the compress volume thing may have some adversary interaction with the MSYS2 runtime, which is the only thing I can think of as possible explanation in your case. The "fork bug fix" in 2.12.1 is unlikely to address your issue, it is a bug that happens when the Bash started successfully and *other* processes are spawned.

Maybe you can test whether plain [Cygwin](https://cygwin.com) works on your C: drive?

**Comment by dscho** [comment]
@Magneticmagnum please be advised that 1.9.4 has serious security issues. If it works for you, though, and you keep this as a working setup, we could close this ticket?

**Comment by Magneticmagnum** [comment]
Hmm, conhost doesn't seem to be working for me either, running it directly from 'C:\Windows\System32'

**Comment by dscho** [comment]
> Hmm, conhost doesn't seem to be working for me either, running it directly from 'C:\Windows\System32'

What I meant was: to configure Git Bash to use the ConHost instead of the MinTTY option in the Git for Windows installer.

Also, I just noticed that you ran this with v2.11.0. I did work on a couple of bugs in the MSYS2 runtime since that version, maybe the latest snapshot works for you? https://wingit.blob.core.windows.net/files/index.html

**Comment by jakehockey10** [comment]
@dscho I'm having the same problems with running git bash on my Windows 10 machine.  All the same symptoms as mentioned above.  I installed the latest snapshot and I still can't get git bash to run.

**Comment by dscho** [comment]
@jakehockey10 so, which Git for Windows version do you use? Did you try the ConHost option for Git Bash? Did you test the latest snapshot?

**Comment by jakehockey10** [comment]
The latest version of git for Windows from the official website as well as the latest snapshot that was available from the link you provided above. I did not try conhost.

**Comment by dscho** [comment]
> I did not try conhost.

Could you? This may help us find the root cause.

**Comment by themooserooster** [comment]
I'm on Win 10 x64 with version 2.13.2 and am experiencing pretty much the same thing. bash.exe and sh.exe hang up completely on install and it never completes. I can kill those process via task manager and get the install process to say its finished, but anything that touches either just hang up forever.

**Comment by dscho** [comment]
@themooserooster you could try running the installer again with the `/LOG` option and see whether it contains useful information.

**Comment by myk5000** [comment]
I give up, I'm using the windows console by itself. I can't have nice things...

**Comment by dscho** [comment]
> I can't have nice things...

... and I can't have the log? :smile:

**Comment by dscho** [comment]
There have been a ton of updates to the MSYS2 runtime (which is most likely responsible for those crash bugs; the installer hanging bug is unfortunately a distraction in this ticket which I want to ignore unless it is reported separately, with the log I asked for).

So I *hope* that things are better now? Could everybody who experienced that crash try v2.14.2(3)?

**Comment by luyaoguang** [comment]
where is address

**Comment by dscho** [comment]
> where is address

You mean where Git for Windows can be downloaded? Try Git for Windows' homepage: https://gitforwindows.org/

**Comment by dscho** [comment]
Hopefully one of the updates [I mentioned earlier (and which either have not been tested, or at least there was no feedback about them)](https://github.com/git-for-windows/git/issues/1052#issuecomment-336494432) fixed this.

**Comment by Pritep** [comment]
Creo que se cual es el error, es un archivo que falta en la carpeta de git/bin se llama "msys-2.0.dll"

**Comment by Pritep** [comment]
Esa es la solución ya lo probé . lo descargan y lo pegan en Git/bin

**Comment by dscho** [comment]
> Creo que se cual es el error, es un archivo que falta en la carpeta de git/bin se llama "msys-2.0.dll"
>
> Esa es la solución ya lo probé . lo descargan y lo pegan en Git/bin

I don't think that is the correct solution, as nothing in `Git/bin` is an MSYS2-dependent executable. Those are all in `Git/usr/bin`. The executables in `Git/bin` are variants of the ["Git wrapper"](https://github.com/git-for-windows/MINGW-packages/blob/main/mingw-w64-git/git-wrapper.c) whose only purpose is to set a couple of environment variables and then spawn the _actual_ program. For example, `Git/bin/bash.exe` will set `MSYSTEM` and `PATH` and spawn `Git/usr/bin/bash.exe`.

**Comment by Pritep** [comment]
pero yo mismo hice la prueba. si lo quitas no se ejecuta como debe... si lo colocas otra ves si va a ejecutar
haz la prueba para que veas

**Comment by dscho** [comment]
> haz la prueba para que veas

Well, it works here without copying `msys-2.0.dll` into `C:\Program Files\Git\bin`... Maybe there is an incompatible `msys-2.0.dll` in your `C:\Windows\system32`?
