### ISSUE TITLE
Git submodule allow (fix) adding of yet unitialized reposiotries

### ISSUE THREAD

**Issue by yatagarasu25** [git-for-windows/git#1059]
Here is the situation. We are using GitLab to host repositories (but I think the same applies to any repository scenario). So what I do. I create three empy repositories in gitlab, they are uninitilized and have no commits.
Let's call that root, submodule1, and submodule2.

After that I create empty local repository at my hard drive, set it's remote to repository 'root', than add two submodules to it using 'git submodule add git@ourserver:submodule1.git' and 'git submodule add git@ourserver:submodule2.git' commands. What happens, git complains that this repositories are empty and have no commits. That is ok.

Also git creates folders sumbodule1 and submodule2 with .git files in it and correctly set up remotes. And that is what I expect.

But what does not happen is this submodules does no appear in .gitmodules file, which I think i wrong, as the result they are not in submodule foreach list, and it is not possible to 'make first commits and initilize remote reps' by tools whic h rely on submodule list.

I tihink if git creates that folders and ,git files in them, than it should also update .gitmodules file and have that folders in foreach list, otherwise feature looks incomplete, and the whole state of repository seems to be broken after that.

**Comment by shiftkey** [comment]
Please resubmit this issue using the [Issue Template](https://github.com/git-for-windows/git/blob/master/.github/ISSUE_TEMPLATE.md). This form contains a lot of helpful information for us to help investigate and reproduce the issue.

**Comment by PhilipOakley** [comment]
Igor,

I think this report should go upstream to git@vger.kernel.org - their archive is at https://public-inbox.org/git/ there has been a lot of on-going sub-module development recently.

When copying upstream:

1. They only allow plain text emails - all HTML is classed as spam!

2. It may take up to 24hrs for the initial contribution to reach the list because of whitelisting delays.

2. Space out the text in your report so that the commands stand out as lines on their own, particulalrly if you can create a short script that can be run for the reader to test.

3. Add a concise summary of the _problem_ at the beginning. e.g. "Adding a remote submodule fails to add the submodule to the .gitsubmodules list".

regards

Philip

  ----- Original Message ----- 
  From: Igor Karatayev 
  To: git-for-windows/git 
  Cc: Subscribed 
  Sent: Monday, February 13, 2017 6:43 AM
  Subject: [git-for-windows/git] Git submodule allow (fix) adding of yet unitialized reposiotries (#1059)


  Here is the situation. We are using GitLab to host repositories (but I think the same applies to any repository scenario). So what I do. I create three empy repositories in gitlab, they are uninitilized and have no commits.
  Let's call that root, submodule1, and submodule2.

  After that I create empty local repository at my hard drive, set it's remote to repository 'root', than add two submodules to it using 'git submodule add git@ourserver:submodule1.git' and 'git submodule add git@ourserver:submodule2.git' commands. What happens, git complains that this repositories are empty and have no commits. That is ok.

  Also git creates folders sumbodule1 and submodule2 with .git files in it and correctly set up remotes. And that is what I expect.

  But what does not happen is this submodules does no appear in .gitmodules file, which I think i wrong, as the result they are not in submodule foreach list, and it is not possible to 'make first commits and initilize remote reps' by tools whic h rely on submodule list.

  I tihink if git creates that folders and ,git files in them, than it should also update .gitmodules file and have that folders in foreach list, otherwise feature looks incomplete, and the whole state of repository seems to be broken after that.
