### ISSUE TITLE
How can I get back Git Branch option in context menu ?

### ISSUE THREAD

**Issue by MrGrabazu** [git-for-windows/git#1085]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10, 64-bit
```
$ cmd.exe /c ver
Microsoft Windows [version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I've installed TortoiseGit 2.4.0.2

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

The one Git install, so mintty I guess.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
None, the feature is sadly missing.
```
 - What did you expect to occur after running these commands?

See all synchronized branches of the repository in a submenu and change in just one single click !

 - What actually happened instead?

Nothing, the feature is sadly missing.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It happend with all repositories

**Comment by fourpastmidnight** [comment]
The feature you are describing is not a feature of Git for Windows. That is a Tortoise Git feature. Please either repair or reinstall Tortoise Git. If you have further issues with the Explorer context menu missing items, you'll need to contact them.

The only Windows Explorer context menu items that are installed are "Git Bash Here" and "Git GUI Here". And these items, if selected for installation, only appear when you're in a Directory in Windows Explorer.

For any future issues with Git for Windows itself, please don't hesitate to open another issue.

**Comment by MrGrabazu** [comment]
On my last PC I had SourceTree instead of TortoiseGit and I had this menu item in my context menu.
And that item was explicitly separated from the TortoiseGit menu item, and when I try to configure the context menu in TortoiseGit I don't see this option, so I doubt that it's a TortoiseGit feature.

And to be sure I try to Repair, Uninstall, Reinstall TortoiseGit and there is not change...
I saw post of other people that facing the same issue and for some install an older version of Git (1.9.5 exactly) make it back in context menu, so once again I'm pretty sure that it's not a Tortoise feature...

So if you don't have the answer can you redirect me to peaple that can have it ? 

Thanks a lot.

**Comment by dscho** [comment]
> On my last PC I had SourceTree

Maybe "Git Branch" is a SourceTree option, then?

OTOH since you talk about Git for Windows 1.9.5, you may have opted for the Explorer extension called [Git Cheetah](https://github.com/msysgit/Git-Cheetah) which was abandoned when switching to Git for Windows 2.x.

**Comment by fourpastmidnight** [comment]
Oh, yeah, that's definitely not from Atlassian SourceTree, so I agree with dscho, since you referenced Git for Windows 1.9.5, you must be referring to Git Cheetah which is no longer distributed with Git for Windows.

**Comment by johne53** [comment]
I know this issue is closed so sorry for re-opening.

Yesterday I spent about an hour trying to find out about Git Cheetah. I found plenty of instructions for adding it - but I couldn't find a description of what it actually does!! However, if this WAS provided by Git Cheetah, it was an incredibly useful option. I'd like to add my name as someone who'd like to see it return.

Basically it was just a simplified version of Git Switch/Checkout (without the option to check anything out). Let's say I already had 3 branches checked out. The 'Git Branch' menu item allowed me to switch between them very easily - without needing to wade through maybe dozens of other branches each time.

**Comment by dscho** [comment]
@johne53 all it takes for Git Cheetah (which was intended to be a light-weight, portable alternative to TortoiseGit) is to take maintainership of it.

**Comment by johne53** [comment]
Hmmm... I wonder if I've been misinformed? The basic story here is that I recently updated TortoiseGit and I was disappointed to realise that "Git Branch" is no longer present in its popup menu (i.e. the Explorer menu). Over at TortoiseGit they told me it had never been a part of TGit but in fact, it was provided by the underlying MsysGit (which has now been dropped, in favour of Git for Windows). But when I dug a bit deeper, I got told that although it was bundled with MsysGit it was in fact a 3rd party utility called "Git Cheetah".

It seems like nobody really knows who (or what) provided Git Branch but it's a BIG loss - it was an incredibly useful feature... :-(

**Comment by MrGrabazu** [comment]
I couldn't be more agreed with that ! It's a huge loss for me too, now when I need to switch from a branch to another I must go deeper in the contextual menu to click on Switch/Checkout and find my branch in the middle of thousand other branches (locales and remotes...) in the dropdown list...

**Comment by dscho** [comment]
[Git Cheetah](https://github.com/msysgit/Git-Cheetah) was started by me, and it was set up as a separate project from Git for Windows (which BTW is *not* msysGit; y'all are constantly referring to the development environment to develop Git for Windows, when you mean Git for Windows instead). The reason was that I wanted it to work also in macOS' Finder and in Linux various file managers.

Alas, the interest was low in it, and contributions were scarce and hard to get by.

As I had been increasingly busy with Git for Windows, I could not maintain it any longer, and since nobody stepped up, I had to abandon the project called "Git Cheetah".

Now, y'all can want features all you want, but that does not change one *simple* fact: *somebody* has to do the  work. Seeing as y'all are comfortable with not doing said work, it simply won't get done.

If, on the other hand, you step up to the Open Source deal (you get stuff for free, but you make sure you contribute back by improving it in lieu of paying money), you can get what you want. Either by contributing the "Git Branch" item to TortoiseGit or by maintaining Git Cheetah, the choice is yours.
