### ISSUE TITLE
Why git-for-windows/git is forked from msysgit/git? Not git/git?

### ISSUE THREAD

**Issue by TurnOffNOD** [git-for-windows/git#112]
the title is al I want to say. Just curious.

**Comment by nalla** [comment]
Thanks to `git remote`s thats not an issue. so this is not an issue and can be closed.

**Comment by sschuberth** [comment]
That's because `msysgit/git` already contains all the Windows-specific patches on top of `git/git` that we need. In other words, the old MSYS1-based "msysgit" and the new MSYS2-based "Git for Windows SDK" use pretty much the same Git source code. It's "just" the Unix-like environment that has changed.

**Comment by TurnOffNOD** [comment]
@nalla ,sorry for that. But I didn't find "tag" button when I post the topic. Otherwise I would tag it as "discussion" and that would be nice

**Comment by sschuberth** [comment]
@TurnOffNOD As a closing note, the is an *issue* tracker, not a question tracker (as already stated several times as part of other "issues"). Questions and discussions should be directed to the [mailing list](http://groups.google.com/group/git-for-windows) instead.
