### ISSUE TITLE
Include debug build versions of executables in release artifacts

### ISSUE THREAD

**Issue by flcdrg** [git-for-windows/git#1122]
I think it would be helpful when trying to diagnose crashes to have debug build versions of git.exe (etc) optionally available for download.

Rather than requiring an end-user to pull down and compile the project themselves just to get a useful stack trace for a crash, they could grab the debug build and use that to reproduce and more clearly report the problem.

Also providing optional pdb symbols in a separate zip could also be helpful even for the release builds.

**Comment by dscho** [comment]
This sounds very good in theory!

In practice, it amounts to a ton of work, not to mention a very real maintenance burden. For one: did you know that you cannot generate `.pdb` files using GCC? And that is what Git for Windows uses. Compiling Git for Windows with GCC's debug option won't help you much, either: the crashdumps won't pick up DWARF symbols.

So I am not sure that you understand what size of a project you just tried to dump into my lap...

**Comment by flcdrg** [comment]
Yes you are completely right that I didn't understand the implications of what I was suggesting.

**Comment by dscho** [comment]
> Yes you are completely right that I didn't understand the implications of what I was suggesting.

It may be possible to use the `cv2pdb` executable (available in Git for Windows' SDK via the `mingw-w64-x86_64-cv2pdb` and the `mingw-w64-i686-cv2pdb` packages) instead of `strip.exe` when [building the `mingw-w64-git` package](https://github.com/git-for-windows/MINGW-packages/blob/9a26a674eaea46c333185e45814be5370946d355/mingw-w64-git/PKGBUILD#L159-L162).

Sadly, I lack the time to do this myself. @flcdrg do you have time?
