### ISSUE TITLE
Question: How to make `core.ignorecase` false by default after clone?

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#1138]
By default after cloning, `core.ignorecase` is set to `true`. Is there a way I can make clones default this setting to `false` by default, or leave it unspecified at the repository config level, and allow the global setting to determine the config value?

**Comment by tboegi** [comment]
The anser(s) is No, No.
For each repository core.ignorecase is probed and the config is set to true under
Windows.
Why do you want to set it differently ?

**Comment by dscho** [comment]
Please do not use this bug tracker for questions how to use Git. Thanks.

**Comment by rcdailey** [comment]
@dscho Where is the discussion board/ML for Git for Windows?

**Comment by rcdailey** [comment]
@tboegi Because people clone the repositories on Linux, which is case sensitive. Sometimes the case of directories matters for the other platforms. I think given this fact, it's more disruptive for Git to ignore case by default. So having the ability to override the default when cloning makes sense as a user choice.

**Comment by shiftkey** [comment]
@rcdailey 

> Where is the discussion board/ML for Git for Windows?

It's accessible from the [home page](https://git-for-windows.github.io/): http://groups.google.com/group/git-for-windows

**Comment by tboegi** [comment]
Could you give an example?
Windows will treat dir1/File1 and DIR1/File2 as if they are in the same directory.
Having dir1/File2 on disk but DIR1/File2 in the index is OK under the Windows file system.
And because Git needs to know this (If I expect DIR1/File2, but find dir1/File2, this is OK)
Under Linux 2 different directories are created, regardless how core.ignorecase is set.
If you want to have them in one directory, make up your mind and run
git mv DIR1/File2 Dir1/File2 && git commit -m "mv DIR1/File2 Dir1/File2"
This can be done both under Windows or Linux.

**Comment by landstander668** [comment]
@rcdailey While this doesn't actually make it the default, it's fairly simple to get your desired behaviour using an alias. Here's a minimal example:

    git config --global alias.foo '!git clone "$1" && cd "$( basename "$1" .git )" && git config --local core.ignorecase false'

In this scenario, you'd simply run `git foo ...` instead the usual `git clone` command.
