### ISSUE TITLE
the alias feature extention idea

### ISSUE THREAD

**Issue by ranistar** [git-for-windows/git#1156]
I know i can alias commands in git,but my branch name has some constant prefix,so can i alias this prefix?

just like this:branch name : `bugfix_0000_00000000`

i want to alias the "bugfix_0000" into "bug". so i can checkout this branch by git checkout bug_00000000.

here is what i tried:

alias "bugfix_0000" into "bug",but not work for me.
i also had alias "git checkout" to "gck", butgck bug_00000000 is not work.

**Comment by kostix** [comment]
Git aliases do not work like this.

In its simple form they create a git "command" which is expanded into a list which is then taken to mean another Git command, like:

    $ git config --add alias.see 'log --graph --oneline --decorate'

would allow you to run

    $ git see HEAD ^master

and have it expanded into

    $ git log --graph --oneline --decorate HEAD ^master

To achieve what you're after you have two options:

* Try the second form of Git aliases which calls into a shell:

         git config --add alias.foo '!some_shell_script'

     would call `some_shell_script` passing it all the arguments specified, so you can do any pre-processing of those arguments you need and then call out to actual `git`.

* Instead of aliasing, write a (shell or whatever) script or a shell function to create an "external command" which would, again, call out to actual `git` program after properly cooking the list of arguments for it.

In either case, this question is out of scope of the Git project itself — it's about general programming.

**Comment by dscho** [comment]
Please note that the Git *for Windows* project is already shorthanded as it is, and therefore it would be better to direct questions, especially when they are of a general nature, not specific to Windows at all, to [the Git mailing list](mailto:git@vger.kernel.org) instead of this bug tracker. Thanks.
