### ISSUE TITLE
Shouldn't cherry-pick (and rebase) stick to its definition even when there is conflict?

### ISSUE THREAD

**Issue by johnx7271** [git-for-windows/git#1159]
Cherry-Pick definition: "Given one or more existing commits, apply the change each one introduces, recording a new commit for each".

However, from what I observed, this will not be the case when conflict happens. Instead, when conflict happens, Git's behavior is more like a merge, but I don't like that. Someone explained: when conflict happens, git will have difficulty to figure out the patch context, so it will behave like a merge.

The reason that I request this behaviors change for is, suppose I made a small bug fix on one branch, now I want to apply the delta  to another branch, which has deviated significantly, if I use cherry-pick, git will output a merged file, which is not desired, what I want is simply to apply the delta, if the context can not be be accurately determined, that's fine, just make a rough guess. If it were done this way, then the changes in the merged file is minimal, so I can more easily make manual adjustment of the context for the delta.

Perhaps, one can add a option to git, which can change the behaviors to the one I described above.

The same also apply to rebase.

**Comment by shiftkey** [comment]
Please submit your question to the [Git Mailing List](https://git.wiki.kernel.org/index.php/GitCommunity), unless you have encountered an issue that is specific only to Windows.

**Comment by PhilipOakley** [comment]
As an aside, there is a terminology and expectation issue here as well. 

When the docs say "apply the change" it means, essentially, that a patch or diff for the given commit is created (which is what is being cherry-picked), and that patch/diff is then applied to the local branch, which **is** a merge (of that patch).

Most of this comes out of the expectations from the Linux patch update workflow, which Git was designed (primarily) to support.

It is easy to be caught out by these slippery phrases when they have separate common or garden meanings as well.

**Comment by YueLinHo** [comment]
> if the context can not be be accurately determined, that's fine, just make a rough guess. If it were done this way, then the changes in the merged file is minimal, so I can more easily make manual adjustment of the context for the delta.

@johnx7271 Perhaps try the option `-X theirs`:
```
git cherry-pick <commit_sha-1> -X theirs
```

**Comment by PhilipOakley** [comment]
@johnx7271 Would you like to expand a bit more on what you think might be different because, as far as I can tell, what you want is what Git provides. It does do:

> is simply to apply the delta, if the context can not be accurately determined, that's fine, just make a rough [best] guess

In Git's case it marks the points where the guess has to be made.

If the `-X theirs` option is used you get _no indication_ that there was ever a problem, which then goes against your

> so I can more easily make manual adjustment of the context for the delta.

In all these cases the computer has to stop, point at the problem, and get the real human to provide the background knowledge, context and intelligence (that's us) to choose the appropriate resolution. 

Maybe you would like a different way of marking the conflict?

[Aside: maybe it should resolve using `-X theirs`, but at the same time leaves the regular conflict markers so that you can simply delete the old context/conflict markings if the `-X theirs` is acceptable. And for a rebase sequence it would pause for confirmation]
