### ISSUE TITLE
Post official Docker Image

### ISSUE THREAD

**Issue by computeronix** [git-for-windows/git#1163]
Feature Request:
Post an official docker image for Windows nano and core on the docker store
Here is the docker build files and a sample here
Store Sample:
https://store.docker.com/community/images/computeronix/mingit

Git Hub Dockerfiles:
https://github.com/computeronix/docker-mingit

Again just samples for reference

**Comment by shiftkey** [comment]
@computeronix is this something that needs to be done by the core team, or can anyone do it? I see you seem to have the bits already setup, I'm just wondering what gaps there are...

**Comment by computeronix** [comment]
Anyone can create a repo but to create an official repo and get that presence the following would need to happen.

-create free docker account (https://cloud.docker.com)
-setup organization on docker
-invite xxx members to org whom can manage
-publish to store (https://store.docker.com and click publish)

As far as I am aware it's all free to do the above.

Sample official store: https://store.docker.com/images/gitlab-community-edition?tab=description

Plenty of other sample official images in the store.

From there, just add a dockerfile to a location in the official git for Windows repo

(The dockerfile I have has a static version but can easily be changed with powershell to pull a version dynamically depending on requirements).

For the user community then they can reference the official image and build off of it for their own container or they could look at the dockerfiles and utilize the code to further expand their own build image.

I think that's everything :). Let me know if you have any questions

Thank you,

Bill

Sent from my iPhone

On May 12, 2017, at 1:12 AM, Brendan Forster <notifications@github.com<mailto:notifications@github.com>> wrote:


@computeronix<https://github.com/computeronix> is this something that needs to be done by the core team, or can anyone do it? I see you seem to have the bits already setup, I'm just wondering what gaps there are...

**Comment by shiftkey** [comment]
@computeronix and what's the use case for Git being on the store for consumers? Are people building Git things into their Docker images?

**Comment by computeronix** [comment]
Correct and here are a couple examples

Looks like a couple cases open around containers:
https://github.com/git-for-windows/git/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20docker

Also an example of using fit within windows container
https://github.com/Storj/storjshare-daemon/blob/master/dockerfiles/storjshare-daemon-win.dockerfile

Again these are Windows examples since this is git for Windows :). But same concepts in Linux too.

Thank you,

Bill

Sent from my iPhone

On May 12, 2017, at 1:58 AM, Brendan Forster <notifications@github.com<mailto:notifications@github.com>> wrote:


@computeronix<https://github.com/computeronix> and what's the use case for Git being on the store for consumers? Are people building Git things into their Docker images?

**Comment by computeronix** [comment]
FYI updates the code to automatically retrieve the latest git for windows release when you build a docker with mingit

https://github.com/computeronix/docker-mingit

**Comment by dscho** [comment]
Thank you!

Contrary to common belief, Git for Windows does not have a large team running it, it relies very much on volunteers such as yourself.

And often, innocuous feature requests turn out to place a rather large burden on me, the maintainer, as they never stop with simply implementing one thing and be done with it.

In this instance, I would like to point you to this ticket: https://github.com/git-for-windows/git/issues/1007

As you see, it is very relevant to your feature request: if I put in the effort of publishing the Docker image you requested, and put in even more effort to automate the process so that it is properly updated every time a new Git for Windows version is released, you will probably agree that the problem with volume mapping becomes a much larger problem, as all of a sudden the Docker image would get a more "official" blessing, and every user would expect me to fix the bugs...

Therefore my preference would be to keep the setup as-is, possibly changing my [release script](https://github.com/git-for-windows/build-extra/blob/295bb2a7a5afc4222701ccb72e5417be8a1b656d/please.sh#L2423-L2575) to send an automated notification to you, if that helps you.

**Comment by dscho** [comment]
I'll close this until the time when Git for Windows has enough contributors to do this. It's easy to reopen the ticket then.
