### ISSUE TITLE
When use "git cat-file blob t/feature1:.topdeps" from bash, "fatal: Not a valid object name t\feature1;.topdeps" will display.

### ISSUE THREAD

**Issue by quyanwei** [git-for-windows/git#1171]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
32-bit
```
$ git --version --build-options

** insert your machine's response here **
$ git --version --build-options
git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
Microsoft Windows [版本 10.0.14393]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

PortableGit-2.13.0-32-bit.7z
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **
My windows 10 is Simplified Chinese version

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
I use cmder 160206, run Git from bash mode.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
git cat-file blob t/feature1:.topdeps

 - What did you expect to occur after running these commands?

** insert here **
master

 - What actually happened instead?

** insert here **
fatal: Not a valid object name t\feature1;.topdeps

I think the object name should not be changed to t\feature1;.topdeps
I don't know whether the object name is changed from t/feature1:.topdeps to t\feature1;.topdeps.

When I use the same command from windows cmd, there is no problem.
When I use the same command under linux, there is no problem.

When I use the following command:
git cat-file blob t/feature1:README
the file content is displayed. There is no problem.


 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
This is covered in our [Known Issues](https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues) (that you probably read diligently in every new Release Notes, right? :smile: ).

In particular, it says:

* If you specify command-line options starting with a slash, POSIX-to-Windows path conversion will kick in converting e.g. "`/usr/bin/bash.exe`" to "`C:\Program Files\Git\usr\bin\bash.exe`". When that is not desired -- e.g. "`--upload-pack=/opt/git/bin/git-upload-pack`" or "`-L/regex/`" -- you need to set the environment variable `MSYS_NO_PATHCONV` temporarily, like so:

  > `MSYS_NO_PATHCONV=1 git blame -L/pathconv/ msys2_path_conv.cc`

(The problem here is that MSYS2 has no chance to determine that your command-line argument does *not* refer to a path list a la `PATH`.)

**Comment by quyanwei** [comment]
Thank you very much!
