### ISSUE TITLE
64-bit git-bash forking error - multiple Git for Windows versions

### ISSUE THREAD

**Issue by rprastein** [git-for-windows/git#1200]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.0.windows.1
built from commit: eba7af3dbb4c846c6303c5f64102acee696c9ab0
sizeof-long: 4
machine: x86_64

but also versions 2.10.0.windows.1, 2.7.1.2, and 2.6.4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]

64-bit Windows 7 Enterprise
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

but I also tried with symlinks, credential manager and fs cache enabled or disabled, and with the Windows terminal option.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I started out with Git for Windows 2.7.1.2 and a year-old copy of SmartGit 7.1.2 (a 32-bit application which had a portable installation of Git for Windows 2.6.4 bundled with it), they worked together nicely for a year.  The trouble began yesterday, after I uninstalled SmartGit 7.1.2 and installed version 17.0.4 (which includes Git for Windows Portable version 2.10.0.1).  My "External Tool" which called my installation of git-bash 2.7.1.2 from within SmartGit broke first, while calling it from the Start Menu was fine.  Thinking perhaps I needed to reboot to complete the installation, I did so - whereupon git-bash called from the Start Menu also failed, as did double-clicking it within Windows Explorer.  

Interestingly, the 32-bit portable instance of git-bash 2.10.0.1 included with SmartGit works just fine.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Start | All Programs | Git | Git Bash
also, double-click on C:\Program Files\Git\git-bash.exe
also, within SmartGit, ${gitDir}\git-bash.exe --cd=${filePath}
```
 - What did you expect to occur after running these commands?

Bash shell terminal window to open in my home directory, without error messages.  Initial window title is "/usr/bin/bash --login -i".  Then it changes to "MINGW64:<homedir>" and I see a bash prompt consisting of 
username@hostname MINGW64 ~
$

 - What actually happened instead?

Terminal window opens still showing "/usr/bin/bash --login -i" in the window title, with the message:
`Failed to fork child process: Resource temporarily not available.  DLL rebasing may be required.`
Sometimes, there is a second command window open behind it, that says:
`1729188 [main] mintty 8800 fork: child -1 - forked process 11028 died unexpectedly, retry 0, exit code 0xC0000005, errno 11`
The process numbers vary, but the exit code and errno are always the same.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I don't even get to the point of specifying a repository.

Additional information:
I spent a day and a half uninstalling and re-installing different versions, including installed vs portable and including 64-bit vs 32-bit.  I determined that the problem only occurs with 64-bit builds, including the one that always worked fine before.  I also noticed the post-install.bat file that is run by the portable exe file after file extraction.  It tests for the presence of MINGW32 before doing a rebase of the code.  After all I had read on Stack Exchange and elsewhere (I am not building anything here and I am not a linux geek, most of what they said was somewhat over my head) and references to rebasing issues in the past, I edited post-install.bat to check for MINGW64 instead of MINGW32 and ran it in my 64-bit installation directory, and Poof!  it works now.  

So, I don't know whether the SmartGit installation did anything, or whether something else in my Windows environment changed, but it seems to me that post-install.bat needs to run the rebasing on 64-bit OS even if it's a 64-bit build that is being installed.  This worked for both the portable and the installed versions.

**Comment by elieux** [comment]
The rebase process is messy and takes time while the 64-bit version is less likely to be affected by these DLL conflicts, so that's IMO why it's disabled.

Maybe there needs to be a way to invoke a rebase on demand (taking into account that the DLL landscape on a machine may change during the lifetime of an installation).

**Comment by dscho** [comment]
As this problem is most prevalent with 32-bit installations, there is some documentation in https://github.com/git-for-windows/git/wiki/32-bit-issues. Maybe it can assist you to resolve this issue, most likely this section: https://github.com/git-for-windows/git/wiki/32-bit-issues#adjusting-msys-20dlls-address-range-manually ?

**Comment by rprastein** [comment]
Thank you, dscho, that link nicely summarizes things.  It also makes more sense now that I've done all of the other reading and experimenting.   :-)  I particularly like the boil-down of how to do the rebase manually, as an end user.  

My only comment at this point is that this statement on that page, though perhaps mostly true, is not true enough for me and may not be true enough for someone else: 
`The address range available in 64-bit Windows is so large as to virtually guarantee that the address range of the MSYS2 runtime never has to be adjusted. This is by far the easiest solution, now that Git for Windows 2.x offers a 64-bit version.`

Likewise, because of that assumption on the part of the installer package that 64-bit Git for Windows doesn't need any help, this is also not true for me:
`reinstalling Git for Windows will typically fix the problem because it adjusts the address range preemptively.`

I would like to see the pre-emptive address range adjustment for 64-bit as well as 32-bit.  That would be very easy to implement.  I'm quite willing to save off my settings if needed and then re-install, should the need occur in the future and I've lost my reference to how to adjust it manually.

Having an on-demand rebase command as elieux suggests would be cool, too.

Thanks,

Rebeccah

**Comment by dscho** [comment]
> Having an on-demand rebase command as elieux suggests would be cool, too.

How cool would it be to take the lead in this and drive it to completion? 😉

**Comment by dscho** [comment]
I'll just close this. Every time I see this ticket, it makes me sad, and seeing @rcdailey's thumbs-down on my suggestion to do the adult thing and take one's fate into one's own hand is even more discouraging: such reactions are what make me question whether it is worth it to maintain open source projects ("You already worked your butt off for me, why do you ask me to contribute anything at all instead of working your butt off for me even harder?"). Of course, I can remind myself that it is only 0.01% of the users who do this, but still, it is pretty disappointing, every single time.

**Comment by rcdailey** [comment]
New year, same old garbage attitude. As usual, your rudeness, sarcasm, and utter disrespect do nothing to encourage people to spend their free time to do work for you. Your narrow view of contribution (anything other than a PR) is harmful to the community as a whole.

At least it's easy to know when to not read your responses. The only time I see you put in an effort is when you type an unnecessarily long response to my comments. Can't say I feel encouraged to even look at your github page anymore, because I know exactly how you will respond.

Happy new year!

**Comment by dscho** [comment]
For the record, I blocked @rcdailey because I consider his message abusive and a violation of our code of conduct.

I promise to try my best at keeping an open mind if anybody wants to defend their behavior and make a case for unblocking them again.

Likewise, if anybody wants to comment (in a polite and decent manner) on my comment where I offered my frustration about the conduct (or lack thereof) of some users, I will do my very best to learn from it instead of getting defensive.
