### ISSUE TITLE
add SHA256 algorithm for some exe file

### ISSUE THREAD

**Issue by wbsdty331** [git-for-windows/git#1205]
It looks like some of exe file only have sha1 algorithm for code signing
For Security Reason,Please add sha256 algorithm.

Thanks.

**Comment by dscho** [comment]
Details, please. Git version. The exact `.exe` files. At least one. This is really frustrating so far.

BTW I doubt that I can even do anything about this, as I no longer have a valid SHA-1 code-signing certificate. Therefore, if your statement is correct, it is about `.exe` files that I did not sign myself.

**Comment by wbsdty331** [comment]
I'll check it.

**Comment by dscho** [comment]
> I'll check it.

Please do.

**Comment by wbsdty331** [comment]
Sorry For the late reply.
All of `usr\bin` exe file is not signed.

**Comment by dscho** [comment]
> All of usr\bin exe file is not signed.

That is totally different from the original claim that the `.exe` files are SHA-1 signed.

And the `usr\bin` files are unsigned because the developers who packaged those files chose not to code-sign them (or they do not have access to a valid code-signing certificate).

It would be improper for me to code-sign them because I did not build them.

Therefore, this is intentional.
