### ISSUE TITLE
126 zero sized files in the mingw32\libexec\libcore directory of the Git-2.13.2-32-bit.tar.bz2

### ISSUE THREAD

**Issue by tdkuehnel** [git-for-windows/git#1232]
looking for a git for windows version running on an old win xp sp2 machine i worked my way through several archives:

Git-2.8.4-32-bit.tar.bz2
Git-2.10.0-32-bit.tar.bz2
Git-2.13.2-32-bit.tar.bz2

because all the newer installers i have tested require sp3.

Around the 2.8.4 version there are only 16 many zero sized files in the libexec\libcore directory, so unpacking and running git via the git-bash works well for invoking git for help and maybe other simple commands, but when cloning or initializing a new repo strange "fatal: unable to launch xyz-abc" errors occur.

I nailed it down with copying over the zero sized files in the libcore dir with sized ones found around in the other /bin /cmd or whatever directories, so this looks like symbolic links not properly resolved during packaging. 

As in the actual version (2.13.2), the number of files have grown to actually 126 i thought its time to mention it here before things grow out of hands :)

Thanks for the great work, with this small issue resolved git is working on this old xp machine, too !

**Comment by dscho** [comment]
Those files are not zero-byte sized, but they are hard links. For example, `git-tag.exe` and `git-commit.exe` are not two different files, but really hard-linked copies of one another.

If you extract the files with a hard link-aware `tar`, it will work. If your `tar` does not handle hard links, or if it punts in the presence of a FAT file system (which does not support hard links), you will see 0-sized files.

It does not really matter in most cases, because most of the hard-linked files are simply referring to "dashed" forms of builtin commands. Nobody should access Git commands as, say, `git-commit` anymore, it was a foolish design to begin with and is long deprecated, the highly recommended way is `git commit`.

The only exception is `git-remote-http.exe` and `git-remote-https.exe`, which really need to be present, both, either as hard-linked copies or as verbatim copies.

But again, if you use a correctly-implemented `tar` (the report leaves out that crucial piece of information) to extract the files, it will work.

**Comment by tdkuehnel** [comment]
Thanks for the insight! Sorry for not putting the tar version used into my report. It was 7zip 4.65. The filesystem is a FAT32 filesystem. With Filzip 3.05 the files show up with zero size before extracting, too, as in 7zip. Ich checked with filzip extracting to a ntfs-volume, which gives zero sized files and dlls on disk, so the used tools are the significant factor.
An easy to find hint for such users with old os/systems would be nice.

I hope people with old os running into the same issue find the solution like i did. Just copying the non zeor sized files scattered over the different directories over to the zero one sized ones in the mingw32\libexec\git-core directory to make git running with all subcommands.

**Comment by dscho** [comment]
> An easy to find hint for such users with old os/systems would be nice.

Where?

**Comment by tdkuehnel** [comment]
I suggest a place where the people look next when the current offered exe/msi installers do not work. For me the link at the bottom of the https://git-for-windows.github.io page gave me the option to walk back in the versions and to find the zip/tar archives at all, which was good. The installer versions only give error messages about missing something. They should instead tell something like "version xy of os required for the automatic installers to run, but you can use the zip/tar versions with a recent tool with hardlink support to make the software run on your os."

In the readme/install document of each zip/tar archive would be another possibility.

**Comment by dscho** [comment]
I can't just go and change every single .zip/.exe of every past release.
