### ISSUE TITLE
Include rebaseall into the installer and the portable Git, execute it, too

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#125]
In a test on XP, things went less than smooth without rebasing the `.dll` files: a simple `git rev-parse` (called by the Bash prompt) would take ages, only to exit with the code `128`.

The truly sad part is that this happened *despite* running `autorebase.bat` directly before building the installer (on a Windows 8 machine).

That means that we *have* to run `/usr/bin/rebaseall` in 32-bit installations, which means that we have to include the files `usr/bin/rebase.exe` and `/usr/bin/rebaseall` (and maybe `/autorebase.bat`, but that requires also `usr/bin/dash.exe`; I still have to figure out whether there are technical reasons to prefer `dash` over `bash` there, but then, `dash.exe` is only ~100kB and it seems to work without any further files than that).

We might want to write a new script called something like `runmefirst.sh` that also runs [the `post-install` scripts](https://github.com/git-for-windows/build-extra/pull/46).

**Comment by tkelman** [comment]
> I still have to figure out whether there are technical reasons to prefer `dash` over `bash` there

As I understand it, ash or dash are necessary because they can avoid using fork or other cygwin dll features that the rebase process needs to modify.

**Comment by elieux** [comment]
> include the files `usr/bin/rebase.exe` and `/usr/bin/rebaseall` (and maybe `/autorebase.bat`, but that requires also `usr/bin/dash.exe`)

The batch file explicitly calls dash only because Windows can't parse the shebang of `rebaseall`. And it seems that this script is the only part of the whole rebase mechanism that actually requires (d)ash. This is for 1) technical reasons (explained below), and 2) because it enumerates running processes are refuses to run if bash (or any other Cygwin program) is running.

The technical reasons -- and I just checked on #cygwin -- for using (d)ash is because it imports no libraries other than `cygwin1.dll` (or its equivalent). But if you're using the MSYS2 build of bash, you can also use it to run `rebaseall`, because it's linked statically as well; the only issue with that is the point (2) above.

**Comment by dscho** [comment]
@tkelman @elieux thanks for the explanation. I already have an [experimental branch](https://github.com/git-for-windows/build-extra/compare/autorebase) (I will probably drop the last commit because the problem I tried to solve lies completely [elsewhere](https://github.com/git-for-windows/git/issues/127)).

**Comment by dscho** [comment]
Fixed in https://github.com/git-for-windows/build-extra/commit/fdd7a1299b953515ed0a6aec6151a531da5b4fff
