### ISSUE TITLE
Unicode Encode Error when printing utf-8 characters to Git Bash

### ISSUE THREAD

**Issue by jschwarzwalder** [git-for-windows/git#1254]
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.13.3.windows.1
built from commit: faaf2320f32f6ac52a69502c6b157b6ea4781f50
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This issue only occurs when I'm using Git Bash. I've set Python 3.6 to my path as python when using Git Bash
```
$ python --version
Python 3.6.0

```

![encoding](https://user-images.githubusercontent.com/8946787/28902855-794b8562-77b6-11e7-8a8a-54bb8567fa85.png)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
Bash
```
![git bash options](https://user-images.githubusercontent.com/8946787/28902773-f3f83aea-77b5-11e7-98aa-30dc766e81d8.png)
![mintty](https://user-images.githubusercontent.com/8946787/28902776-fa527356-77b5-11e7-911b-6d3180a43342.png)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I've been having problems with utf-8 characters not displaying properly in Git Bash. 

To help identify the problem I ran a program that decodes bytes from encoded utf-8 characters 
I used this file input: [languages.txt](https://learnpythonthehardway.org/python3/languages.txt )
[My code](https://github.com/jschwarzwalder/learnpython3thehardway/blob/master/Jami/ex23.py)

To run the program I typed in ```python ex23.py utf-8 strict```

```
import sys

print(sys.stdout.encoding)

s = "አማርኛ"  # Amharic
raw = s.encode("utf-8", errors="strict")
print(raw)
print(raw.decode("utf-8", errors="strict"))

```

 - What did you expect to occur after running these commands?

![expected vs reality](https://user-images.githubusercontent.com/8946787/28902876-9080a10e-77b6-11e7-83af-1aec9d2864b3.png)

 - What actually happened instead?

when I try to display any UTF-8 characters I get a Unicode Encode Error

I was able to run ```export PYTHONIOENCODING=utf-8```
but if I close by Git Bash and reopen, then I get the same Unicode Encode Error

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

[ex23.py](https://github.com/jschwarzwalder/learnpython3thehardway/blob/master/Jami/ex23.py)

**Comment by dscho** [comment]
Python is not part of Git for Windows. As such, it is not really supported by Git Bash. You may have luck using `winpty` to execute your script, or to execute your script using `python.exe` instead of `python`.

**Comment by vtgn** [comment]
Hi,
I've got the same problem today, but I want to understand what could have happened because I didn't have the problem 2 weeks ago, and nothing has been updated with my python installation, and the versions of my python dependencies.
So I think the problem is caused either by gitbash or by a windows update.

I'm using the same git version 2.39.1.windows.1 since 2 years.
I've got the problem with my fastapi web server: 2 weeks ago I could launch it on git-bash, but not anymore because of UTF-8 characters printed by the fastapi-cli command. I use exactly the same version of python, the same version of fastapi-cli and the same versions for all the python dependencies that I set in a requirements.txt file.

The server starts perfectly from windows cmd console, so the problem is only present on the git bash console.
Why the sys.stdout.encoding Python command returns utf8 on cmd console, but cp1252 on git bash?
My git bash is perfectly configured to manage the utf-8 characters by using the system configuration which is correct, it displays perfectly them with an echo command. I use the same installation of Python 3.12.6 that I installed 2 months ago.
So maybe something bad happened with my git-bash. Has this kind of behavior already happened?

Thanks.
Regards.

**Comment by mintty** [comment]
>  >  it then re-installed minnty 0.9.5.1 (mintty-0.9.5-cygwin17.zip) and it works now. Strange.

> Source: https://stackoverflow.com/questions/4780591/mintty-terminal-python-curses-and-utf8-incorrect-display

That's more than 10 years ago and many things have changed since, e.g. MSYS2 has enabled ConPTY support by default. Not sure whether your older version of Git-for-Windows already integrates that; you should upgrade anyway. What if you run `MSYS=enable_pcon mintty` (or set this in file /etc/git-bash.config)?
Also, depending on what build of python you use, it might help to set `chcp.com 65001`.
