### ISSUE TITLE
"Error in startup script" popup after the "git-gui -h" popup

### ISSUE THREAD

**Issue by Deadooshka** [git-for-windows/git#1284]
![screenshot - 29 08 2017 9_37_47](https://user-images.githubusercontent.com/3809026/29808259-fb779550-8c9f-11e7-8c14-5c158756ed69.png)
```
$ git --version --build-options

git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86
```
```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```
```
$ cat /etc/install-options.txt

portable
```
 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd/bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
```
git-gui -h
```

**Comment by PhilipOakley** [comment]
The image in the issue report didn't show in the email notifications.

The Image shows the error stack.

The reported error is 
```
 invalid command name "tk_messageBox"
             while executing
"tk_messageBox -icon error -type ok -title "git-gui: fatal err"
-message $err"
```
from "Git/mingw32/libexec/git-core/git-gui.tcl" line 34.

so that will be where to start (and check my copy typing;-)

Maybe the command name has a miss-spelling. 

Then again, maybe the git-giu itself can't cope with the -h option which is think is pre-processed by the `git` command (there is magic to work out what to do between the --help, -h and git help command views).

It maybe a further layer up the command stack at `git-gui` line 25 (see the image)

**Comment by mfriedrich74** [comment]
In my tcl coding experience, this was usually caused by a missing "package
require Tk" when running from the console interpreter (tclsh.exe).

Best regards, Mike

**Comment by dscho** [comment]
The underlying problem is completely different: you use (quite unnecessarily) the `git-gui.exe` wrapper (which actually does not perform the operation but hands off to `git.exe gui <arguments>...`.

If you call `git gui -h` (note the *space* between `git` and `gui`), it works.

**Comment by dscho** [comment]
And the report failed to include the *first* window that pops up:

![git-gui-h-failure](https://user-images.githubusercontent.com/127790/29868821-bdd6586c-8d80-11e7-93af-52c48bb03185.png)
