### ISSUE TITLE
Shortcut to Git Bash is wrong.  

### ISSUE THREAD

**Issue by DevinCook** [git-for-windows/git#1290]
Shortcut to Git Bash is wrong.  

It points to "C:\Program Files\Git\git-bash.exe" but should point to C:\Program Files\Git\bin\bash.exe

It is also wrong in the registry for "Git Bash Here" entry.

### Setup

 - 64-bit?

```
$ git --version --build-options

git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

10 - 64

```
$ cmd.exe /c ver

Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

```

**Comment by dscho** [comment]
> It points to "C:\Program Files\Git\git-bash.exe" but should point to C:\Program Files\Git\bin\bash.exe

Actually, that is incorrect. Git Bash is more than just `bash.exe`. It is

- meant exclusively for *interactive* usage
- an optional MinTTY vs Win32 Console window,
- setting up environment variables so that Git is easier to use.

Those are things that the `git-bash.exe` progam do before calling the `bash.exe`.

Therefore, the shortcut is actually pointing at the correct executable.
