### ISSUE TITLE
git-bash.exe fails on AppVeyor starting from Git 2.13.3

### ISSUE THREAD

**Issue by FeodorFitsner** [git-for-windows/git#1293]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

other - AppVeyor build agent spawns a new child process using Win32 API and runs CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
"C:\Program Files\Git\git-bash.exe" --no-cd --command "echo test!"
```
 - What did you expect to occur after running these commands?

Process exists with 0

 - What actually happened instead?

Command exited with code -1073741819

Test build on AppVeyor: https://ci.appveyor.com/project/FeodorFitsner/git-bash-error/build/1.0.3

If before running the command Git downgraded to 2.13.2 then it works fine.

[Git 2.13.3 release notes](https://github.com/git-for-windows/git/releases/tag/v2.13.3.windows.1) mentions "Comes with MSYS2 runtime (Git for Windows flavor) based on Cygwin 2.8.2.". Could it be the issue? What that error code could mean?

**Comment by dscho** [comment]
> -1073741819

Converting this to hex yields `ffffffffc0000005`, meaning our "good old friend" 0xC0000005, the Access Violation (or for Unix folks: segmentation fault).

Could you repeat the experiment with `bin\bash.exe`, `usr\bin\bash.exe` and prefixed with `strace.exe`?

**Comment by dscho** [comment]
Oh, another question: how do you get the Git for Windows-specific `git-bash.exe` into your system? If you modify `pacman.conf` to leverage Git for Windows' Pacman repository, then a new `msys2-runtime` (it is being built as we speak) may fix it miraculously.

**Comment by FeodorFitsner** [comment]
Well, `bin\bash.exe` worked: https://ci.appveyor.com/project/FeodorFitsner/git-bash-error/build/1.0.4

**Comment by FeodorFitsner** [comment]
oh, and we install Git for Windows to our build images with the official installer: https://github.com/git-for-windows/git/releases/download/v2.14.1.windows.1/Git-2.14.1-64-bit.exe

Thanks for looking into that!

**Comment by dscho** [comment]
> Well, bin\bash.exe worked: https://ci.appveyor.com/project/FeodorFitsner/git-bash-error/build/1.0.4

Okay, good!

Please note that `--no-cd` is no longer necessary, as enough people chimed in with convincing arguments to change `git-bash.exe` so that it does not change directories by default (and `bin/bash.exe` was never affected, anyway).

> oh, and we install Git for Windows to our build images with the official installer: https://github.com/git-for-windows/git/releases/download/v2.14.1.windows.1/Git-2.14.1-64-bit.exe

Okay!

Back to your original bug report: It would be interesting to find out what causes that access violation. Last time I chased a bug like this (only reproducible in CI, probably a bug in `msys-2.0.dll`), it took me three days straight to figure it out, and I had to compile a custom `msys-2.0.dll` with tons of debug information over and over again.

Of course, it might be just some problem within MinTTY (because `git-bash.exe` is supposed to open a MinTTY window, and it may be unhappy about being headless).

In light of these difficulties, I am inclined to simply close this ticket and hope that the bug either does not affect anyone else, or somebody finds a much easier MCVE allowing me to investigate more efficiently.

What do you think?

**Comment by FeodorFitsner** [comment]
OK, we'll be just re-mapping `.sh` extension to `bin\bash.exe` then. That should work in a long term, so yes I think the issue can be closed.
