### ISSUE TITLE
Add console enhancement - tig

### ISSUE THREAD

**Issue by Kirill** [git-for-windows/git#1294]
Please review add tig to release. For now I and other users must install cygwin for compile and build tig for windows. May be you can include tig in default installation?
https://github.com/jonas/tig

**Comment by PhilipOakley** [comment]
Maybe download the SDK and see what is involved in creating a Pull Request. A little bit of self help goes a long way ;-). 

If you are already happy compiling and building within Cygwin, then it shouldn't to too great a step in getting the SDK (Msys2, pacman, dev environment, etc) ready to build. 

At least you will be able to see the size of the additional dependencies and whether they make the current GfW size/bloat even larger.

--Philip

**Comment by Kirill** [comment]
Hi. My C++ knowledge poor.
I compile and build exe tig from source. For now this exe need 3 dll: cygiconv-2.dll,cygncursesw-10.dll,cygwin1.dll. I download git for windows sdk and try build tig in sdk, but have much error. For example, in tig.h needed wait.h from cygwin
https://github.com/jonas/tig/blob/master/include/tig/tig.h#L48. I can't find this file in sdk. I try comment this line, next header file select.h.  But how can use this header in sdk I don't know. Sorry

**Comment by dscho** [comment]
> For example, in tig.h needed wait.h from cygwin
> https://github.com/jonas/tig/blob/master/include/tig/tig.h#L48.

This means that you have to compile it as an *MSYS2* package (`wait.h` is POSIX functionality, therefore `tig` will require the POSIX emulation layer provided by the MSYS2 runtime, instead of being compiled as a pure Win32, or "MINGW" program). See https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages for details, in particular this part:

> To build MSys packages, you need to start the `MSys` shell (e.g. `C:\git-sdk-64\msys2_shell.cmd -msys`, which sets `MSYSTEM=MSYS` before running the Bash), clone the [`MSYS2-packages`](https://github.com/git-for-windows/MSYS2-packages) repository (recommended location: `/usr/src/MSYS2-packages`), `cd` to the appropriate subdirectory and call 
>
> ```bash
> makepkg -s
> ```

In that document, you will also find that a `PKGBUILD` file is required to build new packages, and MSYS2 packages' `PKGBUILD` files should go into `/usr/src/MSYS2-packages/<package-name>/PKGBUILD`.

The funny thing is that there already *is* a `tig`. Which means that you can probably install it into your local Git for Windows SDK via `pacman -Sy tig`.

Armed with this information, you could [build an installer](https://github.com/git-for-windows/git/wiki/Making-an-installer), then head over to [the commit that added `git-flow`](https://github.com/git-for-windows/build-extra/commit/920c19bd0381a89735326eab2490fd27e1ca4951) (ignoring the `getopt.exe`/`util-linux` part that is irrelevant as far as `tig` is concerned) and imitate that to add `tig` to the installer's file list, then build another installer, test that, and compare the installer's size before and after. If it does not add *too* much to the installer size, we could totally include it (Pull Request warmly welcome!).

Maybe you can take it from here?

**Comment by Kirill** [comment]
@dscho Thank you.. I try call `pacman -Sy tig` in SDK. And tig install correctly. I copy this file (tig.exe) to git-install\bin and it's wotk without cygwin and etc...
For installer I will try. But PR I wouldn't create, because my level for it is small. I think it must create professional :smirk:

**Comment by dscho** [comment]
> For installer I will try. But PR I wouldn't create, because my level for it is small. I think it must create professional :smirk:

Oh, but please do. We can work together to make it professional. I'd actually like that.

**Comment by Kirill** [comment]
Hi... At home I haven't time to test this errror. But on work I haven't this error and installer build without any problem. I create pull-request https://github.com/git-for-windows/build-extra/pull/157

**Comment by dscho** [comment]
@Kirill thanks. Let's continue the discussion there.
