### ISSUE TITLE
I hava a space in my home dir which causes the .ssh/id_rsa file cannot be found by ssh.

### ISSUE THREAD

**Issue by Biello** [git-for-windows/git#1300]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
$ git --version --build-options

git version 2.14.1.windows.1
built from commit: 82d9b3f3b2407b52251620597d4b14933685459d
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
cannot list dirs with spaces in path,
```
$ ls /c/Users/Kobe Biello/.ssh/
ls: cannot access '/c/Users/Kobe': No such file or directory
ls: cannot access 'Biello/.ssh/': No such file or directory
```
but the files exist. 
```
$ ls /c/Users/Kobe\ Biello/.ssh/
id_rsa  id_rsa.pub
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh -T -v git@github.com
```
 - What did you expect to occur after running these commands?
```
Hi xxx ! You've successfully authenticated, but GitHub does not provide shell access.
```

 - What actually happened instead?
```
OpenSSH_7.5p1, OpenSSL 1.0.2k  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to github.com [192.30.255.112] port 22.
debug1: Connection established.
debug1: identity file /c/Users/Kobe Biello/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Kobe Biello/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Kobe Biello/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Kobe Biello/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Kobe Biello/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Kobe Biello/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Kobe Biello/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /c/Users/Kobe Biello/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.5
ssh_exchange_identification: read: Software caused connection abort
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 No.

**Comment by dscho** [comment]
> ```
> debug1: identity file /c/Users/Kobe Biello/.ssh/id_rsa type 1
> ```

The `1` means that it was loaded correctly.



> ```
> debug1: key_load_public: No such file or directory
> debug1: identity file /c/Users/Kobe Biello/.ssh/id_rsa-cert type -1
> ```

The `-1` means that it was not loaded correctly, and the error message "key_load_public: No such file or directory" was displayed *above* that line (see [this StackOverflow answer](https://superuser.com/questions/962888/what-does-key-load-public-no-such-file-or-directory-mean#962895)).

> ssh_exchange_identification: read: Software caused connection abort

That error message does *not* say that your key failed to authenticate you. It says that the remote host hung up on you. See [this StackOverflow answer](https://serverfault.com/questions/445045/ssh-connection-error-ssh-exchange-identification-read-connection-reset-by-pe#445059) for more information.

Now, this being GitHub, it is unlikely that they deny your IP to connect unless you did really bad things.

Maybe calling `ssh` with *several* `-v` options (which increases the verbosity, I typically use `-v -v -v` to diagnose similar problems) can help identify the root cause?

**Comment by dscho** [comment]
Oh, and BTW this issue:

> ```
> $ ls /c/Users/Kobe Biello/.ssh/
> ls: cannot access '/c/Users/Kobe': No such file or directory
> ls: cannot access 'Biello/.ssh/': No such file or directory
> ```

is a well-known hurdle for new users of Unix shells: parameters are separated by white space. If you want white space to be *part* of the parameter (rather than separating parameters), you have to either escape it with a backslash (as you did later), or by quoting the parameter (double quotes will interpolate shell variables and other special characters such as the backtick, single quotes will not).

**Comment by Biello** [comment]
@dscho thanks a lot! You are right, the file is accessable. It turns out to be a network problem. When I get home, connecting to my family wifi, the problem is gone.
