### ISSUE TITLE
PortableGit installation is too large

### ISSUE THREAD

**Issue by AlexIljin** [git-for-windows/git#1308]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
- PortableGit v2.14.2, 64-bit.

```
> git --version --build-options
git version 2.14.2.windows.1
built from commit: 788debdfb6b794425a3b949dd1a0eb2425a72e96
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running?
 - Windows 8.1, 64-bit.

```
> cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the defaults?
 - I have installed the Portable version: `PortableGit-2.14.2-64-bit.7z.exe` into `C:\Programs\Dev\Git`.

```
> type "C:\Programs\Dev\Git\etc\install-options.txt"
The system cannot find the file specified.
```

### Details

  I have just upgraded my installation from PortableGit-2.**12.2.2**-64-bit.7z.exe to PortableGit-2.**14.2**-64-bit.7z.exe and noticed that the git folder grew in size from about 237Mb to about 488Mb. (I have renamed the old folder to "git.bak", did not install one over the other.) The main reason for that growth seems to be the `git/mingw64/libexec/git-core/` folder: ~50Mb -> ~288Mb.

  I can see that most of the executables in there jumped in size from ~41Kb to 2185Kb. It looks like you've got some sort of regression in that area between releases 2.12.2.2 and 2.14.2.

**Comment by dscho** [comment]
Indeed, this is a bug. BTW you should do more fine-grained upgrades than skipping 8 (!!!) versions. Otherwise it is a lot harder to pinpoint problems.

Back to the bug.

A little background: ages ago, when we still used MSys as our base, there were tons of user complaints about huge installation sizes (which all turned out to be incorrect reports, as Windows Explorer counted hard-linked files as if they were copies). The worst "offenders" were all those builtins (e.g. `git-add.exe`) which are simply hard-linked to `git.exe`, all 115 of them. So what we did was to introduce what we call the "Git wrapper", a little drop-in `.exe` that does nothing else than call `git.exe` so that we could replace all those hardlinked builtins by that wrapper, which would make the total installation size look much smaller overall (even if we actually increased the size by a couple of kilobytes). When we started to bundle portable Git versions, naturally this became more than just a cosmetic change, as the file format for those versions (`.7z`) cannot encode hardlinks, therefore the files are now *real* copies.

The current way the `mingw-w64-git` packages are built, however, still installs Git's builtins as hard-links, so that MSYS2 users can benefit from that. Git for Windows' SDK then [overwrites those builtins by hardlinking to the `git-wrapper.exe`](https://github.com/git-for-windows/build-extra/blob/8d979af491c1fd5102383605ef502183a869b24b/git-extra/git-extra.install#L53-L70).

Now, when I build these `mingw-w64-git` packages, I don't do that manually anymore, as it is tedious and error-prone. I use [a script](https://github.com/git-for-windows/build-extra/blob/8d979af491c1fd5102383605ef502183a869b24b/please.sh) to automate as much as possible, making it more efficient, less error-prone, and also documenting the whole process.

In this instance, I issued the command `./please.sh upgrade git`. This is itself a combination of the steps that build the packages, install them into the local Git for Windows SDK, upload them to Git for Windows' Pacman repository, and finally update the Release Notes.

And this "upload them to Git for Windows' Pacman repository" is where things went wrong: for some stupid reason, my network connection went flakey and the upload timed out. Hence I had to complete that process manually, which I did, and for extra good measure, I made sure that the newest `mingw-w64-git` package version was installed.

However, it is the `git-extra` post-install script that replaces the builtins by hardlinks to the Git wrapper. That is why `./please.sh install git` code [explicitly re-installs `git-extra` at the end](https://github.com/git-for-windows/build-extra/blob/8d979af491c1fd5102383605ef502183a869b24b/please.sh#L2201-L2204). But it tries to install the latest `git-extra` built on *this* machine, which failed, as I now use multiple VMs to build packages. So I fear that that step failed and I did not notice.

And then I built the packages without realizing that the builtins were still the hardlinks (that were turned into copies in `PortableGit-2.14.2-64-bit.7z.exe`).

My apologies!

As to the likelihood of this to reoccur: very small, as I fixed the `install` step in git-for-windows/build-extra@5506d70f9, and I also introduced extra safety checks into the `release` step (that builds the installers and portable Gits) in git-for-windows/build-extra@f91790012 so that I won't build too-large portable Gits by mistake in the future. The next Git for Windows version will hence have the "normal" portable Git size again.

**Comment by AlexIljin** [comment]
Thank you for fixing this, and for an interesting explication of the internal workings of your development process. I especially liked the name of the `please.sh` script. Apart from being a useful word I could employ to name my own scripts, it brings back the memories of the INTERCAL Reference Manual.
