### ISSUE TITLE
Bad performance of b2sum in 32-bit build

### ISSUE THREAD

**Issue by AlexIljin** [git-for-windows/git#1309]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
 - PortableGit v2.14.2, 64-/32-bit.

```
> git --version --build-options
git version 2.14.2.windows.1
built from commit: 788debdfb6b794425a3b949dd1a0eb2425a72e96
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 - Windows 8.1, 64-bit.

```
> cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
 - CMD

  I have downloaded the PortableGit-2.14.2-**32**-bit.7z.exe and PortableGit-2.14.2-**64**-bit.7z.exe, then extracted the `usr/bin/b2sum.exe` using 7-zip from each archive, along with the necessary libraries:
 - for 32-bit: msys-2.0.dll, msys-gcc_s-1.dll, msys-iconv-2.dll, msys-intl-8.dll;
 - for 64-bit: msys-2.0.dll, msys-gcc_s-seh-1.dll, msys-iconv-2.dll, msys-intl-8.dll.

 - What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) this will help us understand the issue.

  I have found a big file on my system (11Gb video), ran the following command and measured the run time:
```
b2sum -b -l256 big-file-name
```
 - What did you expect to occur after running these commands?

  I expected the run time of the 64-bit version to be slightly greater than that of the 32-bit version.

 - What actually happened instead?

  The run time was **3.85 times** greater.
```
b2sum-git-x64: 23815 msec, \9793d158095a0b5e6d672164d98adbef3dec97c3833eb2d0b672479d318011fb
b2sum-git-x32: 91709 msec, \9793d158095a0b5e6d672164d98adbef3dec97c3833eb2d0b672479d318011fb
```

 For other hashes the 64-bit version, extracted the same way from the same 7-zip distros, outperformed the respective 32-bit versions only by a small margin (<~10%). Everything was tested on the same 11Gb file:
```
sha1sum-x64: 32415 msec, \b20cac810b6f49d90756f87dfdf238797f718022
sha1sum-x32: 33580 msec, \b20cac810b6f49d90756f87dfdf238797f718022

sha256sum-x64: 72597 msec, \361fc66d990fec214b5f3446275681f8ed15b7e3ed9908623c2b78cb2eb53f20
sha256sum-x32: 80523 msec, \361fc66d990fec214b5f3446275681f8ed15b7e3ed9908623c2b78cb2eb53f20
```

**Comment by dscho** [comment]
First of all: you *do* know that `b2sum` has *nothing whatsoever* to do with Git, right? Like, even if I had *some* time to spare to work on this, I shouldn't, because my role is to maintain Git for Windows, right?

Having said that, who can say no to a good side-track. Certainly not I.

So let's dive in. Before anything else, if you have not done so, install [Git for Windows' SDK](https://git-for-windows.github.io/#download-sdk). You really have to, because for the reason mentioned above, the main part of the investigation will be yours to perform.

In the SDK's `git-bash`, you can easily find out which Pacman package owns the `b2sum` program:

```sh
pacman -Qo $(which b2sum.exe)
```

Turns out it is owned by `coreutils`, which is a bit, uhm, strange, I have to say, given that BLAKE2 is a cryptographic algorithm, so I would have expected something like OpenSSL. But whatever (I actually did not find any way to make `openssl.exe` calculate any hashes but MD4, MD5, MDC2, RMD160 and SHA-1).

So let's take a deep dive into `coreutils`. For that, you should first build that package in your SDK. See https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages for details about that.

Once you have done that, conveniently the source code will be in `/usr/src/MSYS2-packages/coreutils/src/coreutils-8.26`.

As you can easily see, the source code for `b2sum` seems to be squarely in the `src/blake2/` subdirectory. I did not find any assembly code there, let alone MMX, but I did not really look very closely. But that absence, if it holds true, would explain your findings, I guess, as BLAKE2b was optimized for 64-bit (IIRC).

So where does that leave you?

You have a couple of options, including:

- Trying to find other, specialized tools with hardware acceleration also on 32-bit systems.
- Looking at OpenSSL (but it does not seem as if https://github.com/openssl/openssl/tree/master/crypto/blake2 has any `asm/` subdirectory as eg. `sha` does).
- Coming up with your own, super-fast implementation of BLAKE2b.

Of course, you could also just use any number of already-available projects to do hardware-accelerated BLAKE2b, such as

- https://github.com/minio/blake2b-simd
- https://github.com/weidai11/cryptopp
- and of course https://github.com/BLAKE2/BLAKE2 (which is the reference implementation)

BTW I found these by a very quick & dirty web search for "blake2 mmx".

**Comment by dscho** [comment]
I guess I'll just close this ticket, as it would only be fun if there was a dialogue ;-)
