### ISSUE TITLE
git clean fails for files named NUL

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#1323]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.2.windows.3
built from commit: 924c19fc000d3759486b68bd73bc592fa02e367c
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git init
Initialized empty Git repository in F:/Projects/t/.git/

$ touch NUL

$ git clean -f
fatal: Cannot lstat 'NUL': No such file or directory
```
[This patch](https://gist.github.com/orgads/4dbfec4399e7f9b3b15562ba442243a4) fixes the issue for me, but it's a bit hacky. I'm not familiar with Git internal design. Can you please improve the patch and post it? Thanks.

**Comment by dscho** [comment]
`NUL` is a reserved word. You cannot create a file with that name, as it is illegal as per the Win32 API. That is why Git cannot clean it.

What you did was to create such a file using the MSYS2 Bash, and it is unfortunate that it allows you to do that.

I am pretty sure that this is not something Git should learn to care about, as it should not be possible to create such a file in the first place...

**Comment by orgads** [comment]
I came into this because of https://bugreports.qt.io/browse/QTBUG-62985 which created many files named NUL (they were created by mingw32-make that I executed from a plain command prompt), and I could not clean them up.

**Comment by dscho** [comment]
While I understand your problem, I really have to point out that not even `DEL NUL` in a cmd window will be able to delete those files.

The reason: those file names are really illegal as per the Win32 API. So what Git does is actually correct, the fault lies with the tools that jump through hoops to generate those illegal files.

What you *can* do is to work around this by using the same flawed tools that generated the illegal files to remove them, too:

```sh
find -name NUL -exec rm -rf {} \;
```

**Comment by orgads** [comment]
Did you take a look at the patch?

**Comment by dscho** [comment]
> Did you take a look at the patch?

Yes.

It is in spirit very similar to what we do for long paths: prefix with `\\?\`. The problem with this approach is that it is noticably *slower* than the current code, because it not only has to prefix the path, it also has to normalize it and before that make it absolute (because most paths are relative), and then the NTFS code has to traverse all those paths back to the current directory. Sadly, I forgot to record the exact performance impact, but IIRC it was somewhere between 5-10% for file accesses, which is pretty bad. See https://github.com/git-for-windows/git/issues/929#issuecomment-336497691 for my mini report.

If you are really interested to have this, I think what we need to do is to introduce a new mode "unsafe" for `core.longpaths` based on my patch (and we could also introduce another config setting that does not mention long paths but more like `windows.allowIllegalPaths` or some such).

I have little motivation to work on this, though... do you? If you do, please do not hesitate to butcher my patch series into shape.

**Comment by orgads** [comment]
Nah, I give up :)

This is a corner case after all, and I'm too loaded for that.

**Comment by dscho** [comment]
> I'm too loaded for that.

I hear you. Maybe the "up for grabs" label gets somebody interested, otherwise we can leave this closed for now.
