### ISSUE TITLE
Problem with `git push . branchname` doesn't seem to work

### ISSUE THREAD

**Issue by ericnewton76** [git-for-windows/git#1327]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

C:\Projects\gmaps\master>git --version --build-options
git version 2.14.2.windows.3
built from commit: 924c19fc000d3759486b68bd73bc592fa02e367c
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

C:\Projects\gmaps\master>cmd /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

C:\Projects\gmaps\master>type "C:\Program Files\Git\etc\install-options.txt"
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

(cant think of any)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd and bash, seems to make no difference

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
C:\Projects\gmaps\master>git checkout -b fix-getresultfordirections-test
C:\Projects\gmaps\master>git stash pop
C:\Projects\gmaps\master>echo "changed" >newfile.txt & git add . & git commit -m "changed something"
C:\Projects\gmaps\master>git status
On branch fix-getresultfordirections-test
Your branch is ahead of 'master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

C:\Projects\gmaps\master>git push
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push . HEAD:master

To push to the branch of the same name on the remote, use

    git push . fix-getresultfordirections-test


C:\Projects\gmaps\master>git push . fix-getresultfordirections-test
Everything up-to-date

C:\Projects\gmaps\master>git status
On branch fix-getresultfordirections-test
Your branch is ahead of 'master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

C:\Projects\gmaps\master>git push
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push . HEAD:master

To push to the branch of the same name on the remote, use

    git push . fix-getresultfordirections-test


C:\Projects\gmaps\master>git push . fix-getresultfordirections-test
Everything up-to-date

C:\Projects\gmaps\master>git status
On branch fix-getresultfordirections-test
Your branch is ahead of 'master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

C:\Projects\gmaps\master>git push -u origin fix-getresultfordirections-test
error: src refspec fix-directionresults-test does not match any.
error: failed to push some refs to 'git@github.com:ericnewton76/gmaps-api-net.git'

C:\Projects\gmaps\master>git push
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push . HEAD:master

To push to the branch of the same name on the remote, use

    git push . fix-getresultfordirections-test


C:\Projects\gmaps\master>echo "SMH.  Reboot.  Start drinking early"
SMH.  Reboot.  Start drinking early

```
 - What did you expect to occur after running these commands?

New remote branch created, commits pushed

 - What actually happened instead?

says "Everything up-to-date" but its not, and nothing pushed to new remote branch

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/ericnewton76/gmaps-api-net

**Comment by dscho** [comment]
> SMH. Reboot. Start drinking early

Good strategy.

😄 

I am actually quite surprised that nobody else jumped in to help you, as this is a *really* easy ticket and hardly requires my in-depth knowledge of Git for Windows' dirty intestines.

If you call `git push` and the default remote does not have a branch with the same name as your current branch, it refuses. This is what you saw first.

If you call `git push . <branch>`, you actually try to push *into the local repository*, which obviously is already up-to-date, because it really is, uhm, the same repository, so the branch is also one and the same.

But then you actually called the correct command: `git push -u origin fix-getresultfordirections-test`

The problem there seems to be some sort of typo or some such, as Git said that the *src* refspec cannot be found, i.e. the local branch that should be pushed. I cannot spot the typo, but maybe you want to use an easier invocation anyway: `git push -u origin HEAD`? This would push your current branch (whatever it is) to the remote repository, and set up tracking information.

> ```
> C:\Projects\gmaps\master>git push -u origin fix-getresultfordirections-test
> error: src refspec fix-directionresults-test does not match any.
> ```

Ah, I think I just spotted something. You may not have copied this entirely faithfully, eh? The error produced by Git mentions a branch name that does *not* contain the substring "getresultfordirections" but rather "directionresults"... Maybe you actually used a different command, one that did not have the correct branch name?

**Comment by ericnewton76** [comment]
TBH, i think it resolved itself after a newer release, although I havent checked it as thoroughly, opting to just ignore what it said, and go with what I know works (git push -u origin branchname)

This feels like it was sooooo long ago, and it was barely 2 mos!
