### ISSUE TITLE
Creating a symbolic link to the parent folder will fill your harddisk

### ISSUE THREAD

**Issue by janpetersen** [git-for-windows/git#1337]
Calling "ln -s" to the parent folder in GitBash will create an endless recursion, until either the hard disk runs out of space, or the file names get too long for Windows.

### Boring version:
1. Open GitBash, and type in:
1. mkdir foo
1. cd foo
1. mkdir bar
1. cd bar
1. ln -s ../

### More fun version:
1. Go into the root folder of a very big project, and type in:
1. ln -s ../ foo

I had quite some fun with the latter version. 👍 

### System:
* Windows 10 (64Bit, Build 1703)
* Git 2.14.3.windows.1 (64Bit)

**Comment by dscho** [comment]
This is really a problem of [MSYS2](https://msys2.github.io/)... Maybe report it there?

**Comment by ildar-shaimordanov** [comment]
Definitely, this is the issue of MSYS2 prior Git for Windows. I've seen the similar troubles when I tried to create a symbolic link with `ln -s`. In fact, the command simply duplicates everything instead of creating symlink. 

In addition, I've reported one more issue #858 having to do with symlinks (see the last comment with a lot of details https://github.com/git-for-windows/git/issues/858#issuecomment-341076942).
