### ISSUE TITLE
Stash causing stack overflow error

### ISSUE THREAD

**Issue by billerr** [git-for-windows/git#1338]
Hi,
I've been experiencing the following issue:
every time I'm using the stash (either stashing items or popping them), a sh.exe.stackdump file appears in the project root, reporting a stack overflow error.

I've experienced this on all versions up to 2.14.3, but it appeared to be fixed on versions 2.12 - 2.14 I think.

I've been using Git on Windows 10 x64 Creators update / Fall Creators update, through Git Bash.

**Comment by dscho** [comment]
Okay, since you simply deleted the issue reporting template instead of filling it out diligently, I will just punt this flatly back into your court. If you *think* that it was fixed in a specific version, then you can just as easily verify that, e.g. by installing that version's PortableGit.

Here is another venue you should investigate: in the past, some stack overflow errors have been caused by certain "funny" environment variable settings, such as having UNC paths in the `PATH` variable. If you see something in the output of `env` in your setup, try removing/changing it and see whether that fixes it. Also, you could drop in the `usr\bin\msys-2.0.dll` of the last working version into the first non-working version and see whether that works around the issue.

**Comment by billerr** [comment]
Hi!

I tried the avenue you suggested about the UNC in `PATH`, but there were none.
Next, I tried installing various versions of Git (non-portable, all 64bit) sequentially, to verify at which point the issue cropped up.
Going from 2.14.3 (clean install) to 2.12.0, the issue persisted.
Going back to 2.11.0, the issue disappeared. Upgrading then to 2.12.0, 2.13.3, 2.14.0, 2.14.3 in order, the issue is not reproducible again.

I don't know what might be causing this inconsistent behaviour - do you have any clue as to something else I should try to find out what's causing it? Otherwise, I suppose this issue can be closed if no one else is experiencing it.

Also, below you can find the issue reporting template, filled out diligently as you requested:
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.3.windows.1
built from commit: dbc8d81072630bc50324938b9ac950140669ced9
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.19]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None that I can think of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

`git stash` / `git stash pop` in an unclean working tree

 - What did you expect to occur after running these commands?

Only the non-commited files to disappear / re-appear in the working tree.

 - What actually happened instead?

A _sh.exe.stackdump_ file appeared upon `git stash` in the working tree root directory.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This is a private repository.

**Comment by dscho** [comment]
> git stash / git stash pop in an unclean working tree

Sadly, this does not qualify for a Verifiable example.

So the task of investigating is squarely in your court. You can do that relatively easily, too: the sh.exe.stackdump file may help you dig further: it contains hex addresses of a stack dump, and since those are most likely pointing into the MSYS2 runtime, and since that component has not changed since v2.14.3, you can easily [install Git for Windows' SDK](https://gitforwindows.org/#download-sdk) and run `addr2line -e /usr/bin/msys-2.0.dll <address>` to find out which function was in the trace. This should give you a reasonable idea what causes the stack dump (it could be a really full environment, for example, or funny environment variables).

**Comment by billerr** [comment]
Hi!
Actually, at the time of reporting, it was actually a Verifiable example, per the term's definition (invoking the commands reliably reproduced the problem).

Anyway, I'm reporting back what solved it for me, in case someone else comes here looking for a solution:
I went on re-installing versions 2.10.0 through 2.14.3 (on top of existing installation to rollback the version) and the problem actually solved itself. I have no info on what caused it, but that's what got this fixed.

**Comment by dscho** [comment]
Okay, thanks for reporting back!

**Comment by timmayo-ubi** [comment]
I see the same problem using 2.16.2 64-bit on Windows 10. A workaround is to switch to the 32-bit version

**Comment by dscho** [comment]
@timmayo-ubi can you please open a new ticket, specifically filling in as much of the suggested information (and anything else you can think of that may be related)?

**Comment by jcberthon** [comment]
Could this have been related to #1630?
