### ISSUE TITLE
Branch name lost from Git bash prompt

### ISSUE THREAD

**Issue by billerr** [git-for-windows/git#1339]
I haven't been able to find many reports of this issue (only [one on SO](https://stackoverflow.com/questions/22689548/where-exactly-git-bash-for-windows-prompt-is-defined) without any actual answer).

Up to version 2.10, the current branch name was visible at the end of the prompt in Git Bash.
All subsequent versions fail to show it properly on my configuration:  it shows up properly after launching a new Git Bash instance, and while using bash commands (cd, ls, etc) After using the git command once, the branch name never shows again in subsequent prompts for that bash instance.

The only solutions I've found online involve editing the PS1 via .bash_rc or .bash_profile (which haven't been created upon installation on my system). Could certainly use this as a workaround, but seems like a bug to report, since it appears properly until the first git command. Also, the only other suggestion (from the aforementioned SO question) to uninstall and reinstall outside the Program Files folder, doesn't work.

As mentioned before, this has been reproducible on all versions from 2.11 onwards (x64), on a Windows 10 machine.

**Comment by PhilipOakley** [comment]
----- Original Message ----- 
  From: Bill Gouveros 
  I haven't been able to find many reports of this issue (only one on SO without any actual answer).

  Up to version 2.10, the current branch name was visible at the end of the prompt in Git Bash.
  All subsequent versions fail to show it properly on my configuration: it shows up properly after launching a new Git Bash instance, and while using bash commands (cd, ls, etc) After using the git command once, the branch name never shows again in subsequent prompts for that bash instance.

  The only solutions I've found online involve editing the PS1 via .bash_rc or .bash_profile (which haven't been created upon installation on my system). Could certainly use this as a workaround, but seems like a bug to report, since it appears properly until the first git command. Also, the only other suggestion (from the aforementioned SO question) to uninstall and reinstall outside the Program Files folder, doesn't work.

  As mentioned before, this has been reproducible on all versions from 2.11 onwards (x64), on a Windows 10 machine.

  ----
You'd be right that the display of the current branch name is part of the bash PS1 functionality. It is not part of Git itself (other then providing various PS1 and other PS (=Prompt Script) options for you to install.

I would have expected that you would still have your prompt, but you my have tweaked something at some time and it gone awry.
--
Philip

**Comment by KevTheRev13** [comment]
Hi

I'm having the same exact issue. Running 2.14.3.windows.1 on a Windows 10 laptop.

![image](https://user-images.githubusercontent.com/19419989/32147526-37809052-bcbf-11e7-8b40-262ad341ea54.png)

**Comment by billerr** [comment]
Hi!

Well, the weirdest thing happened while I was looking into another issue I'd been having (#1338).
After rolling back to v. 2.11.0, the issue did not occur again. I then upgraded to 2.12.0, 2.13.3, 2.14.0 and 2.14.3 (in this exact order), and the issue was not reproducible again after each of these upgrades.

Maybe some setting or something persisted through the upgrades, but is not applied after a clean install of 2.14.3 (which I originally had)?

In any case, here are also the details of my setup and issue, in case anyone wants to look further into this:
 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.14.3.windows.1
built from commit: dbc8d81072630bc50324938b9ac950140669ced9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.19]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None that I can think of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Any Git command

 - What did you expect to occur after running these commands?

The branch name at the end of the bash prompt should persist.

 - What actually happened instead?

After the first Git command, the branch name at the end of the bash prompt disappears.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Private repository.

**Comment by dscho** [comment]
> Following the accepted answer on this page https://stackoverflow.com/questions/42721519/git-bash-prompt-current-branch-name-stops-showing-after-git-command/43659303#43659303 fixes the issue for me.

Are y'all doing custom prompts or what?

**Comment by billerr** [comment]
Nope, no custom prompts here.

Anyway, I'm reporting back what solved it for me, in case someone else comes here looking for a solution:
I went on re-installing versions 2.10.0 through 2.14.3 (on top of existing installation to rollback the version) and the problem actually solved itself. I have no info on what caused it, but that's what got this fixed.

**Comment by dscho** [comment]
Okay, thanks for letting us know!
