### ISSUE TITLE
TERM=screen-256color  not work well in git-bash (arrow key, and HOME, End not work)

### ISSUE THREAD

**Issue by eromoe** [git-for-windows/git#1341]
Env:
os: win 7 x64
git: git version 2.12.2.windows.2 

### Details

Because I am using tmux(msys2),  I need `TERM=screen-256color` to make  arrow key and powerline theme work .  Then I found this setting would break arrow key and HOME/End in git-bash.

**Comment by fourpastmidnight** [comment]
Have you set the terminal type within the mintry terminal emulator options? Have you tried using `xterm-256color`? Would that work? Again, ensure you set the terminal type in the mintty terminal emulator options.

**Comment by eromoe** [comment]
`xterm-256color` does work with git-bash. Though `Home, End` doesn't work if `TERM=xterm-256color`,  only `screen-256color` is perfect.
And I have switched to msys2 completely, I am here just report `TERM=screen-256color` not work.

**Comment by dscho** [comment]
The real question is why you set `TERM` differently from its default, `xterm`.

**Comment by dscho** [comment]
(I use `tmux`, too, and it sets `TERM` to `screen` here, and everything is working fine and dandy.)

**Comment by eromoe** [comment]
@dscho With default config, `tmux` is fine with `TERM=screen`. 

But

1. I want use powerline theme in `tmux` (msys2)

only `xterm-256color` and `screen-256color` can render theme correctly.

2. if I use  `xterm-256color`  

then `Home` and `End` doesnt' work.

3. So I have to change to  `screen-256color` 

Then I found `screen-256color` not work well in git-bash,    `arrow key` , `HOME`, `End`, `Backspace` all go wrong.

**Comment by fourpastmidnight** [comment]
There are also keyboard settings in the mintty terminal options. Not sure if anything there may help. For example, there are options about what the backspace key should do and for ALT vs. ALT Gr.

**Comment by dscho** [comment]
@eromoe can  you download https://github.com/git-for-windows/git-sdk-64/blob/master/usr/share/terminfo/78/xterm-256color?raw=true and copy it to `C:\Program Files\Git\usr\share\terminfo\78\xterm-256color` (needs administrator's permissions), then try again?

**Comment by eromoe** [comment]
@dscho  Thanks , but I am not searching the solution for this, just indicate git-bash should fix this.

**Comment by dscho** [comment]
> just indicate git-bash should fix this.

@eromoe you have been given a lot of work, for free, by MSYS2 and Git for Windows. It would be a fine opportunity *now* to give back by confirming the proposed fix works.

I mean, I am not even asking you to spend the time to make this a proper fix, I am just asking the *bare minimum* from you by simply downloading a simple file and copying into a precisely-specified location, and then perform the test that only you can perform: to verify that this fixes the problem you reported. I will spend substantially more time after that to turn this into a set of commits so that future Git for Windows versions will have the fix you so desire.

Is it really too much to ask for a *little* bit of assistance?

**Comment by eromoe** [comment]
@dscho  OK, because I had uninstalled git-bash at that time, I thought you just let me try some setting to fix the problem, forgive me .

Reinstall it and replace `xterm-256color` file ,  confirm work well with `screen-256color` . Good job.
