### ISSUE TITLE
2.4.0.1 comes up positive for viruses with Avast! scanner

### ISSUE THREAD

**Issue by malachib** [git-for-windows/git#136]
Perhaps it's just a glitch with Avast! but be warned

**Comment by malachib** [comment]
2.3.7.1 tests OK

**Comment by nalla** [comment]
See [issue#113](git-for-windows/git/issues/113)

**Comment by dscho** [comment]
Yeah, duplicate. @malachib thanks for participating in this project. Next time you find an issue, I would like to ask you to search the issue list first, and add a comment to any existing ticket instead of opening a new ticket.

Having said that, it would be good to work with the Avast developers (who work with customers like you, not non-customers like me) to find out whether there is *anything* we can do on Git for Windows' side to avoid these pesky issues from taking our time needlessly. Would you do that, please?

**Comment by malachib** [comment]
Roger that.  I did not think to search closed issues

**Comment by dscho** [comment]
> Having said that, it would be good to work with the Avast developers (who work with customers like you, not non-customers like me) to find out whether there is anything we can do on Git for Windows' side to avoid these pesky issues from taking our time needlessly. Would you do that, please?

@malachib please do that, still.

**Comment by malachib** [comment]
Roger that x 2.  Or 1.5, since in my mind I had already agreed :)

**Comment by dscho** [comment]
@malachib any news?

**Comment by malachib** [comment]
Avast! has me manually submitting the file via their ftp site.  They closed the issue since I didn't respond in time, but claim they will re-open it again if I request so - which I have.  When they respond, I'll share their response.

**Comment by malachib** [comment]
update:

"Our virus specialists have been working on the problem and it will be fixed in next VPS update."

Sounds heartening !

**Comment by dscho** [comment]
Thanks!

**Comment by dscho** [comment]
(I just marked it as a "wontfix" because it seems as if it is indeed not our problem. So: On to the next tickets :smiley_cat:)
