### ISSUE TITLE
C:\Program Files\Git\usr\bin\scp.exe: *** fatal error - cygheap base mismatch detected

### ISSUE THREAD

**Issue by garfieldbanks** [git-for-windows/git#1373]
I don't have any cygwin installed other than what comes with Git-2.15.0-64-bit.exe.
Here is the command I tried:
`scp file user@xxx.xxx.x.xxx:/path/to/file`
  
This is the full error:
 ```
     1 [main] scp (9732) C:\Program Files\Git\usr\bin\scp.exe: *** fatal error - cygheap base mismatch detected - 0x3B57408/0x3517408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] scp 2736 fork: child -1 - forked process 9732 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
fork: Resource temporarily unavailable
```

**Comment by dscho** [comment]
Was this closed because the bug was resolved? If so, how was it resolved?

**Comment by garfieldbanks** [comment]
This is what caused it:
https://winaero.com/blog/beware-incorrectly-implements-aslr-windows-fix-available/
After removing the MitigationOptions key, I no longer had the issue.

**Comment by dscho** [comment]
Thanks! I do not quite understand how that bottom-up strategy fixes the problem, I would have expected it to exacerbate the problems. However, a reboot may have provided the workaround necessary to fix the Cygwin base address contention...

**Comment by garfieldbanks** [comment]
Yeah, I tried a bunch of things, including multiple reboots, before I remembered I had made this change a few days earlier. I think I had to reboot after removing the registry key too.

**Comment by conioh** [comment]
> After removing MitigationOptions, I no longer had the issue.

@garfieldbanks If you deleted the `MitigationOptions` value it means you have disabled all of the mitigation options are are using the defaults. Specifically it means you have disabled Mandatory ASLR. Bottom-up is irrelevant for modules than aren't markes as ASLR-ready, which is all of the Git for Windows binaries, except `git-bash.exe` and its two friend.

**Comment by dscho** [comment]
@conioh are you saying that `mingw64\bin\git.exe` is not marked ASLR-ready?

**Comment by conioh** [comment]
@dscho:
No. I'm saying that `usr\bin\hostname.exe` isn't marked ASLR-ready  and `usr\bin\mv.exe` isn't marked ASLR-ready and `usr\bin\bash.ex`e isn't marked ASLR ready (though `bin\bash.exe` is).

The binary the issue referred to was `C:\Program Files\Git\usr\bin\scp.exe` and it is still not marked ASLR-ready. The fact that it works after OP deleted the `MitigationOptions` Registry value is not due to enabling bottom-up randomization but rather due to disabling Mandatory ASLR (and bottom-up randomization on the way).

You're correct I was inaccurate when I said that *all* Git for Windows binaries except 3 aren't marked ASLR-ready, but there are plenty of them to make the Git for Windows package (esp. "git bash" but not only) unusable without disabling Mandatory ASLR or adding exceptions. After adding manually 3 exceptions (starting with `hostname.exe` which was the first one to give me error after I enabled Mandatory ASLR) I got tired of checking them one by one.
