### ISSUE TITLE
Included nano version does not work with some Windows nano configuration files

### ISSUE THREAD

**Issue by mdekstrand** [git-for-windows/git#1383]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.1.windows.1
built from commit: 81ab034ac9b601ef5a4f4ab53e910d9fe8047cb0
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.64]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Portable installation via [scoop](http://scoop.sh).

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I have `nano` for Windows installed via Scoop, and have been using it with `GIT_EDITOR=nano` prior to Git 2.15.1.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

1. Check out [Nano Syntax Highlighting Files](https://github.com/scopatz/nanorc) with DOS line endings (`core.autocrlf=true`)
2. Create `~/.nanorc` that loads at least one of them; `zsh.nanorc` is known to cause the problem

    include "/path/to/syntax/zsh.nanorc"

3. Set `$env:GIT_EDITOR='nano'`

4. Run `git commit` in a repository with changes

 - What did you expect to occur after running these commands?

Clean git commit

 - What actually happened instead?

Nano syntax errors about `syntax` commands not starting with `"`. 

Normal Windows nano (installed via `scoop`, it installs the official Windows NT build) runs cleanly, it seems that the MSYS version of `nano` that is included with Git for Windows does not handle some configuration files that are stored with DOS/Windows line endings.

**Comment by mdekstrand** [comment]
If there is not a reason the MSYS build is required, it seems that switching from MSYS nano to official nano builds would fix this problem. I have been using official nano builds as my `GIT_EDITOR` for several months with no problems.

**Comment by dscho** [comment]
> If there is not a reason the MSYS build is required

... but there is. It is the ease of package management that was the reason for Git for Windows 2.x to be based on MSYS2.

I think the best course of action would be to fix MSYS2's nano to accept DOS line endings in configuration files.

In the meantime, you can work around the problem using two methods:

1. simply delete `C:\Program Files\Git\usr\bin\nano.exe`, or
2. add a simple wrapper to your `$HOME/bin/nano` that simply calls the real one (this method does not require administrator privileges and also persists over upgrades):
  ```sh
  #!/bin/sh
  
  exec /path/to/real/nano "$@"
   ```

**Comment by dscho** [comment]
> I think the best course of action would be to fix MSYS2's nano to accept DOS line endings in configuration files.

@mdekstrand are you up for an adventure in Open Source?

**Comment by mdekstrand** [comment]
> @mdekstrand are you up for an adventure in Open Source?

I might be able to take a look.

I just installed msys2 and found that the current version of Nano that it ships (2.8.7) does not support DOS line endings either.

**Comment by dscho** [comment]
> I just installed msys2 and found that the current version of Nano that it ships (2.8.7) does not support DOS line endings either.

Right.

So to get started, call `msys2_shell.cmd -msys` in the top-level directory of your MSYS2 installation (you can also do that in a Git for Windows SDK, but since you're already there...).

Then, clone MSYS2-packages: `mkdir -p /usr/src && git clone https://github.com/Alexpux/MSYS2-packages /usr/src/MSYS2-packages`.

Then rebuild the `nano` package, just to get going: `cd /usr/src/MSYS2-packages/nano && makepkg -s`.

This will downloaded the sources, build the artifacts and package them. The more interesting thing now is that it leaves behind a directory in `src/` (probably called `nano` or `nano-<version>`), where you can poke at the source code in question.

If the source code was extracted from a `.tar` file, I typically initialize a Git repository immediately (this assumes that you have Git's source code checked out at `/usr/src/git/`, which would be the case in Git for Windows's SDK): `cd src/nano-<version> && /usr/src/git/contrib/fast-import/import-tars.perl ../nano-<version>.tar.gz && git reset import-tars`

Note: there may have been patches applied already, you can find out by looking at `/usr/src/MSYS2-packages/nano/PKGBUILD` and search for `prepare`. Likewise, if you want to know how MSYS2 builds the artifacts, look for the `build` function.

I could imagine that you can get to the location that needs patching by calling `git grep` with an appropriate term, e.g. `.nanorc`.

Please let me know how your adventure goes, or if I can help to get you unstuck anywhere.

**Comment by dscho** [comment]
@mdekstrand Are you still interested in this?
