### ISSUE TITLE
git remote for new protocol XYZ://

### ISSUE THREAD

**Issue by xbotuk** [git-for-windows/git#1389]
I am intending to create a new protocol for git remote and would like to know what should I be looking at? For example can you please show how the HTTPS protocol is done?

**Comment by PhilipOakley** [comment]
Start with the [Contribute ](https://git-for-windows.github.io/#contribute) page. Down load the SDK which will then download and build Git for Windows complete.

Have a read of the git/Documentation/technical to get some of the backgrounds.

However, do ask yourself, "Why do I need a new protocol?" What is missing, what needs to be better, Will this new protocol go public? (i.e. you hope to get it accepted upstream). because Git has become a storage system of record, the trasport protocols need to be very rigorous and well reviewed, so expect push back for public changes.

However if it is a personal project for enlightenment and some other intersting capability, then why not.

The upstream list archive is available at https://public-inbox.org/git/?q= (amnong many), and any queries can be sent to git@vger.kernel.org but must be plain text (NO HTML, nor banned words) - slight delay for first submission, but otherwise not too frightening..

So main question is what would this protocol do?

**Comment by dscho** [comment]
> So main question is what would this protocol do?

That is an excellent question.

> The upstream list archive is available at https://public-inbox.org/git/?q= (amnong many), and any queries can be sent to git@vger.kernel.org but must be plain text (NO HTML, nor banned words) - slight delay for first submission, but otherwise not too frightening..

And this is indeed where this discussion should continue, as it is not Windows-specific (and the Git for Windows project is really short on hands to deal with non-Windows-specific issues...).
