### ISSUE TITLE
Git worktree and branch folder

### ISSUE THREAD

**Issue by tallichet** [git-for-windows/git#1390]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [version 10.0.16299.64]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**cmd**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**git worktree add feature/app1**
```
 - What did you expect to occur after running these commands?

**I expect a new folder feature with a sub folder app1. The new worktree should be linked to the feature/app1 branch**

 - What actually happened instead?

**The folder is created as expected. But The work tree is linked to a new branch named app1 (I have lost the "branch folder" named _feature_). This results in two separated branches.
In the root folder of the repository, I have an untracked files for feature/**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**have this with many repository**

**Comment by dscho** [comment]
> The folder is created as expected. But The work tree is linked to a new branch named app1 (I have lost the "branch folder" named feature).

Sadly, this is actually by design. The reason seems to be that the original author of the worktree command, @pclouds, intended it to be used with paths *outside* of the current Git project.

As a work-around, simply provide the same argument via `-b` again: `git worktree add -b feature/app1 feature/app1`.

**Comment by pclouds** [comment]
This is more about dwim-ing than paths outside the current git project. Yes only the last component of the given path is used for branch name when -b is not given. But how do you decide how many path components should become the branch name? what if you do "git worktree add ../foo/bar" when you're still inside the current project but at subdir "somewhere" instead of at the top directory?

If you can come up with good heuristics for this, feel free to suggest it on git mailing list.
