### ISSUE TITLE
Download wouldn't work

### ISSUE THREAD

**Issue by surajana** [git-for-windows/git#1396]
Hello, 

I'm trying to download git bash for windows through https://git-for-windows.github.io/

When I click on download it complains saying - "The request signature we calculated does not match the signature you provided. Check your key and signing method." Could you please check?

**Comment by shiftkey** [comment]
This is an incomplete report, and lacks details about your setup:

 - which version of Windows you are running
 - which browser you are using (and which version of it)

My initial gut feeling with this is that it's related to the release artifacts - which are hosted on GitHub's releases infrastructure - but given I've not heard other reports of this it appears to be an isolated incident.

**Comment by shiftkey** [comment]
I just tested this out on Windows `10.0.15063` and Microsoft Edge `40.15063.674.0` and was able to download the latest release without issue.

**Comment by surajana** [comment]
Apologies for incomplete information.

I am using Windows 7 professional (SP1). 
Tried both chrome (62.0.3202.94 64-bit) and IE (v11).

**Comment by dscho** [comment]
A quick web search for "The request signature we calculated does not match the signature you provided. Check your key and signing method." seems to suggest that this is an error message produced by Amazon Web Services, and since we do not use AWS' API directly, this might be location dependent, or some proxy problem, or an inadvertent change from `https` to `http`, so many things.

@surajana you could try to document as much about your particular setup/location/network configuration (including, if you don't want to type everything, screenshots) as possible, to increase the chances that anybody else may be able to reproduce the issue (or explain it).

**Comment by dscho** [comment]
> you could try to document as much about your particular setup/location/network configuration (including, if you don't want to type everything, screenshots) as possible, to increase the chances that anybody else may be able to reproduce the issue (or explain it).

Or not ;-)
