### ISSUE TITLE
Running scp returns an error `/usr/bin/ssh: No such file or directory`

### ISSUE THREAD

**Issue by c33s** [git-for-windows/git#1401]
needing rsync on windows made me search for rsync solutions for windows. 

there is 
- https://itefix.net/cwrsync
- http://repo.msys2.org/msys/x86_64/

i tested both and i have gone with cwrsync. the problem with cwrsync is, that it is not compatible with the ssh binary bundled with  git for windows.

```
dup() in/out/err failed
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
```

by deleting the `ssh.exe` shipped with git for windows, the problem was solved. `cwrsync` correctly uses its own ssh binary.

but now i have the problem, that `scp` bundled with gitlab for windows don't look for `ssh.exe` in the `$PATH`, it looks like it has the path hardcoded. i get the following error:

```
/usr/bin/ssh: No such file or directory
```

is there a way to tell `scp` to use the ssh provided in the `$PATH`?

```
$ which ssh
/c/home/bin/cwRsync/ssh
```

**Comment by c33s** [comment]
retested rsync from msys:

```
rsync --dry-run --checksum --verbose --chmod=ugo=rwX --progress --exclude .git --recursive --perms --times --group --owner hieradata/customer/company-name/ ../company-data/company-name/hiera
```
leads to the following error:
```
rsync: pipe: Operation not permitted (1)
rsync error: error in IPC code (code 14) at pipe.c(122) [sender=3.1.2]
```

**Comment by dscho** [comment]
> retested rsync from msys

Do you mean old MSys instead of [MSYS2](https://msys2.github.io/)? If so: that's too old to even *try* to support.

You can download the MSYS2 version of `rsync.exe` from the Git repository tracking Git for Windows' SDK: https://github.com/git-for-windows/git-sdk-64/blob/master/usr/bin/rsync.exe, and it should work by just dropping it anywhere on the `PATH`.

Please note, however, that even something as benign as this answer distracts me from supporting *Git* for Windows, i.e. Git users will not benefit from my help here.
