### ISSUE TITLE
fatal: error ummapping packed-refs file .git/packed-refs: Invalid argument

### ISSUE THREAD

**Issue by SteveALee** [git-for-windows/git#1410]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit
```
$ git --version --build-options

git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64

Fails in last few releases **but is OK in 2.14.0.windows.2**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10 Fall update 64 bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.125]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None I know of

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash or cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
anything - eg git status
```
 - What did you expect to occur after running these commands?

Output

 - What actually happened instead?

fatal: error ummapping packed-refs file .git/packed-refs: Invalid argument

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It fails with 2 private repositories I've had on my PC for ages. Originally bit bucket. Lots of big binary files
Other repositories are fine

The 2 that fail are in folders under my Documents folder

What can I run to give you some diagnostics?

**Comment by dscho** [comment]
> What can I run to give you some diagnostics?

Could you run [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) while executing the failing Git command?

Since those are private repositories, you will have to do the digging... The output in Process Monitor is a bit overwhelming at first, but you can easily filter it e.g. by finding an entry with `git.exe` as its process, right-clicking and then selecting "Include git.exe".

What I would look for would be the entries mentioning the `packed-refs` file and seeing whether the return value (most likely an error) says anything obviously wrong, leading the path to a deeper understanding of the root cause.

**Comment by Zeex** [comment]
I had the same issue today. Deleting `.git/packed-refs` fixed it. I'm not sure if this is safe to do, but I haven't noticed any damage so far.

**Comment by dscho** [comment]
> I had the same issue today. Deleting .git/packed-refs fixed it. I'm not sure if this is safe to do, but I haven't noticed any damage so far.

You most likely deleted all kinds of tags and branches. Not safe.

**Comment by Zeex** [comment]
I'm pretty sure all branches and tags are in place. I had this in multiple repos. Maybe I'm just lucky.

**Comment by dscho** [comment]
Or you are missing branches and tags you do not know about (remote-tracking ones, for example).

It is really not safe to go around `.git/` and delete files. Not safe at all.

**Comment by Zeex** [comment]
I agree, it was dumb. I had a backup.

If it helps, my `.git/packed-refs` was 0 bytes in size. In fact, if I move my existing `packed-refs` file and create a new one with `touch .git/packed-refs` I get the same error. My "valid" file contains only this line:

```
# pack-refs with: peeled fully-peeled sorted
```

**Comment by kgybels** [comment]
@Zeex Yes, that helps.

@dscho The problem happens because [xmmap_gently](https://github.com/git/git/blob/v2.15.1/sha1_file.c#L698-L699) returns null when mmap fails but length is zero. This leads to the problem of not knowing if we should call munmap or not, if mmap succeeds we should have a matching call to munmap.

I suggest adding a matching xmunmap to handle this case that needs to be used together with xmmap/xmmap_gently. See changes on my branch [mmap-zero-length](https://github.com/kgybels/git/commit/mmap-zero-length).

Bonus reproduction:
```
kim@DESKTOP MINGW64 /c/git/bug
$ ls
bug.sh*

kim@DESKTOP MINGW64 /c/git/bug
$ cat ./bug.sh
#!/bin/bash

git init example
cd example
touch .git/packed-refs
git status

kim@DESKTOP MINGW64 /c/git/bug
$ ./bug.sh
Initialized empty Git repository in C:/git/bug/example/.git/
fatal: error ummapping packed-refs file .git/packed-refs: Invalid argument
```

**Comment by SteveALee** [comment]
So pleased there's some progress! I had little luck finding useful info with procmon

**Comment by SteveALee** [comment]
Wahoo!
