### ISSUE TITLE
Installer does not ask where should it install this product

### ISSUE THREAD

**Issue by kasper3** [git-for-windows/git#1423]
In a typical windows installer, user is presented with a directory picker where it should install the product. The default value is a hardcoded string such as `C:\Program Files\git` or the path chosen during the previous installation.

Is it something we can expect from git installer in a foreseeable future?

PS I don't know which environment variable or registry value was set on my system, that it always installs git at some non-program-files location "c:\products".. that has started to happen when I once installed it from powershell command line (to rehearse docker step).

**Comment by shiftkey** [comment]
It's the first option you see when running the installer:

<img width="522"  src="https://user-images.githubusercontent.com/359239/34667590-048bbe2a-f440-11e7-9a3e-6979765db0c0.png">

**Comment by dscho** [comment]
IIRC if you installed it previously, it skips that page and installs into the same place. I would consider that a feature...

**Comment by kasper3** [comment]
> IIRC if you installed it previously, it skips that page and installs into the same place. I would consider that a feature...

The reason why I opened this issue..

**Comment by dscho** [comment]
@kasper3 as explained by @shiftkey, your report was incorrect in presenting it as if this was an issue always. I consider it a feature that it does not ask again where to install Git for Windows when you already made up your mind previously.

**Comment by PhilipOakley** [comment]
This feature is something that is usually useful, but occasionally very annoying (it happened to me a long while ago), in that most of the time the previous decision can still stand as being good, but occasionally, if one want to change something (i.e. this install location), then at the moment we don't (IIRC) provide the option to change anywhere (maybe on one of the other mandatory option pages?).

So if @kasper3 is able to create a PR that provides a good blend for both scenarios that that would be a nice to have.

**Comment by dscho** [comment]
@kasper3 if you want to do that, these two links should help you to get there:

1. https://github.com/git-for-windows/git/wiki/Making-an-installer (note that the file you will want to change is in `/usr/src/build-extra/installer/install.iss` once you followed those instructions)
2. https://www.jrsoftware.org/ishelp/index.php?topic=setup_usepreviousappdir

**Comment by kasper3** [comment]
That's right Johannes, the current behavior of installer affects user experience on "re-install only".
Sorry I do not have much experience with installers and C, so can't help there.
Not sure if the state of this issue remain closed by maintainers, will it ever get fixed by potential contributor..

**Comment by dscho** [comment]
> Not sure if the state of this issue remain closed by maintainers, will it ever get fixed by potential contributor..

Judging by your enthusiasm to get busy and fix your problem, I imagine that it does not matter whether this ticket is open.

It is an all-too-common fallacy I encounter many, many times: for some reason, there are people out there who think that tickets that are left open will -- by some miracle -- get the ticket addressed by _somebody_.

This is wishful thinking and seems to have little to do with reality.

In fact, this behavior -- ask for a change in behavior (that may, or may not, be perceived as enhancement by others) and then expect others (preferably somebody highly competent, somebody who is incidentally also willing to ask for nothing in return) to do all the work seems to be quite *discouraging*.

The best indicator that a ticket will get addressed: bug reporters who are willing to put in the work to get it fixed, and essentially asking for advice how to go about it.

**Comment by PhilipOakley** [comment]
@kasper3 clarifying, Issues are not locked to further contributions. The top level 'closure' was/is more of a triage by the lead maintainer so that it is easier to see the new and progressing issues. If we left open all issues that _might_ get a _bit_ of attention _eventually_ then we souldn't be able to see the wheat from the chaff.

A PR, even in draft, with bits missing (but noted as so) is very welcome, even to 'closed' issue, as long as it's making progress. 

To rephrase @dscho 's comment: It is not that the reporter has to provide a complete fully fledged fix to a problem that has totally eluded them. 

Rather it is that the issue reporter is/should be making small steps to assist in first nailing down (and reporting) the symptoms and the reproduction of the issue, along with the conditions, such as the OS version and worflow in use. 

With luck, some aspect of the fine detail of the reports will allow someone on the list to see a deeper pattern they have observed elsewhere (serendipity) so that a major step forward is suddenly taken. By exploting the problem we (and especially the reporter) will be able to 'learn by doing', which is the most effective type of learning.

Don't get disheartened by not knowing one of the code languages - they are all the same, being variants on pushing 1s & 0s. Gently breeze over the code till you spot something that you think you might understand, and start there.  Signing up for the mailing lsit means you see the code (especially the 'interesting' code) go by, and a bit of learning and understanding will rub off.

Remember that the Tortoise beat the Hare. Once you have cracked open the door the code will swing easily into view..

Oops hope I haven't droned on too much. If you have managed along the steps @dscho outlined, then do report it, please.

**Comment by kasper3** [comment]
Usually repo maintainers let the reporter decide when to close the issue as opposed to slapping doors on face, unless the issue is inactive for ridiculously long time.

> In fact, this behavior -- ask for a change in behavior

Woah easy, i am not *demanding* anything from you. I have reported something that I think is an issue, but now that you are saying it may or may not be perceived as enhancement.. though I am not seeing any fans of current behavior, scratch that.

**Comment by dscho** [comment]
@kasper3 I do not consider this a bug. It works as intended. If you disagree, it is your solemn duty to do something about it. That's all I had to say, and maybe this is even the last time I'll say it.
