### ISSUE TITLE
git status reports changes after git checkout -- .

### ISSUE THREAD

**Issue by LegalizeAdulthood** [git-for-windows/git#1438]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
```
c:\Code\iterated-dynamics\iterated-dynamics
> git checkout -- .

c:\Code\iterated-dynamics\iterated-dynamics
> git status
On branch dev
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   common/gifview.cpp
        modified:   common/lorenz.cpp
        modified:   headers/prototyp.h

no changes added to commit (use "git add" and/or "git commit -a")

c:\Code\iterated-dynamics\iterated-dynamics
> git checkout -- .

c:\Code\iterated-dynamics\iterated-dynamics
> git status
On branch dev
nothing to commit, working tree clean

c:\Code\iterated-dynamics\iterated-dynamics
>
```

 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by PhilipOakley** [comment]
Could this be a manifestation of the same issue as #1437 `git status` reports (non-existent) modifications after `git stash push` ? (and vice versa).

Can you create a simple test case (test reo) that shows the issue for this command sequence, so that any common areas can be identified (sounds like it has the same root cause, but without a minimal test case it woill be hard to check).

**Comment by tboegi** [comment]
What does 
git ls-files -s --eol | grep gifview.cpp
say ?

**Comment by dscho** [comment]
These _*insert here*_ placeholders should have been replaced before hitting the "Submit issue" button.

For this reason, this ticket is currently invalid.

**Comment by atetubou** [comment]
Sorry, I confrimed that my PR 89230f4a729e78b01226232474b38db8ccd92e21  introduced this regression.
Please revert the PR.

* test.sh
```sh
#!/bin/bash
set -eux

git init
echo A > test.txt
git add test.txt
git commit -m A
echo B >> test.txt
git checkout .
git diff  # no diff.

# content of test.txt is modified correctly
diff test.txt - <<EOF
A
EOF

git status  # test.txt is shown as modified file.

git checkout .  # retry
git status  # disappear test.txt
```

* expected output
```sh
$ bash test.sh
+ git init
warning: templates not found C:\src\git/share/git-core/templates
Initialized empty Git repository in C:/src/git/test/.git/
+ echo A
+ git add test.txt
+ git commit -m A
[master (root-commit) 4a4ba1b] A
 1 file changed, 1 insertion(+)
 create mode 100644 test.txt
+ echo B
+ git checkout .
+ git diff
+ diff test.txt -
+ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        test.sh

nothing added to commit but untracked files present (use "git add" to track)
+ git checkout .
+ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        test.sh

nothing added to commit but untracked files present (use "git add" to track)

```

* Actual output
```
$ bash test.sh
+ git init
Initialized empty Git repository in C:/src/git/test/.git/
+ echo A
+ git add test.txt
+ git commit -m A
[master (root-commit) d630ceb] A
 1 file changed, 1 insertion(+)
 create mode 100644 test.txt
+ echo B
+ git checkout .
+ git diff
+ diff test.txt -
+ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   test.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        test.sh

no changes added to commit (use "git add" and/or "git commit -a")
+ git checkout .
+ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        test.sh

nothing added to commit but untracked files present (use "git add" to track)

```

**Comment by atetubou** [comment]
After investigation, I understand how my commit broke git for windows when `git checkout .`.

git's index holds file timestamp to check file is modified in fastpath.
My change made lstat return cached stat after checkint out the modified file.

When we run `git checkout`, [checkout_paths](https://github.com/git-for-windows/git/blob/v2.16.0.windows.2/builtin/checkout.c#L242) calls [checkout_entry](https://github.com/git-for-windows/git/blob/v2.16.0.windows.2/builtin/checkout.c#L367).
In [checkout_entry](https://github.com/git-for-windows/git/blob/v2.16.0.windows.2/entry.c#L409), [write_entry](https://github.com/git-for-windows/git/blob/v2.16.0.windows.2/entry.c#L476) was called having [lstat](https://github.com/git-for-windows/git/blob/v2.16.0.windows.2/entry.c#L372) where stat should be got from actual disk.
But due to this stat is taken from fscache, git index holds old file timestamp and `git status` shows the file is changed even after running `git checkout .`.

I should check the behavior carefully. Sorry again.

**Comment by orgads** [comment]
Looks related: https://github.com/git-for-windows/git/issues/1442

**Comment by PhilipOakley** [comment]
> I should check the behavior carefully. Sorry again.

It is easy to be wise after the event. It is good that you have identified the cause, and with luck and a following wind, a fix soon. There have been other problems from upstream so you are in good company. Once resolved the speed upshould still be useful.
