### ISSUE TITLE
Git for Windows v2.16.0 release - add link to Git 2.16.0 RelNotes

### ISSUE THREAD

**Issue by kkolinko** [git-for-windows/git#1448]
The release announcement for Git for Windows 2.16.0(2) at [1][2] is missing the usual "Comes with Git v2.16.0." item.

[1] https://github.com/git-for-windows/git/releases/
[2] https://github.com/git-for-windows/git/releases/tag/v2.16.0.windows.2

The Git 2.16.0 release notes to link here are at:
https://github.com/git/git/blob/v2.16.0/Documentation/RelNotes/2.16.0.txt

The notes for upcoming 2.16.1, tagged a few hours ago:
https://github.com/git/git/blob/v2.16.1/Documentation/RelNotes/2.16.1.txt

**Comment by dscho** [comment]
Bah, I am already deep in the release engineering of Git for Windows v2.16.1. It will *also* lack this customary link :-(

How is your Unix shell fu? It would make most sense to add code to the script used for release engineering...

Come to think of it, I thought I had done that.

*Clicketyclick*

Yep! https://github.com/git-for-windows/build-extra/blob/1e3dbc35431b0b7201a9b4b733b61ae3bb697646/please.sh#L3113-L3122

The reason it was missing was that due to a number of unfortunate coincidences, v2.16.0 was never released, but v2.16.0(2) instead (see https://github.com/git-for-windows/git/issues/1433). The script assumes that (2) versions do not need the link *again*.
