### ISSUE TITLE
Random "Permission denied" when adding submodules

### ISSUE THREAD

**Issue by Myllyenko** [git-for-windows/git#1469]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.1
cpu: x86_64
built from commit: 1a4ee4d5d83bbba63f6d8b71c427f627769f3386
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.192]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

CMD is being run as an Administrator.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I'm unable to provide a verifiable example as the issue occurs absolutely randomly with

```
git submodule add http://<any-repo-on-my-company's-private-git-lab-server> <any-path-to-module>
```
 - What did you expect to occur after running these commands?

Something like this:

```
Cloning into '<full-path-to-module>'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 8 (delta 2), reused 0 (delta 0)
Unpacking objects: 100% (8/8), done.
```

 - What actually happened instead?

After
```
Cloning into '<full-path-to-module>'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 8 (delta 2), reused 0 (delta 0)
Unpacking objects: 100% (8/8), done.
```
`fatal: could not open '<full-path-to-module>/.git' for writing: Permission denied` in console, <full-path-to-module> contains only the .git subdirectory and there is no new module in .gitmodules.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This issue occurs absolutely randomly. For example, I've been experimenting with adding one repo as different submodules of one project and some of them were created successfully while others were not.

Then I tried to reproduce the issue with my GitHub project and many times `git submodule add` worked fine. Now I'm unable to reproduce it neither with a public nor with a private repo.

**Comment by dscho** [comment]
This sounds like an antivirus or something similar might be interfering...

Sorry, that's the only suggestion that comes to mind so far.

**Comment by Myllyenko** [comment]
Maybe you can suggest any debugging facilities in Git that I can enable to try to pinpoint the issue?

**Comment by dscho** [comment]
The most straight-forward way to test my hypothesis might be to add an exclusion to the path into which you want to clone your repository with submodules, before actually cloning it.

**Comment by Myllyenko** [comment]
@dscho I've excluded `Git\mingw64\libexec\git-core\git-remote*.exe` from Windows Firewall's scope. Hope this will help.

**Comment by dscho** [comment]
Great! Please let us know how this experiment goes.

**Comment by dscho** [comment]
I assume it helped.

**Comment by Myllyenko** [comment]
@dscho Unfortunately not :)

**Comment by dscho** [comment]
So how did your experiment go?

**Comment by dscho** [comment]
(BTW the exclusions would have to be in the antivirus, not the firewall, and not for Git's executables but for the paths for which you see the "Permission denied" errors.)

**Comment by Myllyenko** [comment]
Test scenario: import the same submodule to different subpaths in a target repo two dozen times.

Environment: no third-party firewalls and antiviruses, only those embedded in Windows.

Test 1: antivirus is off (completely), firewall is on -> one import failed.
Test 2: antivirus is off (completely), firewall is off -> all imports were successfull. But it does not mean that this test will not fail on some next iteration.

**Comment by dscho** [comment]
> But it does not mean that this test will not fail on some next iteration.

No, but it means that we now have evidence that the firewall may actually have something to do with it (contrary to my previous beliefs).

Hmm.

Or it may have something to do with the active firewall making certain lock contention issues more likely. As in: if multiple Git operations are in effect at the same time, *and* one of those operations wants to read the `.git` file (for submodules, it is a file) *and* another of those operations wants to write that `.git` file (probably with the exact same contents), then we get this nasty situation.

It would seem that the write operation in question is performed in the `connect_work_tree_and_git_dir()` function: https://github.com/git-for-windows/git/blob/e1848984d1004040ec5199e749b5f282ddf4bb09/dir.c#L3034-L3067

This function is called, unsurprisingly, from `git submodule--helper clone`: https://github.com/git-for-windows/git/blob/e1848984d1004040ec5199e749b5f282ddf4bb09/builtin/submodule--helper.c#L925-L926

And since nothing in either function verifies that that file had not existed before (let alone that it already has the intended contents), we run into this situation.

Now, this is only a Windows-specific problem insofar that it is worse because of the locking issues (a file that is being read cannot be written at the same time, Linux allows this). But Linux could run into even worse problems when one process tries to read the `.git` file while another one tries to write *different* contents to it.

So I think we should report this to the Git mailing list, which I will do later today.

**Comment by Myllyenko** [comment]
@dscho Thank your for this analysis!
I'll try to find more information about the issue.

**Comment by dscho** [comment]
Posted here: https://public-inbox.org/git/nycvar.QRO.7.76.6.1802201709570.31@ZVAVAG-6OXH6DA.rhebcr.pbec.zvpebfbsg.pbz/T/#u
