### ISSUE TITLE
Unable to install git for windows SDK 64bit

### ISSUE THREAD

**Issue by pekof** [git-for-windows/git#1479]
When I try https://dl.bintray.com/git-for-windows/pacman/x86_64/git-for-windows.db
I get "Forbidden!"

Running install::
---------------------------------------------------------------
:: Synchronizing package databases...
error: failed retrieving file 'git-for-windows.db' from dl.bintray.com : The req
uested URL returned error: 403
error: failed to update git-for-windows (unexpected error)
 mingw32                  378.5 KiB   830K/s 00:00 [#####################] 100%
 mingw32.sig               96.0   B  46.9K/s 00:00 [#####################] 100%
 mingw64                  378.6 KiB  1434K/s 00:00 [#####################] 100%
 mingw64.sig               96.0   B  46.9K/s 00:00 [#####################] 100%
 msys                     159.8 KiB   883K/s 00:00 [#####################] 100%
 msys.sig                  96.0   B  46.9K/s 00:00 [#####################] 100%
error: failed to prepare transaction (could not find database)

There was a problem accessing the MSYS2 repositories
If your setup requires an HTTP proxy to access the web,
please specify it here, otherwise leave it empty.

HTTP proxy:

**Comment by dscho** [comment]
Indeed. This is a huge problem right now!

Explanation: we currently use BinTray to serve our Pacman repository. At some stage last Friday, during the frenzy to get v2.16.1(2) released, I apparently hit some threshold and BinTray "rate-limited" us "due to overuse".

Except that it did not rate-limit us. Instead, it now forbids any download of any file we ever uploaded.

I am in the process of moving to Azure Blob Service, which will also have the nice benefit of being a lot more reliable than BinTray (there have been tons of inexplicable timeouts, and I cannot tell you how much time I sank into working around this, and at other times BinTray's status page claimed that everything was green when in reality all uploads failed without good error messages).

**Comment by dscho** [comment]
FWIW Git for Windows' Pacman repositories moved to Azure Blobs.

So what does that mean for you, dear reader, who may have found this ticket in search of a solution to getting a working Git for Windows SDK?

# Fixing existing SDKs

You can fix your existing SDK (if you installed it successfully before Friday, February 2nd 2018) by downloading either

- https://wingit.blob.core.windows.net/x86-64/git-extra-1.1.241.91af289c6-1-x86_64.pkg.tar.xz for 64-bit SDKs, or
- https://wingit.blob.core.windows.net/x86-64/git-extra-1.1.241.91af289c6-1-i686.pkg.tar.xz for 32-bit SDKs,

and then executing `pacman -U <downloaded-file>`. This will have the main effect of updating your `/etc/pacman.conf` so that a subsequent `pacman -Syu` will find the new home of Git for Windows' Pacman repositories.

# Initializing a new SDK

If you did not yet have a working SDK, the [installer as per Git for Windows' home page](https://gitforwindows.org/#download-sdk) will not work (I hope that we get all of this sorted out this week).

The idea is to support a completely new, more robust method of obtaining a working SDK:

```cmd
git clone --depth 1 https://github.com/git-for-windows/git-sdk-64
```

(or `.../git-sdk-32` for 32-bit setups) and then call `git-bash.exe` in the top-level directory of the checkout.

(These repositories are essentially synchronized by a scheduled job running on Visual Studio Team Services, and the set of installed packages was chosen so as to support the most common operations developer would want to perform in a Git for Windows SDK.)

This does already work! However, there is currently a bug in Git that prevents fetches/clones from working unless `http.sslBackend` is configured (which the Git for Windows installer does, hiding the issue). So if you just call `git config --system http.sslBackend schannel` in the Git Bash before cloning anything, you should be fine.

## Future work

I plan on doing a couple more things in the git-sdk-* repositories, and every bit of help with those tasks will be greatly appreciated:

- add a `README.md` explaining the purpose, the most common operations, context and design
- modify [`/etc/profile.d/git-sdk.sh`](https://github.com/git-for-windows/build-extra/blob/master/git-extra/git-sdk.sh) so that it auto-initializes the `git`, `build-extra`, `MINGW-packages` and `MSYS2-packages` worktrees in `/usr/src`: they should only be `git init`'ed and `git add remote origin ...`, but *not* fetching anything yet. They can then be initialized on demand by e.g. `git -C /usr/src/git pull origin master`
- ensure that a regular clone works, especially 32-bit, where some of the files seem to be committed with incorrect line endings
- modify the git-sdk-installer to use the new method instead
- maybe add an `/etc/motd` that describes how to build stuff, how to bundle a custom installer, how to keep the SDK up-to-date, etc. Or maybe a helper. Dunno.

**Comment by dscho** [comment]
> However, there is currently a bug in Git that prevents fetches/clones from working unless http.sslBackend is configured (which the Git for Windows installer does, hiding the issue). So if you just call git config --system http.sslBackend schannel in the Git Bash before cloning anything, you should be fine.

For the record: this should no longer be necessary, as the Git for Windows SDK was updated with Git for Windows v2.16.1(3).

**Comment by dscho** [comment]
Actually, the rest of what needs to be addressed in this ticket is properly described here: https://github.com/git-for-windows/git/issues/1357. So I will close this here ticket now and continue in the other ticket (which I hoped some enthusiastic volunteer could pick up, because it really is a fun project, and I have to address quite a few non-fun projects in the meantime that I do not want to burden anybody else with).

**Comment by bbolli** [comment]
The correct link for the 32-bit package is https://wingit.blob.core.windows.net/i686/git-extra-1.1.241.91af289c6-1-i686.pkg.tar.xz. The architecture path component is `i686` for 32 bit.

**Comment by dscho** [comment]
@bbolli d'oh, of course! Thanks!

**Comment by dscho** [comment]
@bbolli FWIW I updated the comment accordingly.
