### ISSUE TITLE
Perl missing dll

### ISSUE THREAD

**Issue by DraakUSA** [git-for-windows/git#1486]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]

64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
perl -v
```
 - What did you expect to occur after running these commands?

perl version information

 - What actually happened instead?

```
C:/Program Files/Git/usr/local/bin/perl: error while loading shared libraries: msys-perl5_22.dll: cannot open shared object file: No such file or directory
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

 - Additional info

I went to C:\Program Files\Git\usr\bin and found msys-perl5_24.dll and copied it to msys-perl5_22.dll, and did the same in C:\Program Files\Git\usr\lib\perl5\core_perl\CORE

This allowed perl to run.  However, perl is responding with yet another version:

```
$ perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-msys-thread-multi

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by bbolli** [comment]
> C:/Program Files/Git/usr/local/bin/perl

That's strange; the standard perl.exe is in `/usr/bin`, i.e. `C:/Program Files/Git/usr/bin` and is version 5.24 in the released Git for Windows.

Try running `/usr/bin/perl -v`.

Did you build a more recent Perl yourself?

**Comment by dscho** [comment]
> > `C:/Program Files/Git/usr/local/bin/perl`
> 
> That's strange; the standard perl.exe is in /usr/bin, i.e. C:/Program Files/Git/usr/bin.
> 
> Try running /usr/bin/perl -v.

Indeed. There is not even a `/usr/local` in a regular Git for Windows installation.

I *strongly* suspect that there is something going on that should have been in the answer to "Any other interesting things about your environment that might be related to the issue you're seeing?"

@DraakUSA you probably have copied custom stuff to `C:\Program Files\Git\usr\local\bin`, yes?

(It cannot be a left-over from Git for Windows 1.x days, as there was not even a `/usr/bin` back then.)

> The perl5.26.1 package indeed has the wrong DLL:

@bbolli indeed. However, the reporter mentioned `msys-perl5_22.dll`, not `msys-perl5_24.dll` nor `msys-perl5_26.dll`. So the problem you identified is independent, and does not, in fact, prevent `perl -v` from working in a regular Git for Windows v2.16.1(4):

```sh
$ perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-msys-thread-multi

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

> It should contain msys-perl5_26.dll, no? Offending line: https://github.com/git-for-windows/MSYS2-packages/blob/e9ccd752a8a59faabcb0aad8ec1808d34f1b76b1/perl/PKGBUILD#L209

Yes. Since you already figured it out, how about relieving me of even more maintenance burden and open a Pull Request? Thanks in advance!

**Comment by DraakUSA** [comment]
You are correct, there was a perl executable in /usr/local/bin (the only thing in that directory).  I have no idea how it got there.  I deleted it, and deleted the 5_22 dlls I created.  perl -v now reports correctly 5.26 (even though the dlls are actually 5_24.  Thank you for the assist.

**Comment by dscho** [comment]
I am glad it works for you now.

**Comment by dscho** [comment]
> > The perl5.26.1 package indeed has the wrong DLL:
> 
> @bbolli indeed.

Not trying to blame anybody, but... it took 3 days to clean up the mess caused by that rename.

The reason? The name of the `.dll` is hard-coded in any user, be it `perl.exe`, any core Perl module with native code, and most crucially any non-core Perl module with native code. That latter includes `perl-Net-SSLeay`, `perl-HTML-Parser`, `perl-TermReadKey`, `perl-Locale-Gettext` and `subversion`, most of which I never had to build myself but simply consumed from MSYS2. I think in hindsight, I would probably not have renamed that `.dll` because it is just a cosmetic issue as far as Git for Windows is concerned: we do *not* encourage end users to build their own Perl modules against Git for Windows' Perl.
