### ISSUE TITLE
Moving hidden Folders to the parent directory with git mv does not work

### ISSUE THREAD

**Issue by Treppenhouse** [git-for-windows/git#1506]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
 
```
Given is the following directory structure:
.
|-- .git
|
`-- someFolder
    |-- .abc
    |   `-- file.txt
    |-- .def
    |   `-- file.txt
    `-- .ghi
        `-- file.txt
```
Here I would like to move all (hidden) folders from `someFolder` together with their files one directory up in the parent directory.
Using the `mv` command this yields: 
```
$ mv someFolder/.* .
mv: cannot move 'someFolder/.' to a subdirectory of itself, './.'
mv: cannot move 'someFolder/..' to a subdirectory of itself, './..'

$ ls -la
total 16
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:51 ./
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:23 ../
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:45 .abc/
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:45 .def/
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:45 .ghi/
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:47 .git/
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:51 someFolder/
```
 So there is a warning but it works.

Trying to do the same with `git mv` however does not work:
```
$ git mv someFolder/.* .
fatal: '..' is outside repository

$ ls -la
total 16
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:53 ./
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:23 ../
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:53 .git/
drwxr-xr-x 1 ENHMZ 1049089 0 Feb 19 12:53 someFolder/
```

 - What did you expect to occur after running these commands?
I would expect the behaviour of `git mv` to be aligned with `mv`. Furthermore, there is not a trivial way to move several hidden directories to the parent folder using `git mv` at least not that I know of.

**Comment by dscho** [comment]
The problem is not so much on Git's (or Bash's) side... the problem is the pattern.

If you call `ls -d .*`, you will see what I mean: this pattern not only matches the hidden directory you intend to move, but also `.` (i.e. the current directory) and `..` (i.e. the parent directory of the current directory).

Obviously, you cannot move `.` nor `..`.

And Git even tells you why it cannot (and won't) move `..`: it *is* outside the repository, as your current directory is already the top-level directory of the Git worktree, and its parent directory really is outside the repository, fair and square.

The solution to your problem is to provide a stricter pattern, e.g. `.[a-z]*`, as in:

```sh
git mv someFolder/.[a-d]* someFolder/.ghi ./
```

By the way, you cannot move `.git/` using `git mv`. That directory contains the repository itself. Besides, Git will helpfully error out, saying that this folder does not contain tracked files (it can't).

Oh, and since you want to move directories from a folder that contains a `.git/` directory and is therefore its own, nested Git worktree, I am fairly certain that you cannot move those folders into the current directory, as it is part *of a different Git worktree*.

**Comment by Treppenhouse** [comment]
Thanks for the reply! The idea with the pattern much better.

Still, I think the fact that `mv` which obviously has the same problem with the `.` and the `..` directory does perform the move while `git mv` does not is a bit confusing/unexpected.

**Comment by dscho** [comment]
@Treppenhouse `mv` is just a bit lax. It was a conscious decision to make `git` a bit stricter (i.e. refuse to do half the job, warning about the other half that was not done). This not only extends to `mv`, by the way: `git apply`, for example, is a lot stricter than GNU `patch`. And `git pull --rebase` (which imitates a bit what `svn update` would do) refuses to run if there are unstashed changes (unlike `svn update`).

Also please remember that `mv` is part of a completely different software project than `git mv`. Those projects are run *very* differently. You should not try to hold them to the same standard.

And lastly, this is not a Windows-specific issue that you are complaining about. So a better place for those complaints would be [the Git mailing list](https://git-scm.com/community).
