### ISSUE TITLE
Sign the installers

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#155]
In this time and age, trust is a commodity that needs to be backed up by digital signatures. That means that this maintainer needs to get a code signing certificate and use the SDK's `signtool.exe` to provide the proof that the Git for Windows installer indeed originates from the Git for Windows maintainer and nobody else.

**Comment by bviktor** [comment]
I've been fiddling around with this recently. If you need something cheap, K Software has the best value, they're a Comodo reseller company and a 1 year code signing cert costs just 95 bucks. We've been using this for a few years.

If you need something more robust, DigiCert is pretty good, their price is 223 bucks a year and they're one of the only 2 issuers whose certs are accepted for Windows Store apps. Although this is pretty irrelevant for msysgit2, at least for now, but there may be other advantages, too.

**Comment by nalla** [comment]
There is also https://startssl.com

**Comment by dscho** [comment]
Heh, @bviktor "msysgit2"? Nope...

As to which provider: I already settled for Certum which offers the certificate free of charge for Open Source. That beats any other alternative, especially because I would have to pay for this from my own money while I would not even benefit from it, because I already trust myself very much.

**Comment by dscho** [comment]
> I already settled for Certum which offers the certificate free of charge for Open Source.

For the record, I followed the excellent advice given in http://pete.akeo.ie/2011/11/free-code-signing-certificate-for-open.html.

**Comment by bviktor** [comment]
Yeah, I also saw that, I just never tried them so I didn't want to suggest something that I don't trust yet :)

The new Git for Windows release will rock ;)

**Comment by pfumagalli** [comment]
I *think* this might be due to the lack of signature, but just FYI, all the binaries seems to be identified as "WS.Reputation.1" (and quarantined) by Symantec/Norton antivirus.

**Comment by dscho** [comment]
> I think this might be due to the lack of signature, but just FYI, all the binaries seems to be identified as "WS.Reputation.1" (and quarantined) by Symantec/Norton antivirus.

Wrong ticket? Did you maybe mean to comment on a ticket commenting on false positives with anti virus software?

**Comment by pfumagalli** [comment]
Nope, I think this is the correct thread :-) Sorry if I didn't explain myself more verbosely.

Basically "WS.Reputation.1" is not really a virus signature, it just means that the Symantec/Norton doesn't know the binary "well enough" (it hasn't built a reputation for it) and will simply forbid to execute it, slapping it in quarantine.

There was a long thread few years back on [YCombinator](https://news.ycombinator.com/item?id=4152539) precisely about this, and one of the most important factors (although it doesn't 100% guarantee it) in order to avoid being identified as a false positive was precisely to sign binaries (your reputation goes up).

For now, I managed to get local IT here to nuke Symantec/Norton from my dev box, so I'm happy, but as the release date approaches you might find more people (especially in corporate environments) with the same issue, and just wanted to make a note of it!

**Comment by dscho** [comment]
> as the release date approaches you might find more people (especially in corporate environments) with the same issue, and just wanted to make a note of it!

Well, I opened the ticket already, and I even acted on it, so I have the code signing certificate. All I need to do is make sure that I sign the installers before uploading them.

**Comment by dscho** [comment]
Done, the installers of the release candidate are all signed. Now, the only problem is that I must not forget to sign the installers when making releases ;-)

**Comment by bviktor** [comment]
Yay!

**Comment by pfumagalli** [comment]
I can confirm that with the signature Symantec/Norton does not have issues with the binaries anymore. False positives all gone! :+1:
