### ISSUE TITLE
sendemail support in gitconfig

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#160]
Based on lots of trial and error, back in the msysgit days (last time I worried about it), one could not simply use the `sendemail` config options in git to configure email SMTP servers for sending email. I had to setup a `~/msmtprc.txt` file with that information.

I share my global `.gitconfig` across multiple platforms so it would be useful to store my email / smtp settings in the git config instead of a windows-specific text file. Is there better support for this in git SDK?

If not, it would be nice to see support implemented for this. Maybe just a simple layer that propagates settings from the git config `sendemail` values to an auto-generated `msmtprc.txt` file.

**Comment by dscho** [comment]
In Git for Windows 1.x, we compiled `msmtp` ourselves. In Git for Windows 2.x, we use the packages of [the MSys2 project](https://msys2.github.io/). You could contribute support for `msmtp` as a MINGW-package to https://github.com/Alexpux/MINGW-packages and then open a Pull Request to reinstate support to Git for Windows 2.x.

**Comment by rcdailey** [comment]
Are you saying that sending email doesn't work here? What exactly do you mean when you say you use the packages of MSYS2 project? Does that mean that it behaves the same as it would on Linux (as far as configuration is concerned)?

**Comment by dscho** [comment]
Git for Windows is very different from Git for almost everything else in one important respect: Windows does not provide the POSIX infrastructure Git expects.

Therefore, we always had to ship with much more than any other Git distribution: we have to provide a Bash, a Perl, many POSIX tools such as `sed`, `awk`, `tr`, etc.

Git for Windows 1.x did that by starting off from an MSys installation and just packaging all the required files as-are. MSys did not sport any package manager at the time I started Git for Windows, so all of the updates were quite manual, and some of the components we shipped were not even part of MSys -- such as `msmtp` or `WhoUses` -- so we had to compile them from scratch, and maintain those components ourselves.

This became really too tedious, so much so that when I was bogged down with day job, I simply did not have the time to provide updated Git for Windows installers.

At some stage, it became obvious that I needed a better solution. @sschuberth had already started a separate project to leverage the package manager that MSys had introduced at that stage, `mingw-get`. However, it turned out that the packages were not maintained all that well, and besides, MSys' runtime had not been kept up-to-date with Cygwin, and was falling behind in terms of features and support.

In a two-hour Skype session about the course of Git for Windows with @t-b and @sschuberth, we decided to give MSys2 a whirl. MSys2 was started with the idea to restart the MSys project, frequently updating with Cygwin and just keeping the spirit of MSys to provide a very stripped-down POSIX layer, essentially a bare-minimum version of Cygwin. MSys2 also sports a package manager (`pacman`) and keeps those packages up-to-date very well. Another bonus: MSys2 is available for 64-bit in addition to 32-bit, while MSys was stuck with 32-bit.

Thanks to sponsoring of GitHub, I could afford to spend the time to investigate the possibilities with MSys2. It turned out that MSys2 already provided most of the parts we needed, and would make maintenance much, much easier. I really spent an insane amount of time (thanks GitHub!) to get everything up to speed, even fixing a couple of long-standing bugs in Git for Windows.

And yes, the idea is still the same as the original one: I basically update my MSys2 setup, together with a Git package built from Git for Windows' source code, then bundle the relevant files together with a couple of extra files into an installer. Then I sign it and upload it. And that is Git for Windows 2.x.

Now, keep in mind that MSys2 and Linux are very different beasts. Their distributions might include packages that are built from the same source code (i.e. the `binutils`, `gcc` or `bash` package), but the runtime is very, very different: MSys2's runtime is a stripped-down, slightly modified Cygwin runtime running on top of the Windows kernel, while Linux' runtime is the Linux kernel, running as a separate OS altogether.

To answer your question about "Does that mean that it behaves the same as it would on Linux?": No, it does not. It is close, but it is *definitely* not the same.

Now, with what I just described to you, you will understand that supporting sendemail is not as easy as flipping a switch, or installing one additional package. It would be if that package existed, but it does not.

This is Open Source, however, so everybody interested and capable enough can contribute whatever they need to address their needs. And that includes you: you could imitate e.g. https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-assimp-git/PKGBUILD to open a Pull Request to build [`msmtp`](https://github.com/tpn/msmtp), the component that Git for Windows 1.x uses to support sendemail. Our documentation will be helpful in that endeavour: https://github.com/git-for-windows/git/wiki/Package-management, in particular https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages.

**Comment by rcdailey** [comment]
Thanks for the history explanation. I think that's super valuable information. In fact, so valuable, that it would be a shame for it to exist only in this Github issue. Perhaps you should move that to a wiki page for others to benefit. It's always been a mystery to me as to how and why the project migrated.

I'm happy to help when and where I can, that's not an issue. I guess as a side-question I'm asking: How does one support send-email currently, as things already are in git for windows 2.x? Is it simply non-functional at the moment, or am I missing some instructional documentation somewhere?

I'm assuming that `msmtp` is only one method of implementing it and perhaps another already exists simply to say you shipped Git for Windows with support for this.

Thanks again for the info.

**Comment by dscho** [comment]
> Thanks for the history explanation. I think that's super valuable information. In fact, so valuable, that it would be a shame for it to exist only in this Github issue. Perhaps you should move that to a wiki page for others to benefit

Well, it probably is not obvious, but it took me almost one hour to write this. And I am busy with other tickets that I would have to neglect if I were to write that Wiki page. Maybe you could help?

> How does one support send-email currently, as things already are in git for windows 2.x?

As far as I know, nobody tried to set up sendemail with Git for Windows 2.x yet, until you came around.

> I'm assuming that msmtp is only one method of implementing it and perhaps another already exists simply to say you shipped Git for Windows with support for this.

It would definitely be the easiest method. There are other options, of course, but they all appear more involved to me than just getting msmtp to compile, bundle it as a Pacman package and use it as we used it in Git for Windows 1.x.

**Comment by nalla** [comment]
See https://github.com/git-for-windows/git/wiki for that wiki text

**Comment by dscho** [comment]
@nalla you are awesome!

**Comment by dscho** [comment]
@rcdailey so... what's the status?

**Comment by rcdailey** [comment]
Honestly I've been so busy with work that I completely forgot about this. Let me add a note for myself to look into this tonight when I get home. It can't be that hard to just add a new package.

**Comment by rcdailey** [comment]
I'm working on setting up the `PKGBUILD` for msmtp. I am basing this off of your fork in the git-for-windows list of repositories. I planned to initiate the PR there, unless you want it to go upstream instead. Let me know.

I've never done a `PKGBUILD` before, so I'm stuck on a few things. I'm using [this `PKGBUILD`][1] as a reference. Some questions below, if you don't mind helping me.

1. What do I use as `sha1sums`? Supposedly this is the SHA1 of the source code, but if all I'm providing is a link to the github repository, how does it know which commit to checkout? If it's following HEAD, the sha1 calculation would have a different result. I'm just not sure how to calculate this and I can't find any information on it.
1. The `source` field I have set to:

        source=("${_realname}"::"git+https://github.com/tpn/msmtp.git")

 Is this correct? What I've done is copied the `assimp-git` package and am modifying it specifically for `msmtp`. I guess the `-git` prefix is to indicate that it connects to a git repository to build it.
1. Could you pass along the build commands you used for msmtp when you compiled it for msysgit? Do you have a build script hosted somewhere I can use as a reference? I'm assuming the actual commands we'll use to build msmtp won't change across these 2 fundamentally different packages of git.

Thanks in advance. If I think of any more questions I'll let you know.

[1]: https://projects.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/msmtp

**Comment by sschuberth** [comment]
@rcdailey 

1. In that case, just use the literal word `SKIP` instead of the SHA1.
2. Looks correct to me.
3. You should be able to retrieve the build commands from [here](https://github.com/msysgit/msysgit/blob/master/src/msmtp/release.sh).

**Comment by dscho** [comment]
@rcdailey any progress?

**Comment by rcdailey** [comment]
Sorry for the late response. I'm going to withdraw myself from this one. I've made no significant progress nor do I feel I will be able to get back to this.

**Comment by PhilipOakley** [comment]
> Sorry for the late response. I'm going to withdraw myself from this 
> one. I've made no significant progress nor do I feel I will be able to 
> get back to this.
—
Is your earlier work available publicly to give something to work on?

--
Philip

**Comment by rcdailey** [comment]
@PhilipOakley As I stated, I made no significant progress, so I have nothing to share really. I wish I had more to give, sorry guys.

**Comment by dscho** [comment]
That's quite a bit disappointing.

**Comment by dscho** [comment]
@rcdailey it was actually not at all difficult, but it would have relieved me of yet another task if this was a proper "quid pro quo" and not a "quid pro quid" all the time.

May I ask you at least to test? https://github.com/dscho/MINGW-packages/releases/tag/msmtp-tmp

**Comment by rcdailey** [comment]
I have no idea what you're talking about. What is that in English?

**Comment by rcdailey** [comment]
@dscho Not sure what your "quid pro" stuff was all about, but it feels like you're upset that I didn't finish the work. Well, I'm not paid to do this nor do you have the right to be upset (I can't be upset with you for not working on stuff I want you to do).

I always felt you or someone else was a better candidate to complete this item, because I simply do not have the domain knowledge necessary to do it. I had to spend most of the time I spent on this learning anyway. I could rarely find the information I want, and it was frustrating trying to convince people to help me. I'm glad you feel the task was not difficult, that is all the more reason I'm glad you did it. I probably wouldn't have done it correctly anyway and you would spend *more* time coaching me on fixing it. I originally offered to do this because it didn't seem that difficult.

And no, sorry, I can't test it. I am happy to test it once it ships with an actual release of Git for Windows. Thanks for your contribution!

**Comment by dscho** [comment]
For lurkers finding this ticket: I just got confirmation by @kusma that `git send-email` works without `msmtp` in Git for Windows 2.x.

Thanks, @kusma!

**Comment by t9nf** [comment]
Saudis in the audies🐮 👌
