### ISSUE TITLE
GIT Command is dissapearing after opening

### ISSUE THREAD

**Issue by rameshp14587** [git-for-windows/git#1640]
Hi,
I’m using GIT software to clone, commit, push and pull the code, but my GIT command prompt is disappearing after opening, please do needful in this concern.

**Comment by dscho** [comment]
Hi @rameshp14587, I am sorry that you have encountered a problem.

However, by simply removing the issue reporting template (instead of filling it out diligently, as you were supposed to do), you now created another problem... There really is no substitute for a careful bug report, so please provide one!
