### ISSUE TITLE
diff filter for utf-16 encoded files

### ISSUE THREAD

**Issue by crea7or** [git-for-windows/git#1689]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Why not to include diff filter for utf-16 encoded files? Every setup I modify git for viewing diffs of these files from Visual Studio windows native apps: app.rc and resources.h files. There is no need to include huge iconv since Windows can convert utf-16 to utf-8 easily and I have [build a small (9kb)](https://github.com/crea7or/wiconv) tool that convert these files on the fly ( only if needed, because they can be ASCII in the older Visual Studio versions ).

**Comment by crea7or** [comment]
I think that Visual Studio uses only little-endian, however it's not really hard to add few lines to the conversion code. Again, it's not for every utf-xx file, only for resource files in Windows native projects in Visual Studio.

**Comment by bbolli** [comment]
Quoting [the relevant commit](https://github.com/git/git/commit/107642fe2661236f48b912480e090799e339c512):

> 
>  convert: add 'working-tree-encoding' attribute
> 
> Git recognizes files encoded with ASCII or one of its supersets (e.g.
> UTF-8 or ISO-8859-1) as text files. All other encodings are usually
> interpreted as binary and consequently built-in Git text processing
> tools (e.g. 'git diff') as well as most Git web front ends do not
> visualize the content.
> 
> Add an attribute to tell Git what encoding the user has defined for a
> given file. If the content is added to the index, then Git reencodes
> the content to a canonical UTF-8 representation. On checkout Git will
> reverse this operation.

So you define your files as UTF-16 and Git will convert to this on checkout and back to UTF-8 on `git add` for storage in the index and blobs. What do you think is missing?

**Comment by crea7or** [comment]
Is there 100% guarantee that these files will be in utf-16 at checkin? Should everyone update git to the latest version and set some options in local git config? There is only problem with viewving diffs of utf-16 files and it can be done without conversion at every checkin/checkout. There is no advantage of keeping these files in utf-8 internally in git.

**Comment by bbolli** [comment]
What I mean to say is: I think it's not useful to add a feature to Git for Windows now that will be added natively in a few weeks.

**Comment by crea7or** [comment]
It's a different thing. It's not the auto line endings feature. If these files by some reason will not be converted back to utf-16 - they will not work.

**Comment by bbolli** [comment]
I'm not talking about end-of-line.

**Comment by PhilipOakley** [comment]
I believe there a little bit of being "at cross purposes" in the discussion here. 

If I understand the points correctly, 

@crea7or (pavel) is refering to a few specific files in the worktree that are generated by VS and that Git, and diff, would normally detect as being binary. Meanwhile it is those same files, in that format, that he wants to be diff'ed. These files may not even be in the index/repository. Pavel's tool is there for the diff programme to use for on-the-fly conversion to utf-8 that diff will work with (from a local file). Meanwhile VS still has the original, unchanged, utf-16 file it needs to carry on in blisful ignorance. I'm guessing his (unstated!) set up is to set a --textconv via "Performing text diffs of binary files" in [gitattributes](https://git-scm.com/docs/gitattributes) (note the line "diffs generated by textconv are not suitable for applying.")

@bbolli (Beat) is a refering to the issue of adding/storing/committing those same files into the index/repository where there are new options for a reversible(?) 'working-tree-encoding' conversion into using utf8 as the cannonical storage format (just like one may use LF ending as connonical EOL on Windows). This capability is the other side of the coin, so that others (say those on *nix machines) could 'read' those files from the repo, without the 'working-tree-encoding' set, and simply see the utf8 representation, but clearly that would be useless for VS (needing utf-16), but then who'd run VS on *nix anyway...

Would that be about right. Hopefully the wordiness helps tease out the differences between the two "same but different" goals.

If @crea7or could confrm how their Git attibutes/conf settings are setup that may clarify the issue (maybe add it to the readme of the reference tool repo as well).

**Comment by bbolli** [comment]
@PhilipOakley you have it right. My main beef with Pavel's method is that we shouldn't add a feature to Git for Windows that wil be implemented (and incompatibly, configuration-wise) by upstream Git in the next release (and we all know how fast Dscho releases his GfW after the upstream release!). Whether there's a conversion to UTF-8 for storage etc is an implementation detail IMO. The effect of both methods is the same: diffs don't just say "binary files differ", but the user can see the textual delta.

**Comment by dscho** [comment]
> There is no need to include huge iconv

Too late ;-) 

```sh
$ which iconv
/usr/bin/iconv
```

**Comment by crea7or** [comment]
@dscho wow, now it's even easier!

**Comment by dscho** [comment]
> since iconv already in repo, only script(a bit modified for iconv) is required and short note for users - it would be enough. I hope iconv will not convert non utf-16 resources files.

@crea7or this sounds like a perfect opportunity for you to get involved.

**Comment by crea7or** [comment]
@dscho ok, I'm ready. So, to be clear: I'll test iconv with windows resources files and decide what to do next with conversion, then prepare script and docs for PR?

**Comment by dscho** [comment]
@crea7or sounds good to me!

**Comment by larsxschneider** [comment]
Thanks for your great summary @PhilipOakley !

@crea7or : Author of `working-tree-encoding` here. I implement the feature for Visual Studio users at @Autodesk and I would like to learn more about the problems you see.
 
> Is there 100% guarantee that these files will be in utf-16 at checkin?

It should be consistent for certain VS file types. However, if they are not 100% UTF-16 at checkin ... wouldn't your textconv filter trip over this too?

> Should everyone update git to the latest version 

Unfortunately yes 😢 . I agree that this is a major downside of `working-tree-encoding`. However, in companies you can sometimes control the Git version and therefore it might not be that big of a problem. Time can only solve that I guess. Another problem are libgit2 based clients. I will work on libgit2 support for `working-tree-encoding` next. 

> and set some options in local git config? 

A config change is not necessary. The conversion is defined in `.gitattributes` and that is stored in the Git repo.

> There is only problem with viewving diffs of utf-16 files and it can be done without conversion at every checkin/checkout.

Unless you want to look at the content with web based tools like GitHub, BitBucket, GitLab...

> There is no advantage of keeping these files in utf-8 internally in git.

You could consider it the "canonical form". That makes all kinds of text transformations (e.g. line ending conversions, but even search/replace in some cases) easier.

**Comment by crea7or** [comment]
@larsxschneider didn't thought about web based viewers and canonical form is a very good thing in overall  solidity of the tool. I will take a look into it.

**Comment by dscho** [comment]
@crea7or can we close this now? Or maybe you could write up your learnings about `working-tree-encoding` in a wiki page, to help the next users struggling with the very same problem as you are, and then we close it?

**Comment by dscho** [comment]
> maybe you could write up your learnings about working-tree-encoding in a wiki page, to help the next users struggling with the very same problem as you are

I marked this ticket "Up for grabs" with this in mind.

**Comment by crea7or** [comment]
@dscho yes, we can close it. I'll try to describe both methods in wiki later.
