### ISSUE TITLE
High CPU Usages

### ISSUE THREAD

**Issue by CheoWalker** [git-for-windows/git#1729]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options

**git version 2.13.2.windows.1
built from commit: 914b84c9d949b14a135ab50c8b881cdee9be116c
sizeof-long: 4
machine: x86_64**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows Server 2012R2 64-bit
```
$ cmd.exe /c ver

** Microsoft Windows [Version 6.2.9200]**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
 type "C:\Program Files\Git\etc\install-options.txt"

**D:\jenkins\jobs\Node test\workspace>type "C:\Program Files\Git\etc\install-options.txt" 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled**
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**None **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** CMD**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** We are using Jenkins Git Plugin to pull code from a remote repository and then push the code up to our hosting environment**
```
 - What did you expect to occur after running these commands?

** Before we updated from version 2.13.2.windows.1 we our CPU Usages never went pass 60% for more that 5 seconds**

 - What actually happened instead?

** After updating to version 2.17.1.windows2 our CPU Usages jumps to 99% and can lasting from a minute to 15 minutes **

**Comment by MagicAndre1981** [comment]
Download and install the Windows Performance Toolkit from the [Windows 10 SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk) (this also SDK works on Win8/2012).

Open cmd.exe as admin and run **wpr.exe -start CPU -start ReferenceSet -filemode && timeout -1 && wpr.exe -stop C:\HighCPUUsage.etl**. Now run the command that triggers the CPU usage and if you captured 1 minute of the usage, press a key to stop logging.

Download the [PDBs](https://github.com/git-for-windows/git/releases/download/v2.17.1.windows.2/pdbs-for-git-64-bit-2.17.1.2.a60968cf43-1.zip) and extract them in a folder. 

Open the HighCPUUsage.etl in WPA.exe, add the [PDBs from the extracted zip to WPA](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/load-symbols-or-configure-symbol-paths), Load the symbols (this takes some time, depending on your Internet Connection), drag and drop the **CPU Usage (Sampled)** to analyze pane

![grafik](https://user-images.githubusercontent.com/8274816/41772950-c9b1ca8a-761a-11e8-9ad1-1b271687a08e.png)

Now expand the stack of the git.exe that has the high CPU usage and look what git.exe does.

**Comment by randomascii** [comment]
After further research I have closed issue 1889 and have recommendations on how to better deal with git's PDBs. After downloading the PDBs it is better to run this command (changing c:\symbols to whatever your local symbol store cache is) from the directory where you unzipped the PDBs:

"c:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symstore.exe" add /r /f *.pdb /s c:\symbols /t git

This will add all of the git symbols to your local symbol server cache so that WPA, windbg, and VS can all automatically find them.

This method is better because you don't need to worry about which git.pdb you should ask the tools to load (there are two for each version of git) and because you can have the symbols for multiple git versions in your symbol store simultaneously and know that the tools will automatically find the correct ones.

**Comment by PhilipOakley** [comment]
Is this [loading of PDBs] something that could implicitly/explicitly be included in the SDK and its script. E,g. as an option post build to load those files by execution the commands?

A short PR would be be able to include a reference to these issues, so that future users/devs would aslo be able to find the backstory. As always, PRs are welcome.
