### ISSUE TITLE
http.sslCAPath not working

### ISSUE THREAD

**Issue by rhoellwarthwork** [git-for-windows/git#1730]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7 Professional SP 1 64 Bit
```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I changed http.sslbackend from "schannel" to "openssl" because with "schannel" i got the following error which didn't show up with "openssl":
```
$ git clone https://<server>/shg/deploy-to-bsh.git
Cloning into 'deploy-to-bsh'...
fatal: unable to access 'https://<server>/shg/deploy-to-bsh.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - Die Sperrfunktion konnte keine Sperrprüfung für das Zertifikat durchführen.
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git-Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I tried cloning with a https-URL from a server inside our network. That failed because we use self-signed certificates and git didn't find it. 
I then copied the certificates from c:/Program Files/Git/mingw65/ssl/certs/ca-bundle.crt, our self-signed certifcate and the two parent certificates of the self-signed certificate into one big file and pointed git to it with ```git config --global http.sslCAInfo D:/repos/DGI/CRT/Alle_Certs.pem``` The cloneing succeeded.

Then I tried using http.sslCAPath: I copied the ca-bundle.crt and our own three certificates into a directory and pointed git to it with ```git config --global http.sslCAPath D:/repos/DGI/CRT/crt```

 - What did you expect to occur after running these commands?

The cloneing should succeed.

 - What actually happened instead?

I got the following error:
```
$ git clone https://<server>/shg/deploy-to-bsh.git
Cloning into 'deploy-to-bsh'...
fatal: unable to access 'https://<server>/shg/deploy-to-bsh.git/': error setting certificate verify locations:
  CAfile: C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt
  CApath: D:/repos/DGI/CRT/crt
```

The problem here is: the defaultvalue for http.sslCAInfo ist wrong. There is no directory 'ssl' below 'libexec' so there is no ca-bundle.crt to use:
```
$ find /c/Program\ Files/Git -name 'ca-bundle.crt'
/c/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
/c/Program Files/Git/usr/ssl/certs/ca-bundle.crt
```

If I additionally set http.sslCAInfo to the correct path c:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt then I get the following:
```
$ git config --list | grep http.sslc
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslcapath=D:/repos/DGI/CRT/crt

$ git clone https://<server>/shg/deploy-to-bsh.git
Cloning into 'deploy-to-bsh'...
fatal: unable to access 'https://<server>/shg/deploy-to-bsh.git/': SSL certificate problem: self signed certificate in certificate chain
```
Therefore I think that sslCAPath is ignored.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> fatal: unable to access 'https://<server>/shg/deploy-to-bsh.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - Die Sperrfunktion konnte keine Sperrprüfung für das Zertifikat durchführen.

Unfortunately, we have not completely figured out where that comes from, so for now, you can work around this by setting `http.schannel.checkRevoke=false`.

> I changed http.sslbackend from "schannel" to "openssl"

If you do this by reinstalling Git for Windows and switching to the OpenSSL option, the `http.sslCAinfo` setting will be correct.

> $ git clone https://<server>/shg/deploy-to-bsh.git Cloning into 'deploy-to-bsh'... fatal: unable to access 'https://<server>/shg/deploy-to-bsh.git/': error setting certificate verify locations: CAfile: C:/Program Files/Git/mingw64/libexec/ssl/certs/ca-bundle.crt CApath: D:/repos/DGI/CRT/crt

Yes, this is a know problem in our MSYS2/MINGW-specific patches to the `mingw-w64-curl` package. If you are interested to work on this:

1. install the [Git for Windows SDK](https://gitforwindows.org/#download-sdk)
2. `sdk cd MINGW-packages`
3. cd `mingw-w64-curl`
4. `makepkg-mingw -s`

This will perform an initial build of the `mingw-w64-curl` package.

Then, `cd src/curl-7.60.0` will get you into the correct work space. It is not a Git worktree, so if I were you, I would make it one by calling `git init && git add -A . && git commit -m initial`.

The culprit is `0001-Make-cURL-relocatable.patch` in the `mingw-w64-curl/` directory. So I would suggest to revert that first, and then reapply it so it is easier to work on that patch:

```sh
git apply -R <../../0001-Make-cURL-relocatable.patch
git commit -a -m TO-UNDO
git am ../../0001-Make-cURL-relocatable.patch
```

Now, look for the file `lib/url.c` and specifically for the call to the `get_dll_path()` function. This is the function that determines where the `libcurl-4.dll` file is located, and its output is then used by the `get_relative_path()` function that assumes that it is in `<root>/mingw64/bin/` to find `<root>/mingw64/ssl/certs/`.

Before the `get_relative_path()` function gets to play, though, the `strip_n_suffix_folders()` function is then asked to strip off the file name of the `.dll` and the directory separator, so that the result points to the `bin` directory. However, that `.dll` file can also live in `<root>/mingw64/libexec/git-core/` instead (to prevent `libcurl-4.dll` from being picked up in the system directory when executing `.exe` files located in that directory, we have to hard-link it here). So we need

By the way, please do not look too hard at the implementation in `lib/pathtools.c` (the fact that `strip_n_suffix_folders()` calls `strrchr()` twice instead of simply assigning the return value to a local variable makes me shudder): it is not really our task to clean up that code, I don't think that the MSYS2 project is really interested in that.

The easiest way I could imagine to do fix the issue is to insert this snippet after the `strip_n_suffix_folders(relocated, 1);` call in `lib/url.c`:

```c
{
    size_t len = strlen(relocated);
    /*
     * If the .dll lives in /libexec/git-core/, force `relocated` down one level, to
     * the same level as /bin/, so that we can append the relative path further down.
     */
    if (len > 17 && !strcmp("/libexec/git-core", relocated + len - 17))
        relocated[len - 9] = '\0';
}
```

I *think* that should work. If you can test that (`make` should produce an updated `lib/.libs/libcurl-4.dll` that you can copy into your Git's `libexec/git-core/` to test), and open a PR, that would be super helpful.

Thanks.

**Comment by rhoellwarthwork** [comment]
Thanks for your comment.

That means my problem with the Default-Value for http.sslCAInfo is connected to my change of the http.sslBackend without Reinstallation. 

Is this also the reason why http.sslCAPath is ignored? Or is this related to something other?

ronald

**Comment by dscho** [comment]
> Is this also the reason why http.sslCAPath is ignored?

I don't know ;-)

Maybe debugging with `GIT_TRACE_CURL=1` set will shed more light into this issue. Or using `curl` directly, with the `--capath` option...

**Comment by rhoellwarthwork** [comment]
Thanks for the hints.
I tried GIT_TRACE_CURL=1 and --capath but nothing helped. Then I digged into  the documentation of curl and found that if curl is build against OpenSSL the directory given with --capath **must** be processed with c_rehash in order to function. The curl that is shipped with git for windows ist build against OpenSSL so i c_rehashed the directory and voila - it worked as expected.

**Comment by SixYearsInFebruary** [comment]
I also found this question. But after `http.schannel.checkRevoke=false` and reinstall many times, the problem is also.

**Comment by shiftkey** [comment]
@SixYearsInFebruary you'll have to wait for the next update to Git for Windows as that config value isn't valid - see #1747 for the context and resolution.

**Comment by dscho** [comment]
Please note: there are snapshot builds that are built from Git for Windows' `master` branch: https://wingit.blob.core.windows.net/files/index.html

Even if you find yourself unable to contribute in other ways, testing the snapshot builds and verifying that the bugfixes work for you is a great way to show gratitude for this project.

(Side note: the automated builds were paused by mistake, I re-enabled them: https://git-for-windows.visualstudio.com/git/_build/results?buildId=14689&_a=summary&view=logs; even so, the latest snapshot has the checkRevoke fix)

**Comment by nil4** [comment]
I installed the [Aug 1 64-bit snapshot build](https://wingit.blob.core.windows.net/files/Git-prerelease-2.18.0.windows.1.20.g9b68f5ad5b-64-bit.exe) and found that git.exe crashes every time (even `git --version`) with access violation exceptions like the one below captured in the Windows event log:

```
Faulting application name: git.exe, version: 2.18.0.1, time stamp: 0x5b61f70e
Faulting module name: git.exe, version: 2.18.0.1, time stamp: 0x5b61f70e
Exception code: 0xc0000005
Fault offset: 0x00000000001bc652
Faulting process id: 0x2958
Faulting application start time: 0x01d42bd4f6ed5019
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\Program Files\Git\mingw64\bin\git.exe
```

In case you have access to WER reports, IDs `a3571666-58f6-4c5c-aaea-b17bf12760e0`, `351ffb4f-41a8-4324-8a01-77e6450db2d0`, `88d227f8-bbe8-4637-8b6c-f7d42cab4094` should include the data for the most recent crashes.
