### ISSUE TITLE
Git for Windows Installer hangs

### ISSUE THREAD

**Issue by alperenguman** [git-for-windows/git#1763]
Git for Windows installer hangs with the green bar complete on a Windows 10 Pro (Build 17134.165).
It's running mkdir when it hangs at the end. The only possible action is to force kill. This results in post-install steps being incomplete. 

Immediate observations of aberrant behaviour: Git command not in PATH, not in shell context menu, vim is the default editor despite nano being selected in the installation. Post-install.bat script remains untouched in the program directory.

Options Selected:
Git from the Windows Command Prompt
Use (Tortoise)Plink
Checkout Windows-style, commit Unix-style line endings
Use MinTTY
Enable file system caching
Enable Git credential manager

Log:
https://pastebin.com/Ez8cxHQV

Notes:
Tried installing previous versions: 2.17, 2.11 and observed the same behaviour. When uninstalling and reinstalling again Revo Uninstaller is used to make sure no traces of the program remain in the registry.

**Comment by dscho** [comment]
You could run `wmic process list` to figure out which Git processes are running *and* what their command-lines are. Maybe that gives us an idea what is happening.

**Comment by HappyTreesDev** [comment]
This is really annoying and until it is fixed the old version of git should be uploaded on the site

**Comment by dscho** [comment]
@HappyTreesDev rather than vent at the people who do all the work for you, you might want to consider actually helping. Like, for example, running said `wmic process list` and investigating what is causing the hang. You can't just sit back and shout at others what they should do, that won't have the intended effect at all.

**Comment by alperenguman** [comment]
@dscho In the attachment you can find the relevant section of `wmic process list` I outputted to a text file during installer hang:
[wmic-git.txt](https://github.com/git-for-windows/git/files/2298926/wmic-git.txt)

**Comment by HappyTreesDev** [comment]
@dscho I was more getting at that the old version should be uploaded in this situation, which I do not have control over. I am willing to wait for the fix.

**Comment by dscho** [comment]
@HappyTreesDev no old installer has been removed.

And: your intention to lay back lazily and expect others to work for you is not appreciated here. Not one bit.

**Comment by HappyTreesDev** [comment]
[wmic_git.txt](https://github.com/git-for-windows/git/files/2416351/wmic_git.txt)
Is there any other information I can provide to help?

**Comment by dscho** [comment]
> In the attachment you can find the relevant section of `wmic process list`

Hrm.

@alperenguman So if it hangs in `mkdir`, maybe we can create those directories pre-emptively. I'll need you to drive this forward, but I'll assist. To drive this,

1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk)
2. `sdk cd build-extra`
3. create an installer via `./installer/release.sh 0-test`
4. verify that this installer also hangs at the end (if not, the problem is miraculously gone)
5. edit `installer/install.iss` so that it creates the two directories that would otherwise be created by the post-install script: before https://github.com/git-for-windows/build-extra/blob/bf91b39e3c32f5b7e5a2660feea7b832d21bc7c2/installer/install.iss#L2657-L2673, insert something like this:
    ```pascal
    if not ForceDirectories(ExpandConstant('{app}')+'\dev\shm') then
        LogError('Could not initialize /dev/shm');
    if not ForceDirectories(ExpandConstant('{app}')+'\dev\mqueue') then
        LogError('Could not initialize /dev/mqueue');
    ```
6. create another installer via `./installer/release.sh 0-test` and test that one.

**Comment by dscho** [comment]
I hope that everybody here is happy that once again, I had to do all the work: git-for-windows/build-extra#255. Because I am not.
