### ISSUE TITLE
Cannot parse Git version string

### ISSUE THREAD

**Issue by whotired** [git-for-windows/git#1793]
I install git 2.18.0 and 64 bit for Windows 7. While clicking "Gig GUI here" and getting error:
git-gui:fatal error
Cannot parse Git version string
The path in environment virable is "C:\Program Files\Git\cmd" as default.
![git-gui-error](https://user-images.githubusercontent.com/15623105/44127361-91c5fe8c-a06f-11e8-95d8-b6a950acf9d7.jpg)

**Comment by dscho** [comment]
This is *really* little information to go on.

I only saw something like this when `GIT_TRACE` was set, but with those few breadcrumbs thrown leisurely into my vague direction, it is hard to tell.

**Comment by shiftkey** [comment]
:wave: Hi @dscho.

I wasn't quite at the point of reaching out to you on this but I've encountered this same issue with a handful of GitHub Desktop users in terms of Git LFS not being able to read any output from `git --version` or `git version`.

The investigation so far is happening in https://github.com/desktop/desktop/issues/5247 but I'll try and summarize it here:

 - `git-lfs` does a version check that it has a valid `git` available by [spawning `git version`](https://github.com/git-lfs/git-lfs/blob/d1cd726b79fca1951e235e8d85f3626934adfafd/git/version.go#L17-L28)
 - for some users, no `stdout` is returned and so `git-lfs` raises an error to Desktop
 - one user (not @whotired) also tried this out with vanilla Git for Windows (`2.18.0.windows.1`) and encountered the above error message with `git-gui`
 - poking at [the source](https://github.com/git/git/blob/1d89318c48d233d52f1db230cf622935ac3c69fa/git-gui/git-gui.sh#L925-L946) I see this is the same pattern as what `git-lfs` is encountering (no `stdout` returned, so :boom:)

Things I've tried to eliminate as the root cause:

 - another program on `PATH` named `git.exe` that is called instead 
 - some third-party tool like anti-virus that likes to interfere with spawned processes (Carbon Black gets a mention but users don't think that's to blame)

Any other thoughts or things to eliminate would be greatly appreciated.

**Comment by dscho** [comment]
> for some users, no stdout is returned and so git-lfs raises an error to Desktop

That is indeed strange.

> another program on PATH named git.exe that is called instead

Wait, what?

**Comment by shiftkey** [comment]
Just had word that Carbon Black is to blame and they're rolling out an update to fix this: https://github.com/desktop/desktop/issues/5247#issuecomment-413303337

@whotired can you confirm whether you have Carbon Black installed?

**Comment by whoisj** [comment]
Perhaps something like [GetFileVersionInfoExW](https://docs.microsoft.com/en-us/windows/desktop/api/winver/nf-winver-getfileversioninfoexw) would be safer?

**Comment by shiftkey** [comment]
@whoisj safer for whom?

**Comment by whotired** [comment]
@shiftkey  Yes, Carbon Black has been installed on 2018-8-12 on my machine. But my colleague has same program and no this error "Cannot parse Git version string", he can open git-gui correctly.
![carbonblack](https://user-images.githubusercontent.com/15623105/44180493-5e27c680-a12f-11e8-9554-7d52b279d675.jpg)

**Comment by shiftkey** [comment]
@whotired it's not clear to me which version has the issue, but hopefully @mpauser can share once they've received an update.

**Comment by whotired** [comment]
@shiftkey Thanks

**Comment by whoisj** [comment]
@shiftkey my point was instead of running an external process, which could be intercepted by interventionist services like Carbon Black, it could be _safer_ to just use the OS provided API to query the version information.

Example:

```C
#include "pch.h"
#include <iostream>
#include <Windows.h>

#pragma comment(lib, "mincore.lib")

static const wchar_t *path_to_git = L"C:\\Program Files\\Git\\cmd\\git.exe";
static const wchar_t *prodver_format = L"\\StringFileInfo\\%04hX%04hX\\ProductVersion";
static const wchar_t *vfi_trans_format = L"\\VarFileInfo\\Translation";

int main()
{
    unsigned long len;
    unsigned int info_size;
    unsigned int cult_size;
    void *data = NULL, *info = NULL;
    struct LANGANDCODEPAGE {
        WORD language;
        WORD codepage;
    } *culture;
    wchar_t query_string[256];

    len = GetFileVersionInfoSizeExW(FILE_VER_GET_NEUTRAL, path_to_git, &len);

    if (len <= 0)
        goto failure;

    data = malloc(len);

    if (!GetFileVersionInfoExW(FILE_VER_GET_NEUTRAL, path_to_git, 0, len, data))
        goto failure;

    if (!VerQueryValueW(data, vfi_trans_format, (LPVOID*)&culture, &cult_size))
        goto failure;

    for (int i = 0; i < (cult_size / sizeof(LANGANDCODEPAGE)); i += 1)
    {
        len = wsprintfW(query_string, prodver_format, culture[i].language, culture[i].codepage);
        query_string[len] = 0;

        if (!VerQueryValueW(data, query_string, &info, &info_size))
            continue;

        wprintf(L"File Version: %s", (wchar_t*)info);

        goto clean_up;
    }

failure:
    len = GetLastError();

    if (len > 0)
        wprintf(L"fata: error 0x%04h.\nUnable to read version information from \"%s\".\n", path_to_git);
    else
        wprintf(L"Unable to read version information from \"%s\".\n", path_to_git);

clean_up:
    if (data)
        free(data);
}
```

**Comment by shiftkey** [comment]
@whoisj no problem. It's just that for `git-lfs` (that originally encountered this issue) and `git-gui` have to support other OSes to Windows, and I've not looked into the equivalents to `GetFileVersionInfoExW` there (if they even support it).

**Comment by dscho** [comment]
I guess it's not only that. While the *version check* would be helped by `GetFileVersionInfoExW()`, both Git LFS and Git GUI have to spawn Git for other purposes, like, to let Git do *real* work. And I have no doubt in my mind that those services like Carbon Black (or more commonly, at least as far as appearances on this bug tracker go, Comodo Internet Security) will wreak havoc with those calls anyway. We can try to work around their bugs all we want, eventually it is up to them to fix their software (or to tell us *precisely* what bug Git for Windows has, because so far they haven't come up with *any* convincing bug report).

**Comment by whotired** [comment]
This morning I opened my computer, it did windows update, then I clicked git-gui.exe, it can be opened correctly without the error "Cannot parse Git version string", I thought the windows update fix the issue. But when I restart the computer two hours later, the same error occured again :(
![image](https://user-images.githubusercontent.com/15623105/44706113-2166b280-aad3-11e8-90da-d353c6697b0c.png)

**Comment by dscho** [comment]
I'm going to close this out because I don't believe there's anything we can do in Desktop to address this, and it seems like updates to products like Carbon Black should resolve the issue eventually. (See also https://github.com/desktop/desktop/issues/5247#issuecomment-424712141)
