### ISSUE TITLE
When is 2.19.0 for Windows (stable) going to be released?

### ISSUE THREAD

**Issue by rangka-kacang** [git-for-windows/git#1826]
It has been 2 days since 2.19.0 came out but looking at https://github.com/git-for-windows/git/releases it seems that we are still stuck with RC2 from 6 days ago. Any news?

Edit: @dscho

**Comment by PhilipOakley** [comment]
It is being worked. The release process is a little bit longer this time because dscho is on a well earned holiday at the moment and his team are working through the release process. 

It has been merged to master #1825 - 

there are certain security steps that need doing at the end which might need dscho's personal signoff (otherwise it wouldn't be security, would it...)

**Comment by PhilipOakley** [comment]
The release is now out. 

Time to do the usage/testing, and have a try of the new faster (though marked 'experimental') rebase and stash built-ins. If you find an issue, you know where to find us / the issues tracker...

I'll close the issue just now, if that is OK.
