### ISSUE TITLE
log -L/<regex>/,+1 not accepted

### ISSUE THREAD

**Issue by pdolland** [git-for-windows/git#1856]
$ git log -L'/DRIVER_STATE = "/',+1 -- plm-dev/Wolke_M600_UTF8.java
fatal: -L argument not 'start,end:file' or ':funcname:file': /DRIVER_STATE = "/,+1

whereas blame with the same arguments does it:

$ git blame -L'/DRIVER_STATE = "/',+1 -- plm-dev/Wolke_M600_UTF8.java
51afb3c491 (Peter 2018-04-19 10:23:41 +0200 51)         protected static final String DRIVER_STATE = "180419";

The same behavior with git versions 2.5.1 and 2.19.0.windows.1.

**Comment by PhilipOakley** [comment]
Have you been able to check if this issue is also present on Linux? It may be a a global Git problem rather than just a G-f-W issue.

I know there were some fairly recent upstream patches regarding the start,end aspects of the the '-L' option (IIRC mainly about the values spanning the end of the file).

There are a number of these options that do not carry fully between commands.

**Comment by dscho** [comment]
It would be appropriate, but what @PhilipOakley asked you, @pdolland, was whether this is Windows-specific behavior. Because if it is not, then the feature request would be better sent to git@vger.kernel.org (the real Git mailing list; please make sure to send plain-text-only mails).

You saw fit to simply delete the issue reporting template instead of filling it out, so I have no way to assess whether [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) would be an option for you.

**Comment by dscho** [comment]
It is really one of the most frustrating aspects of open source that users seem to be totally comfortable with spending maintainers' time freely without matching the effort.

> git log -L'/DRIVER_STATE = "/',+1 -- plm-dev/Wolke_M600_UTF8.java

In the meantime I suspect that this is a simple "pilot error": forgetting the `:<file>` part of the `-L` argument.

Since the communication broke down, I'll simply close the ticket.
