### ISSUE TITLE
ConsoleZ support

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#188]
With the previous stable release from git-scm.com I could configure [ConsoleZ](https://github.com/cbucher/console) to run git bash by specifying `C:\Program Files (x86)\Git\bin\sh.exe --login -i` as the shell.  Now when I try to use `C:\Users\jkolb\AppData\Local\Programs\Git\git-bash.exe` it fails.

**Comment by dscho** [comment]
You probably want to use `C:\Users\jkolb\AppData\Local\Programs\Git\git-cmd.exe --command=C:\Users\jkolb\AppData\Local\Programs\Git\usr\bin\bash.exe --login -i`.

**Comment by kjeremy** [comment]
Thanks that gets the basics working.  However a few things don't work anymore:
1. My `.bashrc` doesn't execute
2. `clear` doesn't clear the console, it just moves the cursor to the top.
3. Hitting CTRL-C to stop a command will kill the whole console.
4. Startup takes about 5 seconds.

I'm not sure if the above is due to the command above being not quite right (misconfiguration on my part) or not but they are regressions compared with using `git-1.9.5-preview` in `ConsoleZ`

**Comment by dscho** [comment]
As a general rule, please open new tickets for new issues, after verifying that the issue had not been reported before. And in this case, the `clear` bug has been fixed already (see https://github.com/git-for-windows/git/issues/169).  It's just not in any release because I would need to fix https://github.com/git-for-windows/git/issues/185 before that, and I am so busy commenting on tickets that that bug fix gets delayed further and further :stuck_out_tongue_winking_eye:

**Comment by kjeremy** [comment]
No problem.  I just wasn't sure if those were additional issues or a misconfiguration first.  Now I know and will open up more issues.
