### ISSUE TITLE
Fatal Error Message on new line while pushing to a branch with different case

### ISSUE THREAD

**Issue by bhubanstha** [git-for-windows/git#1886]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
** git version 2.18.0.windows.1 - 64 bit **

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 7 - 64 bit
```
$ cmd.exe /c ver

** Microsoft Windows [Version 6.1.7601]**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
** Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

**git push origin {branch}**
```
branch name is in lower case while my actual branch name has first letter capitalized. 
e.g I typed development instead of Development
```
 - What did you expect to occur after running these commands?

**Expected changes to get pushed to branch if not error message on line after that**

 - What actually happened instead?
** fatal response is displayed on new line where git command has to be typed**

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**It may occur on any repo**

**Comment by PhilipOakley** [comment]
This, (case preserving, case ignoring) is **a known issue** that unfortunately can't be changed because it is an integral part of the way the Windows file system (FS) works, which is different from the Linux FS which does expect a case sensitive FS.

If you review all the issues (including the closed ones) you will see a number of reports, e.g. #1709, and suggestions e.g. #1623, but ultimately it needs someone (are you free/available?) to find a methods of detecting the issue that does not grossly slow the code down.

Different commands will respond slightly differently depending on the severity of the misunderstanding.
