### ISSUE TITLE
Git-Subtreee split

### ISSUE THREAD

**Issue by Grzy7316** [git-for-windows/git#1921]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - I chose the Defaults 

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
```
Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

cmd , git bash or powershell 

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git Subtree split -P C:/SVG2/Corporate/SQL_Scripts/Solutions/Jira_SSMS -b Jira_SSMS
git Subtree split -P /Corporate/SQL_Scripts/Solutions/Jira_SSMS -b Jira_SSMS
git Subtree split -P ./Corporate/SQL_Scripts/Solutions/Jira_SSMS -b Jira_SSMS
```
 - What did you expect to occur after running these commands?

I expected to do a subdirectory based subtree split for that folder 

 - What actually happened instead?

I recieved the error(s) below 
```
git Subtree split -P C:/SVG2/Corporate/SQL_Scripts/Solutions/Jira_SSMS -b Jira_SSMS

assertion failed:  test Corporate/SQL_Scripts/Solutions/Jira_SSMS = C:/SVG2/Corporate/SQL_Scripts/Solutions/Jira_SSMS
assertion failed:  test Corporate/SQL_Scripts/Solutions/Jira_SSMS = C:/SVG2/Corporate/SQL_Scripts/Solutions/Jira_SSMS
assertion failed:  test Corporate/SQL_Scripts/Solutions/Jira_SSMS = C:/SVG2/Corporate/SQL_Scripts/Solutions/Jira_SSMS
assertion failed:  test Corporate/SQL_Scripts/Solutions/Jira_SSMS = C:/SVG2/Corporate/SQL_Scripts/Solutions/Jira_SSMS
assertion failed:  test Corporate/SQL_Scripts/Solutions/Jira_SSMS = C:/SVG2/Corporate/SQL_Scripts/Solutions/Jira_SSMS
No new revisions were found

git Subtree split -P /Corporate/SQL_Scripts/Solutions/Jira_SSMS -b Jira_SSMS

C:/Program Files/Git/Corporate/SQL_Scripts/Solutions/Jira_SSMS' does not exist; use 'git subtree add'

git Subtree split -P ./Corporate/SQL_Scripts/Solutions/Jira_SSMS -b Jira_SSMS

assertion failed:  test Corporate/SQL_Scripts/Solutions/Jira_SSMS = ./Corporate/SQL_Scripts/Solutions/Jira_SSMS
assertion failed:  test Corporate/SQL_Scripts/Solutions/Jira_SSMS = ./Corporate/SQL_Scripts/Solutions/Jira_SSMS
assertion failed:  test Corporate/SQL_Scripts/Solutions/Jira_SSMS = ./Corporate/SQL_Scripts/Solutions/Jira_SSMS
No new revisions were found

```

However, When using linux git under WSL to perform the command git Subtree split -P /mnt/c/SVG2/Corporate/SQL_Scripts/Solutions/Jira_SSMS -b Jira_SSMS the subtree split is working

**Comment by dscho** [comment]
@Grzy7316 hopefully you will find the following information useful in fixing this issue:

* your MCVE is not a Complete example, as it does not work without the (obviously private) repository, and you did not work on creating a minimal, public repository to make the example complete.
* `git subtree` is actually a Unix shell script, located in `C:\Program Files\Git\mingw64\libexec\git-core\git-subtree`
* the "assertion failed" message is generated by the `assert()` function in `git-subtree`: https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L76
* there are actually only three calls of that `assert()` function that could be responsible for those error messages:
    * https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L494
    * https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L495
    * https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L538
* From the looks of your report, the most likely candidate is https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L494
* The shown assertions indicate that the `dir` parameter passed into [`subtree_for_commit()`](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L488-L500) are not quite in the expected form: they are expected to be regular, relative paths, but seem to be either absolute paths or relative paths starting with `./`.
* There is only one caller of `subtree_for_commit()`: https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L655 (in [`process_split_commit()`](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L625-L675))
* The `process_split_commit()` function does not define that `dir` variable but uses it, which means  that it most likely reuses the value assigned here: https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L180
* The code path leading to those error messages most likely calls `process_split_commit()` here: https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L781 (there is only one other caller, in `check_parents()`, and that seems to be called only from `process_split_commit()` recursively)
* The assignment [`dir="$(dirname "$prefix/.")"`](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L180) uses the variable `prefix`, which in your case is set directly from the parameter passed in via [`-P`](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.sh#L104-L106)
* In contrast to [all](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.txt#L250) the [examples](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.txt#L277) in [the](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.txt#L291) documentation [of](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.txt#L297) the [`git subtree`](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.txt#L303) command's [documentation](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.txt#L313), ([there](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.txt#L322) are [more](https://github.com/git-for-windows/git/blob/v2.21.0-rc2.windows.1/contrib/subtree/git-subtree.txt#L337)), you do *not* specify the prefix as regular relative path (which in your case would be `Solutions/Jira_SSMS`, I guess, or maybe `Corporate/SQL_Scripts/Solutions/Jira_SSMS`, another thing that the bug report left unclear) but as
    1. an absolute Windows path (which is not supported by `git subtree`)
    2. an absolute "Unix" path (which is incorrect in your case, as you would have to prefix it with `/c/SVG2` to refer to the correct path), and
    3. a relative path starting with `./` (which is not suggested anywhere in the documentation, and which I therefore would consider a pilot error rather than a bug in `git subtree`)

Since there was not enough information in the bug report to make enough sense of the issue, this is all I can do here, and the ball is squarely back in your court, @Grzy7316.
