### ISSUE TITLE
Include smimesign in Git for Windows distribution

### ISSUE THREAD

**Issue by onovotny** [git-for-windows/git#1984]
GitHub (and Git 2.19+ have support for using the `smimesign` command for using X509 certificates for signing commits.

Currently smimesign is a separate tool that needs to be installed. Can this be bundled with the Windows installer?

https://github.com/github/smimesign

**Comment by dscho** [comment]
> https://github.com/github/smimesign

This project is written in Go which is

1. hard to integrate with MSYS2's packaging system (which would be a pre-requisite to integrate *anything* into the Git for Windows installer), and
2. typically comes with a Go runtime bundled (read: it would increase the file size substantially).

So I am mildly negative on this idea. However, if there is anybody putting in the work, and if it would turn out to not increase the file size of the installer noticeably, I could be convinced otherwise :grin:

**Comment by onovotny** [comment]
@dscho They have an installer and have a pre-compiled binary. My idea was to take their binary and include it in the bin directory Git produces?

**Comment by onovotny** [comment]
Are there docs on how the packing system pulls in the binaries to create its installer? Or where is that in the source tree?

**Comment by shiftkey** [comment]
This was a similar situation to Git LFS, which was deferred a bit until the demand was there for bundling in the app. Check out the package details [here](https://github.com/git-for-windows/build-extra/tree/master/mingw-w64-git-lfs) for how it's currently consumed into GfW as well as the original discussion in https://github.com/git-for-windows/build-extra/pull/110 which touches on things relevant to this discussion.

For me, I'd hold off a bit to see how the early adoption proceeds. The additional installer hit isn't worth it if no-one is using it. I'm also working to get this into `dugite-native` in https://github.com/desktop/dugite-native/pull/117 so we could use this in GitHub Desktop down the track, but I need to support a broader set of platforms than just GfW.

**Comment by dscho** [comment]
> The size of the compiled file is 10 megs.

This is *large*. The entire Git for Windows installer is 44MB right now (and it has grown, uncomfortably, from just under 30MB as little as 3 years ago), so I am really loathe to include that much of an additional payload for something that I am not even sure will "win" in the long run.

@onovotny if you have any splendid idea how to support smimesign without such a huge hit, you have my attention.

Maybe smimesign could be built with the same options that made `git-lfs.exe` a lot smaller? Or maybe you can prove that `smimesign` compresses well because it is so similar to `git-lfs.exe` (which also includes at least part of the Go runtime) and does not bloat the Git for Windows installer much further? For a quick experiment, you could install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk), `sdk cd build-extra`, build a test installer using `./installer/release.sh 0-test`, insert a hacky line at [line number 115 of `installer/install.iss`](https://github.com/git-for-windows/build-extra/blob/0b446e85ae6e6bd62554a030d0e8600d19be3c61/installer/install.iss#L115) to include that binary, and build another test installer via `./installer/release.sh 1-test`, and then compare the size before and after?

**Comment by dscho** [comment]
Closing due to lack of progress/conversation.
