### ISSUE TITLE
Git For Windows, and Git-Bash, and 

### ISSUE THREAD

**Issue by duaneellissd** [git-for-windows/git#2013]
Maybe this is in a wiki somewhere, but I am not finding it - and google is not helping.

As a user - I find these three things:

(A)   https://git-scm.com/    - Many know this places a "git bash"

And 

(B)  https://gitforwindows.org/   - 
       This seems to be the same thing as (A) - the installer comes from the same place

AND

(C)  (on GitForWindows click:  Download SDK)

But there are no clear directions on how to install both
Both of these seem to install, or want to install in two diferent directories

I do seem to understand that (A) and (B) - are for the  GIT USER
But often I find that it is MISSING something beyond just git

Often this involves adding GCC and/or other tools so I can add that one more thing.
But it's not simple - 

So that is why I think the SDK exists...

If these are the same, why does one install in c:\Program Files
And the other installs in c:\git-sdk-64

In some ways  it seems GIT-SDK-64 has many of the missing features I need
so why don't I just use that to start with?

But I come back to the initial question - why are there 3?
How exactly do I install - or is the better word "overlay" - the SDK over the existing GitBash?

I mean there are different ICONS that give me what looks like two differently installed GItBash instances

Thanks

**Comment by dscho** [comment]
> I do seem to understand that (A) and (B) - are for the GIT USER
> But often I find that it is MISSING something beyond just git

Git for Windows is just this: *Git*, *for Windows*. It never promises, or tries to support, anything beyond Git.

> Often this involves adding GCC and/or other tools so I can add that one more thing.

If you want GCC, you are not looking for Git for Windows, but for Cygwin or MSYS2.

> So that is why I think the SDK exists...

No, the SDK does not exist to provide GCC. The SDK exists to help build Git for Windows (the fact that it currently contains GCC is just by necessity, at some stage we may replace this by Clang, or switch to Visual C, or whatever).

> How exactly do I install - or is the better word "overlay" - the SDK over the existing GitBash?

That is neither an intended nor a supported scenario.

Git for Windows is intended for users of Git. The SDK is intended for contributors improving Git for Windows.

**Comment by PhilipOakley** [comment]
Just to add to dscho's answer:

First, was the subject line complete. I'm not sure that we saw the the full question and context of where the question came from. Is this just a query about the terminology so that from another step back an OP may be confused about where to start and whether they are meant to be the same or different? 

i.e what is the 'it' context in "often I find that it is MISSING something beyond just git"? 

[A-B Ans: the git-scm and the gitforwindows.org should both point at exactly the same code when on a windows machine, even though the two web sites are formally independent. The SDK is special for developer/contributors]

When dscho said 'No' (to gcc), a re-ordering of the phrases would also allow the SDK to be a 'yes' (the SDK is there to provide the gcc) but still in the narrow context of developing git-for-windows only.

If the reader @duaneellissd is looking for a "linux on Windows" environment that dscho's comment still stands, the SDK isn't the right thing, even if it is pretty expansive so as to support the git-for-windows  development. On can also try the Windows 10 WSL (Windows System for Linux).

Hope that helps
