### ISSUE TITLE
Don't know what to do

### ISSUE THREAD

**Issue by David263** [git-for-windows/git#2021]
I am a beginner. I assume I'm allowed to post here and that I can get help, because I could not find a forum for Git For Windows.

Using https://www.jamessturtevant.com/posts/5-Ways-to-install-git-on-Windows/ I installed chocolatey and git. But after that, "git" results in "file not found" instead of running Git for Windows as I expected. I'm lost.

Also, I am very confused by the fact that although I have now installed git, GIt for Windows, and GitHub Desktop on my Windows 10 computer, I don't really know how I am supposed to use these three tools (four if you include github.com). I can find no help that really helps me answer this question or get started. I'm stuck.

Even though I am a retired and still productive software engineer, I have not found a usable tutorial. I have started reading four or five tutorials and give up because they are either too simple or too complicated or assume I'm running Linux.

Can someone please point me to documentation that really answers these questions?

**Comment by PhilipOakley** [comment]
Hi, I can see your confusion. If you are starting out, you will need to pick just one method, hopefully one that best matches your local environment and knowledge (i.e. asking why you might want to pick the GitHub desktop vs the Git-for-Windows install, maybe colleagues have a specific one, or you've piad a support fee somewhere).

Personally I just use the https://gitforwindows.org/ Download (its should be identical to the one that git-scm will deliver.).

I use the support of the `git gui` and `gitk` viewer to complement a few items on the git command line.

If you are "a retired and still productive software engineer" then I'd suggest you look for something that explains the general git internals (the objects types, and the way the file tree and commit history DAG are organised). e.g. http://eagain.net/articles/git-for-computer-scientists/

You should 'forget' old style command and control VCS ideas - They are based on old drawing office procedures that forgets that computers can produce perfect duplicates at the drop of a hat. We also have mass storage almost for free, so every body get a copy of everything and everybody gets to commit [to their local copy].

What is now important is validating that what you have has the same hash as the authoritative leader. If you have the right file tree hash, but the wrong commit hash then you have the wrong view of the history but the right view of the code. The commit had includes both the prior history hash and the tree's hash, and the commit message. Quite simple really.

In the Linix and Git development they still exchange (send) patches to upstream, but then users fetch the whole history. 

The Github method is to push your local changes to your github account/repo and then ask the usptream to accept that your can merge on top of theirs - you have already pre-prepared the final result. If the upstyream reject (hopefully with reasons), you then use 'rebase' to iterate till you have acceptable code.

Branches are used often and commits are small and often (which makes the chance of collision lower).

If you want to lurk the [git.git repo](https://github.com/git/git) and [mailing list](https://public-inbox.org/git/) is one way. The https://gitforwindows.org/ repo is less fun (i.e. not as clean) because it needs to follow the upstream git and patch all the Linux/Posix - Windows incompatibilities ;-)

Hope That helps

**Comment by shiftkey** [comment]
> (four if you include github.com)

@David263 the [GitHub Help](https://help.github.com/) site is worth checking out, there's a [bootcamp](https://help.github.com/categories/bootcamp/) section to help you get familiar with some parts of Git and GitHub, but also contains a lot of troubleshooting resources that might help when you encounter something unexpected.

**Comment by David263** [comment]
I finally got the 'git' command to work on my local computer (the Git for Windows installation had failed to create a PATH environment variable entry in Windows) and am following the apparently excellent half-hour tutorial at https://www.youtube.com/watch?v=HVsySz-h9r4 . The tutorial recommends using 'git' commands for experience before trying to use the GitHub website, Git for Windows, or the Desktop, which are apparently all very limited in functionality.

So far I have had some success in using local commands but failure to use a remote Push to GitHub. Anyone have any ideas why I got this error message? 

```
C:\Web\Tests\git-practice>git push origin master
remote: Permission to grayghostvisuals/practice-git.git denied to David263.
fatal: unable to access 'https://github.com/grayghostvisuals/practice-git/': The requested URL returned error: 403
```

In my latest adventure, I received a strange email from GitHub saying that it created a "personal access token" for me. Following the links revealed no information about this thing except cryptic remarks such as " Tokens you have generated that can be used to access the GitHub API...Personal access tokens function like ordinary OAuth access tokens. They can be used instead of a password for Git over HTTPS, or can be used to authenticate to the API over Basic Authentication."

Personal access tokens are not mentioned in any tutorial I have seen so far.

My assumption will be that they are not important, just a form of security I could use instead of my user/password if I knew how.

Why does git and GitHub seem to have such terse, cryptic, and unhelpful documentation as compared to your typical JavaScript  framework or library? Maybe I just have not found the right URL for clear documentation as yet.

**Comment by kgybels** [comment]
@David263 
>I finally got the 'git' command to work on my local computer

Good to hear you got your git working!

>So far I have had some success in using local commands but failure to use a remote Push to GitHub. Anyone have any ideas why I got this error message?
```
C:\Web\Tests\git-practice>git push origin master
remote: Permission to grayghostvisuals/practice-git.git denied to David263.
fatal: unable to access 'https://github.com/grayghostvisuals/practice-git/': The requested URL returned error: 403
```

You do not have permission to push to that repository. GitHub uses the [Integration-Manager Workflow](https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows). You need to [fork the repositoy](https://guides.github.com/activities/forking/#fork), then push to your own copy, which will be at https://github.com/David263/practice-git.git. If you then want your code to go into grayghostvisuals/practice-git.git, you will need to [make a pull request](https://guides.github.com/activities/forking/#making-a-pull-request). This process is explained in more detail in [GitHub's Forking Projects guide](https://guides.github.com/activities/forking/).

>Personal access tokens are not mentioned in any tutorial I have seen so far.
My assumption will be that they are not important, just a form of security I could use instead of my user/password if I knew how.

You are right, they are not important for you at this point.

>Why does git and GitHub seem to have such terse, cryptic, and unhelpful documentation as compared to your typical JavaScript framework or library?

You are learning a lot at once, which make it more difficult. When learning a JavaScript library, you already know JavaScript, and only need to learn the library itself. In addition, Git and GitHub are separate things, and have their own documentation, but for a beginner it is not always clear what documentation to go to.

>Maybe I just have not found the right URL for clear documentation as yet.

For learning git I recommend the [Pro Git book](https://git-scm.com/book/).

The documentation for each git command is available online at https://git-scm.com/docs, but is also installed with Git for Windows and available with `git commit -h` for short help and `git commit --help` for longer helper (replace commit with the command you want information on). However, the git documentation uses a lot of git terminology, and if unfamiliar with it, I can understand it being cryptic.

For GitHub, there is the [GitHub Guides](https://guides.github.com/) with high-level documentation, and [GitHub Help](https://help.github.com/) for more in-depth information. The Pro Git book also has a [chapter dedicated to GitHub](https://git-scm.com/book/en/v2/GitHub-Account-Setup-and-Configuration).
