### ISSUE TITLE
"git zsh" for Windows

### ISSUE THREAD

**Issue by Mebus** [git-for-windows/git#2023]
Hallo,

on Linux I usually use the zsh with https://github.com/robbyrussell/oh-my-zsh . Would it be possible to build a "git zsh for Windows", that uses the zsh instead of the bash and possibly could also be shipped with "oh-my-zsh"? :grinning: 

Thanks!

Mebus

**Comment by PhilipOakley** [comment]
Being slightly cheeky, I'd suggest the best way to get started is to use the [SDK](https://gitforwindows.org/#contribute) [download](https://github.com/git-for-windows/build-extra/releases/latest) so that you can build your own variant. 

If things go well, then it could be worth a Pull Request so that the zsh (which I don't use myself) can be neatly integrated as an option on the install screen (or whatever).

**Comment by PhilipOakley** [comment]
For extra points make sure that you can load and run zsh on the MSYS2 shim that provides the Linux/Posix semantics (or at least a Minimal SYStem \#2) on top of Windows (within Git-for-Windows - see for example https://github.com/git-for-windows/git/wiki/The-difference-between-MINGW-and-MSYS2)

**Comment by dscho** [comment]
@PhilipOakley is spot on. It really is outside the purview of Git for Windows to provide zsh, and I am loathe to add [another 2MB](https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/zsh-5.6.2-1-x86_64.pkg.tar.xz/download) to the installer size, just to accomodate the few users who want to use zsh. I really think that would be a terrible idea.

@Mebus What you want looks more like MSYS2. If you must, use Git for Windows' SDK (which is a fork of MSYS2), but please note that the active Git for Windows contributors have enough to do supporting Git for Windows and since you want something advanced, it can be expected of you to take care of your problems yourself.
