### ISSUE TITLE
Failed to restrict file handles

### ISSUE THREAD

**Issue by tylernathanreed** [git-for-windows/git#2035]
### Setup

**Git Details**

```
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

**OS Details**
```
Microsoft Windows [Version 10.0.17134.556]
```

**Installation Details**

```
Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Terminal Details

```
Powershell
````

### Command Details

I ran the following command:

```
git tasks/2.11.12/4087-D-nightly-rearchitecture..tasks/2.11.12/4795-W-instance-tracking
```

I was trying to do a `git diff`, but I forgot the `diff` argument. I was expecting to be informed of using an invalid argument or unknown command.

Here's the response from the terminal:

```
warning: failed to restrict file handles (2)

handle #0: 000000000000004c (type 2, handle info (1) 0
handle #1: 00000000000000fc (type 2, handle info (1) 1
handle #2: 0000000000000100 (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'tasks/2.11.12/4087-D-nightly-rearchitecture..tasks/2.11.12/4795-W-instance-tracking' is not a git command. See 'git --help'.
```

The response told me this was a bug, and to report it (so here we are).

Obviously, if I correctly prepend my two branches with `diff`, this works like a charm.

**Comment by PhilipOakley** [comment]
Hi @tylernathanreed 

Thank you for responding to the 'BUG' reporting request. It was an issue in that releases version, which has now been fixed in the more recent versions. Thus it's time to update to a newer or the most recent release.

The releases are all listed here https://github.com/git-for-windows/git/releases/ (the link, for those who maybe hadn't noticed) is at the bottom/footer of the https://gitforwindows.org/ page).

I'll close the report, but you can reply if there are follow on comments.
