### ISSUE TITLE
Bash/GitBash syntax for multiple variable value assignment not working when value is a command's output

### ISSUE THREAD

**Issue by softdev4evr** [git-for-windows/git#2056]
I have GitforWindows 2.20.1 installed in Windows 7 64Bit.

Now as I stated in the question, the multiple variable assignment syntax is not always working, especially when the value to be assigned is a command's output, i.e.:

`read -r a b c <<< $(echo 1 2 3) ; echo "$a|$b|$c"`

works, but these doesn't:

```
read -r SCRIPTDIR MAGE2ROOT <<< $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
## OR ##
read -r -d "\n" SCRIPTDIR MAGE2ROOT <<< $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
```

cause if I print the output just after this like:

`echo $SCRIPTDIR && echo $MAGE2ROOT && exit`

it just prints the path once. Why? And how can we make it work?

Any help/guidance required.

Posted on [Stackoverflow](https://stackoverflow.com/questions/54544940/bash-gitbash-syntax-for-multiple-variable-value-assignment-not-working-when-valu) too but no answer yet so thought, here it could be resolved

**Comment by landstander668** [comment]
Ignoring the possibility of spaces embedded within the current directory path, the `pwd` command will only return a single value. Since you're trying to assign two variables, it's normal that the second item will end up empty in this case. So what you need to do to make the example work is have the here string command incorporate the path twice, like:

    read -r SCRIPTDIR MAGE2ROOT <<< $(cd "$(dirname "${BASH_SOURCE[0]}")" && echo $PWD $PWD)
    echo $SCRIPTDIR $MAGE2ROOT

or

    read -r -d "\n" SCRIPTDIR MAGE2ROOT <<< $(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd && pwd)
    echo $SCRIPTDIR $MAGE2ROOT

For what it's worth, I get consistent results under both Git for Windows and Ubuntu. So this definitely isn't a Git for Windows specific item.
