### ISSUE TITLE
Git Bash Git Gui Branch History External Diff a/b files deleted

### ISSUE THREAD

**Issue by JonPetitta** [git-for-windows/git#2083]
- [x] I was not able to find an [open]

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.20.1.windows.1
cpu: x86_64
built from commit: 7c9fbc07db0e2939b36095df45864b8cda19b64f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
Windows 7 Ent 64
6.1.7601 SP1

$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
```
All defaults except run git bash and cmd, the middle option.

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
```
Not that I know of.
```
### Details

 - Which terminal/shell are you running Git from? 
```
 Bash
```
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Launch Git Bash
CD to project dir
start git gui
git gui menu Repository -> Visualize 'branch_X' History
git history menu Edit -> Preferences set External diff tool (I use UltraCompare GUI from IDM)
select commit X
select file x, right click -> External Diff
```
 - What did you expect to occur after running these commands?
```
External diff tool shows diff of file x
```
 - What actually happened instead?
```
External diff tool is unable to find a/b of file x
```
![image](https://user-images.githubusercontent.com/6631367/53256711-8112d480-3696-11e9-9874-f59bc7d9e6ba.png)

![image](https://user-images.githubusercontent.com/6631367/53256777-b15a7300-3696-11e9-9bf2-bd372e6a3f39.png)

```
The files are created
```
![image](https://user-images.githubusercontent.com/6631367/53257246-ace28a00-3697-11e9-8bad-a8ab3024b4f3.png)

```
I think it has to do with a win32 api call to 
SetDispositionInformationFile - Delete: true by wish.exe
```
![image](https://user-images.githubusercontent.com/6631367/53256807-c59e7000-3696-11e9-9f26-4ed9db726f19.png)

**Comment by dscho** [comment]
This log suggests that you configured UltraCompare in a way that does not wait for the diff to finish before returning control to the caller.

The exact command line that was configured in gitk is something that is notably missing from this report. And that is rather crucial information, as it is most likely the incorrect command line that causes the described issue.

There seems to be some information available from the UltraCompare forum how to configure it for use in Git, see e.g. http://forums.ultraedit.com/git-merge-with-ultracompare-dollar-issue-in-ues-v1-t17088.html?sid=570ff6f0563d22efeda391fca365d066#p57874 ... so that should help.

Good luck hunting for the correct command-line!
