### ISSUE TITLE
Release Request: Add options for latest to be included in the downloadable file names for easy automation access.

### ISSUE THREAD

**Issue by Bioblaze** [git-for-windows/git#2117]
This would be a Idea or Request to do with out hit for windows publishes its releases.

I would like to Suggest having setup a addition too your releases. By setting up the latest tag within the name along with your releases. Example.

`
https://github.com/git-for-windows/git/releases/latest/download/Git-2.21.0-64-bit.exe
`
This will download the latest file automatically. my concept was to do this.
`
https://github.com/git-for-windows/git/releases/latest/download/Git-latest-64-bit.exe
`
This would allow for Applications, and other Developers to include download options directly for the latest version of git, you could also do this for the Source tar as well. 

I was looking to automate the process of helping setup tools for Game Engines and I ran across this issue, I either have to hardcode that version of git into the source, or hold a 3rd party api that I would query to check the latest and get the 64-bit exe. 

If this could be done at all, I believe alot of different communities would be really happy.

I know this isn't a very formal issue request, and yes It may sound odd. I hope someone can comment on it.  Hope I also didn't enrage the community by this Request/Idea. Thank you for your time.

**Comment by PhilipOakley** [comment]
@Bioblaze Please could you proof read your suggestion. The first suggested command is identical to the second 'current'  command.

I also guess that you were using the "tag" term gererically, rather than git-specific, as a git-specific tag should be immutable, and clearly the 'label' URL you hope to suggest (see proof read above) will mutate its destination to the latest release. It will also need to be a distinct URL path, rather than just a trimmed one.

You may also want to look at the home page to see how it's 'Download' button operates https://github.com/git-for-windows/git-for-windows.github.io/blob/master/index.html#L37. Probing the blame for that line leads to https://github.com/git-for-windows/git-for-windows.github.io/commit/29ed632f92ebf87b08b58494a413a9fcba073562.

It would be a great micro project to extract the right details and stick it onto one of the wiki pages (such as https://github.com/git-for-windows/git/wiki/FAQ)

**Comment by Bioblaze** [comment]
@PhilipOakley what your `Download` button does isnt what I'm talking about, also if you do click the download button it just redirects you directly to a listing of downloads.

`
https://github.com/git-for-windows/build-extra/releases/latest
`
Try it yourself, what i'm talking about is setting the actual filenames so that you can procedurally download the latest git, and install it all from simple means.

What you just gave me, is exactly how it is now, and how it is now doesn't really allow for `Automation` it simply makes more hassle then its worth, thus why I made the Suggestion this way other developers who utilize git within their applications, have a easy and simple way to pull the latest/greatest git build and install it. 

I can make a few example scripts in powershell, node.js, and a few other languages to showcase what i'm talking about. 

Currently I need to use a api to query the page, scan for links pull the links, then validate the correct download link then spit it out via the api request. It seems like that can be avoided for alot of programmers by simply just adding in a actual bit into the name. 

Thats why I gave you a example link in my first post.

**Comment by dscho** [comment]
Why not use `https://github.com/git-for-windows/git/releases/latest/Git-$(curl -s https://gitforwindows.org/latest-version.txt)-64-bit.exe`?

**Comment by Bioblaze** [comment]
@dscho I did't even know that was a thing... Thank you!
