### ISSUE TITLE
git for windows need a visually different icon for git bash and git gui

### ISSUE THREAD

**Issue by nim-nim** [git-for-windows/git#2155]
Right now git for windows uses the same icon for  git bash and git gui.

That makes git shortcuts in the launch menu and the task bar very confusing if you use both tools regularly (even if you make the effort to change one of the icons manually in the shortcuts the title bar icon reverts to the built-in one).

git bash probably needs something more terminal-oriented as its icon (gnome-terminal, windows powershell or windows cmd could be taken as inspiration).

If a complete new icon design is too hard, just using different colors for each icon so they can be distinguished visually would be great.

**Comment by dscho** [comment]
Can you propose some icons?

**Comment by rimrul** [comment]
I guess they could be confusing if pinned to the task bar (post vista) or start menu (post 7). The colours and their arangement are based on the windows logo though. Those shouldn't change.

>even if you make the effort to change one of the icons manually in the shortcuts the title bar icon reverts to the built-in one

That shouldn't be a big deal, because Git-Bash and Git-Gui are quite distinct windows from each other and the builtin icon for Git-Gui is the old git icon while the builtin icon for Git-Bash is the Git for Windows icon.

>Can you propose some icons?

How about  adding a white $ and a green (or white) _ to the blue panel for Git-Bash based on [odb/official-bash-logo](https://github.com/odb/official-bash-logo)? Though we might need to contact the FSF about that.

**Comment by nim-nim** [comment]
> > even if you make the effort to change one of the icons manually in the shortcuts the title bar icon reverts to the built-in one
> 
> That shouldn't be a big deal, because Git-Bash and Git-Gui are quite distinct windows from each other and the builtin icon for Git-Gui is the old git icon while the builtin icon for Git-Bash is the Git for Windows icon.

On my windows 10 system  both apps use the same new icon.

**Comment by rimrul** [comment]
![Mockup of my suggestion](https://user-images.githubusercontent.com/6178234/56058901-0e070f80-5d63-11e9-8a00-60044817459b.png)

**Comment by PhilipOakley** [comment]
As a throw away bike shed comment, I'd also _like_ to have the SDK and regular bash window icons slightly different (maybe in the title bar, maybe using the MSYS purple border as the colour distinction).

Why: because if I've got both open on screen then it would assist in telling them apart.

So if anyone has a the know-how and the time to sneak it in as a PR. But I'll live if if nothing happens :wink:

**Comment by nenonix** [comment]
WIT is a good name

**Comment by PhilipOakley** [comment]
> WIT is a good name

I'm guessing that you have replaced the 'G' in Git, with the 'W' from Windows. 

Creates opportunities for 'gwit', 'wigit', or just plain 'gfw', but then "any sufficiently abbreviated technology is indistinguishable from magic" (me, just now, based on Arthur C Clarke's aphorism).

Still need someone to do a PR that integrates the Icon change.. Hope _you_ can help.

**Comment by nenonix** [comment]
@samanro - can you help here? (I will assist with PR if needed).

**Comment by samanro** [comment]
Hi @nenonix  - I don't have any context for this request. Can you explain what this is for, what you need, and what team is requesting? Thanks

**Comment by dscho** [comment]
I guess we can close this due to inaction.
