### ISSUE TITLE
Error in git bash on windows 10: failed to restrict file handles (193)

### ISSUE THREAD

**Issue by VictorBargains** [git-for-windows/git#2163]
$ git remote set-url github ssh://VictorBargains@github.com/VictorBargains/movie-suggester-api.git

$ git push github master
warning: failed to restrict file handles (193)

handle #0: 0000000000000138 (type 3, handle info (1) 0
handle #1: 000000000000013c (type 3, handle info (1) 1
handle #2: 00000000000003e4 (type 3, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
VictorBargains@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by PhilipOakley** [comment]
Hi @VictorBargains Thanks for making the report. I presume you are on a V16 variant which had that problem, which is now fixed by the newer versions. It's time to update :wink: 

The latest releases are listed at https://github.com/git-for-windows/git/releases/ along with the release note summaries.

I'll close the issue, though comments can still be added.
