### ISSUE TITLE
"No such file or directory" when I use "git log" and "git diff".

### ISSUE THREAD

**Issue by BlackConnor** [git-for-windows/git#2164]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.21.0.windows.1
cpu: x86_64
built from commit: 2481c4cbe949856f270a3ee80c802f5dd89381aa
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Tortoise Git version: 2.8.0

```
$ type -a git

git is /mingw64/bin/git
git is /mingw64/bin/git
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git log
error: cannot spawn more: No such file or directory
Submit 3f8ee99278eb273c0d1a6e3f885bd3a34bdbfa79(HEAD - > master)
```
 - What did you expect to occur after running these commands?

Just no error.

 - What actually happened instead?

Just the error.

I am learning the use of Git. I just created a README.txt file in a folder with only "Hello Git!" and this problem occurred when  testing "git log".

I have tried many ways to solve this problem. I modified the installation path without spaces and I set up GIT_SSH. I did anything I could do. But "git log" and "git diff" still have the same error. So, I am confused.

I think this is very important to tell you about that. If you can tell me how to solve this, I will be very grateful to you. Thank you all.

**Comment by BlackConnor** [comment]
And just now I use VSCode to test "git log" and this problem still there. This is my setting "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe" in VSCode. Maybe the real problem is in bash.exe.

**Comment by PhilipOakley** [comment]
How did you install Git?   Did you simply install tortoise git and it then installed an underlying Git version automatically?  Did you try with just a Git-for-Windows install (to remove Tortoise git from being a cause)?

Also could you confirm the different error messages from your different attempts. I note that the message `cannot spawn more:` could easily be confusing. What it is saying is `cannot spawn [the program called] 'more':`. 

The `more` program is a 'terminal pager' (i.e. it gives you one page of output at a time to the terminal screen) and was a development of the original `less` program (which did the original terminal paging). I don't believe that `more` is part of 'G-f-W', rather the `less` program is used as the simplest common pager. This would suggest (to me) that somehow Tortoise Git has updated the command processing to use the (non available) `more` pager.

**Comment by BlackConnor** [comment]
According to your answer, I know some reasons. I installed Git first and then Tortoise Git. To make sure it's not Tortoise Git, I installed Git for Windows on VMWare using Windows 7 without any errors. After that, Tortoise Git was installed, and everything went smoothly. So this must be a problem with my system.
 I'm sorry to have taken up your time. I don't know that "more" is a program. Can you tell me how to install "more" on my system or solve this problem? Reloading the system is a bit of a hassle. Does "more" come with Windows? How do I download it? I'm terribly sorry for the delay. I apologize again, my friend. Thank you for the maintenance of Git, which is a great software.

**Comment by PhilipOakley** [comment]
Hi @BlackConnor No need to apologize for the misunderstanding regarding 'more' - it's an easy mistake. 

The core maintainer of Git for Windows is actually Dscho, who has done **all** the hard work over many years. I'm just doing some lower level support by responding to common problems and pointing folks at similar issues when they are repeats.

You should have 'less' available as a pager. Though I've not played with that area very much. Folks who live Linux know all about that stuff though :wink: The need for pressing space (give me another screenful), or using 'q' (I've seen enough), is so that you don't have to scroll back over thousands of lines of output, especially if your command accidentally produces more than expected ;-). (works with both `more` or `less` - see how they got their names - weird sense of humour those old grey beards ;-).

Assuming the command output is less than a screen most pagers don't need to ask for the 'q' - maybe just adjust your terminal window size to give a few more lines to show enough for your usual command line output (and learn `log -1` and all the other `-<n>` output limiters for the commands - saves a lot of hassle and frustration;-).

Was the `[core] pager` set to `more`? i.e. any idea how it became the required program to spawn on your system? (i.e. can you just set it back to `less` or even unset it, which may default it to less)
