### ISSUE TITLE
Add a PR/CI build that offers an installer/portable Git as artifact

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#2171]
We already use the Azure Pipelines pretty well, but we do not yet build easy-to-test installers and portable Gits. Let's change that.

**Comment by PhilipOakley** [comment]
> build easy-to-test installers and portable Gits.

Dumb question, do we do MSVC builds, including tests/builds for what's in shears/next & /pu? (it's a 'back of the queue' thought)

**Comment by dscho** [comment]
We do, have a look at the [active branches](https://github.com/git-for-windows/git/branches/active) and click on the green checkmarks.

**Comment by PhilipOakley** [comment]
> have a look at the active branches https://github.com/git-for-windows/git/branches/active and click on the green checkmarks.

Thanks. I hadn't realised they were there.

Also, for the lurkers and searchers (IIUC):

1. The active branches are shears/master, shears/next, shears/pu, shears/maint and vs/master. The term 'shears' refers to the script that rebases all the Windows fixes on top of the latest upstream git.git branches of maint, master, next and pu. The 'pu' (potential updates) branch is the most immature and may contain failures. 'vs/master' (IIUC) is produced using the Visual Studio tool chain, rather than the 'gcc' tool chain.

2. After clicking on the **green check-mark**, you will get a pop-up listing the various builds, select the appropriate build (typically ignore the test builds) which drops you onto a second page showing that things passed OK. Click on the `0 errors link` to get the actual build results page. In the top right is the Blue "Artefacts" button, which should get you the item desired. (other routes through the Azure DevOps screens may be possible :wink:

hope I got that right ;-) (esp the vs/master branch..)

**Comment by dscho** [comment]
`vs/master` is `master` with Visual Studio project files committed on top (`make vcxproj`, so that you can build this in Visual Studio *without* Git for Windows' SDK.

**Comment by dscho** [comment]
This is now addressed. As of yesterday, snapshot builds are built using [the same Azure Pipeline as official Git versions](https://dev.azure.com/git-for-windows/git/_build?definitionId=34&_a=summary) (although for obvious reasons, they are not published as GitHub releases, [unlike official Git versions](https://dev.azure.com/git-for-windows/git/_release?_a=releases&view=mine&definitionId=1), instead they [are published](https://dev.azure.com/git-for-windows/git/_release?_a=releases&view=mine&definitionId=2) to https://wingit.blob.core.windows.net/files/index.html.

This addresses the CI part of this ticket. The PR part will never be automatic: those builds are as-good-as-official ones, and only authorized users should be able to trigger those builds, manually. So whenever we need an installer or a portable Git for a given PR, the _Git Artifacts_ pipeline needs to be triggered, with `refs/pull/<number>/merge` as the target branch.
