### ISSUE TITLE
Make git gui GIT_TRACE=1 compatible

### ISSUE THREAD

**Issue by techtonik** [git-for-windows/git#218]
`git gui` rc2 crashes if GIT_TRACE=1 is set.

https://github.com/git-for-windows/git/issues/196#issuecomment-113909611

I see no reason for it to fail. `stderr` description is available if I open `git gui` from cmd.exe session, and even if it is closed, it is possible to add memory buffer for it.

**Comment by dscho** [comment]
This issue is not specific to Windows. Please report it on the Git Mailing list: git@vger.kernel.org

**Comment by techtonik** [comment]
@dscho why are you so sure that it is not specific on Windows? As for me it is at least critical to solve issue #196, so it should stay here at least to track when upstream is fixed and validate that the fix works for Windows.

**Comment by dscho** [comment]
I am so sure because it also is an issue on Linux.

**Comment by techtonik** [comment]
Sent a mail there.

**Comment by dscho** [comment]
Please note that the mail you sent is so short that I expect at least some people will find it rude, and ignore it. Don't shoot the messenger.

**Comment by techtonik** [comment]
I guess pleasing other people by writing long emails is out of my powers.

**Comment by dscho** [comment]
It has nothing to do with "pleasing other people", but all to do with "respectfully ask others to help you".

If you spend 30 seconds to toss a hyper link without any further comment to people who you expect to be more qualified than yourself to solve your problem, you should expect those people to spend roughly the same amount of time on addressing your needs (especially when they can expect nothing at all in return). This is mere logic. If you give others the impression that you value your time over theirs, a lot, do expect them to respond in kind.

As it is, *I* already spent substantially more time (and more polite words) helping you than you possibly could have spent on the entire interaction with the Git project. I did this not so much because I felt that you gave me any incentive to do so, but because I am sympathetic to your woes, and I encourage you to think more along these lines to get a chance to see those woes addressed:

> [*[...] you're not giving him any reason to help us. Okay. Let me show you a little something about incentive-based economics. [...]*](http://www.st-minutiae.com/academy/literature329/523.txt)

**Comment by techtonik** [comment]
@dscho I am a looser in debts and can't give more respect to others than I have for myself. So, please, don't add more misery to this by asking me to be insincere or teaching me all that stuff about the "incentive-based economics".

**Comment by dscho** [comment]
Okay, let's leave it at that.
