### ISSUE TITLE
error: waitpid for .git/hooks/commit-msg failed: No child processes

### ISSUE THREAD

**Issue by Jyonanda** [git-for-windows/git#2208]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

$ git --version --build-options
git version 1.9.5.msysgit.1

** insert your machine's response here **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17763.503]

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 "C:\Program Files (x86)\Git\etc\install-options.txt"
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
"C:\Program Files (x86)\Git

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Tortoisegit

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Using tortoise-git to push code
```
 - What did you expect to occur after running these commands?

its should commit and push

 - What actually happened instead?

 facing issue while pushing code from my local to Gerrit using tortoise git with below error.

error: waitpid for .git/hooks/commit-msg failed: No child processes
git did not exit cleanly (exit code 1) (9547 ms @ 5/28/2019 9:18:41 PM)
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

for all repo its happening.It was working before 2 days,recently facing this issue.

**Comment by dscho** [comment]
> git version 1.9.5.msysgit.1

This is not a supported Git for Windows version.

Even worse: since you are using a Git for Windows version *this old*, you are open to tons and tons of security issues, see https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version.

Further, this bug report is sadly full of holes, where placeholders were left in place (unanswererd) that we put in the issue reporting template with the intention of helping users to craft really helpful bug reports.

> .git/hooks/commit-msg

I can only wager a guess that this hook comes from Gerrit? Please do make an effort and provide the contents of this hook here.

For further brownie points, and assuming that this hook is actually a shell script, add the line `set -x` after the initial `#!/bin/sh` line, and try again, that should give you tons of useful output that you can even analyze yourself.


> while pushing code from my local to Gerrit using tortoise git with below error.

This is not really a good bug report, for multiple reasons:

- There are *way* too many components at play here. In the least, you should cut TortoiseGit out of the picture by calling Git directly, via the command-line. Preferably even cut out Gerrit, as that is such a complex component that could interfere with all kinds of issues, and it is definitely not a piece of software that is under the maintenance/control of the Git for Windows project.
- When you say "pushing code", that sounds as if you said `git push`, but that does not even remotely start the `commit-msg` hook.
- There is nothing even close to a [Minimal, Complete & Verifiable Example](https://stackoverflow.com/help/mcve), something we specifically ask for in our issue reporting template in the hopes that the bug report give us enough information to actually act on.

I fear that there is simply not enough information yet to do anything helpful, which is frustrating not only for you, @Jyonanda, but also for me. What worse thing than knowing that there is a bug but not being able to do *anything* about it!

So please, @Jyonanda, please do fill in the blanks *as best as you can*.
