### ISSUE TITLE
vi has become completely unusable.

### ISSUE THREAD

**Issue by sprintr** [git-for-windows/git#223]
Using v2.4.3 and v2.4.4, vi has become completely unusable. It has also lost its syntax highlighting. v2.4.2 worked fine with vi.

git version 2.4.2 windows 1
![git version 2 4 2 windows 1](https://cloud.githubusercontent.com/assets/3390089/8315930/3ddd4668-1a0d-11e5-867a-6a9a149c80e2.png)

git version 2.4.4 windows 1
![git version 2 4 4 windows 2](https://cloud.githubusercontent.com/assets/3390089/8315940/47fbaf40-1a0d-11e5-88c6-de8bc2837d25.png)

**Comment by linquize** [comment]
where is syntax highlighting in 2.4.4.1?

**Comment by sprintr** [comment]
There is no syntax highlighting in 2.4.4 @linquize

**Comment by nalla** [comment]
What is your output of the following calls?
```bash
cat /etc/vimrc
cat ~/.vimrc
```

**Comment by dscho** [comment]
> There is no syntax highlighting in 2.4.4 @linquize

Uhm.

Just to be sure, here is the information that I would really like in essentially *every* bug report because it is really relevant: 

- This is Git Bash,
- as installed via the Git installer (release candidate 3)
- 64-bit Windows 2012

And editing a C file just works:

![vi-syntax-highlighting-works](https://cloud.githubusercontent.com/assets/127790/8324611/ccfa8da4-1a41-11e5-9736-7a6da648c5f0.png)

Well, maybe it is just PHP highlighting? Nope, that works, too:

![even-php-highlighting-works](https://cloud.githubusercontent.com/assets/127790/8324632/fedd9690-1a41-11e5-8f79-1c3566665cbd.png)

Therefore it is not a problem of Git for Windows per se, but instead an issue in your particular setup. @nalla was nice enough to suggest pointers how to start hunting. I would also offer this pointer:

```bash
ls /usr/share/vim/vim74/syntax/
```

(which takes quite a while here and lists 583 files that are used by vim to provide 583 different types of syntax highlighting.)

I would also like to challenge you to improve the rather hand-waving statement

> vi has become completely unusable

Without specifics, this bug report leaves a lot of room for improvement. Please use that room and improve the bug report to the point that @nalla or I have a chance to help you resolve your problem.

**Comment by sprintr** [comment]
Did a clean install and it has fixed the problem. Could not repro this after that.
