### ISSUE TITLE
Git Bash Fonts Missing

### ISSUE THREAD

**Issue by TGGSJ911** [git-for-windows/git#2240]
Platform: Windows 10

I just noticed that some of the font types (like Consolas, Courier New) in my gitbash window are missing. I tried to reinstall the gitbash but the issue still exists. 
![fontmissing](https://user-images.githubusercontent.com/35349993/59644611-a93dac00-913b-11e9-8285-a173841ceb80.jpg)

Can someone tell me how to solve this problem? Or how to completely remove gitbash so that I can reinstall it like I never had one in my computer.

**Comment by dscho** [comment]
Even if you failed to fill out the bug reporting template, it looks obvious that you use Windows' default console window (rather than MinTTY, which is Git for Windows' default).

This console is totally outside of Git for Windows' shipped files. It probably uses the system fonts, so it would appear that your system is rather broken (and not due to any of Git for Windows' faults).

**Comment by TGGSJ911** [comment]
> Even if you failed to fill out the bug reporting template, it looks obvious that you use Windows' default console window (rather than MinTTY, which is Git for Windows' default).
> 
> This console is totally outside of Git for Windows' shipped files. It probably uses the system fonts, so it would appear that your system is rather broken (and not due to any of Git for Windows' faults).

**Comment by TGGSJ911** [comment]
Thank you for dscho's answer. I reinstall the gitbash applying MinTTY and the problem is solved. 

Really appreciated!
