### ISSUE TITLE
Subtree push is broken

### ISSUE THREAD

**Issue by maxisam** [git-for-windows/git#2241]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 

2.22.0 @Win10 64bit 

### Details

git subtree push doesn't work. 

The result is like this 

https://public-inbox.org/git/20190101131947.GA18907@ash/

Revert back to 2.18 and it starts to work correctly.  (2.19 and 2.20 don't work either)

**Comment by PhilipOakley** [comment]
If it (the suggestion in the lined reference) is working correctly, and is tested (hopefully you have checked), why not create a PR, with crisp commit message, or even submit a patch to the upstream Git list git@vger.kernel.org.

It's unlikely that a revert back to that version (2.18) is likely to happen, so let's move it forward with a Pull Request.

**Comment by maxisam** [comment]
I was just trying to bring this up here, because there might be others having the same issue. Of course I know a revert back to 2.18 is not a solution. Just trying to give people more clue and a workaround. I thought my intention is obvious.

**Comment by PhilipOakley** [comment]
Hi @maxisam Thanks for clarifying. Unfortunately, in the wider domain, most things can be misinterpreted, so it's always worth over-clarifying points about what a comment is about, and what it's not about - I've often fallen into the trap of assuming people would make the same assumptions as me.

That said, if you can send a patch to upstream that would be even more useful :wink:

**Comment by dscho** [comment]
@maxisam what might also help is a proper report including a working MCVE, i.e. a way to reproduce the issue. You chose to delete most of the bug reporting template, which is why you probably missed that part.

Without such a way to reproduce the issue, it is a lot less likely that _anybody_ can help you.

**Comment by dscho** [comment]
> The result is like this
> 
> https://public-inbox.org/git/20190101131947.GA18907@ash/

By the way, this is a poor bug report for multiple reasons:

1. It does not at all state the problem.
2. It sends the reader to a different web page, putting the entire burden of figuring out the bug _report_ on others. You already put the burden of the bug fix on others, so that's a double-burden right there.
3. Your link points to a patch, not to a bug report.
4. That mail you linked to has one reply, claiming that the patch does not fix the problem.

If you want me to be as sloppy with a bug fix as you were reporting the bug, you might not be too happy about the obvious result.

**Comment by maxisam** [comment]
Thank you. I now know why no body wants to report an issue. That question really drove me nuts. I was like no way I am the first one report this bug that has been there almost a year. Good job guys. Keep up the good work. Feel free to close the issue. I think I got all I needed.

**Comment by maxisam** [comment]
You know what? I make it easier for everyone. I will close the issue since people with the same problem can search this anyway. If you decide to fix it properly, feel free to re-open it.

**Comment by PhilipOakley** [comment]
@maxisam We don't know what the problem is as you experience it. No one has actually 'nailed down' what the core problem is, hence it can't be fixed because we are still ignorant of what needs to be looked at or how to even set up the problem (as you experience it). 

As seen on the much higher volume Git list, no one there had any more than an idea either (i.e. no one really followed up the one reply). This is Free, Collaborative, Open source, you get out what the contributors put in. Contributors only have a limited amount of time available, so it's a case of helping them to help you.
