### ISSUE TITLE
Git 2.22.0 Setup wizard - usability issue

### ISSUE THREAD

**Issue by DraxDomax** [git-for-windows/git#2271]
0. I am a new git user.

1. Downloaded Git for Windows Setup 2.22.0 from https://git-scm.com/download/win
2. Ran the executable and proceeded through the wizard until: "choosing the default editor used by git".
= I have a list of options but only the vim option allows for clicking Next
= I have Notepad++ installed but choosing that makes me stuck with no apparent reason (can't click next, no explanation what is going on).

I think you either: 
A. Need to provide some text in that dialogue. So, that the user knows if there is anything they should do in order to prepare notepad++ for viable selection in the git4win setup.
Or: B. Expand the Setup program functionality to let the user hook up his existing notepad++ installation to the git setup.

As it is, I was forced to choose vim in order to get started with git, while I actually don't like vim and would rather use notepad++, which I already have.

**Comment by DraxDomax** [comment]
![image](https://user-images.githubusercontent.com/33070400/61714752-9417f680-ad53-11e9-84ce-8d22037d69c2.png)

**Comment by dscho** [comment]
> I think you either:
> A. Need to provide some text in that dialogue. So, that the user knows if there is anything they should do in order to prepare notepad++ for viable selection in the git4win setup.
> Or: B. Expand the Setup program functionality to let the user hook up his existing notepad++ installation to the git setup.

First of all, when you talk about a generic user and then continue to talk about "his" setup, please note that Git for Windows is an inclusive project. It is never "his". It is always "their" setup when you talk about a user that is not specified any further.

We take this very seriously, and so should you.

Further, I don't think it is appropriate to start this paragraph by "I think you either", as if it was something that somebody else, _anybody_ else needs to do.

This is a community project. You are part of the community. This is as much your task as anyone else's.

We take this community aspect very seriously, too.

Lastly, when the installer grays out the <kbd>Next</kbd> button it is because the Notepad++ installation was not found. The way the installer finds it is by [looking at the registry](https://github.com/git-for-windows/build-extra/blob/942b2e7ca6fb9d332b3146b13c59db7725882d7a/installer/install.iss#L1504), in particular at the string value of `SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\notepad++.exe`.

This is most certainly not configured in your setup, and you are right: the user experience is something that could use improvement.

And this is where you come in, as part of the community: you have the power to make this substantially better, it is open source. And remember [what Spider Man said](https://en.wikipedia.org/wiki/With_great_power_comes_great_responsibility#Origin_and_source).

You could, for example, add some code [after [the part that disables the <kbd>Next</kbd> button](https://github.com/git-for-windows/build-extra/blob/942b2e7ca6fb9d332b3146b13c59db7725882d7a/installer/install.iss#L1461)) to somehow make it known to the user that this editor was not autodetected.

You could also figure out which registry setting contains Notepad++'s path in your setup, or figure out any other way to auto-detect it, and then work on making [the code that performs that auto-detection](https://github.com/git-for-windows/build-extra/blob/942b2e7ca6fb9d332b3146b13c59db7725882d7a/installer/install.iss#L1504) more robust.

**Comment by PhilipOakley** [comment]
@DraxDomax I think I've seen the issue before (can't quite remember where reported), and vaguely remember that one route was to initially select vim, then next, then use the back button at some point to magically get back to discovering Notepad++. If that does work do provide feedback so the symptoms can be correlated with the cure.

As @dscho says, it'll need a bit more research on your PC to discover what is in the registry for the Notepad++ installation link. (check out the links dscho provided for guidance)

**Comment by dscho** [comment]
@DraxDomax Occam's razor dictates that I should assume you lost interest in this, so I'll close this ticket.
