### ISSUE TITLE
warning: 'C:\ProgramData/Git/config' has a dubious owner: 'Administrateur'.

### ISSUE THREAD

**Issue by glhez** [git-for-windows/git#2304]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
C:\Program Files\Git>cmd.exe /c ver

Microsoft Windows [version 10.0.17763.678]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

My Windows 10 is a French professional OEM.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

ConEmu, Bash (""C:\Program Files\Git\git-bash.exe" --cd-to-home")

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git status
warning: 'C:\ProgramData/Git/config' has a dubious owner: 'Administrateur'.
For security reasons, it is therefore ignored.
To fix this, please transfer ownership to an admininstrator.
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
```
 - What did you expect to occur after running these commands?

No warning about C:\ProgramData\Git\config being owned by Administrateur.

See the following screenshot: Administrateur is French word for Administrator.
Unless the check is done with "admininstrator" which raise an error in Firefox spellcheck (want me to use administrator instead).

![image](https://user-images.githubusercontent.com/10855953/63642967-16376a00-c6c8-11e9-8d50-f6a78ec4f4dc.png)

For records, here is the SID of the Administrator account:

```
C:\Program Files\Git>wmic useraccount get name,sid
Name                SID
Administrateur      S-1-5-21-1752033801-3029444-3845327491-500
```

 - What actually happened instead?

I've got a security warning each time I launch a git command.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No

**Comment by PhilipOakley** [comment]
Is this a virus scanner artefact? The middle section of the warning: does not look like a git error message.
```
warning: 'C:\ProgramData/Git/config' has a dubious owner: 'Administrateur'.
For security reasons, it is therefore ignored.
To fix this, please transfer ownership to an admininstrator.
```
Do you have any security software installed?

**Comment by PhilipOakley** [comment]
Hmm. Also found other reports https://developercommunity.visualstudio.com/content/problem/697976/git-failing-with-unknown-author.html  (this error in VS 2019 editions)
which tend to suggest to me checking where %ProgramData% points and if that file is actually present.
Do you also have VS2019 installed?
Intriguing.

**Comment by glhez** [comment]
The only security software is the AV that ships with Windows 10. And I don't have VS2019.
I did not have this message before (I installed today 2.23).
The file mentioned by the warning exists, that's where the screenshot comes from.

**Comment by PhilipOakley** [comment]
@glhez 
your [edit] doesn't show on the mailing list.
> [edit]
> (1) renaming C:\ProgramData\Git to C:\ProgramData\Gitx fix the problem.
> (2) the error message can be found in git.exe (C:\Program Files\Git\mingw64\bin\git.exe) and an hex editor: '%s' has a dubious owner: '%s'

Looks like that git.exe may need a bit of decompiling to see where that message is pulled in from.
Also at (1) does that rename affect the ownership status?

**Comment by PhilipOakley** [comment]
further, the string "dubious owner" is located in libgit.lib when seen from an SDK compilation.

It looks like the string is part of a GetText list of strings, and comes shortly after a 'secur32.dll' message 
```
# GETTEXT POISON #������secur32.dll�����GetUserNameExW��failed to validate '%s' (%ld)���invalid owner: '%s'�����unknown�(unknown)�������(some user)�����'%s' has a dubious owner: '%s'.
For security reasons, it is therefore ignored.
To fix this, please transfer ownership to an admininstrator
```
the <?> chars are nulls. LFs create line feeds... (copied via HxD hex editor)

It may help investigators who know this part of the code better than I.

**Comment by PhilipOakley** [comment]
I've also just seen https://stackoverflow.com/questions/57592530/latest-update-brings-github-error-on-pull-push-or-sync report and cross linked here.

**Comment by glhez** [comment]
> Also at (1) does that rename affect the ownership status?
No. I could also try to reinstall Git without that folder and see what kind of permissions Git is creating the folder with. But I fear this won't work: the user I will use to install is Administrateur and I guess that the permission will be the same.

By the way, by looking at "dubious owner", I did not find anything in Github, but by the second line I found this issue : https://github.com/desktop/desktop/issues/8109 which is 10 days ago. It relates to CVE-2019-1211 and a problem of file permission. It does not help me fixing the issue (beside renaming).

**Comment by PhilipOakley** [comment]
@glhez Thanks for that cross reference. I've posted a question over [there ](https://github.com/desktop/desktop/pull/8101)as the problem is almost, but not quite identical (looks like this is a localisation issue for the same bug). 
It looks like dscho is currently on holiday (well deserved).

**Comment by dscho** [comment]
This is a new warning in v2.23.0, and it is intentional.

What is _not_ intentional is that it triggers for the "Administrateur", i.e. for any administrator.

@glhez could you have a look at https://github.com/git-for-windows/git/blob/v2.23.0.windows.1/compat/mingw.c#L3345 and investigate why this check is not sufficient to let Git know that this file is owned by an administrator?

**Comment by glhez** [comment]
Thanks for pointing the line! I rally don't understand why this line never get reported by Github "search in this repository".

For the issue, I think I found a clue (I don't have a C debugger to further confirm):

```
if (IsWellKnownSid(owner_sid, WinBuiltinAdministratorsSid) ||
	    IsWellKnownSid(owner_sid, WinLocalSystemSid)) {
```` 

If I understand this piece of code, this code check if the owner is either (quoted from [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ne-winnt-well_known_sid_type)) one of these:

Enum value | Description
-- | --
WinBuiltinAdministratorsSid | Indicates a SID that matches the administrator group.
WinLocalSystemSid | Indicates a SID that matches the local system.
WinAccountAdministratorSid | **Indicates a SID that matches the account administrator's account**.

I've put in bold the last one because I think that's the error here: I've renamed the folder from Git to Gitx, and the error is now gone.

What I see now is that the owner is the group `Administrateurs `rather than the user `Administrateur`:
```
C:\Users\Gael>wmic group get name,sid
Name                                          SID
Administrateurs                               S-1-5-32-544
```

I clearly don't remember having made change to this folder or the file inside (the config file is the same than the newly installed one). Perhaps the permission did change at a time?

Now I only have the "/dev/fd" stuff being (`/dev/fd/62: No such file or directory`) annoying, but I know what I have to do (eg; #2291).

**Comment by assarbad** [comment]
Hi, you could try to check the SID of `Administrateur` and `Administrateurs` (group) using `psgetsid -nobanner -accepteula Administrator`. [psgetsid](https://docs.microsoft.com/en-us/sysinternals/downloads/psgetsid) is part of Microsoft's PSTools and therefore can be downloaded from the Microsoft website (and is code-signed). But you already gave the SID by way of `wmic` and a RID of 500 (the last segment of the SID) means it's the built-in administrator as was to be expected.

Anyway, the warning comes from [here](https://github.com/git-for-windows/git/blob/master/compat/mingw.c#L3345).

Alas, what's the likeliest explanation here is that it's indeed owned by `Administrateur` (the built-in administrator _user_) whereas the code:

```
	if (IsWellKnownSid(owner_sid, WinBuiltinAdministratorsSid) ||
	    IsWellKnownSid(owner_sid, WinLocalSystemSid)) {
		ret = 1;
		goto finish_validation;
	}
```

... checks against the ownership of the `WinBuiltinAdministratorsSid` (group) and `WinLocalSystemSid` (aka `SYSTEM`, the computer account ... more privileged than admins in some aspects) but should, as @glhez already pointed out, _also_ check for `WinAccountAdministratorSid` ... and `WinAccountDomainAdminsSid` ... and potentially others like it.

In reality you probably don't want to even check outright against the SID of the owner, but rather whether that SID matches an account that _is_ the built-in admin or member of the built-in Administrators (Administrateurs) group.

Something along the lines [of this](https://bitbucket.org/windirstat/windirstat/src/186490097102a8472ab65fe426316d32bded99d5/3rdparty/lua/src/modules/isadmin.c#lines-18), except that for a token this is presumably somewhat more trivial.

Let me look it up and get back to you. It's been a while since I dabbled with the innards of NT security.

**Comment by dscho** [comment]
> Something along the lines [of this](https://bitbucket.org/windirstat/windirstat/src/186490097102a8472ab65fe426316d32bded99d5/3rdparty/lua/src/modules/isadmin.c#lines-18), except that for a token this is presumably somewhat more trivial.

Maybe something like this, adapted from https://docs.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-checktokenmembership:

```c
	SID_IDENTIFIER_AUTHORITY nt_authority = SECURITY_NT_AUTHORITY;
	PSID administrators_group = NULL;
	BOOL b;

	[...]
	if (IsWellKnownSid(owner_sid, WinBuiltinAdministratorsSid) ||
	    IsWellKnownSid(owner_sid, WinLocalSystemSid) ||
	    (AllocateAndInitializeSid(&nt_authority, 2,
	                              SECURITY_BUILTIN_DOMAIN_RID,
	                              DOMAIN_ALIAS_RID_ADMINS,
	                              0, 0, 0, 0, 0, 0, &administrators_group) &&
	     CheckTokenMembership(owner_sid, AdministratorsGroup, &b) && b)) {
		ret = 1;
		goto finish_validation;
	}

	[...]
finish_validation:
	if (administrators_group)
		FreeSid(AdministratorsGroup); 
```

@glhez please test (if you haven't installed [Git for Windows' SDK](https://gitforwindows.org/#download-sdk), please do so, then call `sdk cd git`, edit `compat/mingw.c` accordingly, build with `sdk build git` and then test with `./git config core.abc`

**Comment by KalleOlaviNiemitalo** [comment]
> `CheckTokenMembership(owner_sid, AdministratorsGroup, &b) && b)) {`

@dscho, no, you can't use `PSID owner_sid` as the `HANDLE TokenHandle` parameter of `CheckTokenMembership`.

**Comment by KalleOlaviNiemitalo** [comment]
There used to be a policy setting "System objects: Default owner for objects created by members of the Administrators group", but it was removed. [947721 – A Group Policy setting is not available in the security policy settings list on a computer that is running Windows Server 2008](https://support.microsoft.com/en-us/help/947721/a-group-policy-setting-is-not-available-in-the-security-policy-setting)

I started elevated Command Prompts on Windows 7 SP1 and Windows 10 and ran `copy nul dihdah` to create a file. In both versions, the file became owned by the Administrators group. I don't know what that KB947721 means when it says UAC "will ensure the user account is being used as owner for all objects created locally."

I am curious how the file originally became owned by `MS-06-ZAKU-II\Administrateur`. I hope it is a rare situation and the administrator can just fix it by giving ownership to the group.

If a user is a member of the Administrators group but a non-elevated process of theirs replaces `C:\ProgramData\Git\config`, then not letting that file affect other users seems safer to me. Somewhat like COM ignores `HKEY_CURRENT_USER\SOFTWARE\Classes` in elevated processes. Thus, if Git needs to be changed here, I would prefer just checking for the specific Administrator SID rather than accepting any member of the Administrators group.

If Git really has to check for membership in the Administrators group, rather than just the Administrator user, then perhaps this can be done with `NetLocalGroupGetMembers` (the Administrators group is local, right?), with `NetUserGetLocalGroups` and `LG_INCLUDE_INDIRECT` (in case the user is a member of a global group that is a member of the local Administrators group), or even with `AuthzInitializeContextFromSid` and 
`AuthzAccessCheck`. But I fear that these functions may fail with `ERROR_ACCESS_DENIED` or require network access.

**Comment by dscho** [comment]
> But I fear that these functions may fail with `ERROR_ACCESS_DENIED` or require network access.

Yes, a very real possibility (let alone performance bottleneck).

**Comment by glhez** [comment]
@dscho I probably won't have time this week, at least not the next two days.

> @KalleOlaviNiemitalo: I am curious how the file originally became owned by MS-06-ZAKU-II\Administrateur. I hope it is a rare situation and the administrator can just fix it by giving ownership to the group.

I have honestly no clue at all: I generally never mess with `C:\ProgramData` and the system was cleanly installed to a new PC with a new M2 SSD. The only stuff I've imported back are file located in `%USERPROFILE%`, since to my knowledge there should be nothing to backup in `C:\ProgramData` (and I hope so :o ).

I suppose that along this security fix, there was another fix in the installation to use the *Administrators* group rather than the user (*Administrateur*) which installed Git for Windows: that is verified  by removing the folder and letting Git recreate them during its (re)installation.

Also, the correction could also be to change the warning: if `Administrators` is considered the true owner of the file, then the warning could simply be changed to explain which owner group it expect, and if possible in the Windows language. 

For example,

> warning: 'C:\ProgramData/Git/config' has a dubious owner: 'Administrateur'.
> For security reasons, it is therefore ignored.
> To fix this, please transfer ownership to the 'Administrateurs' group.

At least, it would not mislead me (which is the primary reason of this bug report): the current message is telling me to *transfer ownership to an admininstrator* but I don't know which, and worse it is already the case, and it is not what Git is doing either way.

**Comment by dscho** [comment]
@glhez you're the best judge what message would be most helpful to you, and I look forward to a PR to adjust it accordingly, whenever you have time.

**Comment by Alcha** [comment]
This is something that came up recently at work and executing the following PowerShell as an admin fixed the issue for us:

```PowerShell
$FilePath = "C:\ProgramData\Git\config"
$FileContent = Get-Content -Path $FilePath -Raw
Remove-Item -Path $FilePath
New-Item -Path $FilePath -Value $FileContent
```

It simply gets the content of your current git config, deletes it, then creates it as an admin again. It may not work for everyone, but it's working great for me 😅

**Comment by KalleOlaviNiemitalo** [comment]
Or do this with cmd.exe as an admin:

```bat
icacls "%ProgramData%\Git\config" /setowner *S-1-5-32-544
```

The PowerShell Set-Acl cmdlet supports setting a DACL or a central access policy but does not support setting the owner. I didn't find a request for such a feature, either; PowerShell/PowerShell#10088 is related.

**Comment by dscho** [comment]
... or help with identifying the patch that we would need to make this work again... I still think that my previous comment should help with that: https://github.com/git-for-windows/git/issues/2304#issuecomment-527176588

**Comment by glhez** [comment]
Sorry I did not have time to change the warning message (or at least try).

I don't know Windows API that much, but I kind of think that if I push some change to the warning, it should contains the exact name of the expected owner (eg: Administrateurs in French, and so on).

That said, I don't even know how to translate the WinBuiltinAdministratorsSid enum into a SID and MSDN does not help (there too many API). Transforming said SID into a human localized stuff is done in the code above, to translate the owner_sid into something useful.

`CreateWellKnownSid`  seems to be what I should use, using NULL for the domain, but I did not dig too much in that.

**Comment by KalleOlaviNiemitalo** [comment]
> `CreateWellKnownSid` seems to be what I should use

Yes, and you can make a local buffer of `SECURITY_MAX_SID_SIZE` bytes for the SID, although WinBuiltinAdministratorsSid would fit in a smaller buffer.

**Comment by dscho** [comment]
> Sorry I did not have time to change the warning message (or at least try).

┐( ˘_˘)┌

> I don't know Windows API that much

Neither do I, to tell you the whole truth.

> I don't even know how to translate the WinBuiltinAdministratorsSid enum into a SID

Neither did I, when I started my search yesterday.

> but I did not dig too much in that.

Well, aren't you lucky that I needed to address this bug myself. But yes, I am miffed that y'all feel so free to leave pretty much _all_ the Git for Windows work to others, which usually means: to me. Without giving back as much as you received. That does not feel so great.

I opened the PR with my suggested solution: https://github.com/git-for-windows/git/pull/2336

Could you at least build and test this in your setup, so that we can be certain that this addresses not only _my_ problem?

**Comment by glhez** [comment]
Problem fixed, Thanks.

**Comment by deoprog** [comment]
Hi! Resolve problem removed files *config* in path _C:\ProgramData\Git_

**Comment by dscho** [comment]
> Resolve problem removed files _config_ in path _C:\ProgramData\Git_

That's not a resolution. You removed the config, now you are missing those settings.

**Comment by PhilipOakley** [comment]
@deoprog which of the config files (--local, --system, --global, --un-named-one)  does that match  `git config --list --show-origin`, and what was in it.
