### ISSUE TITLE
The application was unable to start correctly 0xc0000142

### ISSUE THREAD

**Issue by alexandrul** [git-for-windows/git#2310]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
Plink Path: c:\Tools\PuTTY__x64\plink.exe
SSH Option: Plink
Tortoise Option: true
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

### Details

Random error dialogs when launching IntelliJ, unable to reproduce them reliably.
![git exe - Application Error](https://user-images.githubusercontent.com/663809/63750442-2614a100-c8b6-11e9-917b-6350c1e7378d.png)
[git exe - Application Error - alternative link](http://user-images.githubusercontent.com/663809/63750442-2614a100-c8b6-11e9-917b-6350c1e7378d.png)

**Comment by alexandrul** [comment]
First time experiencing this issue (2.22.0 and older versions were working just fine).

**Comment by assarbad** [comment]
The error you are reporting is quite to the point.

The code `0xC0000142L` is known as `STATUS_DLL_INIT_FAILED`:

> {DLL Initialization Failed}
> Initialization of the dynamic link library %hs failed. The process is terminating abnormally.

By the way: there's a slim chance that you can see that failure in the System or Application log with the Event Viewer (Win+R -> `eventvwr.exe` -> Return/Enter). But it's not certain.

If you are able to use [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) please do so and see if you can narrow it down to a single DLL failing to initialize. You will want to limit your view to "Show Process and Thread Activity" (the toolbar button with the Windows logo) and look for failures.

It's not per-se a problem if a DLL isn't found in one path, as long as other paths are being searched. But at some point it may end up having exhausted the path list and still not have found a matchign DLL name. This should stand out.

It'd be perfect if you could downgrade to a known-working version and do the same routine (with ProcMon) for comparison. This should pinpoint what DLL is the issue here.

You'll also want to ensure that IntelliJ executes the correct `git.exe` (which should be visible from ProcMon also).

**Comment by alexandrul** [comment]
@assarbad thank you so much for the instructions, I will reopen this issue if I will be able to get more details.
