### ISSUE TITLE
Never finished downloading, Download says 64 bit, Task Manager says 32 bit

### ISSUE THREAD

**Issue by petitt0** [git-for-windows/git#2312]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** git version 2.23.0.rc2.windows.1
cpu: x86_64
built from commit: 0567afb01272dd34f9001d360d9f990e6994938c
sizeof-long: 4
sizeof-size_t: 8
 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.17763.678] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
 **

I have selected the 64 bit download and it gets all the way to the end of the progress bar and never finishes. Also in Task Manager it says 32 bit when the download file says 64 bit.

**Comment by PhilipOakley** [comment]
is this an initial download of Git, or an update?

Where is the task manager info gained from (which part - the 'it' you mention). Sometimes (on windows, for various apps) you get as (32 bit) suffix because of the way compatibility is being done.

**Comment by assarbad** [comment]
@petitt0 any particular reason you are using the RC instead of the [actual release v2.23.0.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.23.0.windows.1)? So [this](https://github.com/git-for-windows/git/releases/download/v2.23.0-rc2.windows.1/Git-2.23.0.rc2.windows.1-64-bit.exe) is the setup executable, right? Or are you trying to upgrade the v2.23.0-rc2.windows.1 with v2.23.0.windows.1 and _that_ fails?

[Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) could arguably be used to

1. suspend the stalled process
2. inspect its threads (and call stack), which together with the PDBs (debug symbols) can go a long way
3. dump the process for post-mortem analysis with WinDbg and matching PDBs

The biggest question really is _what_ stalls. The setup itself? Then the debug symbols for Git probably won't help.

Given it stalls at the end: do you have any anti-malware solution running, if so which one? How long did you wait until you concluded it was "stuck"?

-----

**NB:** the setup "wrapper" is 32-bit, correct! But the bundled tools inside, which are to be installed, should be 64-bit nevertheless.

Since you seem to have a working Git for Windows despite the stuck installation, perhaps you could try using [`file`](http://man7.org/linux/man-pages/man1/file.1.html) on the `git` executable, so we're certain? From the MinGW terminal/Bash you'll want to run something like `file $(which git)` (this uses the output of `which git` as argument to the `file` command; the `file` command outputs information about the file types it knows about: see)

```
$ file $(which git)
/mingw64/bin/git: PE32+ executable (console) x86-64, for MS Windows
```

The `x86-64` denotes that this is a 64-bit executable targeting x86 (also known as x64, x86-64, amd64 ...).

For comparison, this is what a 32-bit executable (x86-32) would look like:

```
$ file /c/Windows/SysWOW64/cmd.exe
/c/Windows/SysWOW64/cmd.exe: PE32 executable (console) Intel 80386, for MS Windows
```

**Comment by PhilipOakley** [comment]
@assarbad thanks for the heads-up about it being an rc build. 

@petitt0 - when upgrading from the rc build to the proper first release, you WILL get a dialog saying that it appears that you are down grading versions. Just accept the apparent downgrade (click the button;-). This assumes that is the failure you are indicating.

This is an artefact of the version numbering system used upstream for release candidates, and will be mentioned in the new Security.md file being added to the repo #2311 .

**Comment by dscho** [comment]
Closing due to literally no answers at all from the original poster.
