### ISSUE TITLE
When installing to a non-default directory

### ISSUE THREAD

**Issue by anders43** [git-for-windows/git#2403]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64

```
$ git --version --build-options

git --version
git version 2.24.0.windows.2
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
10, 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.476]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Choose all
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

not really

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
I installed to a non-default directory D:\APPS however the file gitconfig was installed in the default directory, so the path became d:\Program Files\Git\mingw64\etc\gitconfig and not  D:\APPS\Git\mingw64\etc\gitconfig

Not a big issue, just wanted you to know, should be easy to reproduce

**Comment by dscho** [comment]
> I installed to a non-default directory D:\APPS

How do you even do that?

**Comment by anders43** [comment]
By running the install .exe and choosing another target dir.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by dscho** [comment]
> By running the install .exe and choosing another target dir.

Well, I guessed from your report that you managed that somehow. Your answer did not clarify, however, _how_ you did that. I do not see any UI for that in the installer.

**Comment by dscho** [comment]
> I do not see any UI for that in the installer.

Which, I fear I have to spell out, makes it rather hard to believe that this "should be easy to reproduce"

**Comment by anders43** [comment]
You get dialog only if you uninstall the previous version of Git

[cid:image001.png@01D59BAF.F62E9E10]
I hope the illustration makes it easier for you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by rimrul** [comment]
>I do not see any UI for that in the installer.

The magical line for that is install.iss:65

```
DisableDirPage=auto
```

This feature has been copied over from the old Git for Windows 1 installer. The page to select the target directory gets hidden, if the installer finds traces of the same application in the registry.

**Comment by dscho** [comment]
> [cid:image001.png@01D59BAF.F62E9E10] I hope the illustration makes it easier for you.

No, that string does not make it easier. But it does not have to, as I am quite happy with staying out of this from here on.

**Comment by landstander668** [comment]
@anders43 Is there any chance you previously had Git installed into the path where you found gitconfig? I just did a test install of version 2.24.0.2 (64-bit) onto a Windows 10 (10.0.18363.476) VM, and wasn't able to directly reproduce this behaviour... but did encounter a scenario where a previous installation could leave the file behind (albeit in a slightly different location). My steps were:

1. Uninstall the existing 2.24.0.2 installation, and remove `C:\Program Files\Git` which was left behind. Its only contents were the `etc\gitconfig` file.
2. Reinstall 2.24.0.2 in the usual manner, selecting `C:\apps\Git` for the target location (as I'm working in a VM with only a single disk). All other options were left at their default value.

In my test, no `C:\Program Files\Git` directory got created, and the file in question was found at `C:\apps\Git\etc\gitconfig`.

Since the uninstall process seems to leave some remnants behind, I'm wondering if you might have simply seen the leftover file from a previous installation.

**Comment by anders43** [comment]
Hi

That sounds like a likely scenario, I will try it out later today.
Best regards
Anders.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
