### ISSUE TITLE
default config file

### ISSUE THREAD

**Issue by dmodoomsirius** [git-for-windows/git#245]
what is the best way to set a username and either a key or password so i don't have to enter it every time i push a commit.

I have already set user.e-mail and user.username but it keeps prompting me for my username.

**Comment by linquize** [comment]
The correct spelling of these config keys are `user.name` and `user.email`

**Comment by dmodoomsirius** [comment]
```[user]
	name = dmodoomsirius
	email = dmodoomsirius@gmail.com
	password = "Redacted"
	username = dmodoomsirius@gmail.com
[core]
	autocrlf = true
	excludesfile = C:\\Users\\Admin\\Documents\\SourceTree\\gitignore_global.txt
	filemode = false
[push]
	default = matching```

is my current .gitconfig

**Comment by drizzd** [comment]
What about the [user] section?

**Comment by dmodoomsirius** [comment]
when i did the ```` it stripped that i fixed it.

**Comment by rburgstaler** [comment]
As far as I know, the [user] section of the config file does not control the credentials that are used when pushing commits.  How are you pushing your commits?  Are you using http(s) because if you are,  you can setup the Windows Credential manager to remember your username and password for future pushes to the same url.

You can set this up with the following configuration in the config file:
`
[credential]
	helper = !\"C:/Program Files/Git/mingw64/libexec/git-core/git-credential-wincred.exe\"
`

I am not sure if pushing via ssh operates the same way.

I have noticed that the git-for-windows installer does not set up the credential helper during installation.  So my question to the "git-for-windows overseers", would you be opposed to me putting together a pull request gives the option to setup the credential helper during installation?  I just want to know if there is some philosophical reason that you would or would not want this before I put time into coding this.

**Comment by dscho** [comment]
@rburgstaler thanks for translating the original report.

@dmodoomsirius please note that it would be a lot better to ask user questions on the mailing list (or on StackOverflow). This bug tracker is intended to track bugs, and you obviously agree that this is not a bug: you simply need to know how to configure Git correctly, which has been nicely answered by @rburgstaler.

> I am not sure if pushing via ssh operates the same way.

FYI no, it operates differently. GitHub has nice documentation for password-less ssh: https://help.github.com/articles/generating-ssh-keys/
