### ISSUE TITLE
git bash program should have the name git bash

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#248]
Sorry for my title not describing the problem or issue but heres the description

When you open the git bash program on windows and you go to task bar and right click the popup menu shows but to open another program by click the name in that popup show it as terminal it should be git bash and open git bash program not open terminal.

**Comment by dscho** [comment]
You might want to start working on this feature and contribute a Pull Request.

**Comment by paladox** [comment]
I am not very good at coding in windows.

**Comment by dscho** [comment]
A pity.

**Comment by paladox** [comment]
Ok but this is a valid bug. Because I didn't open terminal I opened git.

**Comment by kostix** [comment]
@paladox, that is not quite correct: you cannot "open Git" because `git` is a command-line program (actually, as set of programs) which requires a terminal to work -- show its output and receive its input from the user.  `git` of Git for Windows is able to function just fine without this special terminal emulator called "Git bash": you can run `git` in the stock Windows "console Window" -- the boring `cmd.exe` program, and quite many people do just that.

What's available to the users in the form of "Git bash" is just a convenience hack to make those accustomed to the POSIX environment to feel more at home (mostly because GfW *has to* ship the Windows port of the `bash` shell and a set of POSIX tools like `cat` and `mv` anyway).

**Comment by kostix** [comment]
@paladox, also let me digress a bit...  I've recently seen a whole slew of wishlist-class bugs from you and given the sutuation, I think I could make some things more clear to you.  Wishlist bugs are usually OK, but please notice that notwithstanding its popularity, the Git for Windows project is *severely* undermanned and has no corporate backing (at least no constant backing).

Hence while this is sad, bugs which -- in the eyes of the maintainers -- have zero chances of being worked on in the forseeable future will have good chances of being closed to not clutter the tracker.  After all, if someone will have the same itch you do, but will be able to scratch it, that person will be able to reopen the bug easily.
