### ISSUE TITLE
recentlySeenVersion dirties dotfile diff

### ISSUE THREAD

**Issue by ciarancourtney** [git-for-windows/git#2485]
As per https://stackoverflow.com/questions/59445643/git-for-windows-move-winupdater-section-out-of-gitconfig

Many people version control their `~/.gitconfig` so its a nuisance to commit new `recentlySeenVersion` updates, could it be cached elsewhere?

**Comment by rimrul** [comment]
You could work around this with clean and smudge filters.

**Comment by dscho** [comment]
> Many people version control their `~/.gitconfig` so its a nuisance to commit new `recentlySeenVersion` updates, could it be cached elsewhere?

Sure, we could store it in `~/.git-for-windows-updater` via `git config -f "$HOME/.git-for-windows-updater" ...` instead of `git config --global ...`.

@ciarancourtney if you want that, do please work on a PR. (There should be code to look at `--global` if no existing setting was found, for a smooth transition, I think.)

**Comment by jcgoble3** [comment]
This seems to have been fixed in the pull request above by @ciarancourtney. My Git for Windows installation hasn't touched `~/.gitconfig` since 2.25.0; I'm currently on 2.26.2, and I now have a file at `~/.git-for-windows-updater` with that version number in it. I've done nothing special, just updated regularly via the built-in update mechanism.

Is it time to close this issue?

**Comment by dscho** [comment]
> This seems to have been fixed in the pull request above by @ciarancourtney. My Git for Windows installation hasn't touched `~/.gitconfig` since 2.25.0; I'm currently on 2.26.2, and I now have a file at `~/.git-for-windows-updater` with that version number in it. I've done nothing special, just updated regularly via the built-in update mechanism.


Thank you for paying attention and pointing this out.

> Is it time to close this issue?

Yes :-)
