### ISSUE TITLE
`git difftool` gets confused when files have been added

### ISSUE THREAD

**Issue by tom-jb** [git-for-windows/git#2543]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.25.1.windows.1
cpu: x86_64
built from commit: cceb69da75b4906bb04cfb3a2f7f37b12b985ec3
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.30]
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

## Explanation

Adding a new file to the staging area and then running `git difftool --staged` will cause problems on Windows:

```
{create a new file}
git add .
git difftool --staged
```

WinMerge now runs and tells me that the 'left' file is invalid and is "\\\\.\nul".

The same happens with DiffMerge and KDiff3.

Many people have reported the same issue on StackOverflow. For example:

https://stackoverflow.com/questions/39756836/how-to-get-winmerge-to-show-diff-for-new-file-in-git

Mercurial had no problems here. It launched any one of the above diff tools, and the diff tool reported that the file was newly added.

**Comment by dscho** [comment]
> Mercurial had no problems here. It launched any one of the above diff tools, and the diff tool reported that the file was newly added.

What `diff` does it produce?

**Comment by rimrul** [comment]
The tools are probably launched with a gui and don't produce a plaintext diff, but the diff doesn't matter much anyways. The issue is that `git difftool` passes `nul` to native executables and `/dev/null` to MSYS2 executables for files that don't exist, but hese tools seem to expect some other value. Seeing as they're both based on linux tools I think they might expect `/dev/null`, even on windows. But `kdiff3` doesn't seem to like that either.

**Comment by tom-jb** [comment]
I just tried looking through the Mercurial source, and as far as I can see (I'm not a Python programmer) it simply uses `os.devnull`.

However, I found this answer which seems relevant to the Git problem:

> Unfortunately, the cygpath utility does a poor job converting /dev/null to its Windows equivalent. It will return the invalid \\.\NUL path, and so diffing new files will fail. I'll issue another update with the workaround, as soon as I find it.

https://stackoverflow.com/a/26297369

**Comment by rimrul** [comment]
That stackoverflow answer is only losely related. It's about cygwin git and cygpath, not Git for Windows.

I also don't think mercurial just passes `os.devnull` to `kdiff3`/`winmerge`, because that [should have the same result on windows](https://docs.python.org/3/library/os.html#os.devnull) as what we do.

**Comment by tom-jb** [comment]
I just found this in Mercurial's automated tests:

```
diffing nul "*\\a" (glob) (windows !)
diffing /dev/null */a (glob) (no-windows !)
```

https://www.mercurial-scm.org/repo/hg/file/b7ca03dff14c/tests/test-extdiff.t#l533

I wonder, then, whether all would be fine if Git sent "nul" rather than "\\\\.\nul" on Windows?

**Comment by dscho** [comment]
@tom-jb have you run the command with `GIT_TRACE=1` and verified that's what gets passed?

**Comment by rimrul** [comment]
Git for Windows already sends `nul` (lower case, no leading directory or directory separator).

**Comment by dscho** [comment]
> Git for Windows already sends `nul` (lower case, no leading directory or directory separator).

So what's the problem, then?

**Comment by rimrul** [comment]
The tools on the recieving end don't expect `nul`, but something else. It seems like our full command line for `kdiff3` is `kdiff3 --L1 "foo (A)" --L2 "foo (B)"  "nul" "foo"` where foo is the name of the new file.

**Comment by dscho** [comment]
Okay, this ticket has the scenario woefully underexplained, so it took me a while to set things up (because I don't want to be left hanging waiting for answers).

The way to set this up is to initialize a new repository with `git init`, then configure:

```sh
git config diff.tool DiffMerge
git config diff.DiffMerge.cmd '<Windows-path-to-sgdm.exe-with-forward-slashes> "$LOCAL" "$REMOTE"'
```

When I run this after setting `GIT_TRACE=1`, I get this:

```
[...]
17:03:02.210040 run-command.c:663       trace: run_command: GIT_DIFF_PATH_COUNTER=1 GIT_DIFF_PATH_TOTAL=1 git-difftool--helper new-file /dev/null . . new-file e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 100644
```

which is okay because that `git-difftool--helper` is a shell script.

Instrumenting `/mingw64/libexec/git-core/git-difftool--helper` so that it traces the commands (via inserting `set -x` at the top) shows this:

```
[...]
++ C:/path/to/DiffMerge_4_2_0_697_stable_x64/sgdm.exe /dev/null new-file
```

Of course, the MSYS2 runtime translates that `/dev/null` to `NUL`, as I verified via running [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon).

And indeed, if I run DiffMerge standalone, with `NUL` and `new-file` as arguments, I see the exact same error message.

Indeed, I cannot find a way to launch DiffMerge so that it compares a file against `NUL` or `/dev/null` or `\\.\NUL` or whatever.

Can you?

**Comment by tom-jb** [comment]
Sorry for underexplaining the issue and for not being able to answer specific details for the moment. Unfortunately, I don't have access to a computer for about six hours. As soon as I get home, however, I will answer all questions and try to figure out exactly what Mercurial is sending in this scenario.

Thank you for looking into this issue.

**Comment by tom-jb** [comment]
Well, this is strange. I've now tested Mercurial and found that it has the same behaviour!

I am genuinely baffled by this. Although I haven't used Mercurial in quite a while, I could have sworn it behaved differently here.

Well, I can only guess that this is a problem with the diff tools I'm trying. It seems that Git is not to blame after all.

Apologies for the bad report! And thank you for your assistance regardless.

**Comment by dscho** [comment]
Maybe we can do better, though. It seems to me as if we could introduce a flag for diff tools that don't like `NUL` and handle them by writing an empty file and using that? Or maybe we can find a low-level name that works (something like `\\.\Device\Null` or similar)?

**Comment by tom-jb** [comment]
That sounds good. Would you like me to reopen this issue — or even create a new one?

**Comment by dscho** [comment]
Oh, if you want to know what I'd like, I'll tell you: I'd like you to work on it, and open a PR when you're ready or stuck.

**Comment by rimrul** [comment]
For `kdiff3` variations of `\\.\Device\Null` also don't seem to work.

**Comment by dscho** [comment]
> For `kdiff3` variations of `\\.\Device\Null` also don't seem to work.

I am not even certain that this is the correct path. I typed this suggestion on my phone...

**Comment by dscho** [comment]
Dangit. I really should learn not to trust bug reports too much, especially when they are not quoting error messages verbatim.

And of course, because I relied on the description, I did not pay attention to the error message either. The exact error message says:

```
File 1 could not be imported.

Cannot stat file.
Error: Failed to retrieve file times for 'C:\Users\me\NUL (error 87: the parameter is incorrect.)

C:\Users\me\NUL
```

So the problem is not at all that it does not find `NUL`. It is that `NUL` is not a file, and does not have file times. _That_ is what the problem is.

And the best solution would really be for DiffMerge to be taught to understand the special role of `NUL`.

A workaround until that time would be to write an empty file (e.g. called `empty`) and substitute that for the `/dev/null` in the `cmd` setting. In my test, this one worked (although it is _ugly_ and should probably be folded into `git-difftool--helper` as an option, e.g. `difftool.<tool>.emulateDevNull`):

```ini
[difftool "DiffMerge"]
    cmd = "empty=; if test /dev/null = \"$LOCAL\"; then empty=/tmp/empty.$$.txt; LOCAL=$empty; fi; if test /dev/null = \"$REMOTE\"; then empty=/tmp/empty.$$.txt; REMOTE=$empty; fi; test -z \"$empty\" || >$empty; C:/Users/me/DiffMerge_4_2_0_697_stable_x64/sgdm.exe \"$LOCAL\" \"$REMOTE\"; ret=$?; test -z \"$empty\" || rm $empty; exit $?"
```
