### ISSUE TITLE
Git fails to correctly determine file permissions on WSL2 filesystem

### ISSUE THREAD

**Issue by bert-laverman** [git-for-windows/git#2572]
### Setup

L:\home\bertl\dev\AxonIQ\axon-server>git --version --build-options
git version 2.26.0.windows.1
cpu: x86_64
built from commit: 9c98e1ccdfd839e4eaae1c2747d0088ef89d446b
sizeof-long: 4
sizeof-size_t: 8

Windows 10 Pro, WSL2 (Insider build "slow" track to get WSL2)

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.172]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

- "`install-options.txt`:
```
Editor Option: Notepad++
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This is about files located on the "`\\WSL$`" "quasi" share

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

None of the above. GitHub for Desktop and IntelliJ IDEA are.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

    - Open WSL 2

    - Navigate to your WSL home directory and use "`git clone`" to retrieve any repository that has files with the x-bit set. **Note** this will run the Linux `git` within WSL.

    - Verify the files have the x-bit set using "`git ls-files -s`"

    - Verify there are no changes using "`git status`"

    - Open the Windows file explorer on "`\\WSL$`" and mount the distribution you just used as a drive, e.g. as drive "`L:`".

    - Start "`CMD.EXE`", switch to drive "`L:`" and navigate to the repository you cloned above.

    - Run "`git status`". **Note** This time this runs Git for Windows.

    - Notice that all executable files are marked as changed.

 - What did you expect to occur after running these commands?

    I expect to see the files _not_ marked as changed.

 - What actually happened instead?

    The files are shown as changed and will show up in any listing of changes to commit.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This is not repo specific.

**Comment by tboegi** [comment]
`git config core.filemode false` will help:
https://git-scm.com/docs/git-config

**Comment by bert-laverman** [comment]
Thank you it does reduce the nagging of IntelliJ and GitHub Desktop, but this also means I no longer get any checks on that part, right?

**Comment by PhilipOakley** [comment]
Yes and No. The windows side of the file system does not have an executable bit, so you always need to tell the git index of any changes to the executable bit that needs registering.

The checks are still "performed", but it only looks at the index... (other viewpoints are possible ;-0)

**Comment by dscho** [comment]
Quite honestly, I don't understand why anybody working in WSL would want to use Git for Windows (with Windows' idea of filesystem capabilities) rather than a Linux-native `git`... It's not even _feasible_ to map all of ext4's filesystem semantics to Windows drives.

**Comment by bert-laverman** [comment]
Unfortunately GitHub Desktop uses the Windows executable, being of such persuasion itself. IntelliJ IDEA may or may not, I haven't checked, but accesses the filesystem through the "\\wsl$" SMB mount and suffers the same fate. Their programmers are human, and thus not logical.

**Comment by dscho** [comment]
> Their programmers are human, and thus not logical.

Before you judge others, maybe you could instead focus your energy giving it a thorough try to investigate and fix things yourself.

**Comment by bert-laverman** [comment]
Oh dear, I thought that reference was obvious enough not to cause confusion. Sorry about that. I was not being judgmental, merely making a Star Trek joke. Nor did I take your remark as being a suggestion to run X-Windows on WSL and then use IntelliJ for Linux rather than the native one. WSL 2 is still far from finished and has many unexpected pitfalls. Using the NTFS filesystems will still give you possible performance problems under Linux, while accessing the WSL filesystem appears to cause surprises for Windows applications.

**Comment by tboegi** [comment]
I have made a kind of patch - no test cases, and only tested shortly.
Being unsure if this is worth to push forward, I add the link here:
https://github.com/tboegi/git/commit/e252f3b15d686c556c23e5a448c63442c597f66e

Feel free to pick it up, experiment, test.

**Comment by bert-laverman** [comment]
Like the testcase, because a directory should have the executable bit, whereas a normal file should not have it unless explicitly set. In the introduction you missed the case of a WSL2 filesystem exposed to Windows through virtual-SMB. I don't think that uses Samba on WSL, but a WSL-internal pass-through that emulates an SMB fileshare for the host.

**Comment by dscho** [comment]
> I have made a kind of patch - no test cases, and only tested shortly.
> Being unsure if this is worth to push forward, I add the link here:
> [tboegi@e252f3b](https://github.com/tboegi/git/commit/e252f3b15d686c556c23e5a448c63442c597f66e)

I guess that a slightly better way might be to introduce another level, e.g. `core.windows.fileMode` (which would override `core.fileMode`): That way, only Git for Windows would have to be modified and you would not have to wait for, say, Ubuntu to pick up an official Git version supporting the new config setting.

**Comment by rimrul** [comment]
The commit message says that can also occur in interactions between OS X and Linux, so a fix that only applies to Windows might not be ideal.

**Comment by dscho** [comment]
Wait, macOS now _also_ does not have an executable bit? That can't be right.

**Comment by rimrul** [comment]
Let me quote the commit message..

>One example is Cygwin (or WSL) which want core.filemode=true vs.
Git for Windows (executable bit is always 0) which needs core.filemode=false.

>Another example is Linux-SAMBA-MacOs. where MacOs sees the executable
bit(s) always 1 for all files and needs core.filemode=false.

The Samba share seems to be an important part of this. So macOS has an executable bit, but can get confused about it when a Samba share is involved.

**Comment by dscho** [comment]
Soo all that "Cygwin wants", "Windows wants", "macOS wants" is totally bogus and it is really the network file system that causes the issues, right? I am not sure that we can detect that properly.

One workaround would be to have a conditional include in the config that triggers only on one machine, and overrides `core.fileMode`. I guess `gitdir` as a condition should work, as they are most likely different?

**Comment by Stanzilla** [comment]
> Quite honestly, I don't understand why anybody working in WSL would want to use Git for Windows (with Windows' idea of filesystem capabilities) rather than a Linux-native `git`... It's not even _feasible_ to map all of ext4's filesystem semantics to Windows drives.

Because all the git gui clients on Windows can't use the WSL git version.

**Comment by billziss-gh** [comment]
The lack of support for the executable bit has always bothered me in git for Windows. I also use Cygwin git, which is able to handle the executable bit. My solution to manage repositories from both environments has been the following:

On git for Windows:

```
git config --system core.filemode false
```

On git for Cygwin (or WSL1):

```
git config --system core.filemode true
```

However I believe that it is possible for git for Windows to support the executable bit and will even submit patches if you want me to.

## POSIX Permissions and Windows ACL's

One way to view the POSIX permission model is that every file has a fixed ACL (Access Control List) with exactly 3 ACE's (Access Control Entries), one each for the file owner, file group and everyone else. Each ACE contains Read, Write and eXecute permissions. (In reality you also need negative ACE's to properly model POSIX permissions in some cases, but I will ignore this to simplify the discussion.)

Based on the above observation a number of systems have used a mapping of POSIX UID's to Windows SID's and POSIX permissions to Windows ACL's. The mapping in general does a pretty good job of going back and forth although it is not fully bijective. Such systems include the now discontinued [Services for UNIX](https://technet.microsoft.com/en-us/library/bb463216.aspx), [Cygwin](https://cygwin.com/cygwin-ug-net/ntsec.html) and the FUSE layer of my own [WinFsp](https://github.com/billziss-gh/winfsp/blob/master/src/shared/ku/posix.c).

Although the full mapping is rather elaborate and hard to get right, luckily in git for Windows we only have to worry about the eXecute bit. For example:

- When setting the eXecute bit, we add or modify an Allow ACE that includes the `FILE_EXECUTE` right for the file's owner.
- When getting the eXecute bit, we check to see if the ACL contains an Allow ACE that includes the `FILE_EXECUTE` right for the file's owner.

This example scheme would allow git for Windows to support the eXecute bit in a manner compatible with Cygwin.

## POSIX Permissions and WSL1

In prior versions of Windows 10, WSL1 used to store POSIX permissions in (rarely used) NTFS Extended Attributes. However in a test I just did on my system running Windows 10 2004, WSL1 appears to respect the `FILE_EXECUTE` bit added by Cygwin, so that files that Cygwin thinks are executable, WSL1 thinks so as well. So I believe further research is needed here.

FWIW, there is no Win32 API that can be used to manage Extended Attributes. One has to use the NTDLL calls [`NtQueryEaFile`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-zwqueryeafile) and [`NtSetEaFile`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-zwseteafile?redirectedfrom=MSDN).

**Comment by dscho** [comment]
Closing as stale.
