### ISSUE TITLE
Installation error: Unable to run post-install scripts

### ISSUE THREAD

**Issue by normmacneilottawa** [git-for-windows/git#2606]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64-bit

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.1365]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Tried running as regular user (me) and as Administrator with the same results

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Ran the downloaded installer: Git-2.26.2-64-bit.exe
```
 - What did you expect to occur after running these commands?

The installer would install the program

 - What actually happened instead?

After the error message was displayed, clicking on the "Ok" button continued with the installation and it appears to be ok; however, I have no way of identifying if the installation performed correctly.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a
![errormsg](https://user-images.githubusercontent.com/64543621/80612666-47f89180-8a0a-11ea-91bb-de6b4d468b1d.PNG)

**Comment by dscho** [comment]
Hmm. That comes from this line: https://github.com/git-for-windows/build-extra/blob/4ecc9eb40344c8fc7c1f491b9c28176051abb8b0/post-install.bat#L22

It would appear that the script is unable to determine your Windows version for some reason?

**Comment by normmacneilottawa** [comment]
Is there a debug version of the install script I could run to diagnose what it thinks 'ver' equates to?

Also, what clean-up do I need to do on the install at this point?

Thanks,
  Norm.
________________________________

**Comment by dscho** [comment]
You could try to run `cmd /c ver` yourself. Or run the installer with `/LOG=<path>` and look at that log.

**Comment by normmacneilottawa** [comment]
cmd /c ver yields:
Microsoft Windows [Version 10.0.17134.1425]

Not sure what to make of that.
________________________________

**Comment by dscho** [comment]
That looks right, but why does the script not pick up on it?

**Comment by dscho** [comment]
Is there no error message when you expand the window? Or the log?

**Comment by Taverius** [comment]
Getting the same thing.
> Microsoft Windows [Version 10.0.18363.836]

Is there an install log i can attach somewhere?

**Comment by hedwig-ma** [comment]
I am not sure if this should be a new issue. I got a number of errors towards the end of the install, here is a short part of the log:
2020-05-14 15:52:30.330   Deleting any uninstall keys left over from previous installs
2020-05-14 15:52:30.330   Creating new uninstall key: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall\Git_is1
2020-05-14 15:52:30.330   Writing uninstall key values.
2020-05-14 15:52:30.373   Installation process succeeded.
2020-05-14 15:52:31.159   Message box (OK):
                          Unable to set system config "diff.astextplain.textconv":="astextplain": exit code 1
                          
                          
stderr:
                          

2020-05-14 15:53:11.809   User chose OK.
2020-05-14 15:53:11.810   Unable to set system config "diff.astextplain.textconv":="astextplain": exit code 1
                          
                          
stderr:

**Comment by Taverius** [comment]
Yes, that was what I had as well above, I solved it by installing clink - I had it installed on my old machine, moved all the configs to my new, and that apparently broke cmd.exe in interesting ways until i installed it on my new machine as well.

Truly cmd.exe is the gift that keeps on giving, with its extensive and informative error detection xD

**Comment by dscho** [comment]
@normmacneilottawa @hedwig-ma do you also have a (partial) clink installation?

**Comment by hedwig-ma** [comment]
@dscho I do not have clink installed. I tried reinstalling git using 2.25.1 after a 'clean' uninstall (which is what was running just fine until I did the uninstall | reboot | install 2.26.2. I tried multiple installs (including command line). I finally went in to the registry, tried to find any git entry that looked reasonably to be from GIT (vice some other software mentioning git). I removed all of those. rebooted and ran the install again. This time I didn't get any errors  when I installed, and bash seems to be behaving correctly.

**Comment by dscho** [comment]
> I finally went in to the registry, tried to find any git entry that looked reasonably to be from GIT (vice some other software mentioning git). I removed all of those. rebooted and ran the install again. This time I didn't get any errors when I installed, and bash seems to be behaving correctly.

Hmm. Do you remember which registry settings those were?

**Comment by hedwig-ma** [comment]
> 
> Hmm. Do you remember which registry settings those were?

Unfortunately I was in a meeting while I was doing it, and unable to write them down. One set was the "GIT GUI here" and GIT Bash here", and a couple pointing to the GIT install directory. If I recall, either MS Visual Studio 2019 Community or VS code, or both had pointers.

**Comment by ZSaberLv0** [comment]
got same issue
* run `post-install.bat` by double click, or run `git-bash`, many `permission denied` would occur
* run `post-install.bat` as Administrator, and reboot system, problem seems solved

**Comment by DragRedSim** [comment]
This has been an annoyingly ongoing issue on version upgrades. I found that to get the script to run correctly, I needed to manually run the git-bash.exe environment as an administrator, in order to set up the links. Doing so as the user returns errors on launch due to lack of rights:

`ln: failed to create symbolic link '/etc/mtab': Permission denied
'C:\WINDOWS\system32\drivers\etc\hosts' -> '/etc/hosts'
/usr/bin/cp: cannot create regular file '/etc/hosts': Permission denied
'C:\WINDOWS\system32\drivers\etc\protocol' -> '/etc/protocols'
/usr/bin/cp: cannot create regular file '/etc/protocols': Permission denied
'C:\WINDOWS\system32\drivers\etc\services' -> '/etc/services'
/usr/bin/cp: cannot create regular file '/etc/services': Permission denied
'C:\WINDOWS\system32\drivers\etc\networks' -> '/etc/networks'
/usr/bin/cp: cannot create regular file '/etc/networks': Permission denied
rm: cannot remove '/etc/post-install/01-devices.post': Permission denied
rm: cannot remove '/etc/post-install/03-mtab.post': Permission denied
rm: cannot remove '/etc/post-install/06-windows-files.post': Permission denied
rm: cannot remove '/etc/post-install/99-post-install-cleanup.post': Permission denied`

The problem seems to be that /usr/bin/bash.exe is being called as the user in the post-install.bat batch file, rather than as the administrator; this stems from the installer itself not grabbing true administrator rights, but only those which it requires to write to the Program Files folder, as it is upgrading a previously-installed global installation. However, the bash.exe called from the batch file does not inherit the appropriate rights to set up the environment to run correctly, since it is trying to create and delete files in the Program Files folder as the user! For some reason, this causes bash.exe to go into an endless loop, which appears to the user as the installation having hung.

Once git-bash.exe has been run as an admin once, which executes the post-install scripts, the user is able to use the shell under their user account, folder links and all, and the batch script can be successfully manually run, without the script hanging at the calling of "/usr/bin/bash.exe" (https://github.com/git-for-windows/build-extra/blob/main/post-install.bat#L43)

(Other notes while researching this, only semi-related: Complicating this is that there is currently an OUTPUT_TO_TEMP functionality when the installer is compiled, which grabs a different set of privileges to when it is not defined; but this OUTPUT_TO_TEMP is only used when building with either the --debug, --test, or --test-silent flags. So a test build will cause the setup to request `lowest` privileges, but a release build will be compiled requesting `none` (which itself is, per the documentation of Inno Setup, not a valid value; the only two valid values are `admin` and `lowest` on the current version 6 of Inno Setup, though looking at Inno's source, it still supports this value).)

**Comment by dscho** [comment]
So what's the solution, @DragRedSim?

**Comment by Izofeu** [comment]
Same problem. Killing the installation process and running the .bat script as administrator seems to work.

**Comment by dscho** [comment]
> Same problem. Killing the installation process and running the .bat script as administrator seems to work.

@Izofeu Could you try the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html)? A lot has changed since this report came in.

If it still persists for you, please run the installer with the `/LOG=<path>` option (obviously substituting a real log file path for `<path>`), then see whether you can find any good error message in that log file.
