### ISSUE TITLE
Wrong location is used to start Atom

### ISSUE THREAD

**Issue by dead-claudia** [git-for-windows/git#2616]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.1.windows.1
cpu: x86_64
built from commit: 14af9f9d205f4a6a033c7b6f48980d1eeee2c610
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.778]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Atom
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Atom updated.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Any command that opens an editor

 - What did you expect to occur after running these commands?

An editor to open

 - What actually happened instead?

This error:

```
"%AppData%\atom\app-1.44.0\atom.exe" --wait: %AppData%\atom\app-1.44.0\atom.exe: No such file or directory
error: There was a problem with the editor '"%AppData%\atom\app-1.44.0\atom.exe" --wait'.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Happens with all

-----

My recommended solution is to use `%AppData%\atom\bin\atom.cmd` instead - that file is always up to date, and the source is just this, where `VERSION` is the current version:

```bat
@echo off
"%~dp0\..\app-VERSION\resources\cli\atom.cmd" %*
```

**Comment by isiahmeadows** [comment]
I was able to get what I needed to done via a non-interactive `git reset --soft` + `git commit -m 'new message'`, but this is obviously not ideal. Also, I verified my suggested fix locally, though I have literally zero understanding of this repo.

**Comment by rimrul** [comment]
Yes, this is definetly an issue. Atom uses a Squirrel based installer and thus changes it's exact location when updated. We get the Atom path from the registry when we install Git for Windows, but don't notice Atom updates in between Git for Windows updates.

This script is the version agnostic way to call Atom, so we should call that instead of calling atom.exe directly. From a cursory google search, Atom seems to support neither a system wide installation, nor an installation to a different directory(there is a portable option extracting a .zip, but our installer would consider that a custom editor anyways (because it doesn't show up in the registry)), so we should be fine just hard coding the path to that script in [install.iss](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss#L1697).

---
Side notes:

This is probably only an issue if a user updates Atom twice before they update Git for Windows since Suirrel updates keep 1 prior version around.

It seems weird that Atom updates their registry entries to the corresponding versions on each update instead of just pointing to that script once.

**Comment by dscho** [comment]
> My recommended solution is to use `%AppData%\atom\bin\atom.cmd` instead

You can even make it so:

1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd installer`,
3. edit `install.iss`, modifying [this line](https://github.com/git-for-windows/build-extra/blob/ce505c253f3b903b98273df57c73d27b69263033/installer/install.iss#L1697),
4. build a new installer via `sdk build installer`,
5. verify that that installer works as expected, and finally
6. open a PR.

**Comment by dscho** [comment]
Closing as stale.
