### ISSUE TITLE
Typo in installer

### ISSUE THREAD

**Issue by msg7086** [git-for-windows/git#265]
I noticed the word `sports` when configuring the terminal emulator.

I suppose this should be `supports`.

**Comment by linquize** [comment]
@msg7086 No. The word `sport` can be used as a verb. I think here it means `display`, `wear` ...

**Comment by dscho** [comment]
Yep, not a typo. @msg7086 please feel free to provide more context next time, I had to look quite hard to find what you were talking about. For example, it would have helped enormously to mention the complete message:

```
Use MinTTY (the default terminal of MSys2)

Git Bash will use MinTTY as terminal emulator, which sports a resizable window,
non-rectangular selections and a Unicode font. Windows console programs (such as
an interactive Python console) must be launched via `winpty` to work in MinTTY.
```

**Comment by ctahok** [comment]
http://www.plainenglish.co.uk/

**Comment by PhilipOakley** [comment]
> http://www.plainenglish.co.uk/
>
>
And? (that's just a front page, so what would be your/the advice?)

verb, 3rd person present: sports

     1.  wear or display (a distinctive item).

Achieving something like 
https://en.wikipedia.org/wiki/Simplified_Technical_English (ASD-STE100 
Simplified Technical English) is a major activity that usually has 
specialist departments of major contractors engaged for years...

If you would like to suggest an alternative wording, then it's a short, 
easy step to proposing the change and becoming enrolled in the list of 
contributors.
--
Philip

**Comment by ctahok** [comment]
If the issue was raised 3 times (these are who noticed it) that means it is
troublesome. It is up to you to re-phrase it or keep it.

Regards, Ilkin

**Comment by dscho** [comment]
> If the issue was raised 3 times (these are who noticed it) that means it is troublesome.

Maybe. If it has been raised 3 times. When comparing to what I estimated conservatively to be 3 million regular users (v2.23 was downloaded [over 6 million times](https://www.somsubhra.com/github-release-stats/?username=git-for-windows&repository=git)), it is maybe not _that_ troublesome.

> It is up to you to re-phrase it or keep it.

@ctahok that is an incorrect conclusion. This is open source, not a product for which you paid somebody else to support you. It is up to you to open a PR with a proposed fix, and then to work with the reviewers until it is acceptable to merge it.

I mean, you are using a piece of software that according to https://www.openhub.net/p/git-for-windows/estimated_cost has an estimated cost of over 8 million dollars, and I cannot find any record of you contributing back to the project, or for that matter, even show some appreciation.

To the contrary, I see that you throw about one- or two-line comments and then expect others to do as you say.

Not only is that contrary to the conduct we want to see in this project. If you really wanted to see this issue fixed, it also would appear to be a very odd and counter-productive way to go about it.

**Comment by ctahok** [comment]
Being in IT for long time I certainly appreciate everyone who contribute to
the project and I wish I have had enough knowledge to do so many years ago.
Unfortunately everyone is coder and not everyone is grammar specialist. I
tried to help and it went wrong.
I have just started to use the product, hence there are no contributions.
This was my first attempt to contribute and see you demand long and boring
text to be convinced that a sentence with unusual, synonym requires more
debate than the Brexit in the UK Parliament. There could be many more
millions of users but expecting to write sports instead of wear or any
other synonyms from multilingual consumer market is a bit naive. To be
honest in 20 year in IT it is the first time I came across this kind of
side of "sport".

Thanks for "warm" welcome which will certainly make me think next time my
eye pick up something.

P.S. What is the percentage of those 6m. downloaders contributing or
showing appreciation?

Regards, Ilkin
