### ISSUE TITLE
Pagination and colour do not work from a minTTY cygwin prompt

### ISSUE THREAD

**Issue by cs96and** [git-for-windows/git#267]
I used to use msysgit from a minTTY cygwin prompt with no pagination or colour issues.  I recently upgraded to Git For Windows 2.4.6 RC5, and pagination and colour no longer work.  E.g. doing "git log" will output the whole log to the window in black and white.

If I just run c:\cygwin\bin\bash.exe, then everything works OK.
If I run c:\cygwin\bin\mintty.exe then pagination and colour do not work.

I thought it might be something to do with the TERM envvar, which defaults to "cygwin" when I run bash, and "xterm" with minTTY.  However I tried setting this to "cygwin" on minTTY but with no luck.

I find this slightly confusing as Git Bash uses minTTY with no problems at all.

**Comment by dscho** [comment]
Git for Windows is not expected to play well with Cygwin. Please use Cygwin's own Git instead.

**Comment by cs96and** [comment]
For various reasons, cygwin's git is not usable for my use case, so I have to use msysgit or Git For Windows.  Why did pagination and colour work OK with msysgit, but not with Git For Windows?

**Comment by dscho** [comment]
Please note that "msysgit" is not the correct term. Here is an explanation why: https://github.com/msysgit/msysgit/wiki/Relationship-to-Git-for-Windows

> Why did pagination and colour work OK with msysgit, but not with Git For Windows?

That is a really broad and vague question.

I would still hazard a guess -- because I am bold -- that the reason is here: https://github.com/git-for-windows/git/commit/3adef8de5513390459e1caa999e7774adb89a44d#diff-5a07b657681304b199c3bbacce334efdR558

Feel free to work from here and open a Pull Request!

**Comment by cs96and** [comment]
I've figured out how to fix the colours on a cygwin minTTY  console.  I have posted a patch to fix it here http://pastebin.com/ksWHx2P9

I can't work out why pagination is not working though.  It seems that 'less' is being spawned, but git's output is not being piped into it.  I've tried looking in pager.c and run-command.c but can't work out why its not working.  Any ideas?

**Comment by dscho** [comment]
@cs96and posting a patch on pastebin is not exactly what I asked you to do...

It would surprise me if `less` was spawned because the `isatty()` test is most likely failing.

Your patch is really, really hard to comment on, thanks to being snuck into a pastebin instead of opening a Pull Request.

```c
   if ((!wcsstr(name, L"msys-") && !wcsstr(name, L"cygwin-")) || !wcsstr(name, L"-pty"))
```

Have you actually tried to write out `name` into a file, to see what it looks like?

**Comment by cs96and** [comment]
I've created a pull request properly now.

> Have you actually tried to write out name into a file, to see what it looks like?
Yes, the pty pipe names are very similar in msys and cygwin, except that msys ones begin with "msys-" and cygwin ones begin with "cygwin-" (as shown in the comment that I changed).

> It would surprise me if less was spawned because the isatty() test is most likely failing.
The function that I changed (detect_msys_tty) hacks the ioinfo struct so that isatty returns true.  Using Process Explorer I can see less.exe being spawned as a child of git.exe.

**Comment by dscho** [comment]
Reopening, as the pagination still does not work.

**Comment by cs96and** [comment]
I set my pager to "c:/cygwin/bin/strace.exe -o d:/trace.txt c:/cygwin/bin/less.exe".  After running "git log" in a cygwin minTTY window, I can see this in the trace log...

  130   10370 [main] less 11540 isatty: 0 = isatty(1)
   19   10389 [main] less 11540 isatty: 0 = isatty(1)

After running "git log" from a bog standard cygwin prompt (i.e. in a windows command prompt window running cygwin bash), the trace has this...

  138   12301 [main] less 14196 isatty: 1 = isatty(1)
   18   12319 [main] less 14196 isatty: 1 = isatty(1)

So it would seem that less.exe does not think that the minTTY window is a TTY, if it has been spawned from git.

**Comment by dscho** [comment]
I see very similar output, with one more data point: when I run the Git SDK and specify something like `PAGER='/usr/bin/strace.exe -o /pager.log /usr/bin/less.exe' git log`, I see `1 = isatty(1)` in the output. However, if I call `PAGER='/c/git-sdk-64/usr/bin/strace.exe -o /c/pager.log /c/git-sdk-64/usr/bin/less.exe' git log` from Git for Windows (i.e. as installed via a user-facing installer), I see `0 = isatty(1)` and the pager does not stop, either.

The funny thing is that calling `/c/git-sdk-64/usr/bin/less.exe <some-file>` works even from Git for Windows' Git Bash. It stops correctly after one page. However, if I call the same thing with `/c/git-sdk-64/usr/bin/strace.exe -o /c/pager.log` prefixed, it does not stop any longer!

So it looks as if the problem is much deeper.

**Comment by dscho** [comment]
@cs96and did you have any chance to dig deeper yet?

**Comment by cs96and** [comment]
No sorry, not had a chance to look into it.
