### ISSUE TITLE
Change non-inclusive naming

### ISSUE THREAD

**Issue by lol7344** [git-for-windows/git#2693]
[A very easily found Wikipedia page](https://en.wikipedia.org/wiki/Git_(slang)) and the whole English-speaking community [of the last 1000 years](https://en.wiktionary.org/wiki/git#Etymology_1) have clearly brought this issue to attention: the name of the Git project itself is non-inclusive and could cause unintended consequencies. Quoting [the Cambridge dictionary](https://dictionary.cambridge.org/dictionary/english/git), "git" means "a person, especially a man, who is stupid or unpleasant".

I create this ticket to track the progress of fixing this.

The most rational and logical fix would be to completely rename the project to something more appropriate and that would not offend any gender or ethnicity, although also avoiding terms like "nerd", "geek" _et similia_ because they could also be considered offensive. However, another more radical solution would be to completely dismantle the project, as it has been bringing hate since 2005, mostly by putting a horrible word in such good light.

Any constructive comments are welcome!

**Comment by UltimateForm** [comment]
do it, I dare you, do it

**Comment by evandentremont** [comment]
`git` is mostly a Great Britain word and as the country is a majority white this name is OK as offending white colonisers of privilege is allowable under human rights legislation 

_3f51ccde0404ae11ed53540d43ef610f_

**Comment by lol7344** [comment]
> 
> 
> `git` is mostly a Great Britain word and as the country is a majority white this name is OK as offending white colonisers of privilege is allowable under human rights legislation
> 
> _3f51ccde0404ae11ed53540d43ef610f_

And so is using "master" in relation to a software distribution and architecture (and, actually, many more things), however I see people suddenly hating on it because another possible definition of that term is a bad, negative one. This issue #2693 if the proof that, if we start decontextualising, we can associate the wrong definition to the nouns we are using, and make wrong assumptions and arguments.

In fact, if I were to speak of "git" with my developer friend, or on any development forum, you would instantly understand that I am not trying to offend you by calling you a "git", but rather I am talking about the distributed version-control system we are currently using to communicate.

The same applies to the "master" term: if I were to say that "I pushed on the master branch", unless your cognitive and reasoning skills had serious issues or lacks, you would instantly understand that I am not calling you a slave of any sort, nor am I trying to offend or denigrate you by calling you inferior; you would indeed understand that I just pushed a new update to a project.

**Comment by defmacro-jam** [comment]
I propose `8tTCFoyWCf6UDQPiNo` as the new name for Git because it has no meaning.  With no meaning, it can't upset anyone.

It's still pronounced like the word "get" but all the letters and numbers are silent.

**Comment by SkryptKiddie** [comment]
Maybe the problem isn't the naming, maybe it's the way the git project and community is represented. None of the terms are meant to have or imply a negative meaning, so we shouldn't have to conform to what people want. It's been over 15 years with no major complaints about this, so why should it all change now?

**Comment by adrianos42** [comment]
> I propose `8tTCFoyWCf6UDQPiNo` as the new name for Git because it has no meaning. With no meaning, it can't upset anyone.
> 
> It's still pronounced like the word "get" but all the letters and numbers are silent.

This may actually offend schizophrenic people.
We have no options. Maybe become silent and destroy every single word.

**Comment by magicbc** [comment]
Git is a tool, thats been around for a significant amount of time. Changing the names of things both creates confusion on documentation and creates all kinds of technical confusion when working with things that have grown to depend on it. 

As to git not being inclusive, I think we should avoid making software overly concerned with what people think about it and more concerned about the actions it takes that effect peoples lives (i.e. we don't want to be reactionary to word choice, and more focused on intent) . In that, we should not be concerned with technical terms that people may find offensive simply because of there connotation, as people reading documentation should have a high degree of maturity, perspective, and mental fortitude. 

If someone is reading though documentation and working through tools, and is some how emotionally injured by the use of terms, they should seek the help of mental health professionals so they can better address there lack of grit and possibly there lack of understanding of there peers. I'm not condoning or enabling people who are in general acting in bad faith or people who are acting with malcontent, just saying that sometimes like in anatomy terms chosen reflect an implicit relationship and understanding or even just a time in history. 

The desire to re-label things because someone is being dejected or unable to emotionally cope with a word choice to me wholly misses the point. Many words in many languages have origins that are quilt salacious, but people are ignorant of that context, and so there is no connotation. Movements for social justice don't need tools with different labels, they need tools that help avoid them from becoming marginalized. 

I think this thread does more harm to people who want to see positive change, and is vapid in its motives. Theres not even mention to the reason the word git was chosen. It just rings of pretentious activists who lack astuteness.

**Comment by evandentremont** [comment]
> Maybe become silent and destroy every single word.

That would be "white space" which is non-inclusive of people of colour

**Comment by evandentremont** [comment]
> I propose 8tTCFoyWCf6UDQ_PiNo_ as the new name for Git because it has no meaning. With no meaning, it can't upset anyone.

Well actually Domenico _Pino_ was the commander of Napoleon's guard in the Italian Republic and attempted to overthrow the throne so that series of random characters is likely offensive to someone.

Really we need symbols that can't be misconstrued. perhaps just the phrase "equality" used one through 26 times to mean each letter of the alphabet?

**Comment by evandentremont** [comment]
@lol7344 `md5("Poe's law") == "3f51ccde0404ae11ed53540d43ef610f"` :P

**Comment by tdaugaard** [comment]
> "a person, especially a man, who is stupid or unpleasant".

How is "git" non-inclusive, if whoever is the target for whom it may be insensitive, is literally a stupid and/or unpleasant person?

This is silly. I understand the arguments for the naming scheme of the default branch ("master"), although I don't agree, but changing the name of "git" is silly.

**Comment by dlq84** [comment]
"A very **easily** found Wikipedia page "

That's ableism...
