### ISSUE TITLE
bundled Vim.exe seems to need filetype=mac in vimrc instead of filetype=dos

### ISSUE THREAD

**Issue by IsaacRemuant** [git-for-windows/git#272]
I'm not sure if this is an actual issue or I botched something up but when I call vim from git bash 

`where`
```
C:\Program Files\Git\usr\bin\vim.exe  <- this one as opposed to the one below
C:\Windows\vim.bat
```

It has several problems with ^M characters:

`$ vim`
```
Error detected while processing /c/Users/my_user/.vimrc:
line   13:
E492: Not an editor command: ^M
line   16:
E488: Trailing characters: nocompatible^M
line   17:
E492: Not an editor command: ^M
line   18:
E15: Invalid expression: has('win32') || has('win64')^M
line  211:
E171: Missing :endif
Press ENTER or type command to continue
```

I've tried saving the file in different formats and the filetype=mac format "solved" the issue for the vim in git bash but that's not really a solution since the other vim naturally expects filetype=dos in windows.

I use this .vimrc across computers in Linux/Win without issue and it used to work in the older git bash (msysgit 1.95).

**Comment by dscho** [comment]
I guess that `$HOME/.vimrc` has DOS line endings (*not* Mac line endings, you have CRLF at the end of each line, not CR, otherwise the `.vimrc` would be interpreted as a *single* line).

You can fix this using the command-line `dos2unix $HOME/.vimrc`.

Alternatively, you could work on https://github.com/git-for-windows/MSYS2-packages/tree/master/vim to teach `vim.exe` itself to handle DOS line endings. That would be a very welcome way to say thanks to the Git for Windows project; you will find the following documentation helpful: https://github.com/git-for-windows/git/wiki/How-to-participate#fix-bugs-or-add-features-in-the-git-code-itself and https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages

**Comment by IsaacRemuant** [comment]
Hi, thanks for the quick reply.   I thought dos2unix and similar tools did the same thing as set ff and set ffs.  I've tried them with similar results.  I've even used a vimrc that is in unix format and loads just fine from gvim.exe but I have no clue as to why it only works in the git-bash vim with a mac fileformat.

I'm probably too swamped at the moment to take a look but I'll save those links to read later and see if I'm able to contribute.  Cheers.

**Comment by leif81** [comment]
I just upgraded from Git for Windows 1.9.4 to 2.5.1 and noticed the same issue. Doing a `dos2unix` on my `~/.vimrc` is a one time thing so not a big deal, just a little rough edge.

However I've also noticed that the `.vimrc` I keep in the root of each of my git repo's causes a similar problem. When I clone the repo the `.vimrc` will Windows line endings. So I have to `dos2unix`. Also  the next time I open Git Gui I get a warning about the file (_.vimrc has no changes._) and the `.vimrc` appears in the unstaged changes panel. I've noticed that staging the `.vimrc` will cause another warning (_warning: LF will be replaced by CRLF in .vimrc._), but the file will then disappear for good from Git Gui.

**Comment by dscho** [comment]
@leif81 yes, I expected this to be not only a one-time problem. That is why I was a bit disappointed that [my suggestions](https://github.com/git-for-windows/git/issues/272#issuecomment-130338737) to fix it properly were ignored. But maybe that changes now, what with you noticing the same problem?

It is pretty easy, really. Just install the [Git for Windows SDK](http://git-for-windows.github.io/#download-sdk), then call the following commands:

```sh
pacman -Syu base-devel
cd /usr/src/MSYS2-packages
git fetch
git checkout master
```

After that, you need to open an *MSys2* shell by running the `msys2_shell.bat` script in the top-level directory of the SDK (this is really important because you are going to build an MSys2 program, while the default SDK terminal is set up to build MinGW programs). This will open another mintty -- note the `MSYS:` prefix in the window title -- in which you can build the complete `vim` package:

```sh
cd /usr/src/MSYS2-packages/vim
makepkg -s
```

Once it is build completely, you have the source code at your fingertips in the `src/` subdirectory. I typically run `git init && git add . && git commit -m initial` in there (or in the subdirectory into which the source code was *actually* checked out) and then start hacking.

Please feel free to ask for any more information you need.
