### ISSUE TITLE
Can't send vim or less launched by git to background by pressing ctrl-z

### ISSUE THREAD

**Issue by basinilya** [git-for-windows/git#2751]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Mintty/Bash

 - What commands did you run to trigger this issue?

```
cd /path/to/repo
git commit --allow-empty
# press ctrl-z
```
 - What did you expect to occur after running these commands?

vim goes to background

 - What actually happened instead?

vim stays foreground, after exiting I see:
```
$ git commit --allow-empty
hint: Waiting for your editor to close the file...       0 [sig] bash 455! sigpacket::process: Suppressing signal 18 to win32 process (pid 7456)
Aborting commit due to empty commit message.
```

**Comment by rimrul** [comment]
Our `MSYS2` runtime doen't pass `SIGTSTP` (or any of the following signals: `SIGUSR1`, `SIGUSR2`, `SIGCONT`, `SIGSTOP`, `SIGTTIN`, `SIGTTOU`) to `win32` processes like `git` and `git` can't it's `MSYS2` child processes of a signal it doesn't know about. But even if `git` would somehow inform `vim` or `less` of this signal, they wouldn't handle it like you expect. 

If you launch `git -c core.editor=vim commit --allow-empty` from one `Git Bash` and send a `SIGTSTP` via `kill -n 18` to the `vim` process from a second `Git Bash`, `vim` ignores it. Doing the same with `less` instead of `vim`, `less` seems to try to scroll up.

Launching `vim` or `less` directly from one `Git Bash` and sending `SIGTSTP` from a second one does send them to the background.

**Comment by dscho** [comment]
Did this ever work? (I also see that you're on Windows 7, which might not be fully supported by the MSYS2 runtime any longer)

**Comment by dscho** [comment]
> Would it add much overhead if git.exe was also an MSYS2 program?

It would take away the entire speed advantage that made you switch to Git for Windows. That's all 😁
