### ISSUE TITLE
Integration with OneDrive

### ISSUE THREAD

**Issue by grosch** [git-for-windows/git#2810]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Pretty sure it's 64-bit
Microsoft Windows [Version 10.0.17763.1397]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
Editor Option: VIM
Custom Editor Path:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
  
I've recently started using OneDrive, and it has taken over Documents/Desktop/Downloads.  In windows explorer, if I click on My Documents, it really takes me to the OneDrive folder's My Documents.  If I'm in GitBash though, and I `cd ~/Documents` then I'm not in the OneDrive area.

Is there any way to have GitBash understand this craziness that OneDrive does so that if I do the previous cd, I'm in the onedrive area?

**Comment by dscho** [comment]
This is not really a Git issue, but a usability quirk of what OneDrive does: it _could_ install a symbolic link at `~/Documents`, but does not. I guess the reason is that `~/Documents` was never promised to be _the place_ of your documents. In fact, in previous Windows versions, it was called something different. The canonical way to query for that location is:

```sh
reg query 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders' //v Desktop
```

(If you do this in CMD or PowerShell instead of Bash, use only a single slash when writing `/v`)

You could then rename your current `~/Documents` and use something like `cd "$HOME" && cmd //c "mklink /d Documents '<actual-path>'"` (where `<actual-path>` is what that `reg` call printed) to create a symbolic link, so that `cd ~/Documents` gets you back to your One Drive-backed Documents folder.

**Comment by grosch** [comment]
Thank you very much!  For anyone else who stumbles across this note that the mklink command wants /D instead of /C

**Comment by dscho** [comment]
>  For anyone else who stumbles across this note that the mklink command wants /D instead of /C

Oh... I thought I had used that... Wait:

> `cd "$HOME" && cmd //c "mklink /d Documents '<actual-path>'"`

I did use it. The `/c` is only required for the `cmd` command to accept a command as a command-line parameter...
