### ISSUE TITLE
Git rebase issues: cannot squash the first commit

### ISSUE THREAD

**Issue by Songbird0** [git-for-windows/git#2814]
Hello,
 
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - I'm using Git Windows 64bits

```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

 - I'm using Windows 10, 64 bits

```
$ cmd.exe /c ver
Microsoft Windows [version 10.0.18362.1082]
```
```
$ cat /etc/install-options.txt

Editor Option: SublimeText
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** ... **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Git bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
git rebase -i origin/master HEAD~2
```
 - What did you expect to occur after running these commands?

**My commits being squashed**

 - What actually happened instead?

**fatal: invalid upstream 'origin/master'**

`git log` says:

```
xxx@xxx MINGW64 /a/UnityProjects/3D Development Basics (master)
$ git log
commit d822331252448640335b750062bbaa900d8cb5fa (HEAD -> master)
Author: Songbird0 <xxx@xxx>
Date:   Wed Sep 16 23:07:55 2020 +0200

    Initialisation du projet

commit 4381c637c108e894e445829fea2a2089399f8258
Author: Songbird0 <xxx@xxx>
Date:   Wed Sep 16 22:53:58 2020 +0200

    Ajout du gitignore
```
I have "enough" commits to rebase my branch so what I'm doing wrong? I never had this problem.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** ... **

Thanks for your help!

**Comment by derrickstolee** [comment]
When you squash a commit during interactive rebase, it essentially does a `git commit --amend` on the previous commit _that is also in that rebase_. It does not allow you to squash a commit into a commit not in the rebased range.

If your first commit is the one you want to squash into the second, then you can try reordering the commits. However, it is probably best to squash the second commit into the first, then remove the commit message lines from the first commit when presented with the combined commit message.

**Comment by dscho** [comment]
> fatal: invalid upstream 'origin/master'

This means that your remote called `origin` (usually the place from where you cloned) does not have a `master` branch.

In this instance, since your `git log` shows _only two commits_, and since you want to squash, I have to assume that you did not clone this repository from anywhere, but that you initialized it and then committed twice, and want to squash those two commits. Typically you do that by calling `git rebase -i HEAD~2` (note the missing `origin/master` here!).

Side note: `git rebase`'s [documentation](https://git-scm.com/docs/git-rebase) says that you _can_ provide two arguments after the `-i`, in which case the second one is expected to be a branch name to which Git is supposed to switch before starting the rebase.

However, in your case there _is no `HEAD~2`_! That's because you only have two commits, therefore the parent of the parent does not exist, the parent commit of your `HEAD` is already a "root commit", i.e. a commit without parents, or, if you will, an "initial commit".

But fear not, you can still squash those two commits, using the `--root` form: `git rebase -i --root`.

**Comment by Songbird0** [comment]
Hello!

Sorry for the late answer. It works for me, thanks @dscho & @derrickstolee!
