### ISSUE TITLE
PATH order is different than in cmd

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#2817]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.508]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

cmd `PATH` lists system `PATH` first, then user `PATH`. In MSYS2 the user `PATH` comes before system `PATH`.

```
## Steps to Reproduce the Problem
cmd
PATH
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;...;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\orgads\AppData\Local\Microsoft\WindowsApps;...

Bash
$ echo $PATH
/c/Users/orgads/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/orgads/bin:/c/Users/orgads/AppData/Local/Microsoft/WindowsApps:...:/c/WINDOWS/system32:/c/WINDOWS:...
```

 - What did you expect to occur after running these commands?

I expect the system PATH to come first, like it does in cmd.

 - What actually happened instead?

User PATH comes before system PATH.

This doesn't happen in MSYS2 or git sdk when I set `MSYS2_PATH_TYPE=inherit`. The PATH order is correct.

**Comment by dscho** [comment]
> This doesn't happen in MSYS2 or git sdk when I set `MSYS2_PATH_TYPE=inherit`. The PATH order is correct.

It depends on your point of view what is correct ;-)

Git Bash needs to make sure that its `bash.exe` and its `git.exe` is actually used, to avoid confusing users (and to avoid receiving bug reports when, say, WSL's `bash.exe` is used instead of Git for Windows' bundled MSYS2 Bash).

If that does not strike your liking, you may want to avoid starting the Bash using `git-bash.exe` (which is what the Start Menu item `Git Bash` does), and instead set `MSYSTEM=mingw64` and `MSYS2_PATH_TYPE=inherit` and the launch `...\Git\usr\bin\mintty.exe /usr/bin/bash -li` either manually, or via a script.

For inspiration, you could start with the Visual Basic Script Git for Windows used to use in the early v1.x days: https://github.com/msysgit/msysgit/blob/master/share/WinGit/Git%20Bash.vbs. Or the `.cmd` script we used to use: https://github.com/msysgit/msysgit/blob/4d0911dceccf1524a2d6aeb15bc25d9cdb1eb75d/cmd/git.cmd (you will want to use a shortcut that uses [`start /b [...]`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start) to stop the CMD window from popping up).

**Comment by orgads** [comment]
Never mind. I had python in system PATH, and nonfunctional WindowsApps/python in user PATH. Solved it by prepending the working python in my user PATH.
