### ISSUE TITLE
SSH executable and related binaries not configured with correct build version

### ISSUE THREAD

**Issue by AlanFlorance** [git-for-windows/git#2880]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
```
git version 2.29.2.windows.1
cpu: x86_64
built from commit: cbf8e7474ba2529d5e7269d0cacab6b4e59579db
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.19042.572]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

Editor Option: VisualStudioCodeInsiders
Custom Editor Path: 
Default Branch Option: development
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
CMD
PowerShell
Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```

Get-Command -Name ssh -All

 - What did you expect to occur after running these commands?

** insert here **

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ssh.exe                                           8.4.0.0    C:\Program Files\Git\usr\bin\ssh.exe
Application     ssh.exe                                            8.1.0.0    C:\Program Files\OpenSSH\ssh.exe

 - What actually happened instead?

** insert here **

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ssh.exe                                            0.0.0.0    C:\Program Files\Git\usr\bin\ssh.exe
Application     ssh.exe                                            8.1.0.0    C:\Program Files\OpenSSH\ssh.exe

ssh.exe and related binaries have no build information in them..

Git and OpenSSL do have the correct version, build information

Get-Command -Name git, openssl -All

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     git.exe                                            2.29.2.1   C:\Program Files\Git\cmd\git.exe
Application     openssl.exe                                        1.1.1.8    C:\Program Files\Git\usr\bin\openssl.exe

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment]
> Application ssh.exe 0.0.0.0 C:\Program Files\Git\usr\bin\ssh.exe
> Application ssh.exe 8.1.0.0 C:\Program Files\OpenSSH\ssh.exe

I can only guess that you are referring to the file version that is stored in the resources of the `.exe` file? I.e.

```sh
powershell -c '(get-item "C:/Program Files/Git/usr/bin/ssh.exe").VersionInfo.ProductVersion'
```

If so, on my machine the PowerShell version of OpenSSH is not in `C:\Program Files\OpenSSH\ssh.exe`, but in `C:\Windows\System32\OpenSSH\ssh.exe`.

And yes, the file/product version is not stored in [MSYS2](https://msys2.github.io/)'s `ssh.exe` (which is the `ssh.exe` that is bundled in Git for Windows). Neither is it stored in `bash.exe`:

```sh
$ powershell -c '(get-item "C:/Program Files/Git/usr/bin/bash.exe").VersionInfo'

ProductVersion   FileVersion      FileName
--------------   -----------      --------
                                  C:\Program Files\Git\usr\bin\bash.exe
```

Nor in `ls.exe`:

```sh
$ powershell -c '(get-item "C:/Program Files/Git/usr/bin/ls.exe").VersionInfo'

ProductVersion   FileVersion      FileName
--------------   -----------      --------
                                  C:\Program Files\Git\usr\bin\ls.exe
```

In fact, a quick study of the `.exe` files in Git's `/usr/bin/` shows that only a precious few of them have version info in their resources: `envsubst.exe`, `gettext.exe`, `ngettext.exe`: 0.19.8.1, `mintty.exe`: 3.4.1.0 and `openssl.exe`: 1.1.1h.

In other words, it seems that this is either intentional, or it is a _huge_ ask of the MSYS2 project. If you care about this deeply, I would highly recommend working on a fix yourself. This is how you can get started:

1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd openssh`,
3. build Git via `sdk build`
4. Enter the directory with the source code: `cd src/openssh-*1`
5. Add an appropriately-formed template `openssh.rc.in` (use https://github.com/git-for-windows/msys2-runtime/blob/main/winsup/cygwin/winver.rc as an example), then edit `Makefile.in` to add a rule that uses `sed` to determine the version stored in `version.h` and to generate `openssh.rc` from it, then make sure that it is compiled to `openssh.res` and linked into `ssh.exe` to make sure that the version info is stored in the resources.
6. open a PR at https://github.com/git-for-windows/MSYS2-packages/.

**Comment by dscho** [comment]
Closing as stale.
