### ISSUE TITLE
when executing "bash" __git_ps1 is not found

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#290]
If I'm running Git Bash and from the shell type in "bash" to launch a subshell I see `bash: __git_ps1: command not found` and I lose the branch information that was in the original bash prompt.

**Comment by dscho** [comment]
This is  a known issue: when launching bash *without* `--login`, the profile is not executed, and since the functions required for the prompt to work are not inherited by subshells, you see this error message.

Quick fix: always start `bash --login`.

Longer fix: figure out which file is sourced by bash when starting a subshell (maybe `/etc/bash.bashrc`?) and put special code there to re-initialize the prompt when an interactive console is detected.

@kjeremy you up for the task?

**Comment by dscho** [comment]
@kjeremy it would be nice to see a contributions from your side.

The proper fix for this would actually be to move the prompt from the profile to the bashrc. We can do this in [git-extra](https://github.com/git-for-windows/build-extra/tree/master/git-extra) but we must take pains to move the `git-prompt.sh` outside `/etc/profile.d/` lest it be sourced as part of `/etc/profile` (and hence double-sourced). Then we need to edit `/etc/bash.bashrc` as part of [`git-extra.install`](https://github.com/git-for-windows/build-extra/blob/master/git-extra/git-extra.install.in) to add the line (if it is not there yet):

```bash
test ! -t 0 || . /etc/git-prompt.sh
```

And then all this needs to be tested thoroughly. Ball's in your court now :smiley:

**Comment by nalla** [comment]
No need to move `git-prompt.sh`. Just adding `shopt -q login_shell || . /etc/profile.d/git-prompt.sh` to the `bash.bashrc` sould be enough.
