### ISSUE TITLE
[Question] Corrupted git repo after Windows freeze

### ISSUE THREAD

**Issue by sryze** [git-for-windows/git#2903]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.29.2.windows.2
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
Same on Windows 10 (different builds)
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: FFOnly
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

-

### Details

I'm curious about an issue that keep having with Git repos under Windows. I'm not sure if this is related to Git at all, I thought I'd give it a shot:

Why is it when my Windows system feezes completely and I do a hard reboot, I often find out on the next boot that some Git repository ends up being corrupt? Either .git/config is corrupt (filled with null/zero bytes), or .git/index, or some other file under the .git directory.

Is it because Git for Windows keeps these files open in the background? (I'm not sure if it does). Most of the time, I have my IDE (IntelliJ) and another editor (VS Code) open when this happens. And a few Git Bash instances.

Could Git itself cause a freeze like this?

This only occurs on Windows. I had this problem with both Windows 10 and Windows 7 over the last few years. It's quite frustrating that I must repair my repo after every PC crash. In the last couple of weeks, this happened to the same repo about 3-4 times.  I just want to know if it's somehow related to using Git with NTFS.

Thanks!

**Comment by rimrul** [comment]
AFAIK Git for Windows does not keep those files open while you're not running git commands. But your IDE probably keeps a close eye on your repository, fetching a status regularly, potentially automatically staging changes whenever you save a file, ...

**Comment by dscho** [comment]
The problem actually lies with the journal of NTFS. It sounds very similar to what was reported [here, on the Git mailing list](https://lore.kernel.org/git/202010242019.09OKJTP13180@crypt.org/). Note that this report talks about Ubuntu, and therefore the remedies (switch to a different journal mode) do not apply one-to-one to Windows.

We tried to address this via b35310dcf0f36e695f39606e601aafcabd0d87a7 by setting `core.fsyncObjectFiles`'s default to `true`, but it probably does not matter in your case because that only affects loose object files, and you reported that one of the symptoms is `.git/config` or `.git/index` being corrupted. I _think_ what you are seeing here is the issue that @peff described in https://lore.kernel.org/git/20180117205509.GA14828@sigill.intra.peff.net/.

So far, I did not see any attempt at fixing this, and certainly no good way to replicate this reliably.

I _could_ imagine that this patch might improve things, though:

```diff
diff --git a/tempfile.c b/tempfile.c
index 94aa18f3f7d..21e1ff73e90 100644
--- a/tempfile.c
+++ b/tempfile.c
@@ -286,11 +286,13 @@ int reopen_tempfile(struct tempfile *tempfile)
 int rename_tempfile(struct tempfile **tempfile_p, const char *path)
 {
 	struct tempfile *tempfile = *tempfile_p;
+	int fsync_res;
 
 	if (!is_tempfile_active(tempfile))
 		BUG("rename_tempfile called for inactive object");
 
-	if (close_tempfile_gently(tempfile)) {
+	fsync_res = fsync(tempfile->fd);
+	if (close_tempfile_gently(tempfile) || fsync_res < 0) {
 		delete_tempfile(tempfile_p);
 		return -1;
 	}
```

@sryze if you want to give it a whirl:
1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd git`,
3. apply the patch
4. build Git via `make -j$(nproc)`
5. test either in-place via `./git --exec-path="$PWD" -C <directory> <command>`, or install into the SDK via `make install` and then using the Git SDK Bash to perform your Git operations, or build a new installer via `sdk build git-and-installer`?
6. open a PR?

**Comment by dscho** [comment]
Note: a more complete solution would use transacted writes, but I fear that this would be quite tricky to get into Git's code base as it is _so_ biased toward POSIX APIs.

**Comment by dscho** [comment]
Closing as stale.
