### ISSUE TITLE
Git commands do not honor existing console foreground/background colors

### ISSUE THREAD

**Issue by arvindaiyar** [git-for-windows/git#2919]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit

```
$ git --version --build-options
git version 2.29.0.vfs.0.0
cpu: x86_64
built from commit: 3c7b47771c6afc8e8093f066fe29ff80fcf0b8ac
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.640]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

ConEmu ; Console2

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git log --oneline
```
 - What did you expect to occur after running these commands?

show git log using the existing color options i.e. the output keeps the existing color options intact.

 - What actually happened instead?

the git output prints on a black background and no longer respects the currently set color options.

**Comment by dscho** [comment]
This [has been reported on the Git mailing list](https://lore.kernel.org/git/MWHPR21MB01435E001D3B779017675B1297E90@MWHPR21MB0143.namprd21.prod.outlook.com/), too, but with a much more minimal MCVE (without using under-explained aliases like `gitl`): no need for Console2, a regular CMD will do, all one has to do is call `color 2e` and then _any_ Git command that calls the pager.

It turns out that this is an issue with Cygwin. Anything calling `less.exe` (e.g. `git log` or `git branch`) will trigger this issue. But in Cygwin, it is even easier: simply start Cygwin's Bash in a CMD, then call `color 2e`, then type a few characters and then delete one. The entire line will be colored as if the `color 2e` command had not been called.

Feel free to report this to [the Cygwin mailing list](https://cygwin.com/mailman/listinfo/cygwin/) (plain text only, no HTML allowed).

**Comment by dscho** [comment]
Closing as stale.
