### ISSUE TITLE
Git failed with a fatal error. Failed to write item to store

### ISSUE THREAD

**Issue by suthishnairs** [git-for-windows/git#2922]
When trying to clone GIT repo, getting below error from Visual Studio

> Git failed with a fatal error.
> Failed to write item to store. [0x520]
> A specified logon session does not exist. It may already have been
> terminated
> POST git-upload-pack (214 bytes)
> remote: Azure Repos
> remote: remote:
> Found 3 objects to send (17ms)

Tried in both the versions of Visual Studio Enterprise 2019 16.7 and 16.8.

16.7: Tried to clone multiple times, sometimes all the files gets downloaded but above error still pops up.

16.8: No download or cloning happening, same error.

I tried recreating Azure personal access token, also added an Generic Credentials into Windows Credentials.

Nothing worked, any help here, please.

Using: Visual Studio Enterprise 2019 & Git-2.29.2.2-64-bit

**Comment by mjcheetham** [comment]
Hi @suthishnairs this looks like an error coming from [Git Credential Manager Core](https://github.com/microsoft/Git-Credential-Manager-Core) rather than Git for Windows itself.

The error indicates it is unable to write/save the personal access token in the Windows Credential Manager.
Please can you [open an issue in the GCM Core project](https://github.com/microsoft/Git-Credential-Manager-Core/issues/new/choose), where we can investigate futher? Thanks.

**Comment by suthishnairs** [comment]
> Hi @suthishnairs this looks like an error coming from [Git Credential Manager Core](https://github.com/microsoft/Git-Credential-Manager-Core) rather than Git for Windows itself.
> 
> The error indicates it is unable to write/save the personal access token in the Windows Credential Manager.
> Please can you [open an issue in the GCM Core project](https://github.com/microsoft/Git-Credential-Manager-Core/issues/new/choose), where we can investigate futher? Thanks.

Hi @mjcheetham Thank You. Done, issue created.

**Comment by suthishnairs** [comment]
Issue got resolved...
Refer: https://github.com/GitCredentialManager/git-credential-manager/issues/245
