### ISSUE TITLE
Git for Windows keeps forgetting that it's signed in as soon as my default browser clears its cache

### ISSUE THREAD

**Issue by astrohart** [git-for-windows/git#2928]
So, I am aware that there is a new Git for Windows feature to use your browser to sign in to GitHub from a 3rd-party app (such as Visual Studio 2019).  I think it sucks.

This is all well and fine, but my browser is Chrome and Chrome likes to sign itself out of my Google account at random (as does IE) and I end up having to click the "Git for Windows sign in with your web browser" 2-3 times per day.  It's really annoying and interrupts my train of thought when I am trying to do my work and submit check ins and am "in the zone." as it were.

I much prefer how Git for Windows used to work, where it would prompt for your credentials itself and then remember them forever.  I think that is much preferable to the current set up for ease-of-use purposes.

**Comment by dscho** [comment]
Brian, while I appreciate that you took time to write up your grievance, I do not particularly like the tone. It sounds as if you assume that somebody changed Git for Windows just to annoy you. That somebody spent time to make your life miserable.

I would like to invite you understand that this is Open Source, and you benefit from a tremendous amount of work, mostly by volunteers in their free time. There would be more respectful ways to appreciate this work, e.g. by contributing your time to improve Git for Windows.

As far as this "feature to use your browser to sign in to GitHub" goes, I am not sure I really understand. Do you mean Git Credential Manager Core? If so, you can easily turn it off when (re-)installing:

![image](https://user-images.githubusercontent.com/127790/101534431-71619e80-3997-11eb-904f-f0ab5e411224.png)

And since this is not a bug report, but more an airing of a grievance, I'll convert this to a discussion.
