### ISSUE TITLE
Git Credential Manager Core does not install with latest release

### ISSUE THREAD

**Issue by benh98** [git-for-windows/git#2932]
When you run the latest installer for Windows 64-Bit, and check the box to install credential-manager-core, the installer does not install it.  You must install it manually.

**Comment by dscho** [comment]
Hmm. Please do not just delete the issue reporting template. Fill it out instead. Now I have to ask you most of those questions anyway.

What Windows version are you using?

What Git for Windows version are you talking about? v2.29.2(3)?

Did you upgrade from a previous version? If so, which version?

Are you using Git Bash or Git CMD, or another command prompt entirely?

Are you sure that GCM Core is missing?
- What does `git credential-manager-core version` say?
- What does `git config --show-origin --get-all credential.helper` say?
- What does `ls -l /mingw64/libexec/git-core/git-credential-manager-core.exe` say (when run in Git Bash)?

Have you installed GCM Core manually previously?
- What does `where git-credential-manager-core` say (when run in Git CMD)?

What other things can you tell about your setup, e.g. do you use a specific malware (yes, we had problems with that in the past, where semi-random `.exe` files were quarantined without notice).

If all else fails, would you mind re-running the installer with the `/LOG=<filename>` option to produce a log, then investigate yourself whether there is any tell-tale in the log that could help understand what the problem is?

**Comment by dscho** [comment]
@benh98 ?
