### ISSUE TITLE
"Terminal" button no longer behaves properly in Source Tree

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#296]
In Git version 1.9 for Windows, clicking Terminal in Atlassian's SourceTree launched the terminal with PATH setup correctly (I could find `git`). Now, it launches a terminal as it did before, but `git` commands do not work (it can't find `git`).

**Comment by dakotahawkins** [comment]
I think this is something SourceTree needs to fix. Hopefully they update
their embedded Git version soon and do that.

**Comment by rcdailey** [comment]
Possibly. But the invariant here is SourceTree. Git changed, not source tree. And it worked fine before. Users won't care if Atlassian is doing it wrong, they will see that the last thing they did was install Git and blame it. I thought Git would be backward compatible in this regard, even if it means it's a hack and terrible solution.

I have no idea how SourceTree is starting the terminal. But it's not configurable, AFAIK.

**Comment by kriegaex** [comment]
SourceTree, when configured to use the installed system Git, starts *[GIT-DIR]/bin/bash.exe* instead of *[GIT-DIR]/git-bash.exe*, i.e. it does not start the MinGW mintty terminal (I noticed because of the other prompt and because the terminal window is not fully resizeable). Maybe this is a clue to the root cause.

**Comment by rcdailey** [comment]
Maybe a workaround is to point it to a fake git directory, with
bin/bash.exe being a symbolic link to git-bash.exe. The other directories
can be symlinked as needed.

**Comment by shoelzer** [comment]
What version of SourceTree are you using? An issue just like this was fixed in 1.16.17.

See here:

https://jira.atlassian.com/browse/SRCTREEWIN-3275

https://jira.atlassian.com/browse/SRCTREEWIN-3381

**Comment by kriegaex** [comment]
I use SourceTree 1.6.20.

**Comment by kriegaex** [comment]
AFAIK, *bin/bash.exe* is already a workaround from Git in order to satisfy SourceTree, but as I said, it opens the "wrong" (sub-optimal) terminal.

**Comment by dscho** [comment]
> bin/bash.exe is already a workaround from Git in order to satisfy SourceTree

... and others...

> but as I said, it opens the "wrong" (sub-optimal) terminal

Actually, it does not open a terminal, but it is marked as console program, so unless there is already a console to work with, Windows will want to open a ConHost window.

> I even tried overwriting bash.exe by git-bash.exe, but it does not work and throws an error.

Heh... Nice idea, but it cannot work, as `git-bash.exe` only sets up a few environment variables and the working directory before executing `bash.exe --login -i`...

**Comment by kriegaex** [comment]
This is interesting information, thanks. It sounds as though you know exactly what is going on. So I assume you have an idea how to fix it. Is my assumption correct or do you need anything else?

**Comment by dscho** [comment]
@kriegaex actually, I have no idea about the inner workings of SourceTree and I haven't used it myself yet. It is unclear whether the issue lies with Git for Windows, with SourceTree or with the usage. It is even unclear to me what version of SourceTree triggered this bug report and from where it was installed. In short, not many of the hints in https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines were heeded.

**Comment by kriegaex** [comment]
With all due respect to your private time invested in maintaining this produce and answering questions, it seems to me that in both issues I commented on today, both of which are non-existent in Git 1.9.5, you are main,y trying to avoid having to fix anything on your side and blame it on other tools such as SourceTree or Maven, both lf which I used without any Git-specific problems for years with older Git versions. I think I am just going to switch back to the old version instead of trying to help you diagnose problems in order to fix your product. Thank you very much anyway, I appreciate your effort.

**Comment by kriegaex** [comment]
Oh, and one more thing? How many times do I need to answer the question about the SourceTree version? In the other issue ticket you also asked me for info already provided. Maybe you should read more carefully and not overload yourself by trying to answer too many questions at once. No offense intended, it is just an advice which you can accept or reject.

**Comment by rcdailey** [comment]
While it does suck ass that SourceTree can't properly launch the terminal anymore, I am with @dscho on this one. He's investing his free time to work on his own software. Other than SourceTree, there are a ton of other tools that can break. It's difficult enough to architect stuff designed for Linux to run on Windows, and even tougher to have to hack in solutions into it so it works properly with tools.

If anything, I'm asking for a workaround. Long term, I recognize that SourceTree hard-coding the way the terminal is launched is probably not going to work. It should be flexible. There should be a simple input box that will let me specify the path to the terminal EXE it will launch.

The best workaround I've come up with is symlinks (`mklink /D` on Windows). Replicating old msysgit structure in a separate directory tree somewhere, and telling SourceTree that git is *really* installed there. It's a pain in the ass to maintain, but I can't think of a better way. Maybe @dscho has some neat recommendations? Outside of that, I don't expect any code to be written on behalf of this project to fix the problem.

Closing as this issue as it seems nothing can be done.

**Comment by dscho** [comment]
@rcdailey you got me pretty wrong there. For one, I am no longer doing this in my free time (although I did, for ten years). For another one, I do believe that Git for Windows could accommodate SourceTree better (and not only SourceTree). Further, I am interested in solutions, not in work-arounds, unless absolutely necessary. And finally, I am interested to fix bugs together with people who don't shy away from work when the going gets tough, who keep going even if it costs them some effort. It's not like I ask others to do all the work, and I expect the same courtesy in return.

**Comment by kriegaex** [comment]
I want to make a general comment, please bear with me. It applies to this ticket as well as #315. Both tickets are about a new software version violating backward compatibility rules.

* Somehow Git for Windows 2.5.0, even though on a new technological basis, ended up as the official download for the Windows platform on git-scm.com, i.e. users expect it to be a drop-in replacement for the old version 1.9.5. They only expect the new Git 2.x features to work, not their development tools to fail or behave strangely.

* Git is at the bottom of the development toolchain. Above it are clients like Maven, JGit, GUI clients like  Source Tree, IDEs like Eclipse, IntelliJ IDEA and Netbeans. In my environment, IDEA utilises Maven, Maven utilises JGit, JGit utilises Git. Also SourceTree uses Git. Thus, I think it is not all those tools which should be refactored in order to accomodate changed file locations such as the global Git configuration file or the Git Bash executable. I think that the tool should be installed in such a way that existing (compatibility) contracts are not violated and new features such as the improved, resizeable MINGW64 Git Bash are drop-in replacements to old ones such as the suboptimal old Git Bash (Bash.exe) based on cmd.exe.which bash

* IMO it is expecting too much that you test all combinations of tools, i.e. issues such as the two mentioned in these tickets can occur. I am fine with that. But if a user raises an issue I think it would be good to solve them instead of closing the tickets and saying that "nothing can be done". Something can always be done, and if it is only to take care of getting issues sorted out with tool vendors like Atlassian and finding a cost-/effort-efficient way of solving them.

**Comment by kriegaex** [comment]
Back to the topic in question: I used SysInternals Process Explorer in order to find out how SourceTree starts the terminal when the corresponding button in the GUI is clicked. Here are my findings:

The call graph looks like this:

![image](https://cloud.githubusercontent.com/assets/1537384/9544288/9d4236b8-4d7f-11e5-82bf-5134ab025f02.png)

I.e. SourceTree seems to start cmd.exe, either directly or by using a wrapper tool. Probably there is not much that can be done on Git side in order to change that other than notify the SourceTree maintainer and telling them what they should do instead. BTW, this is the command line used by SourceTree:

    "C:\Windows\System32\cmd.exe" /c "C:\Program Files\Git\usr\bin\sh.exe" --login -i

Further below in the same screenshot you see what happens when a user directly opens *git-bash.exe* or *bash.exe* from Windows Explorer: The former starts *mintty.exe*, the latter starts the console version of *bash.exe*.

**Comment by dscho** [comment]
Here is the download link for SourceTree 1.6.20: http://downloads.atlassian.com/software/sourcetree/windows/SourceTreeSetup_1.6.20.exe

**Comment by rcdailey** [comment]
Well I made some false assumptions but I was trying to defend your efforts.
Anyway as I said I don't see how it's your responsibility to make sure
other unrelated tools don't break when arguably those tools are the ones
"doing it wrong".

**Comment by kriegaex** [comment]
@dscho: I had the latest version already installed when testing this behaviour. What do you expect me to do? Or was the download link for someone else's reference?

**Comment by maoueh** [comment]
@kriegaex 

> ... i.e. users expect it to be a drop-in replacement for the old version 1.9.5. They only expect the new Git 2.x features to work, not their development tools to fail or behave strangely.

Sorry, but I don't agree with you here. Even before Windows Git passed from 1.9.5 to 2.5.0, the normal git release from `1.x` to `2.x` was a backward incompatible release roughly following [semantic versioninng](http://semver.org/) which bumps major version on backward incompatible changes. In this respect, it is expected that Git for Windows `2.5.0` will not be 100% backward compatible with the previous `1.9.5` version.

I would even go further then this. Does launching a terminal running `bash` which is shipped as a support tool aside git core executables should be considered as part of Git for Windows `API` contract?

Don't get me wrong, I'm not ranting about your issue, well, a little bit ;). Overall, backward compatibility with future fixes to keep or getting it back backward compatibility is noble and I'm sure maintainers of this project will try to keep it whenever possible.

I just wanted to say that sometimes, backward compatibility is broken and fix(es) cannot be perform on the project itself and only project using it can change to fix it. I'm with @rcdailey here, I think this will need to be fix in `SourceTree` directly. Your post of `SourceTree` running `cmd.exe` directly seems to point in this direction.

**Comment by kriegaex** [comment]
Maybe it is pointless to duiscuss whether it is a regression bug or not. Probably you are right that it is not. But I also wrote:

> violating either backward compatibility rules ***or user expectations***

I do think that user expectations are violated here because if a user selects the option that he prefers *mintty* over *cmd* as a Git Bash, this should work out of the box. I do think that user experience is an important aspect for any software, developer tool or not. I also believe that the effort to make this happen would not be so big.
