### ISSUE TITLE
Error message from git credential approve in 2.31.0

### ISSUE THREAD

**Issue by glandium** [git-for-windows/git#3125]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.31.0.windows.1
cpu: x86_64
built from commit: 959b2f0c6fb12f8ba13f9015c4482fa8133b7f9c
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1440]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

The install comes from MinGit.zip

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash from msys2

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
(echo protocol=http; echo host=localhost:8005; echo username=foo; echo password=bar) | git -c credential.helper='store --file=C:/Users/glandium/credentials' credential approve
```
 - What did you expect to occur after running these commands?

No output (this was the case until 2.31.0, and is still the case on 2.31.0 on both Linux and Mac)

 - What actually happened instead?

```
fatal: An error occurred while sending the request.
fatal: Unable to connect to the remote server
fatal: No connection could be made because the target machine actively refused it [::1]:8005
```

**Comment by rimrul** [comment]
>No connection could be made because the target machine actively refused it [::1]:8005

 You're telling me that git on macOS or Linux wouln't report an error in this situation?
I find that hard to believe.

**Comment by glandium** [comment]
No, it doesn't. It doesn't even try to do any connection. And it didn't on Windows until 2.31.0.

**Comment by dscho** [comment]
> No, it doesn't. It doesn't even try to do any connection.

That is not quite the truth, is it? What you failed to mention is that you did not test this, at least not on Linux _with Git v2.31.0_. I just did, built it from source in WSL, and lo and behold:

```console
$ ./bin-wrappers/git version
git version 2.31.0

$ (echo protocol=http; echo host=localhost:8005; echo username=foo; echo password=bar) | ./bin-wrappers/git -c credential.helper='store --file=$PWD/glandium-credentials' credential approve
fatal: An error occurred while sending the request.
fatal: Unable to connect to the remote server
fatal: No connection could be made because the target machine actively refused it 127.0.0.1:8005
```

**Comment by dscho** [comment]
Hahaha. I now know what it is.

> ```
> (echo protocol=http; echo host=localhost:8005; echo username=foo; echo password=bar) | ./bin-wrappers/git -c credential.helper='store --file=$PWD/glandium-credentials' credential approve
> ```

Please note this part: `-c credential.helper='store --file=$PWD/glandium-credentials'`. This uses the `credential.helper` setting. Let's read [the documentation](https://git-scm.com/docs/git-config#Documentation/git-config.txt-credentialhelper):

> `credential.helper`
>
> Specify an external helper to be called when a username or password credential is needed; the helper may consult external storage to avoid prompting the user for the credentials. This is normally the name of a credential helper with possible arguments, but may also be an absolute path with arguments or, if preceded by `!`, shell commands.
>
> Note that multiple helpers may be defined. See [`gitcredentials[7]`](https://git-scm.com/docs/gitcredentials) for details and examples.

That second-to-last sentence is curious, isn't it? "Note that multiple helpers may be defined." Let's follow that link to the [`gitcredentials` documentation](https://git-scm.com/docs/gitcredentials#_configuration_options):

> ## CONFIGURATION OPTIONS
>
> Options for a credential context can be configured either in `credential.*` (which applies to all credentials), or `credential.<url>.*`, where `<url>` matches the context as described above.
>
> The following options are available in either location:
>
> `helper`
>
>    The name of an external credential helper, and any associated options. If the helper name is not an absolute path, then the string `git credential-` is prepended. The resulting string is executed by the shell (so, for example, setting this to `foo --option=bar` will execute `git credential-foo --option=bar` via the shell. See the manual of specific helpers for examples of their use.
>
>    If there are multiple instances of the `credential.helper` configuration variable, each helper will be tried in turn, and may provide a username, password, or nothing. Once Git has acquired both a username and a password, no more helpers will be tried.
>
>    If `credential.helper` is configured to the empty string, this resets the helper list to empty (so you may override a helper set by a lower-priority config file by configuring the empty-string helper, followed by whatever set of helpers you would like).

Aha!

Any `credential.helper` setting will be _appended_ to the list of credential helpers, and only specifying an empty value will reset that list.

The thing is, in MinGit there already is a credential helper: GCM Core. It is defined as credential helper in the system config. And you did not reset the list. Neither did I, and I have GCM Core configured even in my WSL setup. Therefore, GCM Core was asked to store the credentials, and since it is a lot more careful than the `store` helper, it tried to verify that those credentials _actually work_ before storing them.

So if you follow the guidance of above-quoted documentation, you can reset the credential helper list by specifying `-c credential.helper=` before specifying your intended credential helper, like so:

```console
$ (echo protocol=http; echo host=localhost:8005; echo username=foo; echo password=bar) |
 git -c credential.helper= -c credential.helper='store --file=C:/Users/glandium/credentials' credential approve
```

... and voilà, it works!

**Comment by glandium** [comment]
Thank you a lot for figuring this out. This was also the root cause of another problem I had that I was trying to pin down to something before reporting.
