### ISSUE TITLE
PATH environment variables related to Git are reset on every update by the installer

### ISSUE THREAD

**Issue by ghost** [git-for-windows/git#3127]
- I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) issue matching what I'm seeing

### Setup

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19042.867]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Notepad++
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```
### Details
 - What did you expect to occur after installing?
Manually added entries to the PATH environment variable to Git subdirectories unchanged

 - What actually happened instead?
On every update, all manually added entries are removed and we are always left with the single default PATH entry

### Steps to reproduce

1. Use a machine with an already installed version of Git for Windows
2. Add some entries to the system PATH related to Git, for example: "C:\Program Files\Git\bin", "C:\Program Files\Git\usr\bin"
3. Update Git to a newer version using the installer (ex: provided by the automatic update checker)
4. Result: added entries are removed

**Comment by dscho** [comment]
>     * On every update, all manually added entries are removed and we are always left with the single default PATH entry

Could you elaborate on that?

> * Add some entries to the system PATH related to Git, for example: "C:\Program Files\Git\bin", "C:\Program Files\Git\usr\bin"
> 
> * Update Git to a newer version using the installer (ex: provided by the automatic update checker)
> 
> * Result: added entries are removed

This is most likely the code responsible for this behavior: https://github.com/git-for-windows/build-extra/blob/4dfcae554dd036efd81fe06ec7c8305305a45c91/installer/install.iss#L2998

It is very much on purpose that Git for Windows considers those path components fair game: you are not supposed to rely on any implementation detail of Git for Windows, such as the presence of `usr\bin`.

In fact, `usr\bin` did not even exist in the Git for Windows v1.x era.

I wonder what exactly you are trying to accomplish. Do you want to risk adding all of the MSYS2 tools to the `PATH`? If so, why not choose this option? 
![image](https://user-images.githubusercontent.com/127790/111753541-41c80980-8897-11eb-83f7-cdcdbd206cd1.png)

**Comment by DMX-David-Cardinal** [comment]
> Could you elaborate on that?

I'm not sure what else I can add... If the issue is unclear I hope my following comments will help clarify.

> It is very much on purpose that Git for Windows considers those path components fair game: you are not supposed to rely on any implementation detail of Git for Windows, such as the presence of `usr\bin`.
>
>In fact, `usr\bin` did not even exist in the Git for Windows v1.x era.
>
>I wonder what exactly you are trying to accomplish. Do you want to risk adding all of the MSYS2 tools to the `PATH`? If so, why not choose this option?

Let's ignore the idea of `usr\bin` for a moment... If a user decides to create a directory named "C:\Program Files\Git\foobar", no matter the reason behind it, and wants to add a reference to it in their `PATH`, they wouldn't expect the Git for Windows installer to remove their `PATH` entry every time they update Git, which is what is happening right now.

From what I can tell from the code you referenced, it seems to match any all entries beginning with the AppDirectory, rather than simply the AppDirectory itself. Wouldn't that behaviour be more self-contained if it were modified to match *only* the entries that match exactly what might be generated by the installer?

**Comment by dscho** [comment]
> I'm not sure what else I can add...

The precise entries added, not just a hint and then an "for example".

> If a user decides to create a directory named "C:\Program Files\Git\foobar", no matter the reason behind it, and wants to add a reference to it in their `PATH`, they wouldn't expect the Git for Windows installer to remove their `PATH` entry every time they update Git, which is what is happening right now.

This is not supported. Git for Windows treats the installation directory as _its own_. If you add things there, sure, you can do that, but don't expect that to be respected. Those files might be deleted without asking on upgrade, or might be encrypted, or added to a Git repository, etc. You're in unsupported territory there, same as if you started meddling with files in your Microsoft Word installation.

> From what I can tell from the code you referenced, it seems to match any all entries beginning with the AppDirectory

That's right. Git for Windows' expectation is that the files inside the AppDirectory _belong_ to Git for Windows.

If you want to add your own files, you can do that in your home directory.

**Comment by DMX-David-Cardinal** [comment]
> The precise entries added, not just a hint and then an "for example".

The example was the precise entries added

> I wonder what exactly you are trying to accomplish.

Ignoring all other scenarios, we at least have to add a reference to `Git\bin` in order to call `bash` from other command line terminals (cmd). Some commands also fail if the `bin` directory is not part of the `PATH`. Perhaps that is a different issue?

I better understand and agree on the propriety of the directory to the installer.
