### ISSUE TITLE
Error: Could not fork child process: Resource temporarily unavailable (-1).

### ISSUE THREAD

**Issue by githubtime21** [git-for-windows/git#3158]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```64-bit
$ git --version --build-options

** C:\Users\*****>git --version --build-options
git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 64-bit
```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.19042.867] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** DLL rebasing may be required; see 'rebaseall / rebase --help'. **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** /usr/bin/bash --login -i **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** bash.exe **
```
 - What did you expect to occur after running these commands?

** a bash prompt **

 - What actually happened instead?

** the previous errors **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** Not sure  **

**Comment by dscho** [comment]
Hi @githubtime21, and sorry about the problem you experience.

Please note that the canonical way to call Git Bash is via the Start Menu, or if you really want to, `C:\Program Files\Git\git-bash.exe`.

Calling `/usr/bin/bash --login -i` directly is not really recommended because your mileage may vary. For example, if you try to run this from Cygwin's Bash, you _will_ run into trouble.

In any case, searching this bug tracker for this error message brings up a few matches: https://github.com/git-for-windows/git/issues?q=is%3Aissue+is%3Aopen+%22resource+temporarily+unavailable%22

The most common workarounds seem to be to [disable ASLR](https://github.com/git-for-windows/git/issues/2989#issuecomment-776327355), [stopping any running `ssh-agent.exe`](https://github.com/git-for-windows/git/issues/910), and [reinstalling Windows 10](https://github.com/git-for-windows/git/issues/2282#issuecomment-536116407).

I do remember vaguely that in some similar instances in the past, a reboot helped.

**Comment by githubtime21** [comment]
Thanks! This solution worked.

Sent from Mail for Windows 10

**Comment by githubtime21** [comment]
This was my problem solution:
The most common workarounds seem to be to disable ASLR<https://github.com/git-for-windows/git/issues/2989#issuecomment-776327355>, stopping any running ssh-agent.exe<https://github.com/git-for-windows/git/issues/910>, and reinstalling Windows 10<https://github.com/git-for-windows/git/issues/2282#issuecomment-536116407>.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dscho** [comment]
Those are three _very_ different workarounds. Which one solved it?

**Comment by githubtime21** [comment]
sorry, disabled ASLR solved my issue. Thank so much! I would been able to participate in class lab without virtual machine that this service was blocking.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
