### ISSUE TITLE
[2.31.1] Error: open /proc/1374/fd/63: The system cannot find the path specified

### ISSUE THREAD

**Issue by jpmorin** [git-for-windows/git#3170]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
 - [x] I was able to find similar closed issue #2291 .

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [version 10.0.19042.867]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Rebase
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Similar issue to #2291 , but happens with some executable and not others.

Most built-in command work with file descriptor syntax `<(echo "content")`, but installed utilities like jq or yq always exit with error reading the file descriptor.

The test command bellow works on any linux container and in WSL.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
#!/bin/bash
value='{"foo":"bar"}'

# working file descriptors
cat <(echo ${value})
diff <(echo ${value}) <(echo '{"foo":"baz"}')
head <(echo ${value})
tail <(echo ${value})
grep 'foo' <(echo ${value})
sed 's/bar/baz/' <(echo ${value})
cp <(echo ${value}) foo.bar

# file descriptors error
jq . <(echo ${value})
yq e . <(echo ${value})
```
 - What did you expect to occur after running these commands?

```bash
{"foo":"bar"}
1c1
< {"foo":"bar"}
---
> {"foo":"baz"}
{"foo":"bar"}
{"foo":"bar"}
{"foo":"bar"}
{"foo":"baz"}
{
  "foo": "bar"
}
{"foo": "bar"}
```

 - What actually happened instead?

```bash
{"foo":"bar"}
1c1
< {"foo":"bar"}
---
> {"foo":"baz"}
{"foo":"bar"}
{"foo":"bar"}
{"foo":"bar"}
{"foo":"baz"}
jq: error: Could not open file /proc/1378/fd/63: No such file or directory
Error: open /proc/1374/fd/63: The system cannot find the path specified.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

none, see test above

**Comment by dscho** [comment]
It is a known bug that MSYS2 Bash's unnamed pipes are not understood by `jq.exe` (or for that matter, _any_ non-MSYS2 program). The fix for this (which won't be easy) will actually have to happen in the _Cygwin_ runtime (from which the MSYS2 runtime was forked).

So while this is an annoying problem (that I share, too!), I would like to advise not to hold any breath for it...

**Comment by dscho** [comment]
@jpmorin I guess I should have mentioned something else, or more appropriately: I should have asked _how_ interested you are in that feature? Maybe we can combine our strengths here and you can work on that, and I give you pointers? Would that work for you?

**Comment by jpmorin** [comment]
@dscho, Yes I am interested in contribution. I can't actively work on this at the moment, but I can manage some spare time here and there to look into it.

Where should I start?

**Comment by dscho** [comment]
> Where should I start?

The first thing to note is that it _is_ possible for command-line Win32 programs to access named pipes, see e.g. https://stackoverflow.com/questions/19370158/named-pipes-with-command-prompt.

Therefore, the MSYS2 runtime will have to open a named pipe, pass its path to the spawned program (in your example, `jq.exe`), then pass through the output from the _other_ spawned program to that pipe (in your example, `echo`).

So where to patch this in? I think in the MSYS2 runtime, where it spawns Win32 processes: https://github.com/git-for-windows/msys2-runtime/blob/12e88192b84673b81c6550e48fb7df9b607dada3/winsup/cygwin/spawn.cc#L706.

If you scroll up a few lines, you will see how to detect that we're about to spawn a non-MSYS2 program (or, in terms of the way the code things, a _Cygwin_ program): [`if (!real_path.iscygexec ())`](https://github.com/git-for-windows/msys2-runtime/blob/12e88192b84673b81c6550e48fb7df9b607dada3/winsup/cygwin/spawn.cc#L694). This is the way that new custom code will need to be guarded.

Or you could piggyback on top of the code that _already_ auto-converts Unix-style paths to Windows-style paths. This is done here: https://github.com/git-for-windows/msys2-runtime/blob/12e88192b84673b81c6550e48fb7df9b607dada3/winsup/cygwin/spawn.cc#L417

The actual conversion seems to happen here: https://github.com/git-for-windows/msys2-runtime/blob/12e88192b84673b81c6550e48fb7df9b607dada3/winsup/cygwin/path.cc#L3884, or more concretely here: https://github.com/git-for-windows/msys2-runtime/blob/12e88192b84673b81c6550e48fb7df9b607dada3/winsup/cygwin/msys2_path_conv.cc#L263

I am not quite sure _where_ the best place would be to detect paths of the form `/proc/<pid>/fd/<fd>` and then to do this named pipe dance, but probably in `path.cc` (not in `msys2_path_conv.cc` because that latter file is really only concerned with translating Win32 <-> Unix paths, and you need to spawn a new thread at least, to open that path, open a named pipe, and then pass through the data).

Oh, and here is a wiki page that describes how to build the MSYS2 runtime in the first place: https://github.com/git-for-windows/git/wiki/Building-msys2-runtime

**Comment by bob-marcus** [comment]
@dscho what could be a good enough workaround for this issue in the meantime?

**Comment by uniphiny** [comment]
***@***.***

**Comment by dscho** [comment]
Closing, as the only interested person deleted their account.

FWIW I investigated this issue a little bit more with the specific use case of `git diff --no-index` [here](https://github.com/git-for-windows/git/issues/4266).
