### ISSUE TITLE
In the portable version the variable Home links to the %userprofile%

### ISSUE THREAD

**Issue by Evgenioni** [git-for-windows/git#320]
This makes the portable version unportable because the settings stop being portable. It's possible to change the variable for the work process (with setx HOME...) but it breaks some programs (e.g., sublimecodeintel). I like how it is made in MSYS2 (but there is not a comfortable git, not enough cmd/git.exe)

**Comment by dscho** [comment]
The portable version does not set the `HOME` variable, except for the process that runs the bash.

**Comment by dscho** [comment]
(If I misunderstood, please feel free to make your report verbose enough so I can understand what you mean.)

**Comment by CemraJC** [comment]
@Evgenioni is correct in some sense. I am having the issue where certain files like the  `.bash_history` and `.minttyrc` are writing to the Windows **%userprofile%** regardless of the values of the **HOME, USERHOME**, and **HOMEPATH** variables. npm also writes its `npmrc` to this location.

It is possible to manually stop this from occurring by setting *every* possible variable for configuration, but this is tedious and potentially avoidable.

----

#### The crux of the issue:
It has become  very difficult to use dotfiles on multiple machines.

Please advise :)

**Comment by dscho** [comment]
@Evgenioni Overriding `HOME` to point to the current directory should fix the issue. If I understood correctly, you did exactly that, but where is the output? Where is the information what happens to the `HOME` variable, where is a recipe to reproduce the issue?

Just as an illustration, I will describe in a precise and comprehensible way what I did to verify your claim. After unpacking a portable Git, I opened `cmd.exe` and called these commands:

```cmd
C:\Users\git\Downloads\PortableGit>echo %HOME%
%HOME%

C:\Users\git\Downloads\PortableGit>mkdir c:\tmphome

C:\Users\git\Downloads\PortableGit>set HOME=c:\tmphome

C:\Users\git\Downloads\PortableGit>git-bash
```

In the Git Bash window that popped up, I called the following commands:

```sh
git@MYMACHNE MINGW32 /
$ cd

git@MYMACHNE MINGW32 ~
$ pwd -W
C:/tmphome
```

So you see, just overriding the `HOME` environment variable to point to a valid directory will make it work.

And sure, in the technical sense the default `git-bash.exe` does not fulfill the requirements of a portable application: it touches files in the user's home directory. However, this has been the desired behavior of portable Git for Windows from the beginning of its existence, so even if you wanted to "fix" it, it would be too disruptive to tens of thousands' users. So we cannot do it.

**Comment by dscho** [comment]
Oops, I meant to ping @CemraJC not @Evgenioni.

**Comment by CemraJC** [comment]
My apologies - you are correct @dscho . In my rush to complete other tasks I recognize that I did not provide a proper description or explanation of the issue. ... That sounded really formal :)

-----

I have identified my **source of trouble** to be setting the `HOME` environment variable in the bash's `profile` (and other dotfiles - regardless of parsing order) instead of in the windows command environment and launching bash from the command prompt. **dscho's course of action above resolved all the problems I encountered.**

Also, for any others having this problem, I have made an example batch file `(git-bash.bat)` which launches 'git-bash.exe', with the proper environment set up prior to execution - for the sake of simplicity. One can also launch the mintty terminal directly (for more control), although one may also need to add certain path's to the `PATH` variable to get things working correctly.

**Batch file is as follows:**

*Both Examples assume the batch file is in the same directory as 'git-bash.exe'*

```batch
rem Setup environment (replace 'user' with your desired username)
set HOME=home\user
set USERPROFILE=%HOME%

rem Launch the git bash
start git-bash.exe
```

**To launch mintty directly:** *(Replace the start command in the file above with this one)*
```batch
rem Execute bash shell with the mintty interface - for more control
start .\usr\bin\mintty.exe /usr/bin/bash.exe --login -i
```

Please note that I have also set the `USERPROFILE` environment variable, as upon inspection I have found certain packages (like node's **npm**) use the Windows `%userprofile%` variable when saving userconfig files - which does not suit the purposes of a portable setup that can run from a USB thumb drive.

**Although my response is fairly verbose, hopefully this clears any confusion :)**

P.S. Using the command (on the git-bash terminal) `env | grep -i home` may also identify other environment variables that are not set to the desired path if any other issues arise.

**Comment by LeonT-A** [comment]
Just wanted to say thanks a bunch to all of you for this info. I'd been struggling with the %USERPROFILE% problem for months now ever since I started using GitBash. My best solution was adding `HOME=/home` to the top of various dotfiles, which as you know breaks with updates.

I would like to see an update that doesn't require using a terminal/batch file to specify environment variables before running, but instead will do something like look for a .env file alongside the .exe or somewhere else in the hierarchy. It would be optional for those that don't need it but a blessing for anyone who uses the portable version.

Until then, this method will work fine, but some clarification in the README.portable or a link to this issue would have been a huge time saver.
