### ISSUE TITLE
could not find /tmp when my TEMP directory contains chinese characters

### ISSUE THREAD

**Issue by techstay** [git-for-windows/git#331]
#### Here is the mount mapping :
 D:/Program Files/Git on / type ntfs (binary,noacl,auto)
D:/Program Files/Git/usr/bin on /bin type ntfs (binary,noacl,auto)
C:/Users/▒ٴ▒/AppData/Local/Temp on /tmp type ntfs (binary,noacl,posix=0)
C: on /c type ntfs (binary,noacl,posix=0,user,noumount,auto)
D: on /d type ntfs (binary,noacl,posix=0,user,noumount,auto)
Z: on /z type ntfs (binary,noacl,posix=0,user,noumount,auto) 
#### Here is my windows temp directories
C:\Users\百川>echo %TEMP%
C:\Users\百川\AppData\Local\Temp

C:\Users\百川>echo %tmp%
C:\Users\百川\AppData\Local\Temp

#### I tried to change charset to gbk in mintty,but is still didn't work and met new errors when I tried to pull from remote repository

Could not create directory '/c/Users/\351\226\273\321\204\345\204\263\347\273\220\302\233/.ssh'.

**Comment by techstay** [comment]
OK,I find a way that would not be the bestsolutions:

change my user path TEMP and TMP to a new directory instead of the default path containing chinese characters. And it works

**Comment by linquize** [comment]
Is it related to #336?

**Comment by lychichem** [comment]
Seems so, and I think the reporter must using Windows 8+ and sign in with Microsoft Account. The default setting used user's name on Microsoft which contains Chinese characters, and as I am a user upgraded from Win7 to Win10 I don't have the user profile problem.

**Comment by techstay** [comment]
Yes,so I have to change my environment path to avoid it.When can the bug be fixed?

**Comment by lychichem** [comment]
As I'm not the developer of git, I don't know. Maybe you should ask @dscho .

**Comment by dscho** [comment]
> When can the bug be fixed?

It might not have been your intention, but the impression you left was that you expect others to fix your problem. This is not the impression you want to leave in *any* Open Source project.

Assuming that you actually meant to participate actively, as you should, I uploaded an `msys-2.0.dll` (64-bit) [here](https://github.com/dscho/msys2-runtime/releases/tag/tmpfs-non-ascii) that you can download and test by replacing the `C:\Program Files\Git\usr\bin\msys-2.0.dll` file with the temporary version.

Please note that it will accelerate the fix if you test, and it will delay the fix if you don't.

**Comment by techstay** [comment]
I replaced it and it seemed to work.Thank you !

**Comment by lychichem** [comment]
Replaced the dll file. But it only works for user profile, if I manually set a repository path to somewhere which has none ASCII characters (here I use "D:\Downloads\测试\localized-addons"), the git GUI will show "couldn't change work directory" while pulling and will also get error while pushing, so the issue is not fully fixed.

**Comment by dscho** [comment]
@lychichem first of all: you are welcome that I work to fix your problems. It is nice that you appreciate that so much.

Second, the Git GUI bug is *different* from *this* bug. This bug is about `/tmp/`. And this bug has been fixed.

Third, I warmly invite you to work on your problem. `git gui` is a Tcl/Tk script, so you can just edit the file (if you unpack a portable Git, there will not be permission problems).
