### ISSUE TITLE
Version is duplicated in name of app in list of installed apps

### ISSUE THREAD

**Issue by rakleed** [git-for-windows/git#3319]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1052]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

—

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

—

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
—
```
 - What did you expect to occur after running these commands?

The app title will display only the title without the version number.

 - What actually happened instead?

The version of the app is duplicated in the name of the app in the list of installed apps in "Settings - Apps - Apps & features" and "Control Panel - Programs - Programs and Features" in the version for Windows. Please remove the version number from the app name, as the version number is displayed next to the name in a separate field.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

—

 - Additional context

<details>
<summary>Screenshots</summary>

![2021-07-13 23-24-34 Settings](https://user-images.githubusercontent.com/19418601/125524704-f303e071-9354-4398-babf-c02c854c8a7e.png)

![2021-07-13 23-25-30 Programs and Features](https://user-images.githubusercontent.com/19418601/125524711-4af6f9ed-1ae9-49a0-9e8f-f86aef5e6159.png)

</details>

**Comment by PhilipOakley** [comment]
Does this 'duplication' actually cause any particular problem? 

Because of the regular updates and improvements to Git it can be of benefit to users to see their version number directly in the app name. 

I have used other programmes where I have had to decode subtle icon changes when I've need to have two versions available because of compatibility issues so, for me, it feels sensible.

**Comment by dscho** [comment]
First of all: I see the same over here, thank you for the very detailed bug report. It is delightful to receive well-crafted and thoughtful tickets.

Next: I have a really tough time finding _where_ this is defined in https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss, I have to admit. I looked for the term `APP_VERSION` (because that is what is set to 2.32.0.2) and for `APP_NAME` (because that is set to "Git"). The closest I got to something that _might_ be responsible was this: https://github.com/git-for-windows/build-extra/blob/58610eaabc62f88fab22b2d7fb49861637516395/installer/install.iss#L154-L155

But you will note that it has a trailing " Setup", therefore I am not certain that this is it.

Now, taking a step back, the first thing I see when _not_ clicking on the entry in "Apps & features" is the title _without_ the version. Therefore, the version only gets duplicated once you click on it.

With the last point in mind, I tend to agree to @PhilipOakley's wonderment whether this causes any particular problem.

**Comment by rakleed** [comment]
@PhilipOakley @dscho, but you don't need to open additional menus in the control panel to see the version of the app.

This does not cause any problems in the operation of the app, but visually it looks strange. Most other apps don't indicate the version of the app in the name of the app, but just indicate it in a specially made field for this. Therefore, it would be nice if your app followed this behavior.

**Comment by dscho** [comment]
@rakleed if you truly care, feel free to work on it and open a PR (the pointers I gave above should help). I am definitely not _opposed_, but I am not enough in favor to invest any time other than for reviewing any PR.

**Comment by denis-adamchuk** [comment]
@dscho  @rakleed Just FYI - I've just found this change when upgraded to git version 2.33 and discovered that my application is no longer able to tell if "git version 2" is installed because it looked on DisplayName registry key...
I admit this is my bug but just wanted to inform you about potential issues from other people in advance :)
Thanks a lot!
