### ISSUE TITLE
Slow `git config`

### ISSUE THREAD

**Issue by gabyx** [git-for-windows/git#3339]
I am a bit concerned why git on windows takes so much time for certain command compared to on linux.
I am seeing this mostly when running my tests for the Githooks manager in https://github.com/gabyx/Githooks
on windows compared to the linux variants.

https://app.travis-ci.com/github/gabyx/Githooks/builds/233614529
![image](https://user-images.githubusercontent.com/647437/127454944-8aceb30d-fda1-463c-8680-f8d13362b898.png)

I have not completely nailed it down, but a quick look showed that as I read some git config variables in the hook manager, that most time goes into executing `git config ...` (compiled with go, same as exe. in terminal). On Linux that returns in no time < 1-10ms, on windows it takes like 10-20times longer. I am just wondering what makes the Windows build having such a sluggish performance (not only related to git config).
I am seeing this not only on WindowsServer in my tests, but also on any Windows 10m Platform I installed git-for-windows.
Does anybody know which could be the issue here? Of course this depends on how big your Git configs are. See the command below.

### Setup

 -  **64-bit** newest.

```
$ git --version --build-options

git version 2.32.0.windows.2
cpu: x86_64
built from commit: 3d45ac813c4adf97fe3733c1f763ab6617d5add5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1110]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

** **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**git-bash.exe**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# Windows
Measure-Command { & git config --global a.a.a }

# Linux
sudo perf stat -r 10 -B git config --global a.a.a

```
 - What did you expect to occur after running these commands?

Linux: 1.159 ms
Windows: 27 ms

 - What actually happened instead?

It takes approx 10.-20 times longer on windows to complete.

**Comment by dscho** [comment]
Yes, spawning processes on Windows is a lot more expensive than on Linux. Linux was optimized for spawning processes, and for a long time lacked proper support for real threads. Windows was optimized for multi-threading and never spent much effort on making it more efficient to spawn more processes. Since Git was created by the same person who steers the Linux development, obviously Git was designed to make use of Linux' strengths (and it was probably not even clear in the first year of Git's development that it would eventually be ported to Windows at all).

The best advice I can give is therefore to avoid many calls to `git.exe`. This can often be achieved by calling `git config --null --list` and parsing its output into an internal data structure in Go. That strategy can be seen in action e.g. [in Git Credential Manager Core](https://github.com/microsoft/Git-Credential-Manager-Core/blob/d9d62c7ce9100c9b1866a5ca3ed390151ff6e7be/src/shared/Microsoft.Git.CredentialManager/GitConfiguration.cs#L120).

**Comment by gabyx** [comment]
Thanks very much for your elaborate response and suggestion.

Von meinem iPhone gesendet
