### ISSUE TITLE
mintty window appears briefly when running .sh script from Explorer or CMD Shell

### ISSUE THREAD

**Issue by jstine35** [git-for-windows/git#340]
Hi, it is my expectation that running a .sh  script from Explorer or CMD shell should not cause a window to appear on-screen.  This was the default behavior in 1.9x versions of Git For Windows.  I use .sh scripts extensively in my visual studio build projects, and the litany of popups are not helpful, and also prevent the sh script output from being properly piped back into the VS console.

I am able to fix the problem locally by changing the association for sh_auto_file like so:

ftype sh_auto_file="c:\Program Files\git\bin\bash.exe" --login "%L" %*

I'm not very familiar with the under-workings of msys2, so I'm not sure if there are negative side-effects to running bash.exe directly.  So far in limited testing on my environment it has behaved as expected, and even relatively complex pipes via a combination of .cmd > .sh > .cmd > .sh nested invocations worked.

Assuming there are no specific drawbacks to invoking bash.exe directly, then it would seem like this should be the default behavior for sh_auto_file, in order to avoid popup windows and allow piping sh console.

**Comment by dscho** [comment]
Please note that you are calling the `/bin/bash.exe` stand-in that is included for backwards-compatibility. This is *not* the Bash, but a little redirector which nevertheless is necessary because it sets up the environment variables before calling the *real* Bash.

So I think that your fix is almost fine:

1. you need to drop the `--login` option, and
2. you should open a real Pull Request editing [this](https://github.com/git-for-windows/build-extra/blob/6ea681cc5349e7c7da59f5002f21def55590d9b3/installer/install.iss.in#L148) line and [this](https://github.com/git-for-windows/build-extra/blob/6ea681cc5349e7c7da59f5002f21def55590d9b3/installer/install.iss.in#L155) line (but you can strip the `--no-cd` options, they are no longer necessary).

**Comment by jstine35** [comment]
Dropping the --login option causes the spawned bash process to have an uninitialized $PATH (eg, it has one which was inherited directly from windows).  $PATH lacks any mention of /usr/bin/ for example, when invoked without --login. 

I imagine that could be corrected through some modification or addition of etc/bashrc, though I'm not sure if that would be appropriate.

**Comment by dscho** [comment]
Dropping the `--login` option would do what you say *iff* we were calling the real Bash. But we don't. We call the redirector *that adjusts the environment*. But there is one problem: there is a bug in the way [it adjusts the `PATH` variable](https://github.com/git-for-windows/git/blob/78e3a23c6b27c0666b9d0f6c834ec33232d0ddff/compat/win32/git-wrapper.c#L97-L110): it should detect that it was called as `bin/bash.exe` (or for that matter, `bin/sh.exe` or `bin/git.exe`) and strip one more path element (`bin/`) from `path2`.

@jstine35 if you have time to give it a shot, that would be really good because I am still busy with other tickets.

**Comment by dscho** [comment]
Okay, I am closing this ticket, for two reasons:

1. I am about to merge fixes to the `PATH` problem when calling `/bin/bash.exe` without `--login`, so that part is going to work
2. I cannot simply change the file association as you wish. Many users rely on the fact that double-clicking on a `.sh` script will show them the output in a console window, and more often than not, let them interact with the program via keyboard input. If I fulfilled your wish, all of those users would be very mad at me, and rightfully so.

What we *could* do to help your use case is to add a checkbox in the installer to force `.sh` scripts to run without a window when double-clicked, default *off*. This would require a change to the `install.iss.in` file, somewhere around [here](https://github.com/git-for-windows/build-extra/blob/0fd86a3dc4604095a1dd23a6a3aa5ac579adb96e/installer/install.iss.in#L941-L964), most likely renaming the "Performance options" into "Expert options".

Having said that, this wish will not fulfill itself. It will require your active contribution. @jstine35 Are you prepared to do that?

**Comment by jstine35** [comment]
Hmm.. ok.

It seems to me that the root problem is that Windows doesn't appear to offer separate associations for `explorer (double-click)` vs. `cmd.exe (cli).`  Thus when I execute an `.sh` script from a `.cmd` script, it invokes `git-bash.exe`, which in turn opens a new mintty and breaks any standard pipe connections.

I don't mind the idea of a double-clicked `.sh` script opening a console window.  Rather, I would like `.sh` scripts run from a Cmd Prmot (or `.cmd` script) to run inside the prompt, attached to the existing console instance, and inherit stdin/stdout/stderr.  Such behavior should be OK for other users as well, since the console window popup is only bypassed in situations where a console already exists.  Unfortunately it doesn't seem like Windows provides that sort of differentiation.

I'll need to think on this more to see if there's some ideal solution lurking in the shadows.
