### ISSUE TITLE
"getaddrinfo() thread failed to start" occurs after updated to 2.33.0.windows.2 with Proxifier 4.05

### ISSUE THREAD

**Issue by Namorzyny** [git-for-windows/git#3430]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1202]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I'm using portable version.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I'm using Proxifier to force git*.exe to access the network through a SOCKS5 server. Everything worked well (**2.32.0.windows.2**) until I upgraded to this version (**2.33.0.windows.2**).

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell 5.1.19041.1237

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Any operation related to git-remote-https.exe or other operation using the HTTP protocol.

 - What did you expect to occur after running these commands?

Everything operates normally.

 - What actually happened instead?
```
Error given:
fatal: unable to access 'https://xxxxxxxx/': getaddrinfo() thread failed to start
```

**Comment by rimrul** [comment]
> I'm using Proxifier to force git*.exe to access the network through a SOCKS5 server

Does it work if you don't do that? That sounds like it's likely to break things.

> fatal: unable to access 'https\://xxxxxxxx/': getaddrinfo() thread failed to start

That's probably either [`remote-curl.c:507-508`](https://github.com/git-for-windows/git/blob/1e893a1216a1eec0e5e28e0a26098354e4d5a909/remote-curl.c#L507-L508) or [`http-push.c:1539`](https://github.com/git-for-windows/git/blob/aaa3c8065d86e8f25850eb79e90da68d6adcf03f/http-push.c#L1539). Eitherway, the `getaddrinfo() thread failed to start` part of the error message seems to come directly from libcurl (specifically [`lib/asyn-thread.c:720`](https://github.com/curl/curl/blob/fe7b64228d553274f780ebc98a05a9ae266df828/lib/asyn-thread.c#L720)). And Git for Windows 2.33.0 (2) indeed came with [a new curl version](https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#changes-since-git-for-windows-v2330-august-17th-2021). Do you see anything in the [curl 7.78.0 changelog](https://curl.se/changes.html#7_78_0) that seems like it could be related?

To me these two entries stand out:
* --socks4[a]: clarify where the host name is resolved
* socks4: scan for the IPv4 address in resolve results

Are you sure the proxy server is SOCKS5 and not SOCKS4?

The only thing we changed about the build options between curl 7.77.0 and 7.78.0 is removing the `--with-libmetalink` option, because that is no longer supported and Git never used that feature.

**Comment by Namorzyny** [comment]
@rimrul I'm sure the proxy server is socks5, and if I use http.proxy/https.proxy to specify the proxy without Proxifier it works fine. Also, the curl.exe in 2.33.0(2) works well with Proxifier. That's so weird.
