### ISSUE TITLE
"Official" Dark Mode for Git GUI

### ISSUE THREAD

**Issue by Sashank999** [git-for-windows/git#3433]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1237]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```
I usually run Git GUI itself.
But when I don't find the Git CLI command in Git GUI's options, I will use Git Bash from Git GUI `Repository` menu bar.
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
It isn't actually an issue. But rather a suggestion (or maybe an info gathering, if this is already implemented).
```
 
Is there dark mode for Git GUI ? No, I am not asking for ways to edit those `.tcl` files.
I tried that. Got myself comfortable with the whole page. But still, the menu bar and the window title bar remain white. And that frustates me a bit.

I have searched in Github Issues and Google Groups for the keyword `dark` but got no results I hoped so I'm posting this.

I'm a JS developer. But, I know a little bit of TCL and Tk and happily customised the About page like this. So, I think I can help. Just give me the Ok and I will go ahead.

![image](https://user-images.githubusercontent.com/76554862/134190271-d861407a-31be-436d-aac4-9ea3d72f0fb0.png)

**Comment by Sashank999** [comment]
Okay. I will discuss it there.
Issue prati0100/git-gui#64 .

**Comment by Sashank999** [comment]
Discussion happening in Git Mailing List here: https://marc.info/?l=git&m=163266898221849&w=2 .

**Comment by birgersp** [comment]
> The git-gui is now maintained by Pratyush Yadav and there are already discussions about dark theme on his page/repo https://github.com/prati0100/git-gui/issues/
> 
> It's worth discussing it over there. Git for Windows picks up the latest git-gui from there.

Shouldn't the installer for git for windows have some dark ttk themes packed with it? Wouldn't that be something that needs to be implemented here (in this repo)?

**Comment by hehuahuang** [comment]
birgersp ***@***.***> 於 2021年12月13日 週一 20:05 寫道：

**Comment by dscho** [comment]
> Shouldn't the installer for git for windows have some dark ttk themes packed with it?

@birgersp I don't know. Do you? Did you find out how Tcl/Tk handles dark themes? If so, can you open a Pull Request to add one?

**Comment by birgersp** [comment]
I don't. Not yet. Btw we were discussing it a little on the git-gui repo

https://github.com/prati0100/git-gui/issues/64

**Comment by Sashank999** [comment]
@dscho I have already created a way to make Tk theming in Git GUI dark on Windows. I didn't try it on Linux. Only the Title Bar is left. You can check the mailing list: https://marc.info/?l=git&m=164010323505120&w=2 .

It is not configurable. I will work on making it configurable after I find how to make the title bar black on all Windows versions starting from atleast Windows 7.

BTW, can you please link where the source for `git-gui.exe` is ? It is there in the standard Windows installation

**Comment by rimrul** [comment]
> BTW, can you please link where the source for `git-gui.exe` is ? It is there in the standard Windows installation but I can't find its source code.

https://github.com/git-for-windows/MINGW-packages/blob/main/mingw-w64-git/git-wrapper.c

**Comment by dscho** [comment]
> I will work on making it configurable

Sounds good to me!

**Comment by Twisted-Code** [comment]
Should this be reopened, given what git-gui's new maintainer said in j6t/git-gui#13 about this sort of thing being the responsibility of the desktop environment? I was going to reply to their issue, but realized it might be better to start here since I'm using Git for Windows.
My opinion is that they have a point, in that I think Git for Windows and GUIs contained therein should follow whatever is chosen in Windows' personalization settings for the "color mode", unless a setting is added which overrides this.

**Comment by dscho** [comment]
> Should this be reopened, given what git-gui's new maintainer said in [j6t/git-gui#13](https://github.com/j6t/git-gui/issues/13) about this sort of thing being the responsibility of the desktop environment?

Well, you could have quoted that text here, @Twisted-Code, instead of forcing every interested reader to follow the link and to guess at which part you're referring to. Here is the full quote:

> It is the task of the desktop environment to offer a dark mode that is then propagated to all themed widgets of all applications. If your desktop environment can't do that, choose a different desktop environment. So, not interested.
>
> What is desirable is that all UI elements for which Git GUI uses its own colors adapt to the darkness or lightness of theme in use.

Let's unpack this a bit, okay?

What is meant by "desktop environment"? Is it Windows? Is it Tk? I lean more toward the latter. Which brings us all the way back to [my previous, still unanswered question](https://github.com/git-for-windows/git/issues/3433#issuecomment-998035623): Did you find out how Tcl/Tk handles dark themes?

And then there's the part about "all UI elements [...] which Git GUI uses [should] adapt to the darkness or lightness of theme in use". This is more related to [the findings](https://marc.info/?l=git&m=164010323505120&w=2) of @Sashank999:

> I have the code that will make the screenshot possible.
> Simply put:
> 1. Press Win + R
> 2. Enter "git-gui.exe --trace" and press Enter
> 3. Paste the following code(indented for clarity) in the console
> window(a white window with red and black text) that appears.
>     ```tcl
>     ttk::style theme use default
>     ttk::style configure TFrame -background #333
>     ttk::style configure TLabelframe -background #333
>     ttk::style configure TLabelframe.Label -background #333 -foreground #fff
>     ttk::style configure TPanedwindow  -background #333
>     ttk::style configure EntryFrame -background #333
>     ttk::style configure TScrollbar -background #666 -troughcolor #444 -arrowcolor #fff -arrowsize 15
>     ttk::style map TScrollbar -background [list active #333 disabled #000]
>     ttk::style configure TLabel -background #333 -foreground #fff
>     ttk::style configure TButton -background #333 -foreground #fff -borderwidth 2 -bordercolor #fff
>     ttk::style map TButton -background [list active #555 disabled #111 readonly #000]
>     ttk::style configure TCheckbutton -background #333 -foreground #fff -indicatorbackground #666 -indicatorcolor #fff
>     ttk::style map TCheckbutton -background [list active #555 disabled #111 readonly #000]
>     ttk::style configure TEntry -fieldbackground #333 -background #333 -foreground #fff -insertcolor #fff
>     ttk::style configure TRadiobutton -background #333 -foreground #fff
>     ttk::style map TRadiobutton -background  [list active #555 disabled #111 readonly #000]
>     option add *TCombobox*Listbox.background #333 interactive
>     option add *TCombobox*Listbox.foreground #fff interactive
>     option add *TCombobox*Listbox.selectBackground blue interactive
>     option add *TCombobox*Listbox.selectForeground #fff interactive
>     option add *Listbox.Background #333 interactive
>     option add *Listbox.Foreground #fff interactive
>     option add *Text.Background #333 interactive
>     option add *Text.Foreground #fff interactive
>     ttk::style configure TSpinbox -fieldbackground #333 -background #333 -foreground #fff -insertcolor #fff -arrowcolor #fff
>     .vpane.lower.commarea.buffer.frame.t configure -background #0d1117 -foreground #fff -insertbackground #fff
>     .vpane.lower.diff.body.t configure -background #0d1117 -foreground #fff
>     .vpane.files.workdir.list configure -background #0d1117 -foreground #fff
>     .vpane.files.index.list configure -background #0d1117 -foreground #fff
>     .about_dialog.git_logo configure -background #333
>     ```
> 4. Enjoy Git GUI.

The Git GUI maintainer clearly indicated that these colors should be chosen based on the theme that is currently in effect. So that gives a very clear path forward to a git-gui PR.

And now let's come back to the part of your comment that is easiest to address: Should this ticket be reopened? Nope, it shouldn't. If there is enough interest (by you, or by @birgersp or @Sashank999), you can work on it and open a Pull Request. There is no need to try to beat a dead horse. This ticket had been open without anybody working on it for long enough, there is [no reason to expect any other outcome should we reopen it](https://xkcd.com/1657/).

**Comment by Twisted-Code** [comment]
Sorry, you're right, I probably should have quoted. I had already spent some time to rewrite my comment for this issue instead of the draft I had on the issue I linked, so part of me just wanted to be done writing it. But copy-pasting probably would've taken me like 20 seconds if I had at least thought to do it.

And I suppose I understand, but the fact *neither* PR nor Issue are open made it seem to me, at first glance, like no one is interested at all. That doesn't seem to be quite the case, it's just one of life's many cases of "talk is cheap, show me the code". 

I think I may look into this at some point, if I can figure out enough to fix my existing contrast issue with the provided TCL tweaks (I have no experience with TCL or TK), but I make no promises especially if I am the only one interested in collaborating on it at this point (because I'm probably not skilled enough, yet, to pull off a PR on my own). The tweaks work well enough for me, most of the time, so is anyone else interested in helping? (If replying in a few months -and reading the latest revision of this comment, not the email-, feel free to mention me; I can edit this out if I change my mind)
