### ISSUE TITLE
Set `core.fsyncobjectfiles=batch` will broken some programs still use old version of git(libgit)

### ISSUE THREAD

**Issue by yyjdelete** [git-for-windows/git#3508]
git-for-windows 2.34.0-rc0 introduce an new options `core.fsyncobjectfiles=batch`.

But when I try to set this option, TortoiseGit in the same PC will be broken and report the below message. Is it the expected behavior, or new option key should be introduced for this?

```
Could not get parents of commit "xxxxxx".
libgit reports:
bad boolean config value 'batch' for 'core.fsyncobjectfiles'
```

**Comment by dscho** [comment]
If there is a way to tell TortoiseGit to use your installed Git for Windows, you can use the `batch` mode. Otherwise, unfourtunately it is not possible to use that new setting.

We _might_ want to introduce a new set of conditions for the `[includeIf "<condition>"]` syntax in configs, to conditionally include configs based on the currently-used `git` version's capabilities. But we do not have that facility yet, and the -rc phase is too late to introduce it.
