### ISSUE TITLE
Git Fetch extremely slow due to git-credential-manager-core.exe?

### ISSUE THREAD

**Issue by lugospod** [git-for-windows/git#3531]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.29.2.windows.2
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
WIndows 10 64 bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.1854]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
don't know
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

VDI (virtual machine)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch
```
 - What did you expect to occur after running these commands?

Relatively fast response if there were no changes on Git Server found. 

 - What actually happened instead?

Long time to finish the command. 15 seconds or more and consistently (there is NO CASE that it sometimes finishes faster).

I am attaching tracing two trace logs. One for Git PRotocol 1 and one for Git Protocol 2 because using Protocol 1 is 50% SLOWER then using Protocol 2 for this same scenario - exactly the same parts are slower (same number of lines and traces in both files).
Also attaching git config.

I also tried to change the "credential helper" settings to cache but this just gets ignored and the global manager-core gets used but if I set it to empty string then it prompts me for username/password which sounds like a right thing to do  (but I suppose this should be opened as another issue?).

Current conclusions after analyzing the attached logs:
1. I think the problem is somehow related to Git-Credential-Manager-Core so I included tracing for that application also (the result is also included in the same attached logs)
2. Starting of Git-Credential-Manager-Core executable takes 2 seconds each time? (time difference in the log visible - line 72 & 73)
3. **Why does git fetch call both GET and STORE on credential manager each time it is called? Why does it need to call STORE at all? Due to this, this specific problem time issue is exactly doubled. So if it were only a GET the time would be 50% less.** 
4. In lines 78 & 79 it is visible that a couple of seconds were lost on "something" but couldn't find a reason going through the code of Git-Credential-Manager-Core on GitHub (unfortunately I don't have admin permission on this environment so I can't build my version of this tool and swap it, or install a new version)
5. Half a second is lost in lines 148 & 149 for just returning the result of the command back to git.exe?

I also tried to execute git credential manage core directly, and attached the log below. I executed it using the following command (note that new lines are important!! Snippet ends with three LF in sequence):
`"C:\Program Files\Git\mingw64\libexec\git-core\git-credential-manager-core.exe" get
protocol=https
host=bitbucket.internal.unicreditgroup.eu

`
I would be very grateful if someone can check the logs and the time (just search for a "big difference" in time between lines (everything larger then a half-a-second is a potential "why?".

If any additional information are needed, please let me know.
 
[log_Protocol_1.txt](https://github.com/git-for-windows/git/files/7527333/log_Protocol_1.txt)
[log_Protocol_2.txt](https://github.com/git-for-windows/git/files/7527334/log_Protocol_2.txt)
[git-credential-manager-core.exe.txt](https://github.com/git-for-windows/git/files/7527447/git-credential-manager-core.exe.txt)
[config.txt](https://github.com/git-for-windows/git/files/7527347/config.txt)

**Comment by mjcheetham** [comment]
Hello @lugospod,

I see you've also opened an issue on the GCM Core repository here: https://github.com/microsoft/Git-Credential-Manager-Core/issues/526

> 1. I think the problem is somehow related to Git-Credential-Manager-Core so I included tracing for that application also (the result is also included in the same attached logs)

As I mentioned in that issue, your log shows you are using GCM version 2.0.280, which is pretty old by now. Please can you try updating your version of Git for Windows?

> 2. Starting of Git-Credential-Manager-Core executable takes 2 seconds each time? (time difference in the log visible - line 72 & 73)

GCM is a .NET application, so there is _some_ associated start-up cost for the CLR (.NET runtime). However 2 seconds seems like a lot(!) Do you have any corporate anti-virus software installed that might be slowing things down?
Updating to a later version of Git & GCM should also help perf here.

> 3. Why does git fetch call both GET and STORE on credential manager each time it is called? Why does it need to call STORE at all? Due to this, this specific problem time issue is exactly doubled. So if it were only a GET the time would be 50% less.

This is by design. Git will call credential helpers (any, not just GCM) first with a `get` request, and then follow that up with either a `store` or `erase`. There is no getting away from this without changing the design of Git's credential model.

> 4. In lines 78 & 79 it is visible that a couple of seconds were lost on "something" but couldn't find a reason going through the code of Git-Credential-Manager-Core on GitHub (unfortunately I don't have admin permission on this environment so I can't build my version of this tool and swap it, or install a new version)

I too am not sure what is going on here. It's possible this is either some file I/O that is slow, OR GCM is likely consulting Git for configuration settings by spawning a new process. This can be slow on Windows, and if (as with point 2) there are anti-virus software doing scans of all process launches, this could be it.

> 5. Half a second is lost in lines 148 & 149 for just returning the result of the command back to git.exe?

Again, I'm not sure here. Once GCM gets to the point of saying "end get command" it does very little else except shutdown.

My best bet so far is there is some slow-down in the launching of `git.exe` by GCM to read configuration.

As I mentioned in the GCM issue, I would first start with updating Git for Windows and GCM.
