### ISSUE TITLE
The installer won't allow me to select Visual Studio Code

### ISSUE THREAD

**Issue by dannypike** [git-for-windows/git#3544]
### Setup

Installing Git for windows 2.34.0 x64 on Windows 10.0.19042.1348 x64

### Details

If Visual Studio Code is not installed before I am running the Git for Windows installer, I can't select that as the default editor even though paused the installation of Git and then installed Visual Studio Code before going back to git for Windows.

Can you add a "Refresh" button, so that I can tell the installer to look again at the options that are installed?

**Comment by dscho** [comment]
> If Visual Studio Code is not installed before I am running the Git for Windows installer, I can't select that as the default editor

That is kind of by design.

> Can you add a "Refresh" button, so that I can tell the installer to look again at the options that are installed?

Good idea about adding a "Refresh" button, but a bad idea to ask others to do what you can do yourself! The installer definition is here: https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss and you can build the installer by [downloading the Git for Windows SDK](https://gitforwindows.org/#download-sdk) and running `sdk build installer`. 

The part that discovers the available editors is here: https://github.com/git-for-windows/build-extra/blob/97980b98191a01975484e3b754bd9f0c2b122c9e/installer/install.iss#L1835-L1874

The trickiest part will be to adjust the item descriptions, as they are contingent on the currently available editors, see e.g. [here](https://github.com/git-for-windows/build-extra/blob/97980b98191a01975484e3b754bd9f0c2b122c9e/installer/install.iss#L1881) and [here](https://github.com/git-for-windows/build-extra/blob/97980b98191a01975484e3b754bd9f0c2b122c9e/installer/install.iss#L1907-L1910).

**Comment by dannypike** [comment]
Thanks for the reply. I'm flattered that you think I know how to edit the installer script but, unfortunately, I'm busy trying to learn how to package up a Linux-oriented open source projects for `vcpkg` at the moment.

If I do ever get around to learning how, I'll be happy to add that to my TODO list :)

**Comment by dscho** [comment]
@dannypike I am sure that this ticket will patiently wait for you until you are ready.

**Comment by dscho** [comment]
Or maybe this ticket won't.
