### ISSUE TITLE
PDBs are broken for pdbs-for-git-64-bit-2.34.0.1.7dad2af5e8-1

### ISSUE THREAD

**Issue by neerajsi-msft** [git-for-windows/git#3557]
I'm using xperf/wpa to analyze git-for-windows performance.  I also occasionally using windbg to debug it. 

Looks like PDBs are broken currently.  Seems related to #3488, which seems like a breakage in cv2pdb. 

There are internal errors in the pdb as evidenced by almost no public symbols showing up when running cvdump on mingw\bin\git.pdb.

I'd be happy to investigate further if this isn't a known issue.

Thanks,
-Neeraj

**Comment by rimrul** [comment]
I don't think this is a known issue. #3488 indeed seems like a likely culprit. The PR description of https://github.com/rainers/cv2pdb/pull/67 has a good quick overview of the breakage.

**Comment by dscho** [comment]
> There are internal errors in the pdb as evidenced by almost no public symbols showing up when running cvdump on mingw\bin\git.pdb.

How do I get `cvdump`?

```console
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>cvdump
'cvdump' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by dscho** [comment]
I guess this is it? https://github.com/Microsoft/microsoft-pdb/tree/master/cvdump

**Comment by rimrul** [comment]
> I guess this is it? https://github.com/Microsoft/microsoft-pdb/tree/master/cvdump

That seems to be it

**Comment by neerajsi-msft** [comment]
I'll work on a fix.  I used to be a compiler/linker dev, so I bet this should be easy for me.

**Comment by dscho** [comment]
I investigated this for way more time than I care to admit, and have to take a break for now.

The culprit seems to be that `cv2pdb` interprets all Compilation Units the same way, not even looking at the version number encoded in it. In particular, it does not use the `unit_length` to skip the header ([here](https://github.com/rainers/cv2pdb/blob/v0.49/src/dwarf2pdb.cpp#L1357) and [here](https://github.com/rainers/cv2pdb/blob/v0.49/src/dwarf2pdb.cpp#L1415), and also [misreading `address_size` at potentially the wrong offset](https://github.com/rainers/cv2pdb/blob/v0.49/src/dwarflines.cpp#L182-L183)), assuming that they are all the same size.

However, DWARF5 introduced a new field `unit_type` (to accommodate for the newly-introduced _partial_ Compilation Unit, see 7.5.1.1 in https://dwarfstd.org/doc/DWARF5.pdf and in https://dwarfstd.org/doc/DWARF4.pdf). That makes the assumption incorrect.

I suspect that we will have to introduce hackery similar to [how `cv2pdb` deals with different versions of the line number program header](https://github.com/rainers/cv2pdb/blob/v0.49/src/dwarflines.cpp#L188-L224) to accommodate for different versions of the Compilation Unit header.

**Comment by dscho** [comment]
(Sorry, I forgot to post the previous comment for _hours_.)

**Comment by dscho** [comment]
> I'll work on a fix. I used to be a compiler/linker dev, so I bet this should be easy for me.

Thank you so much!

In the meantime, I added [a workaround](https://github.com/git-for-windows/MINGW-packages/commit/4f745f57d94ac7b5a0013853efda781e18ac3180). Once you fixed `cv2pdb`, I will be just as happy to drop the workaround.

**Comment by dscho** [comment]
> In the meantime, I added [a workaround](https://github.com/git-for-windows/MINGW-packages/commit/4f745f57d94ac7b5a0013853efda781e18ac3180).

I will close this ticket because we have that workaround.

@neerajsi-msft please understand that I am still very much interested in a proper fix for `cv2pdb`. If there is anything I can do to help, please let me know.
