### ISSUE TITLE
Git hangs at the end of a push through SSH

### ISSUE THREAD

**Issue by CharlesB2** [git-for-windows/git#369]
With Git 2.5.1 64-bit on Win7, I have systematic hang at the end of a push, with a "remote:   % Total    % Received etc." transfer staying at 0 progress forever. I then have to kill the process and delete the lock. Fetching it shows that the push has been successful.

With Git-1.9.5-preview20141217 and before, this transfer output wasn't appearing, I have no idea what it is about.

```
$ git push -v origin
Pushing to xxx@xxxx:/git/lightct.git
Password:
Counting objects: 2, done.
Delta compression using up to 6 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 223 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote:   0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0Killed by signal 2.
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
```

**Comment by dscho** [comment]
This is not enough information to help effectively, but I will try to guess as about the causes and leave it to you to investigate in detail.

The suspicious lines are prefixed with `remote:`, meaning that the problem is not *your* machine, but the server. It most likely has a hook installed that is triggered by the push, and its output either confuses Git or is an indicator of a problem on the remote side.

The output looks like `curl` being run in non-silent mode, and it looks like it got "Killed" due to a time-out.

Now, my *guess* is that some very, very clever person installed a hook on the remote side that tries to interact with some web service's API in a very, very clever way, and then fails in a very, very dumb way due to a time-out of *that* web service.

Good hunting!

**Comment by CharlesB2** [comment]
Thanks a lot Johannes, indeed it was a curl command in the post-receive hook. Sorry for the noise!
