### ISSUE TITLE
Could perldoc be added to the distribution?

### ISSUE THREAD

**Issue by scottdotjs** [git-for-windows/git#3735]
[✔] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I'm using Git Bash in Git for Windows v2.34.1, on 64-bit Windows 10. The distribution comes with Perl, but not the [`perldoc`](https://perldoc.perl.org/perldoc) utility for reading [POD](https://perldoc.perl.org/perlpod) in Perl files.

Test case:
```perl
#!/usr/bin/perl
# this is example.pl

=head1 Example of POD

Lorem ipsum dolor sit amet.

=cut
```

Received:
```
scott@Laptop MINGW64 ~/code
$ perldoc example.pl
bash: perldoc: command not found   
```

Expected (this output is from using [Strawberry Perl](strawberryperl.com/)'s Perl in the Windows command prompt):
```
C:\Users\scott\code>perldoc example.pl
Example of POD
    Lorem ipsum dolor sit amet.
```

I've made this shell function to use Strawberry's `perldoc` from Git Bash, but it would be nice if `perldoc` were to be added to the Git for Windows distribution to avoid needing Strawberry installed as well.

```shell
function perldoc() {
    getperldoc="set PATH=C:\Strawberry\perl\bin;%PATH% && C:\Strawberry\perl\bin\perldoc.bat `pwd`/$1";
    cmd //C $getperldoc
}
```

For your reference, this is Strawberry's `perldoc.bat` - it's just a wrapper around [Pod::Perldoc](https://metacpan.org/pod/Pod::Perldoc).

```batch
@rem = '--*-Perl-*--
@echo off
if "%OS%" == "Windows_NT" goto WinNT
perl -x -S "%0" %1 %2 %3 %4 %5 %6 %7 %8 %9
goto endofperl
:WinNT
perl -x -S %0 %*
if NOT "%COMSPEC%" == "%SystemRoot%\system32\cmd.exe" goto endofperl
if %errorlevel% == 9009 echo You do not have Perl in your PATH.
if errorlevel 1 goto script_failed_so_exit_with_non_zero_val 2>nul
goto endofperl
@rem ';
#!perl
#line 15
    eval 'exec C:\STRAWB~1\perl\bin\perl.exe -S $0 ${1+"$@"}'
	if 0;

# This "perldoc" file was generated by "perldoc.PL"

require 5;
BEGIN {
    $^W = 1 if $ENV{'PERLDOCDEBUG'};
    pop @INC if $INC[-1] eq '.';
}
use Pod::Perldoc;
exit( Pod::Perldoc->run() );


__END__
:endofperl
```

**Comment by fourpastmidnight** [comment]
The main purpose for the existence of GfW is to provide a working Git implementation on Windows. Since there are a few git utilities that depend on Perl, it is included with GfW. But GfW is not intended to be specifically a Perl development environment, nor generally a programming environment at all.

I can offer a few suggestions to help you:

1. Install Cygwin, a *nix-like environment on Windows where you can choose to install things, like Git, and Perl with the perldocs.
2. Use WSL and install a Linux distro from the Microsoft Store, such as Ubuntu or OpenSuse, where likewise you can install a variety of *nix tools.

Hth.

Sent from Surface Duo
________________________________
From: Scott Martin ***@***.***>
Sent: Sunday, March 13, 2022 9:40:58 AM
To: git-for-windows/git ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [git-for-windows/git] Could perldoc be added to the distribution? (Issue #3735)


[✔] I was not able to find an open<https://github.com/git-for-windows/git/issues?q=is%3Aopen> or closed<https://github.com/git-for-windows/git/issues?q=is%3Aclosed> issue matching what I'm seeing

I'm using Git Bash in Git for Windows v2.34.1, on 64-bit Windows 10. The distribution comes with Perl, but not the perldoc<https://perldoc.perl.org/perldoc> utility for reading POD<https://perldoc.perl.org/perlpod> in Perl files.

Test case:

#!/usr/bin/perl

# this is example.pl



=head1 Example of POD



Lorem ipsum dolor sit amet.



=cut

Received:

***@***.*** MINGW64 ~/code

$ perldoc example.pl

bash: perldoc: command not found



Expected (this output is from using Strawberry Perl<strawberryperl.com/>'s Perl in the Windows command prompt):

C:\Users\scott\code>perldoc example.pl

Example of POD

    Lorem ipsum dolor sit amet.



I've made this shell function to use Strawberry's perldoc from Git Bash, but it would be nice if perldoc were to be added to the Git for Windows distribution to avoid needing Strawberry installed as well.

function perldoc() {

    getperldoc="set PATH=C:\Strawberry\perl\bin;%PATH% && c:\Strawberry\perl\bin\perldoc.bat `pwd`/$1";

    cmd //C $getperldoc

}

**Comment by scottdotjs** [comment]
As mentioned, I have Strawberry Perl installed already which offers a development environment for Perl if needed. The context of this suggestion was to facilitate those who may occasionally have to run Perl programs inside Git Bash. OK, thanks.

**Comment by dscho** [comment]
The purpose of [Git for Windows](https://git-for-windows.github.io/) is really to bring *Git* to Windows.

While that implies that we have to ship quite a few Unix-like tools, it does not mean that we will include such tools unless they are needed for Git's own operations, or at least for historical reasons (needs of active contributors are sometimes a factor in deciding whether to include a tool or not).

Having said that, what you really are looking for is [MSYS2](https://msys2.github.io/). Git for Windows leverages MSYS2 and ships with a subset of its files. MSYS2 even sports a package management system called "pacman" to install more tools (including Git...), so why don't you give it a whirl?
