### ISSUE TITLE
the process 'git for windows' called by 'IntelliJ IDEA' keeps high CPU usage for a long time

### ISSUE THREAD

**Issue by sodaRyCN** [git-for-windows/git#3736]
#### git for windows version
![git_for_windows_version](https://user-images.githubusercontent.com/35725024/158155328-08996d63-933e-4d88-8627-464fec4ae4ab.png)

#### windows version
windows 10 64 bit
![企业微信截图_16472542245674](https://user-images.githubusercontent.com/35725024/158155796-a7253301-d8db-47d3-8c6e-125a0e2e2334.png)

#### options of the installation

![企业微信截图_1647254433700](https://user-images.githubusercontent.com/35725024/158156241-4a036a16-14c5-4557-a1a1-8804c4b3d5b3.png)

#### and git config --global has none special options, just only email and name

Problem:
When I use IntelliJ IDEA, it will pull up the git for windows process, which will keep at least 10% CPU usage (until I close the git process  in the task manager of windows10 or restart the computer, otherwise git process will remain in this state.)

####git process cpu usages
![企业微信截图_16469824201555(2)](https://user-images.githubusercontent.com/35725024/158194167-7421b0e9-b89d-4eb7-b294-a98b2cbf2dac.png)

####windows wpa
You can find the original elt file and git's pdb [here](https://github.com/sodaRyCN/issue/tree/main/git)
![image](https://user-images.githubusercontent.com/35725024/158198662-28648a9f-5a2b-4eac-a51e-c478a95f7d6a.png)

####idea used git options
![企业微信截图_16472698471842](https://user-images.githubusercontent.com/35725024/158199045-86e62bed-8893-473e-aeb3-7919920bec80.png)

**Comment by dscho** [comment]
Could you find out the full command-lines of those processes? (Use `wmic process where processid=23876 get commandline` in a PowerShell, with the correct Process ID, to find out)

**Comment by sodaRyCN** [comment]
![企业微信截图_16473088181603](https://user-images.githubusercontent.com/35725024/158289672-0709d31f-8000-48d7-99d2-c3eac9677366.png)

**Comment by dscho** [comment]
That is most likely IDEA's fault: the FSMonitor is busy when either file system events occur, or when `git status` is called.

The former should be quiet most of the time.

Now, why would `git status` be called all the time?

Most likely because the FSMonitor writes a "cookie file" before answering the `git status` request, and then collects all file system events until it sees that cookie file, before sending the answer.

There has been an instance where VS Code incorrectly reacted to that cookie file, thinking that something in the worktree has changed, and therefore requesting a new `git status`. But the cookie file is inside `.git/`, i.e. _not part_ of the worktree.

It is likely that IntelliJ suffers the same bug.

Until that is fixed, the only workaround seems to be to set `core.useBuiltinFSMonitor` to `false` (at least in the repository config).

**Comment by sodaRyCN** [comment]
thanks for your reply. 

according to your suggestion, I set core.useBuiltins FSMonitor to FALSE, and my problem is solved. At the same time, I guess using a lower version git (before 2.3.1, this monitor capability was not provided) can also solve this problem.

![image](https://user-images.githubusercontent.com/35725024/158328024-fbc084e3-5b7b-41d7-b3d8-a4df6a052bd8.png)

#### But
I don't understand why this is the error of the IDEA, is it because the idea causes the FSMonitor to be busy or should not use this experimental feature？And I noticed that `fsmonitor--daemon` is provided by version 2.3.1, until the version 2.33 I am currently using, it is still described as an experimental function , may even be deprecated.

![image](https://user-images.githubusercontent.com/35725024/158328266-80d6ff42-9d8d-47ed-b8ae-2ad4ae91624f.png)

**Comment by dscho** [comment]
> I don't understand why this is the error of the IDEA, is it because the idea causes the FSMonitor to be busy or should not use this experimental feature？

IntelliJ probably detects file changes (including added files) in the worktree, and calls `git status` to update its internal representation of the state of the tracked files.

The problem is that it probably also detects the added cookie file inside `.git/`. This cookie file is _not_ part of the worktree, though, and therefore IntelliJ should refrain from running `git status`. But it apparently doesn't.

This is just supposition on my part, as I have no idea about IntelliJ's internals. But given that we had the exact same problem with VS Code, I think it is the likely root cause.

**Comment by sodaRyCN** [comment]
I got it .
thanks again.

**Comment by dscho** [comment]
BTW the FSMonitor is not deprecated, it is still under active development (and still experimental, as things like config setting names are expected to change).
