### ISSUE TITLE
git clone does not prompt for password on stderr redirects

### ISSUE THREAD

**Issue by christian-monch** [git-for-windows/git#3748]
- [x] I was able to find two issues that seem to be related, #327, #760
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 Not to my knowledge

### Details

The problem is that, iff `stderr` is redirected, `git clone` from an ssh-repository-address does not prompt for passwords. Instead, it seems to "read" some invalid data and fails to authenticate towards the ssh server (obviously)..

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 The observed problem occurs in git-bash, PowerShell, and when running `git clone` from python submodule, iff stderr is redirected.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# 192.168.178.20 is a local host with an ssh-server running on port 22
$ unset SSH_ASKPASS
$ git clone 192.168.178.20:/erwerwer 2>ssh.log
```
 - What did you expect to occur after running these commands?

I expected `git` to prompt for a password. 

 - What actually happened instead?

Git seems to "read" some invalid data and fails to authenticate towards the ssh server. It never prompts for a password.

**Interestingly** this error only occurs with the bundled ssh-client, i.e. `\Program Files\Git\usr\bin\ssh.exe`. The problem does not occur if git uses OpenSSH for Windows' client, i.e. `\Windows\System32\OpenSSH\ssh.exe`.

**Comment by dscho** [comment]
The root cause for this issue is that `/usr/bin/ssh.exe` uses MSYS2's POSIX emulation layer ("MSYS2 runtime") to communicate with an emulated pseudo terminal, but `git.exe` is not an MSYS program and therefore the connection to the MSYS2 runtime instance is lost somewhere along the call chain between Git Bash calling `git.exe`, `git.exe` spawning other Git processes, and one of those processes calling the MSYS OpenSSH.

Maybe `winpty git clone ... 2>ssh.log` works around the problem?

**Comment by christian-monch** [comment]
Thank you very much for your help and the explanation. That means for us, that we will use OpenSSH for windows to ensure interoperability.

Also `winpty` is a great tool, we cannot use it in in our case because we need to capture `stdout` and `stderr` of the running `ssh` process (which is not possible with `winpty` according to my understanding).

Thanks a lot again, from my side the issue could be closed.

**Comment by dscho** [comment]
> That means for us, that we will use OpenSSH for windows to ensure interoperability.

You did notice the option in the installer, right?

![image](https://user-images.githubusercontent.com/127790/161761977-8b017d59-0ae5-4a7e-89c1-3b89ba46c30e.png)


> Also `winpty` is a great tool, we cannot use it in in our case because we need to capture `stdout` and `stderr` of the running `ssh` process (which is not possible with `winpty` according to my understanding).

That is true.

> Thanks a lot again, from my side the issue could be closed.

Okay, done!

**Comment by dmichal** [comment]
This problem does not seem to be SSH specific. I experience exactly the same behaviour when cloning repository via HTTP from cmd.exe and with wincred disabled. The minimal command to reproduce the bug is:
`git clone https://github.com/dmichal/test_stderr_clone 2>clone.log`
Then the contents of `clone.log` are:
> Cloning into 'test_stderr_clone'...
> bash: /dev/tty: No such device or address
> error: failed to execute prompt script (exit code 1)
> fatal: could not read Username for 'https://github.com': No such file or directory
Calling `git clone` with redirected stderr while expecting a prompt for credentials may seem as an imaginary usecase, but in my case the problem also occurs when trying to recursively clone a repository with submodules hosted in private repositories. In such a case, the parent repository is cloned successfully, but cloning submodules fails with exactly the same error as above instead of prompting for credentials (I must admit, however, that I'm not sure if in the latter case the `git` command to clone the submodules is called with redirected output or not).
