### ISSUE TITLE
fatal: fsmonitor--daemon doesn't support --super-prefix

### ISSUE THREAD

**Issue by czg-sci-42ver** [git-for-windows/git#3805]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```bash
$ git --version --build-options
git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```bash
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.613]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```bash
PS C:\WINDOWS\system32#  type "D:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details
- Efforts I made simply . 
  -   I checked the [git source codes](https://github.com/git/git/blob/master/git.c) and there are three occurance of **doesn't support --super-prefix**, which all are `die` output version 
      -   but didn't see how `fatal:` triggered . Could anyone **help** me, many thanks 
      -  I think the [run_builtin]((https://github.com/git/git/blob/4027e30c5395c9c1aeea85e99f51ac62f5148145/git.c#L453)) output the error because the rest two are output `argv` not `fsmonitor--daemon`. Am I right? **please** tell me,many thanks 

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```bash
$ bash --version
bash --version
GNU bash, version 4.4.23(2)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
history -a;

PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22000.613
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.613
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

    - `bash` output 
```bash
$ git diff
diff --git a/proxy_clash_template2.yaml b/proxy_clash_template2.yaml
index 51d38c2..aa63801 100644
--- a/proxy_clash_template2.yaml
+++ b/proxy_clash_template2.yaml
@@ -230,7 +230,7 @@ proxies:
 - name: "v2ray1_US"
   type: vmess
   # server:  ... .94
-  server:  ... .167
+  server:  ... .3
   # server:  ... .123
   port: 8612
   uuid: ...
$ pwd
/c/Users/czg/Desktop/scientific_net/clash_config/clash_rule
$ git reset --hard HEAD
Migrating git directory of 'clash_rule' from
'.../clash_rule/.git' to
'.../.git/modules/clash_rule'
fatal: fsmonitor--daemon doesn't support --super-prefix
fatal: fsmonitor--daemon doesn't support --super-prefix
HEAD is now at ...... modified
```
 - What did you expect to occur after running these commands?

    - not make submodule git `.git` repository disappear 

** insert here **

 - What actually happened instead?
```bash
$ pwd
/c/Users/czg/Desktop/scientific_net/clash_config/clash_rule
$ cat .gitmodules
[submodule "clash_rule"]
        path = clash_rule
        url = git@gitee.com:.../clash_rule.git
        ignore = all

$ ls .git/modules/clash_rule/
COMMIT_EDITMSG  FETCH_HEAD         hooks  logs       packed-refs
config          fsmonitor--daemon  index  objects    refs
description     HEAD               info   ORIG_HEAD

$ ls clash_rule/.git
clash_rule/.git

$ ls clash_rule/.git/
ls: cannot access 'clash_rule/.git/': Not a directory

czg@DESKTOP-O0JBM8G MINGW64 ~/Desktop/scientific_net/clash_config (master)
$ cd clash_rule/

czg@DESKTOP-O0JBM8G MINGW64 ~/Desktop/scientific_net/clash_config/clash_rule ((49a37d2...))
$ git status
HEAD detached from 720cbd3
nothing to commit, working tree clean

czg@DESKTOP-O0JBM8G MINGW64 ~/Desktop/scientific_net/clash_config/clash_rule ((49a37d2...))
$ git remote -v
origin  git@gitee.com:.../clash_rule.git (fetch)
origin  git@gitee.com:.../clash_rule.git (push)
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

     - sorry  this is a private  repository and there are some Sensitive Data

**Comment by jeffhostetler** [comment]
Hello.  Could you try setting GIT_TRACE2_PERF to the absolute pathname of a file and trying again.  That will log detailed information about the processes involved.  The output from all of the processes will be a bit intertwined, but the Dx column should help you figure out the parents and children.  Alternatively, set that env var to a directory and each command will log to an individual file.

The "fatal: ..." message is generated by die()  (see die_message_builtin() and some function pointer trickery in usage.c)

I suspect (but haven't confirmed) that your `git reset` command is doing a recursive command inside the submodule (and it is receiving the --super-prefix argument) and that child is calling run_builtin to start the fsmonitor inside the submodule and is passing the super prefix argument to `git fsmonitor--daemon start`.  And that is what is complaining.

WRT 'clash_rule/.git' disappearing.  Look in '.git/modules/clash_rule'.  It looks like the first command tried to normalize
the location of the submodule's .git directory.   It's hard to tell from the output here, but I'm guessing that reset was
trying to normalize things and died prematurely because of the fatal error and maybe left things in a half done state.
(again, i'm guessing here.)

**Comment by jeffhostetler** [comment]
I was not able to reproduce the problem using `git reset --hard HEAD`.  But I was able to reproduce it by:
1. Creating a submodule with an inline .git directory (rather than in the super's `.git/modules` directory)
2. Setting `core.fsmonitor` to `true` in the submodule.
3. Running `git submodule absorbgitdirs` in the super.

This visits each submodule and tries to convert from an inline gitdir to with their .git directory in the super's .git/modules.
The recursive call into the submodule uses `submodule--helper absorb-git-dirs`.  That command needs to read the index and that automatically starts `fsmonitor--daemon` if it isn't already running.  That attempt to start it some how inherits the --super-prefix argument and causes the error.

I'll dig into this.

Thanks for the report!

**Comment by jeffhostetler** [comment]
I am submitting a fix for the stray warning to upstream (core) Git.
https://github.com/gitgitgadget/git/pull/1143

WRT how the .git directory was moved for the submodule, I'm not sure how you
got into that code path, but it looks like that it working as designed.  Git prefers
for submodules to have their .git directories be in the super's .git/modules directory.
Again, I'm not sure why it decided to move it, but the worktree should still work for
you.
