### ISSUE TITLE
Windows version 2.36.0 breaks hooks when pushing to a bare repository located on a DFS

### ISSUE THREAD

**Issue by Balkoth** [git-for-windows/git#3825]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.1415]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Bare repositories with hooks are located on a Windows DFS.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push
```
 - What did you expect to occur after running these commands?

As with version 2.35.3 i expect the hooks in the bare repository to run.

 - What actually happened instead?

```
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Writing objects: 100% (3/3), 248 bytes | 124.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
remote: sh: hooks/post-receive: Too many levels of symbolic links
To I:/SourceControl/Sharepoint/Test.git
   e8ccdf4..03d48af  master -> master
```

As shown here, the hook 'post-receive' did not run, while downgrading to 2.35.3 executes the hook successfully. I don't know which information is needed in order to solve the issue, but will be looking to provide any of them if asked.

**Comment by Balkoth** [comment]
Same problem:

```
$ cd /i/
bash: cd: /i/: Too many levels of symbolic links
```

**Comment by Narrat** [comment]
Still necessary to open a dedicated issue, or will this be renamed? Want to avoid to open a duplicate.
But nevertheless my informations:

 - [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing
Partially: I found the related error message after searching the repo in #3669. But mentioned as something that should be resolved for virtualized environments

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19044.1682]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

This happens with the Bash. Either running on its own or via the Windows terminal.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Changing the working directory to a network drive doesn't work anymore like with previous git-for-windows versions (latest working version: 2.35.3) and fails with `Too many levels of symbolic links`.

```
$ cd /u
bash: cd: /u: Too many levels of symbolic links
```
 - What did you expect to occur after running these commands?

A succesfull change of the working directory

 - What actually happened instead?

It fails with the above mentioned error message. But in general it seems to be possible, as a Bash can be opened on a network drive with `Git Bash here`. Displayed as expected as:
```
<user>@<host> MINGW64 /u
$
```
Switching to different local drives still works:
```
<user>@<host> MINGW64 /
$ cd /d

<user>@<host> MINGW64 /d
$

```

As I was asked to report what happens with cygwin: I simply installed the base setup. Assuming the checked behaviour should be set as default, this happens when I try to switch to a network drive:
```
$ cd /u
-bash: cd: /u: No such file or directory
```
But as it also fails with the local drive `/d` I assume I need to do something additional which I'm not aware of.

**Comment by dscho** [comment]
@Balkoth in Cygwin, you need to `cd /cygdrive/i/`

**Comment by Balkoth** [comment]
```
$ cd /cygdrive/i/
-bash: cd: /cygdrive/i/: Too many levels of symbolic links
```

**Comment by dscho** [comment]
Okay, that confirms that this is a Cygwin problem.

Could you download https://github.com/git-for-windows/msys2-runtime/suites/5723433653/artifacts/189221093 and replace your existing `C:\Program Files\Git\usr\bin\msys-2.0.dll` with the one contained in the downloaded archive? It is a build that integrates some fixes that are not yet included in any official Cygwin version but will be in v3.3.5.

**Comment by Balkoth** [comment]
I can confirm that changing into the drive as well as calling the hooks works with the dll you provided.

**Comment by dscho** [comment]
> I can confirm that changing into the drive as well as calling the hooks works with the dll you provided.

Hooray! I guess we'll need to build a new MSYS2 runtime soon ;-)
