### ISSUE TITLE
git-for-windows changes from 2.35.3 to 2.36.0

### ISSUE THREAD

**Issue by rpier1** [git-for-windows/git#3838]
Hi, we're having severe problems with extremely slow performance on `git 2.36.0` (huge repo with sparse-checkout and local hook scripts)

I have a simple question which might be related?

Why does the following
https://github.com/git-for-windows/git/compare/v2.35.3.windows.1...git-for-windows:v2.36.0.windows.1
only list 35 changed files,

while this
https://github.com/git/git/compare/v2.35.3...v2.36.0
lists 596 changed files?

Is there stuff missing from the windows release? (just suspiciously curious)

Thanks.

**Comment by dscho** [comment]
> Why does the following [v2.35.3.windows.1...git-for-windows:v2.36.0.windows.1](https://github.com/git-for-windows/git/compare/v2.35.3.windows.1...git-for-windows:v2.36.0.windows.1) only list 35 changed files,
> 
> while this [git/git@v2.35.3...v2.36.0](https://github.com/git/git/compare/v2.35.3...v2.36.0) lists 596 changed files?

You probably want the `..` form, not the `...` form: The former gives you the differences between the two specified revisions, the latter first tries to find a merge base and then compares the right side against that. And due to the shape of Git for Windows' commit history (we use ["merging-rebases"](https://github.com/git-for-windows/build-extra/blob/19c17738d6ef48cbfaa4c3d286a9fed4e01ca9aa/shears.sh#L12-L18)) the output is misleading.

A better idea would be to look through the [snapshots](https://wingit.blob.core.windows.net/files/index.html) (which include full releases as long as they were built from the `main` branch, which v2.35.2 and v2.35.3 were _not_) to see whether they pin-point the performance regression more.

My guess is that the regression was introduced with v2.36.0-rc0, in which case we will have to dig in deeper and bisect from there. But let's verify that hypothesis before getting into that rabbit hole.

**Comment by PhilipOakley** [comment]
Hi @rpier1, Just note that (as I recall) 2.35.2 was a special maintenance release that just had the safe.directory CVE fixes on the v2.35 track (and nothing else), while 2.36 has all the regular git release aspects between 35 and 36.

**Comment by rpier1** [comment]
> You probably want the `..` form, not the `...` form: The former gives you the differences between the two specified revisions, the latter first tries to find a merge base and then compares the right side against that. And due to the shape of Git for Windows' commit history (we use ["merging-rebases"](https://github.com/git-for-windows/build-extra/blob/19c17738d6ef48cbfaa4c3d286a9fed4e01ca9aa/shears.sh#L12-L18)) the output is misleading.

Thanks you're right!

I'm closing this issue. I've opened up this one instead: https://github.com/git-for-windows/git/issues/3840

**Comment by rpier1** [comment]
> My guess is that the regression was introduced with v2.36.0-rc0, in which case we will have to dig in deeper and bisect from there. But let's verify that hypothesis before getting into that rabbit hole.

Yes indeed, that's true! I tried `git diff` with our huge sparse repo and it takes ages with `PortableGit-2.36.0-rc0-64-bit.7z.exe` ; 
but is quick with the previous version (`PortableGit-prerelease-2.35.1.windows.2-7-g158a30d60b-20220224121117-64-bit.7z.exe`)
