### ISSUE TITLE
global ignore "ignored" on Win7

### ISSUE THREAD

**Issue by Laro88** [git-for-windows/git#392]
Git 2.5.2 (and NTVS and GitExtensions 2.48.05 ) refuses the global .gitignore file
```
git config --global core.excludesfile "%USERPROFILE%\.gitignore"
```
%USERPROFILE% is correct when echoing it - it is it username without any endings like \ or /
Tried with and without " however the .gitignore is ignored :-)
.gitignore next to .git folder is processed normally.
```
Echo "%USERPROFILE%\.gitignore" is displaying the correct "c:\Users\u45632\.gitignore"
```

**Comment by dscho** [comment]
Did you try that from Git Bash or Git CMD? Does your `%USERPROFILE%` end in a slash or not?

**Comment by dscho** [comment]
> Did you try that from Git Bash or Git CMD?

Still open question.

Oh, and BTW, please do not edit comments and expect anybody to notice. The proper way to answer questions and add new information is to *add* new replies.

**Comment by Laro88** [comment]
It was Git CMD

**Comment by dscho** [comment]
If you start *Git Bash*, what do the commands `grep excludes ~/.gitconfig` and `echo $HOME` print?

**Comment by Laro88** [comment]
grep results in ```excludesfile = C:\\Users\\u320683\\.gitignore```
$HOME just gives ```/p```

**Comment by dscho** [comment]
So your `HOME` is `P:\` but your `USERPROFILE` is `C:\Users\u320683`?

In any case, I would highly recommend to follow the advice in [our guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines), in particular the note about *Minimal, Complete and Verifiable Examples* and *further inspiration* because I find myself in a very frustrating position where you clearly encounter a problem but I have by far not enough information to replicate the issue or otherwise understand what is going on.

So here is a step-by-step illustration what I did:

```sh
$ touch a1.patch

me@work MINGW64 /usr/src/git (master)
$ echo a1.patch > ~/.gitignore

me@work MINGW64 /usr/src/git (master)
$ git config --global core.excludesfile

me@work MINGW64 /usr/src/git (master)
$ git config --global core.excludesfile "$HOME/.gitignore"

me@work MINGW64 /usr/src/git (master)
$ git status | grep a1.patch

me@work MINGW64 /usr/src/git (master)
$ git config --global --unset core.excludesfile

me@work MINGW64 /usr/src/git (master)
$ git status | grep a1.patch
        a1.patch
```

As you can see, everything is working just dandy here. So something must be different between your and my setup. Since my setup is pretty much bog standard (I did not fiddle with environment variables, installation location or user profile, everything is still as pristine as when I logged in the first time after the Windows 10 installation) it must be something on your computer. Of course I could now start guessing... But certainly you are not asking me to do that.

**Comment by dscho** [comment]
@Laro88 no feedback? No testing the same explicit commands I did? Is this no longer a problem?
