### ISSUE TITLE
Installer Release Notes is not accurate

### ISSUE THREAD

**Issue by neolib** [git-for-windows/git#3924]
I downloaded Git-2.37.0-64-bit.exe and intalled it as usual.

1. The Release Notes say it comes with cURL 7.84, but actually what I got is cURL 7.83.1.

2. The 32-bit installer also has same problem with an additional small issue - the bundled nano editor is left behind for a long time (v5.8).

**Comment by rimrul** [comment]
> I downloaded Git-2.37.0-64-bit.exe and intalled it as usual.
> 
> 1. The Release Notes say it comes with cURL 7.84, but actually what I got is cURL 7.83.1.

I think the issue here is that the release notes get updated immediately when the new packages are successfully built, but the sdk is only updated about once per day or so, so the new release was built with an sdk that didn't have the new curl packages yet.

> 2. The 32-bit installer also has same problem with an additional small issue - the bundled nano editor is left behind for a long time (v5.8).

That's probably the [same issue as discussed here](https://github.com/git-for-windows/git/issues/3450#issuecomment-938545960).

**Comment by dscho** [comment]
@rimrul excellent diagnosis. This is [indeed the case](https://github.com/git-for-windows/git-sdk-64/commit/bb783c9144d6daecba9bbfc08eb80e3fb9b47d66): I simply forgot to kick off the `sync` workflows, my bad.

I figure that there will be a v2.37.1 soon (I provided [a bug fix for a regression yesterday](https://github.com/gitgitgadget/git/pull/1273), and more bug fixes might trickle in, which will probably lead to a bug fix version within the next few weeks), which will have the correct cURL version.

Unfortunately, I cannot fix the release notes in the installer now, so I will close this ticket. I can promise, though, to be more careful in the future about component updates that come in the same day as official releases are happening.
