### ISSUE TITLE
Installing a new version deletes configuration data

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#395]
Edits /etc/<anything> should be preserved when installing a new version. The entire directory is currently deleted and recreated when installing a new version.

**Comment by dscho** [comment]
It is only deleted if it is empty, after removing the files that the installer thinks it owns.

**Comment by orgads** [comment]
What if I modified e.g. inputrc? or profile? or vimrc?

**Comment by dscho** [comment]
Those are system files and are fair game when you update. If you want to override them, you need to use the files `$HOME/.inputrc`, `$HOME/.profile`, `$HOME/.vimrc` and if need be, add a new file of your own to `/etc/profile.d/*`.

There is also a good chance that your local configurations may be useful to other users; in that case, the appropriate fix is to offer the configuration as part of the installer (so that the changes are re-applied with the next upgrade).

**Comment by orgads** [comment]
Ok, I realize this is complicated to solve (we would need an apt-like mechanism). I accept your approach.
