### ISSUE TITLE
CVE-2022-24765  : 'Git GUI Here' launches on directory as if it has no Git repo

### ISSUE THREAD

**Issue by nomennescio** [git-for-windows/git#3956]
(Same environment as https://github.com/git-for-windows/git/issues/3955)

Launching 'Git GUI Here' from the context menu on that directory, will not launch Git GUI regularly, but instead it starts as if no repository is present in that directory, with the options to : Create New|Clone Existing|Open Existing Repository.
No error message is shown.

**Comment by dscho** [comment]
@nomennescio this report was unnecessarily unclear. My initial reaction was: What exactly does this have to do with [CVE-2022-24765](https://github.com/git-for-windows/git/security/advisories/GHSA-vw2c-22j4-2fh2)?

As this is not a Windows-specific issue, it would make a lot of sense to take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently). In preparation for that, I will close this here ticket.

When you do report it to the Git mailing list, keep in mind what I just said: the bug report needs to be a lot clearer than "same environment as ...", otherwise I fear that the report will be simply ignored.
