### ISSUE TITLE
Cannot generate ssh keys

### ISSUE THREAD

**Issue by stenw** [git-for-windows/git#3964]
ssh-keygen from git bash returns the error: "gethostname: Bad address". (also when I use the full path).
When I directly start the program from windows it works. 
The issue was not solved by reinstalling git.

### Setup

```
Windows 10 64 bit [Version 10.0.19043.1865]

git version 2.37.1.windows.1
cpu: x86_64
built from commit: 323a69709944b193bb5cee81ff09fe9a4a686df5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

**Comment by dscho** [comment]
> ssh-keygen from git bash returns the error: "gethostname: Bad address". (also when I use the full path).

I cannot reproduce:

```console
$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/c/Users/me/.ssh/id_rsa): /c/Users/me/.ssh/id_test
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /c/Users/me/.ssh/id_test
Your public key has been saved in /c/Users/me/.ssh/id_test.pub
The key fingerprint is:
SHA256:6GHRx1CTGaNbRmJ/FMtM+vku1HSfv0Xwg+2YHt4tIzY me@work
The key's randomart image is:
+---[RSA 3072]----+
|        +.*++.   |
|       o BoO .   |
|      . o B = .  |
|       o = o .+o.|
|      + S   o+ +=|
|     o .    ..=oo|
|      .    . +..o|
|            E.= +|
|           . *.=o|
+----[SHA256]-----+
```

Maybe throwing in a couple of `-v` options (which [the documentation](https://www.man7.org/linux/man-pages/man1/ssh-keygen.1.html) suggests will make the output more verbose) before trying again will shed some light into it?

**Comment by stenw** [comment]
I cannot also not reproduce this on other machines and it did work before. It shows up since I closed the window mid-operation. Adding verbosity does not help
$ ssh-keygen -v
gethostname: Bad address

$ ssh-keygen -vvv
gethostname: Bad address

**Comment by dscho** [comment]
> I cannot also not reproduce this on other machines and it did work before. It shows up since I closed the window mid-operation.

Aha! That changes things. Since you closed the window mid-operation, maybe there is a stray `ssh-agent` process that is still active?

**Comment by dscho** [comment]
> maybe there is a stray `ssh-agent` process that is still active?

Could also be a stray `dirmngr` process.

**Comment by stenw** [comment]
I cannot see ssh-agent nor dirmngr being active. (if they were still open after closing the window I guess they were stopped when I rebooted later).

**Comment by dscho** [comment]
> I guess they were stopped when I rebooted later

🤣 yes, that would be a safe assumption 🤣

**Comment by russele7** [comment]
Dear all, I got the same problem.

 <<
ruslan@DESKTOP-HKSF00V MINGW64 ~/Desktop
$ ssh-keygen
gethostname: Bad address
>>

System: Windows 10 Pro /  21H2 / 19044.1889 / Windows Feature Experience Pack 120.2212.4180.0
Git: git version 2.37.3.windows.1  (for win64)

I clarify the situation:
After installing git and tried "ssh-keygen" and got "gethostname: Bad address". Then I restarted my computer and tried again. This time after ssh-keygen I got the correct output, which is what it should be. But instead of pressing Enter, I closed the bash window (there was a warning box, but I ignored it and closed anyway). Then I re-opened git bash => entered “ssh-keygen” => and then the “gethostname: Bad address” error came up again. And I couldn't fix it. I've tried reinstalling git - doesn't help. I tried installing git for win 32 - it does not output anything at all when executing the "ssh-keygen" command.
What I noticed. After reinstalling git, I still have the font size settings I made in the bash window (I increased the font for readability). Perhaps after uninstalling and reinstalling git, some settings are not reset and this is the problem?

Please help me solve the problem.

**Comment by dscho** [comment]
Judging by the account in https://github.com/git-for-windows/git/issues/3842, this might indeed be an environment problem, and a work-around might be to start `ssh-keygen` from a Windows prompt instead of Git Bash.

**Comment by dscho** [comment]
I'll go with the assumption that my advice of over two years (!) ago was helpful.

**Comment by stenw** [comment]
> I'll go with the assumption that my advice of over two years (!) ago was helpful.

Actually I still have this issue and I gave up

**Comment by dscho** [comment]
> a work-around might be to start `ssh-keygen` from a Windows prompt instead of Git Bash.

And that still does not work for you?
