### ISSUE TITLE
cd // producing odd behavior

### ISSUE THREAD

**Issue by AAckerlund** [git-for-windows/git#3999]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

2.35.1.windows.2
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1889]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing else

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
 $ cd // && time ls

```
 - What did you expect to occur after running these commands?

I expected them all to work as normal.

 - What actually happened instead?

They all took a lot longer than they should have (upwards of 20 seconds before throwing an error about permissions) and were unable to read or write to this // directory. See [this reddit thread](https://www.reddit.com/r/bash/comments/wzhhfh/comment/img37m6/?utm_source=share&utm_medium=web2x&context=3) for more.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no specific repository.

Edit: for clarity

**Comment by dscho** [comment]
@AAckerlund try this:

```console
$ cd //localhost/c$

$ ls
[... contents of the `C:` drive ...]
```

You did not describe what you expected the `//` directory to show ("I expected them all to work as normal" is very, very unclear as to your expectations, because what is "normal" for you is obviously not necessarily "normal" for anybody else).

This example should illustrate, though, what the `//` directory is supposed to show: a "directory" of machines serving network shares. MSYS2 inherits this feature [from Cygwin](https://cygwin.com/cygwin-ug-net/using.html#unc-paths).

The most likely explanation for "an error about permissions" (your report could be even more vague about the error message, you know? 😁 seriously again, please do make an effort of pasting precise error messages, hand-waving reports make it much harder than necessary for others to assist, something those others do not like at all) is that network discovery is turned off, which seems to be the default these days.

You should be able to see whether that is the case in your setup by navigating in your Windows Explorer to the `Network` tab. If you see something like this, then it is indeed turned off (and the most likely explanation to see that "error about permissions"):

![image](https://user-images.githubusercontent.com/127790/187608560-22ff7c71-d261-4045-bff6-81592e6d1654.png)

**Comment by AAckerlund** [comment]
@dscho 
> You did not describe what you expected the // directory to show.

How do you describe something you don't expect to exist? I encountered this issue when I missed the "." key and hit "/" instead. I still do not actually know what is happening when I type "cd //" or where it winds up putting me. This is not an area of computers/programming that I know much about.

> and the most likely explanation to see that "error about permissions"

This doesn't explain why these commands take 20+ seconds to execute though.

If there is something _specific_ I can add (such as output for a command) then I will. Asking me to just "do better" doesn't help anyone.

**Comment by dscho** [comment]
> > You did not describe what you expected the // directory to show.
> 
> How do you describe something you don't expect to exist?

So you expected that directory not to exist, and maybe say that in an error message? That's a very, very different thing than saying "I expected them all to work as normal.". Think about it. How could anyone have guessed that you meant the former when you said the latter?

> This doesn't explain why these commands take 20+ seconds to execute though.

It tries to discover the network servers, is my guess.

In any case, I think that I clarified the misunderstanding as to what `cd //` is supposed to do from MSYS2's perspective (and hence from Git Bash's). So I'll close this ticket as addressed.
