### ISSUE TITLE
 "git for-each-ref --format" does not return any output when format contains spaces on cmd.exe

### ISSUE THREAD

**Issue by phalgunv** [git-for-windows/git#4039]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options


git version 2.30.2.windows.1
cpu: x86_64
built from commit: 37f0a4afad027cf030747a1ef45537ba86162960
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1766]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No. 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Command Prompt(cmd.exe)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git for-each-ref --format='%(committerdate), %09%(authorname), %09%(refname:short)'
```
 - What did you expect to occur after running these commands?
List of refs in the repository.

 - What actually happened instead?

No output

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It happened with all repositories I tried with.

- Additional details
``` 
Below command returns the list of refs. I have remove the space after comma
git for-each-ref --format='%(committerdate),%09%(authorname),%09%(refname:short)'
```

**Comment by dscho** [comment]
Hi @phalgunv!

> `git for-each-ref --format='%(committerdate), %09%(authorname), %09%(refname:short)'`

The single quote character is not special in `cmd`. You probably want to replace it with the double-quote character, like so:

```
git for-each-ref --format="%(committerdate), %09%(authorname), %09%(refname:short)"
```

In other words, I do not think that you are describing a bug in Git, but a behavior (that surprises many users who are coming from Linux/macOS) of `cmd`.

**Comment by phalgunv** [comment]
Thanks @dscho. Replacing single quote with double quote does give the desired result.

>The single quote character is not special in cmd
I do not fully understand how single quote not being special in cmd.exe influences the output of the git for-each-ref command. Also, I want to understand why do I get the output when the space after comma is removed?

**Comment by rimrul** [comment]
> I do not fully understand how single quote not being special in cmd.exe influences the output of the git for-each-ref command. Also, I want to understand why do I get the output when the space after comma is removed? 

The answer to both those questions lies in how the shell splits arguments. Usually this hapens on spaces, so as an example when you call  `foo.exe bar baz`, `foo.exe` recieves `bar` and `baz` as separate arguments.

Now that's not ideal when you want to pass an argument containing a space, so  shells usually offer a way to wrap arguments containing a space in special characters (like single or double quotes) to prevent them from being split up.

So when calling `foo.exe "bar baz"`, `foo.exe` recieves only one argument, `bar baz`. When you call `git for-each-ref --format='%(committerdate), %09%(authorname), %09%(refname:short)'`, `git` recieves four arguments: `for-each-ref`,  `--format='%(committerdate),`, `%09%(authorname),` and `%09%(refname:short)'`. It can clearly understand `'%(committerdate),` as the value for `--format`, but the ones after that could be anything. 

Even if `git` could recognize that those are supposed to be part of the format, it has no way to cleanly reassemble that, because there could be any number of spaces (or some other characters) in between.

**Comment by phalgunv** [comment]
Thank you for the explanation. It would be great to have this information documented. I spent quite a lot of time figuring out why the git command was not working.
