### ISSUE TITLE
while read loop not working properly (variable)

### ISSUE THREAD

**Issue by PierrickG12** [git-for-windows/git#406]
I've found a regression (in comparaison with git version 1.8.4.msysgit.0 ) in the way variable a used in a while loop variable.

The expected result for the follow script is : 

`>` Bonjour
`>` Monsieur
`>` Madame, Monsieur

With file content : 

"Bonjour;Monsieur"

Script implementation

	l:01			#! /bin/bash
	l:02					
	l:03			IFS=";"
    l:04			
	l:05			while read COL1 COL2
	l:06			do
	l:07				echo $COL1
	l:08				echo $COL2
	l:09				
	l:10				RESULT=`echo "Madame, Monsieur" | grep $COL2`
	l:11				
	l:12				echo $RESULT
	l:13				
	l:14			done < /N/PG/TEST/TEST.txt
    l:15			
	l:16			IFS="\n"
	l:17			
	l:18			exit

Here is my output result with windows 2.5.2.2-64bit:

`>` Bonjour
`>` Monsieur
`>` 

COL2 variable is well-knonw because well printed.
but in the line 10 et 12 , $COL2 in no more interprted, I cannot figure out why !

**Comment by nalla** [comment]
Is that some _Git for Windows_ - even _Git_ unrelated `bash` question that you are asking here monsieur?

**Comment by nalla** [comment]
```
$ cd ~/
$ echo "Bonjour;Monsieur" > loop-test
$ ./loop-test.sh
Bonjour
Monsieur
```
The content if `loop-test.sh` is
```bash
#! /bin/bash

while IFS=";" read a b
do
  echo $a
  echo $b
done < ~/loop-test
```
Can not reproduce on this end.

**Comment by dscho** [comment]
Cannot reproduce either. I put

```
Madame;Monsieur
```

into `a1.txt` and

```sh
#! /bin/bash

IFS=";"

#echo "Madame;Monsieur" |
while read COL1 COL2
do
    echo $COL1:$COL2

    echo "Madame, Monsieur" | grep $COL2
done
```

into `a1.sh` and

```sh
$ sh a1.sh <a1.txt
```

does not reproduce the behavior with Git for WIndows 1.x' Bash.

**Comment by PierrickG12** [comment]
Hi,


Edit: A new version was released yesterday evening and the bug is no more reproductible (on another Windows OS). But here is the answer I was writting in order to explain better the issue I saw.

Thanks for the quick answers but I think you misunderstand my words.

I'm not an shell script expert (if I was this guy I weren't talking about any "windows tools" here) and I'm not asking for a workaround (even if I appreciate your alternative solutions).

After several test (on another computer) with the following configurations :

 - Windows 7 Premuim Familly Edition (64 bits)
 - git 1.9.5.msysgit.1
	->	(MINGW32)

 AND 
 
 - Windows 7 Pro (64bits)
 - git 1.9.4.msysgit (don't remenber the last digit and the MINGW versions)
 
 AND 

 - Windows 7 Premuim Familly Edition (64 bits)	
 - git version 2.5.3.windows.1 (MINGW64)
  
 AND
 
 - Windows 7 Premuim Familly Edition (64 bits)	
 - git version 2.5.2.windows (MINGW64)
 
the script presented on my first post was working well (It's maybe not the prettiest or the most optimised solution, but it's was working).
 
So, I cannot reproduce the issue on this computer with the same git version I saw it yesterday (git version 2.5.2.windows.2). Maybe the issue follow the OS version, I will make some more test on monday and let tou know about the results.

I'm aware that it's not directly a command git issue, but more a probable bug/difference in the tools (MINGW 32/64 ?) that are used to emulate the shell commands on windows.

I'm clearly not familiar with those tools and from my point of view it's a regression. A script functionnal with a previous "git for windows package" is no more functionnal with the lasts "Git for windows package", that is the definition of a regression.
 
That is why I open this issue : to let you know about this behaviour difference. Maybe it's a bug, maybe it's a way to proceed that is no more supported, maybe it's something else I don't know...

Let see on monday if I can reproduce the issue with the same computer I discover the issue...

**Comment by PierrickG12** [comment]
And for my personnal knowledge what does "mcve" mean ?

**Comment by rimrul** [comment]
>And for my personnal knowledge what does "mcve" mean ?

[Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)

>Windows 7 Premuim Familly Edition

You mean `Home Premium`?

I've just tested your script (modified the location of the test.txt file, since I dont have any drive N:\) 
and it does not output anything for me in Git for Windows 1.9.4-preview20140929 on Windows 8.1 Pro x64.

**Comment by dscho** [comment]
> I'm clearly not familiar with those tools and from my point of view it's a regression. A script functionnal with a previous "git for windows package" is no more functionnal with the lasts "Git for windows package", that is the definition of a regression.

It might look as a regression to you, I understand. From the perspective of Git for Windows, it is only a regression if it was a supported use case, though, not if it just happened to work in one version as a side effect and then stopped working.

To give you an extreme example: if you happened to rely on the presence of the `/mingw/bin` directory in Git for Windows 1.x, you might consider it a regression that it does not exist in Git for Windows 2.x any longer (because it is now an architecture-dependent `/mingw32/bin/` or `/mingw64/bin/` directory). However, from this project's point of view, it is not a regression but instead an unreasonable expectation that our implementation details should never change.

Since your script works here, and also on your other computer, however, I think you are lucky and it does *not* depend on an implementation detail that happened to have changed. It is more likely something in the configuration of the computer, e.g. a difference of environment variables or some such.

**Comment by PierrickG12** [comment]
>> Windows 7 Premuim Familly Edition

> You mean Home Premium?

Yes probably, I'm french and I've made a word to word translate

I cannot reproduced the issue on the computer at work with the following version : 
   git version 2.5.3.windows.1 (MINGW64)

I will close this issue even if I clearly cannot work with the new version 2.5.x.
It probably because of my lack of knowledge but the scripts that use to work with have unpredictable behaviour with the new versions.

I don't have any more time to dig those problems.
Thanks for your support.
