### ISSUE TITLE
Resizing window while showing `git log` locks up Command Line and PowerShell.

### ISSUE THREAD

**Issue by garretwilson** [git-for-windows/git#4060]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I'm using Git for Windows 2.37.3.windows.1 64-bit on Windows 10.0.19044.0.

1. Find a Git repository with a long commit history.
2. Enter `git log`.
3. Git will show the log history and wait for you to page through the history or hit `q` to exit.
4. Press `Win+Left-Arrow` to snap the window to the left side of the screen.

The window is now hung. Nothing can be typed to get it un-hung. Typing `q` does nothing. Typing `Ctrl+C` does nothing. Typing `<Enter>` does nothing. The only way out of this is to close the terminal window and start a new Command Prompt or PowerShell session.

I've reproduced this with Command Line and with PowerShell 7.2.6.

**Comment by dscho** [comment]
Can you reproduce this with plain [Cygwin](https://cygwin.com/) or plain [MSYS2](https://www.msys2.org/), too?

**Comment by Forge36** [comment]
Are you able to reproduce this directly with `more`? I've seen similar issues (Might be unrelated).

**Comment by dscho** [comment]
> I can reproduce the `git log` issue in cygwin.

@Forge36 that's good! Please [report it to the Cygwin project](https://cygwin.com/problems.html), they have the expertise to figure out what goes wrong efficiently (heck, they probably know immediately what is going wrong just from the description of the bug).

**Comment by garretwilson** [comment]
> Please [report it to the Cygwin project](https://cygwin.com/problems.html) …

Reporting the issue to Cygwin is not simple. Rather than a GitHub bug collector, they require subscribing to a mailing list. Even after going to all the trouble of subscribing, I do not have the expertise even to know what version of Cygwin your project is using, let alone how it's being used.

Have you even tried to reproduce the issue I filed?

No, the appropriate thing would be to 1) try to reproduce the issue, and 2) your project submit a bug report if appropriate to Cygwin, because you have the necessary expertise to describe how you are using this transitive project.

**Comment by ceztko** [comment]
> No, the appropriate thing would be to

As an another point of view, I believe both you and the maintainer were a bit lazy :)
The version of mintty used by git for Windows is 3.6.1 (right click on Windows icon -> Options -> About), the version used in latest cygwin (peace of cake to install) is 3.6.3. The latter also reproduce the issue. The maintainer basically asked you to help him 2 moths ago as he probably didn't have time.

The maintainer at this point could have regressed the version on mintty to one that was working and also reported the issue to cygwin ML, seeing that you weren't gonna do it.

Since I'm now very tired of this issue, I just reported[1] the issue to cygwin ML myself.

[1] https://cygwin.com/pipermail/cygwin/2023-January/252814.html

**Comment by me-and** [comment]
Hi folks, there've been a couple of reports linking to this bug on the Cygwin mailing list:

* https://cygwin.com/pipermail/cygwin/2022-December/252737.html from @Forge36, where I was able to reproduce the bug, and one of the Cygwin developers has produced a tentative fix per https://cygwin.com/pipermail/cygwin/2022-December/252745.html

* https://cygwin.com/pipermail/cygwin/2023-January/252814.html from @ceztko, which links to this issue but describes a problem affecting MinTTY, not cmd or PowerShell, so I suspect is a separate problem to the one covered by this issue. I wasn't able to reproduce the problem in this report.

For the first problem, I don't know when a new Cygwin release incorporating the fix is going to be available, or what the process / timeline is for that fix to be taken by Git for Windows, but a tentative fix is available.

For the second problem, assuming the description isn't just a misunderstanding, I expect someone who is able to reproduce the behaviour will need to engage on the Cygwin mailing lists to help track down the problem.

To be clear, I'm just the messenger here; I don't have have any responsibility or authority around what gets fixed when, either in the core Cygwin libraries (where the first bug appears to be) or in Git for Windows (which I believe is fundamentally a downstream consumer of those libraries). I'm also keen to not end up passing messages back and forth from the Cygwin mailing list to here and vice versa: I wanted to post once to hopefully minimise duplication of effort, but the best way to get help with Cygwin problems really is to engage on the Cygwin mailing list.

**Comment by Forge36** [comment]
Apologies I had forgotten to update this thread when I reported the issue.

I can continue to help the cygwin maintainers if they reach out to me directly (I did not subscribe to the mailing list).

I haven't had an opportunity to test the latest fix.

**Comment by rimrul** [comment]
> Hi folks, there've been a couple of reports linking to this bug on the Cygwin mailing list:
> 
> * https://cygwin.com/pipermail/cygwin/2022-December/252737.html from @Forge36, where I was able to reproduce the bug, and one of the Cygwin developers has produced a tentative fix per https://cygwin.com/pipermail/cygwin/2022-December/252745.html

Thank you for pointing us in that direction. It looks like [this is the patch](https://github.com/cygwin/cygwin/commit/f6e4e98d3071c8e41f50773ec3c7683fb104b3ab) and it's slated for release in Cygwin 3.4.4. We could probably backport that to our Cygwin 3.3 based Msys2 runtime.

**Comment by rimrul** [comment]
> * https://cygwin.com/pipermail/cygwin/2023-January/252814.html from @ceztko, which links to this issue but describes a problem affecting MinTTY, not cmd or PowerShell, so I suspect is a separate problem to the one covered by this issue. I wasn't able to reproduce the problem in this report.

I assume you've tried to reproduce this with *cygwin* git. @ceztko reproduced this with our *native* git executables. The commit message of the patch mentions that less shows this behaviour when called from a *non-cygwin shell*, but I suspect *non-cygwin git* could also bring out this behaviour.

**Comment by me-and** [comment]
> > * https://cygwin.com/pipermail/cygwin/2023-January/252814.html from @ceztko, which links to this issue but describes a problem affecting MinTTY, not cmd or PowerShell, so I suspect is a separate problem to the one covered by this issue. I wasn't able to reproduce the problem in this report.
> 
> I assume you've tried to reproduce this with _cygwin_ git. @ceztko reproduced this with our _native_ git executables. The commit message of the patch mentions that less shows this behaviour when called from a _non-cygwin shell_, but I suspect _non-cygwin git_ could also bring out this behaviour.

I attempted with (a) both Cygwin's Git and Cygwin's less in a Cygwin MinTTY window, and (b) both Git for Windows' Git and Git for Windows' less in a Git Bash window. I wasn't able to reproduce the problem in any of these scenarios.
