### ISSUE TITLE
Git 2.38 breaks safe.directory in included .gitconfig's

### ISSUE THREAD

**Issue by benallred** [git-for-windows/git#4066]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

2.37.3 and 2.38.0, 64-bit

```
$ git --version --build-options

git version 2.37.3.windows.1
cpu: x86_64
built from commit: c4992d4fecabd7d111726ecb37e33a3ccb51d6f1
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
and

```
$ git --version --build-options

git version 2.38.0.windows.1
cpu: x86_64
built from commit: 0355083fbe5582f6d3f819afc130ed2f2375e0bd
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Win 11 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.674]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I used `winget upgrade Git.Git`

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I use PowerShell Core in Windows Terminal and always and only run that as admin.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell and Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
winget upgrade Git.Git
```
 - What did you expect to occur after running these commands?

I run a PowerShell script to set up my machine after a fresh install. All of my repositories are cloned then. That script is run as admin.
Some time ago I had to add `safe.directory = *` to my gitconfig in order to keep this working. [I understand what that setting is for and what `*` implies.]
All of my gitconfig settings are stored in my own file (https://github.com/benallred/configs/blob/3b418ed19e8a5472902f4c0f1afd369855dcf8f2/git/ben.gitconfig#L12-L13) and that file is added as an `include.path` to the global .gitconfig during the machine setup script (https://github.com/benallred/configs/blob/3b418ed19e8a5472902f4c0f1afd369855dcf8f2/config.ps1#L69).

With 2.37.3, any process, admin or not, can perform git commands in any of my repos successfully.

For example:

```
# open non-admin Windows Terminal with PowerShell
> git status
## master...origin/master
```

or

Open VS Code not as admin
Navigate to Source Control panel
Changes are shown as expected

 - What actually happened instead?

After upgrading to 2.38, any process not running as admin cannot perform git commands in my repos.

For example:

```
# open non-admin Windows Terminal with PowerShell
> git status

fatal: detected dubious ownership in repository at 'C:/BenLocal/git/configs'
'C:/BenLocal/git/configs' is owned by:
        'S-1-5-32-544'
but the current user is:
        'S-1-5-21-2964262074-2878752724-2569554567-1001'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/BenLocal/git/configs
````

or

Open VS Code not as admin
Navigate to Source Control panel
Changes are _not_ shown as expected and the panel content says "The folder currently open doesn't have a git repository..." and the Git log under Output says

```
[2022-10-12T17:21:57.189Z] > git rev-parse --show-toplevel [73ms]
[2022-10-12T17:21:57.189Z] fatal: detected dubious ownership in repository at 'C:/BenLocal/git/configs'
'C:/BenLocal/git/configs' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-2964262074-2878752724-2569554567-1001'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/BenLocal/git/configs
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

All repositories I clone as admin

 - Additional Information

In 2.38.0, if I move

```
[safe]
	directory = *
```

from my `include`d gitconfig directly into the global .gitconfig, then the error goes away. This leads to my conclusion that 2.38.0 breaks `safe.directory` resolution in `include`d gitconfig's.

I have downgraded back to 2.37.3 to verify that this worked in that version and then upgraded again to verify that the error started in 2.38.0.

I did not see anything in the release notes (https://github.com/git/git/blob/v2.38.0/Documentation/RelNotes/2.38.0.txt) that indicates this is expected behavior.

If this doesn't belong in the git-for-windows repository, sorry! I don't know where issues go for actual git.

**Comment by rimrul** [comment]
This seems to be the same issue that's been reported to the git mailing liste at https://lore.kernel.org/git/CAPWNY8W_Tr-WoD-GXBddD5Y8w5Y4w+gDNYQdOAJ1uBwVHuRrsQ@mail.gmail.com/

**Comment by rimrul** [comment]
There is now a proposed fix for that:

https://github.com/git/git/pull/1360

It has been submitted to the mailing list at 

https://lore.kernel.org/git/pull.1360.git.git.1665603814.gitgitgadget@gmail.com

**Comment by dscho** [comment]
> @benallred feel free to backport it onto Git for Windows' `main` branch and open a PR so that we get this early.

If this is at all urgent in any way to you, please do feel encouraged to backport and open a PR.

If it is not urgent at all, it is safe to wait for v2.39.0 [which is due December 12th 2022](https://tinyurl.com/gitCal).

In anticipation that this is actually much less urgent than originally indicated, I will close this here ticket.

**Comment by benallred** [comment]
Thank you for following up. I did mean to take a look at backporting but (along with not being super clear how to begin) am in the process of changing jobs so could not get to it. I can wait until December. Thanks again!

**Comment by dscho** [comment]
> take a look at backporting but (along with not being super clear how to begin)

The contribution was sent to the mailing list as https://lore.kernel.org/git/pull.1360.git.git.1665603814.gitgitgadget@gmail.com/. One particularly nice thing about this contribution is that it uses [GitGitGadget](https://gitgitgadget.github.io/) to map a GitHub PR to a patch series submission done via mail. In other words, you can see the original branch (which is completely lost, unfortunately, in transition on the mailing list) at https://github.com/git/git/pull/1360.

The typical way to backport such a branch is to first see whether it needs to be rebased at all, i.e. if there are any commits between Git for Windows' `main` branch and that branch's base commit. Since it is [a single commit](https://github.com/git/git/pull/1360/commits), its base branch is simply [the parent commit](https://github.com/git/git/commit/3dcec76d9df911ed8321007b1d197c1a206dc164) (incidentally the commit to which the v2.38.0 tag points). This is obviously reachable from Git for Windows' `main` branch, so no rebasing is needed.

That makes the backport super easy: simply create a new branch from that commit (which you can obtain e.g. via `git fetch https://github.com/gitgitgadget/git refs/pull/1360/merge`), push it, and open a PR.

Another way to get to a branch for which a PR can be opened is to look at the upstream branch into which the mailing list translated the patches. You can see the name [here](https://github.com/git/git/pull/1360#issuecomment-1278152096): [`gc/bare-repo-discovery`](https://github.com/gitgitgadget/git/commits/gc/bare-repo-discovery) (sadly, there was a bug in GitGitGadget that provided an incorrect URL here, the bug is hence fixed, and I fixed the URL in this here comment, too).

That `gitgitgadget:gc/bare-repo-discovery` branch could even be used directly to open that PR: https://github.com/git-for-windows/git/compare/git-for-windows:main...gitgitgadget:gc/bare-repo-discovery?expand=true

All you would need to do is to provide a good PR description (instead of a copy of the commit message as auto-populated by GitHub), i.e. describe the context, the motivation, the problem and the solution as well as enough links (e.g. to this here conversation, to the mail thread on the Git mailing list, and to whatever else that seems relevant to the bug that is fixed by this commit).

**Comment by dscho** [comment]
FWIW I transmogrified this information into this wiki page: https://github.com/git-for-windows/git/wiki/Backporting-upstream-Git-patches
