### ISSUE TITLE
sparse-checkout not able to do the partial code checkout in window ?

### ISSUE THREAD

**Issue by chunji08** [git-for-windows/git#4067]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.0.windows.1
cpu: x86_64
built from commit: 0355083fbe5582f6d3f819afc130ed2f2375e0bd
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.475]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

`Not I know. 
`

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

` git-bash 
` 
- What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

**Starting from a fresh Git-Bash window, these are the commands I have executed:** 
```
git clone -b <my_branch> --no-checkout <my_repo> src
cd src  
git sparse-checkout set <my_dir>
```

 - What did you expect to occur after running these commands?
```

1.  The first command would clone the <my_repo> for <my_brach> under the directory of src. 
2.  cd to that src dir. 
3.  The 3rd command would do 2 things: 
     3.1 the <my_dir> value is being listed inside the .git/info/sparse-checkout file. 
     3.2 files under <my_dir> would be automatically checked out.  

```
 

 - What actually happened instead?

```
Everything looks ok, till the last 3.2. I don't see any files being checked out under src.  And If I was to run 
git checkout <my_branch> command,  it seems to try to checkout everything, not just the files under <my_dir>.   

I have tried the same steps on UBUNTU, and they are working perfectly fine. 
```

Here is the issue I posted on another thread:  https://stackoverflow.com/questions/73956051/git-can-not-clone-a-repository-in-window-env-because-some-special-file-names, for my initial problem.  And that is the reason I am trying the sparse-checkout way to do a partial checkout in window.

**Comment by derrickstolee** [comment]
The `--no-checkout` is the problem here. You need to do a `git checkout` to something _after_ the `git sparse-checkout set` in order to populate your working directory. This was a purposeful change of behavior around Git 2.34 or earlier, I think.

If you want to get set up with sparse-checkout (and partial clone) in an easier way, I might recommend using `scalar clone <url>` then you'll `cd <repo>/src` and you'll have a sparse-checkout with everything in the root directory. Your `git sparse-checkout set` command will work immediately from there.

**Comment by chunji08** [comment]
Hi Derrick
Thanks for the Tips. But it does not work in my case.  

In the repository, someone introduced these 2 files with very unique name that  git of the window version can not handle it.  
```
./templates/extender/sync/os_firmware/[4.2.2.291,4.2.3.517)|[7.0.0.0,7.0.1.0).jinja2
./templates/extender/sync/os_firmware/(-inf,4.2.2.291)|[4.2.3.517,7.0.0.0)|[7.0.1.0,+inf).jinja2

```
And when I do regular git clone in window, the process keeps failing. 

But Since my part of work does not need these 2 files, that is why I want to do a spare-checkout of my code only. 

Anyway, I have just tried the scalar clone as you suggested, here is the result when I am running this command in git-bash window. 
```
scalar clone <repo>
Skipping GVFS protocol check...
Fetching objects from remote...
Checking out 'master'...
Failed

Cannot clone @ C:\Users\chji\Playground\<repo>

Error: Failed to complete regular clone: error: invalid path 'templates/extender/sync/os_firmware/(-inf,4.2.2.291)|[4.2.3.517,7.0.0.0)|[7.0.1.0,+inf).jinja2'


```
It seems to me, the scalar process is also affected by that file.  And because of that, when I cd to <repo>/src, I don't see the anything at root directory checked out, except that ".git" dir.  

Thanks, 

Chun Ji

**Comment by derrickstolee** [comment]
> ```
> ./templates/extender/sync/os_firmware/[4.2.2.291,4.2.3.517)|[7.0.0.0,7.0.1.0).jinja2
> ./templates/extender/sync/os_firmware/(-inf,4.2.2.291)|[4.2.3.517,7.0.0.0)|[7.0.1.0,+inf).jinja2
> ```

These paths are being blocked because they cannot be valid files on Windows filesystems. See [the `core.protectntfs` config option](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreprotectNTFS) which might allow you to disable the protections here. These protections are for security reasons, but if you trust the repository enough you can try disabling the option. If disabled, then you can create an index with these paths, even though the `git checkout` will fail to write them (or the sparse-checkout definition might not try to put them on disk).

This is very similar to how the Linux kernel can't be checked out on Windows because of an `aux.c` file that is not allowed on DOS-based filesystems.

**Comment by chunji08** [comment]
Thanks for the tips. After I have set this flag to be false, plus my sparse-checkout setting, I was able to do the partial checkout in the end.
