### ISSUE TITLE
gitk fails to run when MSYS_NO_PATHCONV is set

### ISSUE THREAD

**Issue by ninloot** [git-for-windows/git#407]
I'm running Git version 2.5.2.windows.1.  When I invoke gitk from a bash shell it fails with the following error:

Error in startup script
couldn't read file "/mingw32/bin/gitk": no such file or directory

I found that if I removed the MSYS_NO_PATHCONV from my .bash_profile then gitk works as expected.

**Comment by dscho** [comment]
> I found that if I removed the MSYS_NO_PATHCONV from my .bash_profile then gitk works as expected.

That is to be expected! `MSYS_NO_PATHCONV` is *not* a setting you should *always* use! Otherwise we would set it by default, that should go without saying!

`MSYS_NO_PATHCONV` is to be used *only* in *specific* shell invocations, and certainly not for entire scripts! That is just *asking* for desaster.
