### ISSUE TITLE
error: fatal: invalid --pretty format

### ISSUE THREAD

**Issue by aleksanderFox** [git-for-windows/git#4244]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options

git version 2.20.1.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
The system cannot find the path specified.
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Cmd

Command
```
git log -1 --pretty="%H"
```
 - What did you expect to occur after running these commands?

commit hash

 - What actually happened instead?

fatal: invalid --pretty format: H

**Comment by dscho** [comment]
@aleksanderFox `%` is a special character in CMD. Have you tried to escape it?

Besides... your minimal example does not seem to reproduce here:

```console
C:\git-sdk-64\usr\src\git>git show -s --pretty="%H"
7360767e8dfc1895a932324079f7d45d7791d39f
```

But maybe this is all due to you using an old Git for Windows version (and an [vulnerable one](https://github.com/git-for-windows/git/wiki/FAQ#should-i-upgrade-to-a-newer-git-for-windows-version) at that)? See here:

> * Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
>       64-bit
> 
> 
> ```
> $ git --version --build-options
> 
> git version 2.20.1.windows.1
> ```

May I strongly advise to upgrade to [v2.39.1](https://github.com/git-for-windows/git/releases/tag/v2.39.1.windows.1)?

**Comment by aleksanderFox** [comment]
@dscho
Unfortunately on my computer (git 2.33.1.windows.1) the command works without errors.
The error only reproduce on virtual machines, under control Bamboo Server (CI/CD).

I would like to understand if it is possible to bypass/fix the error without git updating?

**Comment by aleksanderFox** [comment]
I figured out what the error is!!!!
If you change the interpreter type of the script that executes inline code in the agent from "bin/sh or cmd.exe" to "Winsows Power Shell", then everything works!

**Comment by Kristinita** [comment]
**Type: Additional information** ➕

[**I reproduced the problem on AppVeyor CI**](https://ci.appveyor.com/project/Kristinita/sashaappveyordebugging#L54). In my case, the problem was that AppVeyor [**incorrectly processes commands with percent symbol**](https://github.com/appveyor/ci/issues/246#issuecomment-2717301993). Possibly, the author of this issue had the same reason of the problem.

Thanks.

**Comment by dscho** [comment]
@Kristinita that's an excellent finding and sounds _highly_ plausible as the underlying culprit of this issue. Thank you for recording this finding for other users to learn from!
