### ISSUE TITLE
Files in `.git\objects` are read only

### ISSUE THREAD

**Issue by JakobDev** [git-for-windows/git#4250]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.39.1.windows.1
cpu: x86_64
built from commit: b03dafd9c26b06c92d509a07ab01b01e6d0d85ee
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19045.2486]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Happens with any command who creates/touches these files
```
 - What did you expect to occur after running these commands?

No File should have a Read Only Attribute, which causes Problems when you want to delete the project folder.

 - What actually happened instead?

The Files in `.git\objects`  have a Read Only attribute

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Any Repo

**Comment by dscho** [comment]
> The Files in `.git\objects` have a Read Only attribute

This is very much by design. The oldest tagged Git version already has the code: https://github.com/git/git/blob/v0.99/sha1_file.c#L1182. To understand the rationale, let's look at the commit that introduced that behavior: aac17941320f7f73e5d411b152bfd041572e8a66. While it does not explicitly talk about the reason why the files are read-only, the idea is that they are immutable. They should never be changed. Deleted, yes. But not modified, ever.

If that explanation isn't good enough for you, please feel free to take the discussion to the Git mailing list. See https://git-scm.com/community for more details.
