### ISSUE TITLE
MinGit 2.38 not reading system-level safe.directory entries

### ISSUE THREAD

**Issue by luhansen-ms** [git-for-windows/git#4280]
This was going to be a bug report, until I saw it was fixed in 2.39! However, I couldn't find release notes for the fix, so I'm not sure if it was intentional. Filing this just to make sure this was intentional, and that this doesn't regress. 

## Setup

Have a repository cloned by admin at `C:\ClonedAsAdmin`

C:\Program Files\Git\etc\gitconfig:
```
[safe]
    directory = * # or C:/ClonedAsAdmin
```

C:\Program Files\path_to_mingit\etc\gitconfig:
```
[include]
	; include Git for Windows' system config in order
	; to inherit settings like `core.autocrlf`
	path = C:/Program Files (x86)/Git/etc/gitconfig
	path = C:/Program Files/Git/etc/gitconfig
```

## Git/MinGit `2.38.1.windows.1`

Perform the following as non-admin user in `C:\ClonedAsAdmin`:
```
> C:\Program Files\Git\cmd\git.exe pull
Already up to date.

> C:\Program Files\path_to_mingit\cmd\git.exe pull
fatal: detected dubious ownership in repository at 'C:/ClonedAsAdmin'
'C:/ClonedAsAdmin' is owned by:
        'S-#-#-##-###'
but the current user is:
        'S-#-##-#-########-##########-##########-#########'
To add an exception for this directory, call:

        git config --global --add safe.directory C:/CloneAsAdmin
```

## Git/MinGit `2.39.1.windows.1`:

Perform the following as non-admin user in `C:\ClonedAsAdmin`:

```
> C:\Program Files\Git\cmd\git.exe pull
Already up to date.

> C:\Program Files\path_to_mingit\cmd\git.exe pull
Already up to date.
```

_________________________________________________________________

 - [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22621.1105]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

n/a

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD/PS

**Comment by dscho** [comment]
I am confident that the answer lies in this ticket: https://github.com/git-for-windows/git/issues/4066. Essentially, Git v2.38 (and not just Git _for Windows_) broke the `include` feature in protected configs (such as `safe.directory`).

And since [the upstream fix](https://github.com/git/git/commit/ecec57b3c973) was only integrated into v2.39.0 (but not into v2.38.2, for which I would have created a MinGit backport only on specific request anyway, as it was published merely one day before v2.39.0 and as per [Git for Windows' policy](https://github.com/git-for-windows/git/security/policy#supported-versions) only the latest release train of Git is followed by Git for Windows), there is no MinGit v2.38.x with the fix.

Because the fix went directly into upstream, there is no specific entry in Git for Windows' release notes, but instead it is covered by [the link to Git v2.39.0's release notes](https://github.com/git-for-windows/build-extra/blob/9ea75ff24db0fdadf771bf7ce4b6c1f5826bf4ec/ReleaseNotes.md?plain=1#L93).

**Comment by luhansen-ms** [comment]
Uh oh. Yeah this is definitely a duplicate of that. Sorry about that! Thanks!

**Comment by dscho** [comment]
No worries. You could not have known. At least now it is documented, here in this ticket.
