### ISSUE TITLE
Unable to set system config  - Installtion problem Code: 4294967295

### ISSUE THREAD

**Issue by SiddheshKukade** [git-for-windows/git#4300]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Git 2.34.2-64bit windows 

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Windows 10

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults 

### Details

 - I tried to install git and keep getting this error please help.
 
![image](https://user-images.githubusercontent.com/65951872/219968757-287ff910-99cb-4852-be8e-3786876a3180.png)

###  Correct behaviour
Git should be installed properly

**Comment by SiddheshKukade** [comment]
@bbolli  @dscho  @shiftkey  @ttaylorr  please take a look and help for guidance thanks.

**Comment by dscho** [comment]
Whoa, that's summoning quite a lot of people at once!

**Comment by SiddheshKukade** [comment]
@dscho sorry I usually don't get replied from Open Source projects most of the time. 
I've now fortunately solved this issue by deleting my antivirus (Net Protector Antivirus) and I've also disabled my firewall.
Now the installation is working fine for me. 
Should we close this now ?

**Comment by eduarddejong** [comment]
I'm currently experiencing this problem.

I'm seeing a whole series of error messages. The first one being "Unable to set system config "diff.astextplain.textconv":="astextplain": exit code 128". And then another one for every next setting.

In my case it turns out there's the installer has a problem with my .gitconfig being a symlink. I need to change it into an actual file to work around this.

The most surprising thing however is that the .gitconfig isn't even being changed at all.
And all those settings belong to "C:/Program Files/Git/etc/gitconfig".
So to me this really looks like a bug.

For me this is specific to Git-2.53.0.
Version 2.52.0 and 2.51.2 don't have this problem in my case.
