### ISSUE TITLE
git push fails without credential.helper

### ISSUE THREAD

**Issue by i1v** [git-for-windows/git#4301]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.18363.1139]
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

If I download this:

https://github.com/git-for-windows/git/releases/download/v2.39.2.windows.1/MinGit-2.39.2-busybox-64-bit.zip

and remove these from `etc/gitconfig`:

~~~init
[credential]
   helper = manager
~~~

any `git push` after that fails:

~~~
bash: can't create /dev/tty: nonexistent directory
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or
directory
~~~

according to the docs, Git should have a fallback when a credential helper is not defined:

https://git-scm.com/docs/gitcredentials#_requesting_credentials

**Comment by rimrul** [comment]
> ```
> bash: can't create /dev/tty: nonexistent directory
> error: failed to execute prompt script (exit code 1)
> fatal: could not read Username for 'https://github.com': No such file or
> directory
> ```
> 
> according to the docs, Git should have a fallback when a credential helper is not defined:
> 
> https://git-scm.com/docs/gitcredentials#_requesting_credentials

It does. And that fallback is running into an error. That's this line:

> bash: can't create /dev/tty: nonexistent directory

And then git tells you that the fallback returned an error.

> error: failed to execute prompt script (exit code 1)

And that it couldn't read the user name from the fallback:

> > fatal: could not read Username for 'https://github.com':

And the error this fallback returned:

> No such file or directory

So let's try to figure out what happened.

> Without any credential helpers defined, Git will try the following strategies to ask the user for usernames and passwords:

 > If the GIT_ASKPASS environment variable is set, the program specified by the variable is invoked. A suitable prompt is provided to the program on the command line, and the user’s input is read from its standard output.

> Otherwise, if the core.askPass configuration variable is set, its value is used as above.

> Otherwise, if the SSH_ASKPASS environment variable is set, its value is used as above.

One of these three was set, because it didn't get to this next part.

> Otherwise, the user is prompted on the terminal.

It doesn't really matter which one is set, the result is roughly the same. The error message tells us the value was pointing to a shell script.

[env.sh](https://github.com/git-for-windows/build-extra/blob/main/git-extra/env.sh#L12) tells us it could be [`/mingw64/libexec/git-core/git-gui--askpass`](https://github.com/git-for-windows/git-sdk-64/blob/main/mingw64/libexec/git-core/git-gui--askpass), but I don't quite see where that would try to access `/dev/tty`.

**Comment by i1v** [comment]
sorry for the trouble, but I think I have to close this for now. when I repeat my original process above, I now get a GUI window asking for credentials. I think it might be because I relogged or restarted Windows.

**Comment by i1v** [comment]
deleted my previous comment and reopening. I thought the issue was resolved, but turns out my environment was contaminated with an old `.gitconfig`. with a clean environment and the steps above, the problem remains

**Comment by dscho** [comment]
@i1v please re-run with `GIT_TRACE=1` so that we can at least see whether `git-gui--askpass` is called at all.

**Comment by dscho** [comment]
> [env.sh](https://github.com/git-for-windows/build-extra/blob/main/git-extra/env.sh#L12) tells us it could be [`/mingw64/libexec/git-core/git-gui--askpass`](https://github.com/git-for-windows/git-sdk-64/blob/main/mingw64/libexec/git-core/git-gui--askpass), but I don't quite see where that would try to access `/dev/tty`.

@rimrul since @i1v reported using PowerShell, I believe that `env.sh` is not even involved. But let's see what that `GIT_TRACE` says.

**Comment by i1v** [comment]
~~~
06:15:10.592237 exec-cmd.c:237          trace: resolved executable dir: D:/Desktop/MinGit-2.39.2-busybox-64-bit/mingw64/bin
06:15:10.599146 git.c:460               trace: built-in: git push
06:15:10.599146 run-command.c:655       trace: run_command: GIT_DIR=.git git remote-https origin https://github.com/i1v/blog
06:15:10.605148 exec-cmd.c:237          trace: resolved executable dir: D:/Desktop/MinGit-2.39.2-busybox-64-bit/mingw64/bin
06:15:10.606145 git.c:750               trace: exec: git-remote-https origin https://github.com/i1v/blog
06:15:10.606145 run-command.c:655       trace: run_command: git-remote-https origin https://github.com/i1v/blog
06:15:10.612281 exec-cmd.c:237          trace: resolved executable dir: D:/Desktop/MinGit-2.39.2-busybox-64-bit/mingw64/bin
06:15:10.816926 run-command.c:655       trace: run_command: bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
06:15:10.818924 run-command.c:655       trace: run_command: 'D:\Desktop\MinGit-2.39.2-busybox-64-bit\mingw64\bin\busybox.exe' --help
bash: can't create /dev/tty: nonexistent directory
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory
~~~

**Comment by i1v** [comment]
Also this is concerning:

~~~
bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
~~~

seems like it would be better to just rewrite that in C, rather than relying on Bash. I know the package comes with BusyBox, but since Bash is not native to Windows, the less its used the better I think. Here is a 7 line program in Go that does the same thing:

~~~go
package main
import "fmt"
func main() {
   var line string
   fmt.Scan(&line)
   fmt.Println(line)
}
~~~

**Comment by dscho** [comment]
> Also this is concerning:
> 
> ```shell
> bash -c 'cat >/dev/tty && read -r line </dev/tty && echo "$line"'
> ```
> 
> seems like it would be better to just rewrite that in C, rather than relying on Bash.

@i1v It would be better in C. If it worked. But it does not. Because `/dev/tty` is not a thing on Windows.

> I know the package comes with BusyBox

But that BusyBox does not come with a `bash`, instead it comes with `ash`, and that `ash` _also_ does not know `/dev/tty`.

> Here is a 7 line program in Go that does the same thing

Actually, it does not. It writes to `stdout` and reads from `stdin` (and in the opposite order as the `bash` scriptlet). The `bash` scriptlet writes to, and reads from, the terminal, regardless whether the standard handles are redirected or not. Try this, for example:

```sh
bash -c 'read -r line </dev/tty && echo "$line"' </dev/null
```

It still reads from the terminal.

To top things off: The default terminal in Git for Windows is a MinTTY window running Git Bash. There is no Win32 console involved at all. It's all a pseudo terminal emulated by the MSYS2 runtime that provides the POSIX emulation layer needed by Bash.

So I am afraid that it is not as trivial a problem as you think it is, not by a very, very far stretch.

**Comment by i1v** [comment]
> @i1v It would be better in C. If it worked. But it does not. Because `/dev/tty` is not a thing on Windows.

right, so just dont use `/dev/tty` then. use something that is universal, or just use standard input, as shown in my example.

> But that BusyBox does not come with a `bash`, instead it comes with `ash`, and that `ash` _also_ does not know `/dev/tty`.

As can be shown in my trace, MinGit does have some kind of Bash. I do not have Bash on my system, so it is coming from MinGit somehow, I just assumed BusyBox.

> Actually, it does not. It writes to `stdout` and reads from `stdin` (and in the opposite order as the `bash` scriptlet).

the order doesn't matter. it was just an example. the lines can just be switched to address your concern.

> The `bash` scriptlet writes to, and reads from, the terminal, regardless whether the standard handles are redirected or not.

I dont see why that matters. the current script doesn't work, my example program does. I would rather have a working program that is more limited (sensitive to redirects), rather than a script that doesn't work (as is the case currently).

> To top things off: The default terminal in Git for Windows is a MinTTY window running Git Bash.

I am using MinGit, so I dont have any MinTTY.

> There is no Win32 console involved at all. It's all a pseudo terminal emulated by the MSYS2 runtime that provides the POSIX emulation layer needed by Bash.

again if program was written in C, then no Bash is needed. simpler approach.

> So I am afraid that it is not as trivial a problem as you think it is, not by a very, very far stretch.

Based on everything I have read so far, yes, it is trivial. You can start with basically the program I gave (or C equivalent). then if need be, program can be improved such that it works regardless of redirection. given that the current `manager` helper, and even the GUI askpass helper dont support redirection, I think it would be fine if the command line version didn't support it either. If its important that the command line helper ignore redirection for some reason, I respect that, but sometimes its better to not make things harder than they need to be.

**Comment by dscho** [comment]
> dont use `/dev/tty` then.

@i1v then you end up with the error you reported.

> just use standard input

The credential helper is used in scenarios where Git spawns processes and feeds them input via a redirected input handle. No keyboard input on that standard input handle!

And even if we could, how to suppress echoing when asking for passwords?

> I do not have Bash on my system, so it is coming from MinGit somehow, I just assumed BusyBox.

Yes, there are a lot of assumptions present here. Too many for a solid analysis.

MinGit does bundle a Bash; It's the MSYS2 Bash. That's why it can typically talk to the terminal, unlike `git.exe`.

> > Actually, it does not. It writes to `stdout` and reads from `stdin` (and in the opposite order as the `bash` scriptlet).
> 
> the order doesn't matter. it was just an example. the lines can just be switched to address your concern.

To address a problem like the one you reported, we cannot cut corners. We need to be diligent. And mixing up the order of showing the prompt and reading the answer is not diligent.

Sure, the order can be fixed. The rest cannot be. And if you want to suggest a better way, you need to be careful. Mixing up the order is just one tell-tale that the proposal needs to be put together with a lot more thought than it has been.

> > The `bash` scriptlet writes to, and reads from, the terminal, regardless whether the standard handles are redirected or not.
> 
> I dont see why that matters. the current script doesn't work, my example program does. I would rather have a working program that is more limited (sensitive to redirects), rather than a script that doesn't work (as is the case currently).
> 
> > To top things off: The default terminal in Git for Windows is a MinTTY window running Git Bash.
> 
> I am using MinGit, so I dont have any MinTTY.

That sounds a lot like "it works on my machine, in my one scenario that I tested, and I don't care how many Git for Windows users' use cases it breaks".

That's not an approach that I can condone.

Your approach would literally have the potential to break hundreds of thousands of users' workflows, if not more. You cannot simply wave away the fact that redirected standard handles are an important crux of the problem at hand. Git frequently operates under such conditions, it even creates such conditions itself by spawning other Git processes and feeding them input via `stdin`.

> again if program was written in C, then no Bash is needed. simpler approach.

I am starting to suspect that you haven't understood what I implied when I said "[...] it does not [work]. Because /dev/tty is not a thing on Windows.".

The prompt needs to access the terminal, no matter whether the standard handles are redirected or not. No matter whether they are closed or not. No matter whether the standard handles are connected to pipes, even ones connected to other Git processes. In all of these instances, the prompt _still_ needs to access the terminal, _not_ the standard handles.

And since that terminal is typically an MSYS2 pseudo terminal attached to a MinTTY instance, you have to involve the MSYS2 runtime. That's what that Bash scriptlet does. That's what your pure C solution will not be able to do, at least not "much simpler than Bash". And certainly not within `git.exe`.

As long as this is not understood, we are stuck in this conversation before we can even _start_ to talk about potential solutions.

That 7-liner is definitely not going to help one bit. Not even close.

**Comment by i1v** [comment]
FYI this seems to work if `/dev/tty` equivalent is required for some reason:

~~~go
package main

import (
   "fmt"
   "os"
)

func main() {
   file, err := os.Open("CON")
   if err != nil {
      panic(err)
   }
   defer file.Close()
   var line string
   fmt.Fscan(file, &line)
   fmt.Println(line)
}
~~~

**Comment by dscho** [comment]
> given that the current `manager` helper, and even the GUI askpass helper dont support redirection, I think it would be fine if the command line version didn't support it either.

BTW this is missing the mark. The `manager` helper as well as the GUI askpass helper do not try to read a password from the terminal because they are _GUI_ programs, unlike `git.exe`. `git.exe` needs to read from the terminal. And none of them need to read from `stdin`. As I pointed out, now several times, they even _must not_ read from `stdin`.

**Comment by dscho** [comment]
> ```go
>    file, err := os.Open("CON")
> ```

That is accessing a _Win32 Console_. The thing that I reported not to be present in a MinTTY session at all.

So no, it's still not one iota closer to helping. The fundamental problem needs to be understood first. MinTTY is an MSYS program that uses the MSYS2 runtime which emulates a Unix-like pseudo terminal. And it is _that_ terminal that you need to be able to talk to. I hope that's clearer now.

**Comment by dscho** [comment]
> `bash: can't create /dev/tty: nonexistent directory`

I think I understand this much better now that you've admitted that you are using MinGit interactively (when MinGit is specifically intended _not_ to be used interactively!). You might be able to "fix" this simply by creating the `dev` directory in your MinGit folder.

Having said that, I cannot reproduce this issue:

```
PS C:\Users\me\MinGit-2.39.2-64> cmd\git -c credential.helper= ls-remote https://github.com/dscho/xyz
Username for 'https://github.com':
```

It might be due to the difference of Windows version (I'm on Windows 11).

But as we've now safely established that this ticket is about an unsupported scenario ([MinGit is intended to be used by third-party applications](https://github.com/git-for-windows/git/wiki/MinGit), which are expected to provide their own credential helper or at least use the provided GUI ones instead of disabling them), it is probably best to leave this here ticket in peace and tend to supported scenarios where Git for Windows does not work.

**Comment by i1v** [comment]
> @i1v then you end up with the error you reported.

the error aries BECAUSE something is trying to use `/dev/tty`. If stdin/stdout is instead used, then that issue goes away.

> The credential helper is used in scenarios where Git spawns processes and feeds them input via a redirected input handle. No keyboard input on that standard input handle!

The credential helper isnt used, thats the whole issue here. the `manager` helper is the default, which is well supported. my argument is that the fallback should also be well support, as detailed in the docs:

<https://git-scm.com/docs/gitcredentials#_requesting_credentials>

from what I can tell, the fallback isnt currently supported, and hasnt been for several years. If I am wrong I apologize.

> And even if we could, how to suppress echoing when asking for passwords?

not sure about C, but other languages can handle this pretty straightforward:

https://godocs.io/golang.org/x/term#ReadPassword

> Yes, there are a lot of assumptions present here. Too many for a solid analysis.

the distribution doesnt contain any `bash.exe`:

~~~
> fd bash
etc\profile.d\bash_profile.sh
mingw64\share\git\edit-git-bash.exe
~~~

so it must be coming from BusyBox. otherwise I dont know where its coming from.

> To address a problem like the one you reported, we cannot cut corners. We need to be diligent. And mixing up the order of showing the prompt and reading the answer is not diligent.

nothing is perfect, if you wait for the person solution, you might be waiting for many years. my suggestion is, anything that works would be an improvement over the current state, which is that the fallback does not work.

> That sounds a lot like "it works on my machine, in my one scenario that I tested, and I don't care how many Git for Windows users' use cases it breaks".

no the point is that MinGit doesnt contain MinTTY, so its dubious to even discuss MinTTY in the context of this issue.

> Your approach would literally have the potential to break hundreds of thousands of users' workflows, if not more.

no, because the default helper is still `manager`. this would only impact users try to use the fallback helper, which is currently broken.

> I am starting to suspect that you haven't understood what I implied when I said "[...] it does not [work]. Because /dev/tty is not a thing on Windows.".

Windows does have `CON`, as well as `CONIN` and `CONOUT`. if a C program was used in this context instead of Bash script, then that obviates any need for MinTTY or POSIX or Bash or `/dev/tty`. This is a Windows Git after all, shouldnt we cater to Windows style of operation, instead of trying to force Unix methods?

> The prompt needs to access the terminal, no matter whether the standard handles are redirected or not. No matter whether they are closed or not. No matter whether the standard handles are connected to pipes, even ones connected to other Git processes. In all of these instances, the prompt _still_ needs to access the terminal, _not_ the standard handles.

I believe `CON` and friends suit that purpose.

> And since that terminal is typically an MSYS2 pseudo terminal attached to a MinTTY instance, you have to involve the MSYS2 runtime.

In my case I am not using MinTTY, so it seems this comment does not apply to the posted issue.

**Comment by i1v** [comment]
> ~~~
> PS C:\Users\me\MinGit-2.39.2-64> cmd\git -c credential.helper= ls-remote https://github.com/dscho/xyz
> Username for 'https://github.com':
> ~~~

FYI that command fails as well, with busybox version:

~~~
PS D:\Desktop\MinGit-2.39.2-busybox-64-bit> cmd\git -c credential.helper= ls-remote https://github.com/dscho/xyz
bash: can't create /dev/tty: nonexistent directory
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory
~~~

and not busybox version (why are there two versions?):

~~~
PS D:\Desktop\MinGit-2.39.2-64-bit> cmd\git -c credential.helper= ls-remote https://github.com/dscho/xyz
fatal: could not read Username for 'https://github.com': No such file or directory
~~~

**Comment by i1v** [comment]
to trigger the error, you need to have NO `.gitconfig` on your system
