### ISSUE TITLE
The 64bit version installer installed into C:\Program Files (x86)\Git

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#44]
The right place should be C:\Program Files\Git

**Comment by sschuberth** [comment]
There is no 32-bit version of the installer. The only installer we have is for 32-bit, even on 64-buit Windows.

**Comment by dscho** [comment]
Actually, there is a self-extracting PortableGit for 64-bit Windows: https://github.com/git-for-windows/git/releases/download/v2.3.4.windows.2/PortableGit-64-bit-2.3.4-dev-preview.7z.exe

@lygstate did you install the development environment via the net installer yet? If so, please check out the `build-extra` repository:

```bash
cd /usr/src/build-extra
git fetch
git checkout master
```

You should find the script to generate both 64-bit and 32-bit portable releases in `portable/release.sh`. Could you have a look at [line 97](https://github.com/git-for-windows/build-extra/blob/143a81c4741a1b539dafcb274e3bdca2b04f6c92/portable/release.sh#L97) and at [lines 15--26](https://github.com/git-for-windows/build-extra/blob/143a81c4741a1b539dafcb274e3bdca2b04f6c92/portable/release.sh#L15-L26)? I imagine that another variable needs to be set, depending on the architecture and used in line 97.

**Comment by sschuberth** [comment]
@dscho As you can see from the installation path mentioned by the OP, this issue was filed against the Inno Setup / MSYS1-based installer. As there is no issue in terms of 64-bit with *that* installer I think this issue should stay closed.

Please do not hook this issue for promoting the newly created MSY2-based portable setup.

**Comment by dscho** [comment]
When running the `PortableGit-*.7z.exe`, it suggests the directory `C:\Program Files\Git` as destination (or at least should do so, see https://github.com/git-for-windows/build-extra/blob/143a81c4741a1b539dafcb274e3bdca2b04f6c92/portable/release.sh#L97).

**Comment by sschuberth** [comment]
> it suggests the directory `C:\Program Files\Git` as destination

Indeed. So MSYS2-PortableGit never uses `C:\Program Files (x86)`, but as that's mentioned in PR's title, the OP cannot have referred to MSYS2-PortableGit.

More importantly, MSYS2-PortableGit *should* suggest `C:\Program Files (x86)` if it's the 32-bit version and we're installing on a 64-bit OS.

**Comment by kusma** [comment]
It still can refer to MSYS2-PortableGit, because if the installer is 32-bit, it'll be run under WoW, mapping  "C:\Program Files\Git" to "C:\Program Files (x86)\Git"...

**Comment by dscho** [comment]
git-for-windows/build-extra@12e698f6080a9df774c673ab3f990444d39d3564

**Comment by sschuberth** [comment]
Hmm, does that commit really do what it should? For example, the 32-bit portable installer should install to "C:\Program Files (x86)" on a 64-bit Windows by default. But in a 32-bit MSYS2 environment, `uname -m` returns `i686` even if Windows is 64-bit. So `PROGRAMFILESENV` is set to `PROGRAMFILES`, which in turn is set to `C:\Program Files` instead of the expected `C:\Program Files (x86)`, or?

**Comment by dscho** [comment]
@sschuberth The trick is that the self-extracting code is 32-bit. So `%PROGRAMFILES%` will expand to `C:\Program Files (x86)` on 64-bit Windows. (I also tested the resulting installers to verify).

**Comment by sschuberth** [comment]
Ok, thanks, I can see how this works now. There might be an issue if some one tries to run the portable installer for the 64-bit version on 32-bit Windows (which would work as the SFX is always 32-bit), but in that case the hard-coded use of `ProgramW6432` would fail as it is unset on 32-bit Windows. But that's an edge case we can live with, I guess.

**Comment by dscho** [comment]
> if some one tries to run the portable installer for the 64-bit version on 32-bit Windows

... then I *want* this to fail. What's the point of installing software that cannot run in your setup, after all?

**Comment by sschuberth** [comment]
You would want the installer to gracefully fail, yes (by "fail" above I was meaning to say "fail to expand to a non-empty string"). But AFAIU that's not what's happening right now: The installer would just propose an odd default installation path of `\Git`, but if the user fixes that, installing the 64-bit binaries would succeed although the 32-bit Windows would not be able to run them.

I'm currently looking into fixing this by using a 64-bit SFX module for the 64-bit portable binaries.

**Comment by sschuberth** [comment]
> I'm currently looking into fixing this by using a 64-bit SFX module for the 64-bit portable binaries.

For the record, turns out that there is [no binary distribution](http://sourceforge.net/p/sevenzip/discussion/45797/thread/7502638f/#b570/0323) for the 64-bit SFX module, and building it from source [requires some modifications](sourceforge.net/p/sevenzip/discussion/45797/thread/86f3ef43/). While those modifications are not hard to so, the 7-Zip project makes it very hard to contribute these changes upstream again as it does not provide a public source code repository, the source code is only available as an archive. I'll not spend time working on such a project.
