### ISSUE TITLE
git-bash: Failed to fork child process: No such file or directory.

### ISSUE THREAD

**Issue by SEAPUNK** [git-for-windows/git#440]
Using git 2.5.3.windows.1 on Windows 7 Professional SP1, 64-bit

For some strange reason, at seemingly random times, when I try to open up git-bash again, it gives me that error, refusing to work again, forcing me to reinstall. The window title is `/usr/bin/bash --login -i`, and I'm assuming that's the command it's trying to run.

The last time it gave me the error and stopped working happened when I closed out of the window while it was in the middle of a process (I had to close, confirm, and then press the close button again).

**Comment by dscho** [comment]
How do you start Git? Please write down all details about your setup. Including the options chosen when installing and the way you start Git.

**Comment by SEAPUNK** [comment]
I start git-bash by running a shortcut in my taskbar. I also tried to run it directly, `git-bash.exe` in `C:\Program Files\Git`. Same result.

Installation options:
![](http://puu.sh/knLUs/bfb4df4d36.png)
![](http://puu.sh/knLVf/93afc70972.png)
![](http://puu.sh/knLVP/15def1e7ab.png)
![](http://puu.sh/knLWG/3b7e2faaa1.png)
![](http://puu.sh/knLXc/800b0c2cdf.png)
![](http://puu.sh/knLXM/cf26deca7a.png)

I also have a `.bash_profile`, which contains:

`cd D:/Users/Owner/code`

**Comment by SEAPUNK** [comment]
Some more info:
`C:\Program Files\Git\bin\bash.exe` exists, and when I open THAT up, it opens up a cmd window that [runs bash just fine](http://puu.sh/knMgT/81485bae29.png).

**Comment by dscho** [comment]
> I start git-bash by running a shortcut in my taskbar.

That is incomplete information. How did that shortcut end up in that taskbar in the first place? Git for Windows does not install that. Please do not leave out crucial information like that, it only extends the time until I can help you effectively because you'll have to tell me those things anyway.

**Comment by SEAPUNK** [comment]
I clicked and dragged the "Git Bash" icon from the start menu search (for git bash) onto the taskbar.

I seriously doubt that it's crucial information, though, since the same error happened when I tried to *open the file directly* (as in, from the Program Files folder).

**Comment by dscho** [comment]
@SEAPUNK The default use case is to install, with all options left to their defaults, and then click Git Bash from the start menu. It works well enough, otherwise this bug tracker would be overflowing with bug reports. Therefore, the default use case seems to work everywhere. That means that whatever does not work for you must be due to a *difference* in the default use case. The more information you withhold about your non-default use case, the more likely is it that I cannot help you and that both of us get very, very frustrated.

So let's avoid that, and include all information, like I asked for, and as our [issue reporting guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) suggest.

As it is, I still have not enough information to understand this issue report, and I still have no way to reproduce the problem on this side (ideally, you would come up with a [Minimal, Complete and Verifiable Example](http://stackoverflow.com/help/mcve)), and whatever time I had to spend on this ticket for this weekend is now depleted by our current exchange.

I'll try to get back to this ticket on Monday.

**Comment by dscho** [comment]
Oh, one last thing for today: if you have installed something like Cygwin, MSys1, Git for Windows 1.x (even a portable version) or anything that is essentially based on Cygwin's POSIX emulation layer, that is probably important information, too.

**Comment by SEAPUNK** [comment]
No need to do Monday, Monday is the day I get back to work. Tuesday should give me enough time to collect enough information about the problem.

**Comment by SEAPUNK** [comment]
I'll close this issue for now; I haven't gotten another error like this for some time.

**Comment by neoadventist** [comment]
I got this error `Failed to fork child process: No such file or directory.` Just now. Happened when I changed my Path to include the android SDK. Will see if this happens If i restart.

**Comment by ShaneCarr** [comment]
I ran into this problem too. Pointing my git hub gui process to the version of bash.exe deployed by a fresh install of git for windows resovled the issue.  In my case after a windows update and reboot I got into this state. Probably something is corrupted (perhaps in registry) pointing to the wrong version of bash. Maybe this can help with the investigation.  I did a clean install of the git tools and this issue stuck around. I had to manually point it which you can do from the settings.After this it fixes up the cmdline as well since it probably uses the same settings.

**Comment by keithjjones** [comment]
:+1: I have this on a fresh Windows 10 Enterprise, with the MS Azure domain.  Broken in Cygwin too.

**Comment by dcneeme** [comment]
the same with my win 10, fresh git install, configured to use git bash only.

**Comment by dcneeme** [comment]
works without that error if run as administrator!

**Comment by keithjjones** [comment]
@dcneeme I traced my problem to using a domain account.  A non domain account worked fine.  Did you run the first one as a domain account, but then run the second one as a local administrator?

**Comment by SamDeBlock** [comment]
@keithjjones Same issue here, also with an azure domain account. It always worked with regular accounts.
When I run bash.exe directly, I get a bash prompt which opens up to Unknown+user@foo MING64 /bin

**Comment by dscho** [comment]
@SamDeBlock any chance that you could give me temporary access to a machine with that account? In the alternative, I could walk you through debugging the problem.

**Comment by garrytrinder** [comment]
I have the exact same issue, however I temporarily fixed it by enabling "Run as administrator" in the Advanced settings of the Shortcut file.

![image](https://cloud.githubusercontent.com/assets/11563347/15706712/eac5210a-27ec-11e6-8e09-222fe1bfa1f2.png)

**Comment by jfjcn** [comment]
Also an issue with an account via email on Windows 10, not just a domain account.  Local accounts seem to work fine since I have this installed on another machine and there is no issue with that one.

**Comment by dscho** [comment]
> Also an issue with an account via email

@jfjcn could you please elaborate?

**Comment by jfjcn** [comment]
Windows supports three kinds of accounts:

1. Local accounts - simply an account on the host.  Think standard *NIX accounts.  So a typical username might be 'jsmith' or 'jdoe'.
2. Domain accounts - there are one or more central authentication servers allowing logins onto a given host.  Think LDAP server on the network doing authentication owned by a company/organization for its employees/contractors.  So example accounts would be 'PrivateCompany\jsmith' or 'Walmart\jdoe'.
3. Email accounts - like domain accounts, except that the authentication server is a Microsoft server on the Internet using your personal email as the username.So example accounts would be 'jsmith@outlook.com' or 'jdoe@gmail.com'.

**Comment by keithjjones** [comment]
Note that my email account seems to be working fine with it on two computers (Windows 10).  It was only when I was hooked up to Azure for AD that there were issues.

**Comment by jfjcn** [comment]
I have it on two computers - one with email and one with local account, and I'm only having issues on the email.  Maybe that's not the core issue then?  Let me know what I can do to help troubleshoot!

**Comment by keithjjones** [comment]
It seems to be a home directory issue, of some sort, when I looked into a while back.  The home directories seemed to be different for AD than other accounts.  My home directory for my email account looks like a normal home directory.  I don't know if this is what the problem is.  It is just an educated guess on my part.

**Comment by lilred** [comment]
Same issue here. Fresh install of Windows 10.

**Comment by SEAPUNK** [comment]
I'll go ahead and reopen the issue for visibility, but I won't be active here because I no longer use this (I'm on a full Linux environment now).

**Comment by dscho** [comment]
@SEAPUNK since you closed it, others have opened new tickets for the same issue. So let's head over to https://github.com/git-for-windows/git/issues/580 to discuss this further (or to work on it, if anybody feels up to the task).
