### ISSUE TITLE
git clone open error

### ISSUE THREAD

**Issue by liuchanglongs** [git-for-windows/git#4411]
git clone open Error
fatal: protocol error: bad line length character: HTTP

**Comment by rimrul** [comment]
This sounds a lot like this issue:

https://lore.kernel.org/git/a7cf2f3bbc6dcd8758e188f79d31e6e0bff44ea3e768fce482309ba532205f6b@mahalux.com/T/#u

**Comment by dscho** [comment]
Indeed, this sounds as if it is an issue not specific to Windows. I am not 100% certain because the reporter chose to delete the bug reporting template and replace it by a too-terse two-liner.

I'll close the ticket and will suggest to send a reply to above-mentioned mail, preferably with enough information (i.e. much more than has been provided).
