### ISSUE TITLE
Bitdefender quarantines git-gui.exe and gitk.exe as trojans.

### ISSUE THREAD

**Issue by ravenland** [git-for-windows/git#444]
Title says it all, when unpacking PortableGit-2.5.3-32-bit.7z.exe Bitdefender quarantines git-gui.exe and gitk.exe as trojans.

**Comment by PhilipOakley** [comment]
Subject: [git] Bitdefender quarantines git-gui.exe and gitk.exe as trojans. (#444)


  Title says it all, when unpacking PortableGit-2.5.3-32-bit.7z.exe Bitdefender quarantines git-gui.exe and gitk.exe as trojans.

Report the false positive to BitDefender... 
It is said that 'they' (the virus scanners) tend to report anything packaged with the open source Inno-setup, because it is misused by some..

**Comment by dscho** [comment]
The funny thing is that `git-gui.exe` (which is bytewise identical to `gitk.exe`) differs from `git.exe` only by a couple of bytes in the file *header* -- essentially marking the former as GUI executable and the latter as console one.

So why is it that `git.exe` is fine?

I am really getting a bit tired being distracted from *real* bugs by these bogus claims...

I guess I will have to start signing those executables, too, as it magically makes virus scanners stop believing that there are Trojans.

Granted, we do call the real Git GUI from `git-gui.exe`. Which is consistent with Trojans' calling their real payload. But that is where the similarities end.

@ravenland please also note that your report included no information that could possibly have helped to fix the issue -- if there had been any. At least the name of that Trojan, better a link to its description, would have been needed. Please try to follow our [guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) when reporting issues.
