### ISSUE TITLE
msys2-runtime: update patch for getprocaddr.c

### ISSUE THREAD

**Issue by wm1** [git-for-windows/git#4442]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

None. I installed "Git for Windows SDK" at https://gitforwindows.org/#download-sdk

==> Making package: msys2-runtime 3.4.6-4 
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2965], 64-bit
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

None.
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git for Windows SDK. Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
 - On a clean Win10 machine, install Git for Windows SDK
 - Start the shell
 - sdk init msys2-runtime
 - sdk cd msys2-runtime
 - sdk build msys2-runtime
```
 - What did you expect to occur after running these commands?

build msys-2.0.dll successfully

 - What actually happened instead?

```
"sdk init" reported some error for every remote: cygwin, msys2, git-for-windows

Updating cygwin
error: unable to normalize alternate object path: /usr/src/MSYS2-packages/msys2-runtime/msys2-runtime/objects
fatal: bad object refs/tags/EOL_registry_mounts
error: https://github.com/Cygwin/cygwin did not send all necessary objects
error: Could not fetch cygwin

"sdk build" exits early with error:

From https://github.com/git-for-windows/MSYS2-packages
 * branch              HEAD       -> FETCH_HEAD
Already up to date.
==> Making package: msys2-runtime 3.4.6-4 
   ...
  -> Applying 0023-Add-a-helper-to-obtain-a-function-s-address-in-kerne.patch
error: winsup/utils/mingw/getprocaddr.c: already exists in working directory
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

None

**Comment by wm1** [comment]
Attach the outputs from shell: [msys2-build-issue.txt](https://github.com/git-for-windows/git/files/11548579/msys2-build-issue.txt)

**Comment by dscho** [comment]
@wm1 thank you for the bug report! A teammate of mine encountered the same issue this past week, and both were under a time crunch and lacked the time to even just record the problem. So: thank you for doing that! 😃 

> error: unable to normalize alternate object path: /usr/src/MSYS2-packages/msys2-runtime/msys2-runtime/objects

That looks as if a MINGW `git.exe` is fed an MSYS path. (For context, see https://www.msys2.org/docs/filesystem-paths/)

It all happens in the context of [package management](https://github.com/git-for-windows/git/wiki/Package-management).

The problem is most likely that Pacman's `makepkg` treats `git+https://`-style source URLs by first creating a bare clone of the repository in the same directory as the `PKGBUILD` file that holds the package definition, then creates _another_ clone, a non-bare one, in the `src/` subdirectory. And this latter clone is using the bare clone as a [`--reference`](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---reference-if-ableltrepositorygt). That option asks `git clone` to set up an [alternate repository](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefalternateobjectdatabaseaalternateobjectdatabase), which is done by adding an absolute path to a certain file deep within the `.git` directory.

And herein lies the rub: that _absolute path_ is either a regular Windows path (with drive letter and all), if the `git clone` command was performed by a MINGW Git (typically `/mingw64/bin/git.exe`), or if it was performed by an MSYS Git (`/usr/bin/git.exe`), it is a pseudo-Unix path that is relative to the directory where the `/usr/bin/msys-2.0.dll` file is installed, i.e. the POSIX emulation layer known as the MSYS2 runtime (is PELKATMR a good acronym for that? 😉).

Therefore, any such `git clone --reference [...]` performed by a MINGW Git will result in a repository that cannot be used with an MSYS Git, and vice versa.

To work around this, I have started to replace these absolute paths by relative ones: those are relative to the directory in which the `alternates` file lives, and is handled correctly by both MINGW and MSYS flavors of the Git executable. There is code in https://github.com/git-for-windows/git-for-windows-automation/blob/65a23e20ee99a88843c987a04375857c6f812669/.github/workflows/git-artifacts.yml#L241 to do exactly that, and I think we will need something similar in [the code that backs `sdk build msys2-runtime`'s initialization](https://github.com/git-for-windows/build-extra/blob/dd1584b7670450629b4a84be907f7a244b06b4f5/git-extra/git-sdk.sh#L186).
