### ISSUE TITLE
Git-Bash cursor in windows-11

### ISSUE THREAD

**Issue by ealaz** [git-for-windows/git#4485]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

PyPortfolia >>git --version --build-options
git version 2.41.0.windows.1
cpu: x86_64
built from commit: ff94e79c4724635915dbb3d4ba38f6bb91528260
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621

```
$ cmd.exe /c ver

** insert your machine's response here **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Bash  **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
I hope I explain clearly: here goes
In my other, windows 10 machines when I move the "Windows" cursor into the g-tbah terminal window
I see an "I" cursor. That is the mouse pointer turns into the I. This allows me to grab text. In windows 11 that cursor vanishes instead of turning into an I. I can still grab text and copy it. The problem is I am grabbing blindly as I don't see the cursor.
```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by rimrul** [comment]
I'll assume you chose `MinTTY` during setup, not `Conhost`, because this sounds like `MinTTY`.

> I see an "I" cursor. That is the mouse pointer turns into the I. This allows me to grab text. In windows 11 that cursor vanishes instead of turning into an I.

I do get the I-Beam cursor on Windows 11, but I have a clue what might be causing this. [`MinTTY` has an option to hide the mouse cursor during text input that is enabled by default](https://mintty.github.io/mintty.1.html). It sounds like there is an issue with your keyboard or keyboard driver and your Git Bash window is constantly recieving some non-modifier non-printing keyboard input which causes `MinTTY` to hide your mouse cursor so it doesn't block what you're "typing".

You can disable this behaviour by adding the line `HideMouse=off` to your `~/.minttyrc` file.

`echo HideMouse=off>>~/.minttyrc`

You'll need to close and reopen Git Bash for this setting change to come into effect.
