### ISSUE TITLE
git log -G fails with "cannot spawn astextplain: No such file or directory" error

### ISSUE THREAD

**Issue by Radrik5** [git-for-windows/git#449]
I use Git 2.5.3 64 bit on Windows 7.

MCVE:
```
Projects $ git clone git@github.com:Radrik5/test-git-log-g.git
Cloning into 'test-git-log-g'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), done.
Checking connectivity... done.

Projects $ cd test-git-log-g/

test-git-log-g $ GIT_TRACE=1 git log -GIniFileFontSection -p
20:03:40.055339 git.c:348               trace: built-in: git 'log' '-GIniFileFontSection' '-p'
20:03:40.057339 run-command.c:335       trace: run_command: 'less'
20:03:40.059339 run-command.c:335       trace: run_command: 'astextplain' 'C:/Users/Radrik5/AppData/Local/Temp/iA3cU9_Document.rtf'
error: cannot spawn astextplain: No such file or directory
fatal: unable to read files to diff
```

**Comment by Radrik5** [comment]
`astextplain` is absent in `C:\Program Files\Git` and subfolders.

**Comment by rimrul** [comment]
`astextplain` should be in `/mingw32/bin` or `/mingw64/bin`. How did you install your Git? Are you using the 32bit or the 64bit version? What options did you chose when installing? Did you run a clean install or an upgrade?

**Comment by dscho** [comment]
> astextplain should be in /mingw32/bin or /mingw64/bin

It should actually be in `/usr/bin/`...

It looks a little bit different here:

```sh

$ git clone https://github.com/Radrik5/test-git-log-g
Cloning into 'test-git-log-g'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
Checking connectivity... done.

me@work MINGW64 ~
$ cd test-git-log-g/

me@work MINGW64 ~/test-git-log-g (master)
$ GIT_TRACE=1 git log -GIniFileFontSection -p
20:23:16.337925 git.c:348               trace: built-in: git 'log' '-GIniFileFontSection' '-p'
20:23:16.344769 run-command.c:335       trace: run_command: 'less'
20:23:16.387786 run-command.c:335       trace: run_command: 'astextplain' 'C:/Users/me/AppData/Local/Temp/6djQ18_Document.rtf'

me@work MINGW64 ~/test-git-log-g (master)
$ echo $?
0
```

**Comment by dscho** [comment]
... and

```sh
$ which astextplain
/usr/bin/astextplain
```

**Comment by dscho** [comment]
Ah, oops. I tested with a test installer. And when I dug deeper, it looked as if a bogus `git-extra-1.1.75` was installed at the time the installer was built (it should have been `git-extra-1.1.74`, so I assume that `pacman` did not update the package because it thought that would have been a downgrade).

In any case, I verified that the next installer will contain `astextplain`.

**Comment by Radrik5** [comment]
Release 2.5.3 32 bit does contain `astextplain` but release 2.5.3 64 bit doesn't.

**Comment by dscho** [comment]
Yep, that was my finding, too. It was simply an oversight that a package I built during the development process of `git-extra` was marked with a higher version number than it should have had (this happens when I add `fixup!` commits, build for testing, and then rebase: the number of commits touching the `git-extra/` directory is used as last part of the version number).

All is well with [Git for Windows 2.6.0](https://github.com/git-for-windows/git/releases/tag/v2.6.0.windows.1.

**Comment by Radrik5** [comment]
Yes, I can confirm that release 2.6.0 64 bit contains `astextplain` and `git log -G` works fine with .rtf files.

Thank you!
