### ISSUE TITLE
Do not require the SDK to build the SDK self-extracting archive

### ISSUE THREAD

**Issue by sschuberth** [git-for-windows/git#45]
The current version of the [script](https://github.com/git-for-windows/build-extra/blob/master/net-installer/release.sh) to build the self-extracting archive for the SDK requires to be run from an existing installation of the SDK (or at least from an existing MSYS2-based portable installation), which creates sort of a chicken-and-egg problem.

It would be nice if the script would instead "bootstrap" the required files (e.g. by downloading and extracting the required pacman packages via wget to some chroot-like environment). This would allow to build the SDK's self-extracting archive from e.g. MSYS1, or even on Linux (provided that 7-Zip is installed).

**Comment by dscho** [comment]
Given that we have ~70x more Git for Windows downloads than net installer downloads, and *especially* given that our net installer does not need to be re-released, once it works correctly with proxies, I would rather focus on that InnoSetup script for building end user installers. More bang for the buck.

**Comment by dscho** [comment]
Actually, I do not see the point of this. The net installer, once it stabilizes, will not need to be updated ever again (or at least only rarely).

**Comment by sschuberth** [comment]
I'm looking at this from a CI / testing perspective. There will always be first-time users of the net installer, and as such we should test it on CI (I imagine it could break because of URLs becoming invalid, for example). But if testing the net installer requires the net installer to have run and installed the SDK before, you basically define your first net installer to be good. Sure, you *can* do that and say "I've tested the first version manually, future versions will be tested by CI", but it just does not feel right to me from an automation perspective.

**Comment by dscho** [comment]
> I'm looking at this from a CI / testing perspective. There will always be first-time users of the net installer, and as such we should test it on CI [...]

Okay, let's assume that you want to test the Git SDK installer. Despite the fact that it would require interaction with the user to know the installation path; We could skip that and use 7-Zip to unpack -- somehow, because we would then need a command-line 7-Zip, and how would we obtain *that* in a CI task?

Even then, running the Git SDK installer would require downloading about 200 GB *every time it is tested*.

Let's assume that this is still not convincing enough to stop us from such an endeavor. Then we still have the problem that MSys2's Pacman repositories live on SourceForge. And SourceForge's services are known to have occasional outages. Do you want to be notified about those breakages when testing the Git SDK installer?

> But if testing the net installer requires the net installer to have run and installed the SDK before

Why, it does not?!? Downloading the installer from https://github.com/git-for-windows/build-extra/releases/ will give you a self-extracting 7-Zip archive that is pretty self-contained (modulo net access to download all of the packages).

I must misunderstand some aspect of this ticket, then.

**Comment by dscho** [comment]
Thinking about this again: @sschuberth were you referring to the self-extracting archive that is the portable Git?

**Comment by sschuberth** [comment]
@dscho As discussed in person at GitMerge 2015 I was really meaning the SDK installer ;-)

**Comment by dscho** [comment]
Indeed... And I still think (as I mentioned ;-)) that it is not crucial to build that installer or test it. But I am certainly happy if you want to work on it... :smiley_cat:

**Comment by dscho** [comment]
Let's just close this ticket. Nobody is working on it, and [I am still convinced that this feature is unnecessary](https://github.com/git-for-windows/git/issues/45#issuecomment-91249240).
