### ISSUE TITLE
Git-flow not tagging last commit on master branch

### ISSUE THREAD

**Issue by burbanczyk** [git-for-windows/git#450]
Hi
Great news you added git-flow into msysgit.
I'm not 100% sure, but shouldn't the master branch be tagged on merge?
Instead the last hotfix commit or last release commit gets the tag.
I guess it might be related to this issue https://github.com/nvie/gitflow/pull/428

**Comment by dscho** [comment]
> Great news you added git-flow into msysgit.

We did not. The project called `msysGit` was retired on August 15th 2015.

> I'm not 100% sure, but shouldn't the master branch be tagged on merge?

Ah, you assume that we start following the same branching model? No, we do not. We continue with our tried-and-tested model. We just offer `git flow` to those users who want to use it (but had problems because `git-flow` fell unmaintained, and as a consequence it was unnecessarily hard for plain users to install `git flow` into their Git for Windows).

**Comment by burbanczyk** [comment]
<blockquote>Ah, you assume that we start following the same branching model? No, we do not. We continue with our tried-and-tested model. We just offer git flow to those users who want to use it (but had problems because git-flow fell unmaintained, and as a consequence it was unnecessarily hard for plain users to install git flow into their Git for Windows).</blockquote>
I don't get it, aren't you using Vincent Driessen's branching model v0.4.2 /usr/bin/git-flow* which should create tags on merge?
I'm new to the matter and the only reason I'm asking is that I'm worried it will be tagged differently using git-flow on OsX.
I agree installing git flow into Git for Windows was painfull and thanks for for helping out with that.

**Comment by dscho** [comment]
> aren't you using Vincent Driessen's branching model

No, we do not. We ship the *tool* so Git for Windows *users* can use it, but the Git for Windows project itself does *not* use that branching model.
