### ISSUE TITLE
usr/bin/bash.exe is extremely slow now and starts up with 'FIND: Parameter format not correct'

### ISSUE THREAD

**Issue by aenichols** [git-for-windows/git#4520]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64-bit

```
$ git --version --build-options

** ::<> bin  git --version --build-options
git version 2.41.0.windows.3
cpu: x86_64
built from commit: 4a1821dfb0c2160a4fcc85d2845f095c54339578
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon **

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit? 10 64-bit

```
$ cmd.exe /c ver

** ::<> bin  cmd.exe /c ver
Microsoft Windows [Version 10.0.19044.3086]
(c) Microsoft Corporation. All rights reserved.

C:\Program Files\Git\usr\bin> **


```

 - What options did you set as part of the installation? Or did you choose the
   defaults? defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** ::<> bin  cat ../../etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled **

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Windows Terminal - "C:\Program Files\Git\usr\bin\bash.exe" **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** Launching "C:\Program Files\Git\usr\bin\bash.exe" **
```
 - What did you expect to occur after running these commands?

** bash to promptly run **

 - What actually happened instead?

** blank screen for 19.13 sec (20 on average) responds: FIND: Parameter format not correct
::<> bin

Then a lot of the git commands are awfully slow.
  **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by landstander668** [comment]
That error sounds like there's something in your `$HOME/.bash_profile` or `$HOME/.bashrc` file which is taking a long time to complete. So I'd start by taking a look at those two files, assuming they're present.

In addition, the `FIND: Parameter format not correct` error is most likely coming from the Windows `find` utility, rather than the version provided by Git for Windows. The two incarnations have different quoting rules (see [here](https://stackoverflow.com/questions/70105981/tzutil-find-parameter-format-not-correct-powershell-command) for an example) which probably explains the error message.

Is there any specific reason you're running `C:\Program Files\Git\usr\bin\bash.exe` directly? I'd suggest launching the Git Bash wrapper instead, as it performs various environment fixups (such as setting `$PATH` appropriately) before launching Bash.

**Comment by aenichols** [comment]
Thank you for the insight. I have tested this on an isolated environment. It is definitely a me issue. I appreciate your time. Hopefully I can find the cause now.
