### ISSUE TITLE
Icon change to folder when creating a local repo

### ISSUE THREAD

**Issue by cpic86** [git-for-windows/git#4524]
Win 10- x64, git ver. 2.38.1
When creating a local repository in a folder is there a possibility of having the folder icon change to indicate its now a local repo. Such as a green checkmark or something like that. I know other source control apps I've seen it changes the folder to indicate that the folder is now a local repo. Without this you may forget its a repo

**Comment by dscho** [comment]
This sounds like a feature for a full Windows Explorer extension, such as https://gitextensions.github.io/.

Git for Windows used to ship with its own Windows Explorer extension ([GitCheetah](https://github.com/msysgit/Git-Cheetah)), but due to lack of contributors' interest the project was archived and the extension unshipped.
