### ISSUE TITLE
Implement package and database signing

### ISSUE THREAD

**Issue by elieux** [git-for-windows/git#456]
It seems that the package databases at Bintray are not signed, as well as the packages. It would be nice to have everything signed. I'm not sure if it has been discussed somewhere previously, and I apologize for the noise if it has.

For an overview of the process and requirements, see [my short pacman signing guide](https://gist.github.com/elieux/fad9451bbfc4ddb5cde7).

**Comment by dscho** [comment]
Thanks for reminding me (I am sure you pointed me to your guide before)!

**Comment by dscho** [comment]
Okay, I uploaded signatures now. But... it was quite a bit more painful than anticipated because I seem to miss where `gpg-agent` is, so I had to type in my passphrase a gazillion times.

@elieux any idea how to fix that? And... what do I need to do to get my public key into the appropriate package?

**Comment by elieux** [comment]
I don't think MSYS2 includes gpg-agent, but I forgot the explanation (if I ever got one). I have a TODO item to somehow fix that (maybe using a gpg-agent from another gpg bundle), but in the meantime, KeePass and/or the clipboard helps me with the repeated typing.

I'll get back to you on the key inclusion later.

**Comment by dscho** [comment]
Oh my. This ticket sure caused much more pain than I anticipated!

**Comment by elieux** [comment]
Sorry for reacting so late. The default trusted keys for pacman are provided by the `msys2-keyring` package. For your key to appear in the SDK installation, you have to either:

1. get your key accepted, cross-signed and included upstream, or
2. fork the package and include your key there, or
3. create a new, similar package with your key, or
4. just add the key during the SDK preparation/packaging process.

(The first three methods involve post-install scripts.)

There are two steps to having the key locally trusted:

1. download the key into pacman's key store (`pacman-key --recv-keys <pubkeyhash>` or `pacman-key --add <pubkeyfile>`)
2. locally sign the key (`pacman-key --lsign-key <pubkeyhash>`)

**Comment by elieux** [comment]
And I think I know what's wrong with the package signatures (as mentioned on gitter). The package entries in the `.db` file don't mention the signatures. I assume that's because you didn't re-`repo-add` the packages after signing them with gpg. I didn't know that this can happen (although it makes sense -- it'd be bad security otherwise). I'll update my signing guide in a minute to reflect this.


The issue looks like this:
```
$ pacman -S mingw-w64-x86_64-git
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-git-2.6.0.1.b73d37c-1

Total Installed Size:  30.09 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                              [###############################################################] 100%
(1/1) checking package integrity                                                                            [###############################################################] 100%
error: mingw-w64-x86_64-git: missing required signature
error: failed to commit transaction (package missing required signature)
Errors occurred, no packages were upgraded.
```

**Comment by dscho** [comment]
I decided to roll back the signatures. This entire process was ill-planned, and of course I take al the blame for that. I thought that there was a gentle upgrade path, but of course reality proved my expectation to be truly ill-considered.

For now, I will recover from the experience and then maybe try to come up with a proper plan that does not affect existing as well as new users of the Git for Windows SDK negatively.

**Comment by elieux** [comment]
Okay. Tell me if and when you need anything.

**Comment by dscho** [comment]
I have no idea what I need, and when. I just know that trying to enable signed packages caused me a lot of grief, so I will postpone it for now.

**Comment by dscho** [comment]
Wow. That was painful, even having the warning of how badly it went the first time. What business, for example, does the `gnupg` package have wiping out Pacman's keyring, for example, *and then only repopulate using `msys2-keyring`*? Sheesh. It should *not* have been that cumbersome to address this ticket, those were completely arbitrary and unnecessary obstacles.

**Comment by dscho** [comment]
To be precise, what I thought was that https://github.com/git-for-windows/build-extra/commit/416406e1c66d3372c48d0feec7748c0b0a8405e1 (adding `git-for-windows-keyring`, which took long enough to research, I had no clue where to look how Pacman's keyring is managed, so I had to dig through source code...) and https://github.com/git-for-windows/build-extra/commit/46e520d7ad6b7e51a61a612fdeedaf48bd1a8af7 (make sure that signatures are created and uploaded).

But I also had to ensure that `git-for-windows-keyring` will get installed by https://github.com/git-for-windows/build-extra/commit/c35041f2b192a2c62e52c5593c4424c72ac3400d (making it a dependency of `git-extra`), which meant that I also had to do https://github.com/git-for-windows/build-extra/commit/d85b21ff7300ca76dac868dc58e9519cc8db1991 (exclude `git-for-windows-keyring` from being bundled in the installer).

I also had to add https://github.com/git-for-windows/build-extra/commit/d06a40acbaa8fe9d77e657cb77cf9152ab67507f to ensure that the environment variable `GPGKEY` is set when i bundle packages because there seems not to be a way to configure this via a custom configuration file. Likewise, this lack of configurability led to https://github.com/git-for-windows/build-extra/commit/32131b12532666e3a19058e7f6adcd2504ff498d, where I ensure in yet another early path that `GPGKEY` is set.

As `repo-add` does not support adding signatures to packages that miss signatures on the fly, I had to add https://github.com/git-for-windows/build-extra/commit/cf2842d00b59570d3276ef5a1974cdf2cca0392a (a separate subcommand to add missing signatures and upload them to the appropriate packages).

Obviously, I had to recreate the SDK installer. This should have been a simple re-run of `build-extra`'s `sdk-installer/release.sh` script, but required https://github.com/git-for-windows/build-extra/commit/422cee4eb185614e413d947ddcee07de324bef53 because we have a new SFX component that does not support the `%%T` placeholder previously used by the SDK installer (I hoped never needing to upgrade the SDK installer ever again, hence I did not bother to check whether its release script was compatible with the new SFX).

But the SDK installer still did not work correctly. I had to add https://github.com/git-for-windows/build-extra/commit/2f1934cb34796e820ef9aaf8ffa78bfb6a9ab4d7 to support obviously new dependencies for `pacman-key`, and also https://github.com/git-for-windows/build-extra/commit/903ceebe4c7e85a27dfae6bc25be1c1fe69e7baf to add `find.exe` which is now required by `info`'s post-install script. While at it, I added a simply style fix with https://github.com/git-for-windows/build-extra/commit/95b7892134bf6dc1613c1ec0f23a7b076e6e82e8, too.

But the SDK installer *still* did not work correctly, despite having the fully populated Pacman keyring.

Turns out that `pacman`, when being installed from scratch, does *not* detect pre-populated keyrings, but just blasts any pre-existing keyring out of the way. Great.

So I had to add https://github.com/git-for-windows/build-extra/commit/23b2f92e6ad70d1675c9f91310d8de519d447aee to include the keyrings in the SDK installer, and https://github.com/git-for-windows/build-extra/commit/ce032c79515557ceb644d802fe980fd55274a4a3 to ensure that it is *reinstalled* after Pacman blows away our carefully initialized keyring. It took several attempts (and a really frustrating hour) to get that latter commit right, as not only `pacman` nukes the Pacman keyring when it is installed, `gnupg` also nukes it when it gets installed.

However, as I found out much later, to my chagrin, when `gnupg` gets *upgraded*, it *also* nukes the Pacman keyring and recreates it *just from `msys2-keyring`* WTF?!?!.

This broke many a CI build, requiring https://github.com/git-for-windows/build-extra/commit/18c48bc2c67fe5992277effca2a340fac789ed40 to fix, and because that fix only affects CI builds, another fix was required: https://github.com/git-for-windows/build-extra/commit/65f1d6631830ff40edabeb0d16fcd61a211c4f42 (repopulate the Git for Windows-specific part of the Pacman keyring whenever it has so inappropriately been blown away).

Sadly enough, these last two fixes *only* work if users are aware that `git-extra` has to be reinstalled from time to time, to fix the mess caused by MSYS2's upgraded packages' post-install script and overwritten configuration files with global, non-overrideable defaults.

So there you go. I should just have refused to address this ticket. It caused more pain and suffering than benefit, and it's not like the interested parties showered me with helpful information.

**Comment by elieux** [comment]
I'm sorry to hear that. While dealing with my own repository, I was aware that my key vanishes from the Pacman keystore from time to time, but I attributed that just to updates of `msys2-keyring`; I had no idea there were so many triggers for that.

> it's not like the interested parties showered me with helpful information

I would be happy to help (still am) in any way I can, but I didn't even notice you started to work on this again. (I hope I didn't miss any email.)

**Comment by dscho** [comment]
Well, I kinda hoped that somebody (you?) would tell me everything I need to know, but [this information](https://github.com/git-for-windows/git/issues/456#issuecomment-145371974) was a little misleading: for starters, the keys should not be added manually, of course, but Pacman's convention is to put the keyring into a specific location. While I would have loved to have a condense step-by-step recipe, https://wiki.archlinux.org/index.php/Pacman/Package_signing#Managing_the_keyring had all the information I needed (but unfortunately plenty more information, too).

Previous experience with the MSYS2 maintainer strongly suggested that I should not even bother to try getting my key accepted into `msys2-keyring`, too.

It is still a major bug that `gnupg` (and also an initial `pacman` install) simply blow away carefully-added keys. Maybe you could do something about that.

**Comment by elieux** [comment]
> It is still a major bug that gnupg (and also an initial pacman install) simply blow away carefully-added keys. Maybe you could do something about that.

I will try to do at least that. Tracking over at msys2/msys2#62.

**Comment by dscho** [comment]
Thanks.
