### ISSUE TITLE
Prefer USERPROFILE to HOMEDRIVE+HOMEPATH

### ISSUE THREAD

**Issue by jaraco** [git-for-windows/git#4625]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

2.40.0.windows.1

64-bit

```
@ git --version --build-options
git version 2.40.0.windows.1
cpu: x86_64
built from commit: 1d90ca2906dd4b7ddaf0669a13c173ec579d794a
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
@ cmd /c ver

Microsoft Windows [Version 10.0.23440.1000]
```

I happen to be using Windows for ARM.

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
 @ cat r'\Program Files\Git\etc\install-options.txt'
Editor Option: VIM
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

xonsh

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
 bug @ mkdir \tmp
 bug @ ls /tmp
 bug @ cat >> /tmp/.gitconfig
[user] 
email=joe@pie.com
^Z
 bug @ git config user.email
jaraco@jaraco.com
 bug @ $USERPROFILE='/tmp'
 bug @ git config user.email
jaraco@jaraco.com
 bug @ $HOMEPATH='/tmp'
 bug @ git config user.email
joe@pie.com
 bug @ del $HOMEPATH
 bug @ git config user.email
joe@pie.com
```

 - What did you expect to occur after running these commands?

The `user.email` value should have been `joe@pie.com` after overriding `$USERPROFILE`.

 - What actually happened instead?

The `user.email` was only overridden by setting $HOMEPATH or removing that variable.

---

There's [some evidence](https://github.com/mitchellh/go-homedir/issues/23) that USERPROFILE is preferred over HOMEDRIVE+HOMEPATH including [this Microsoft reference](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid?redirectedfrom=MSDN). It doesn't explicitly state that HOMEPATH is deprecated, but only USERPROFILE is mentioned, suggesting HOMEPATH is there only for legacy compatibility.

Moreover, I'm using [tox](http//tox.wiki) that only honors passing USERPROFILE:

```
@ tox config -k pass_env
ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at C:\Users\jaraco\draft\bug
[testenv:py]
pass_env =
...
  CXX
  HOME
  LANG
...
  USERPROFILE
...
```

Additionally, [Python gives precedence to USERPROFILE](https://docs.python.org/3/library/os.path.html#os.path.expanduser).

Why is it a problem that Git prefers the legacy value? It means that projects like [pytest-home](/jaraco/pytest-home) must patch both USERPROFILE and HOMEPATH in order to affect both Python and Git. It also means that it's difficult to write tests that capture this missed expectation. I tried to [capture the fault in this test](https://github.com/jaraco/pytest-home/commit/18099bc4288ac8ec4afb8ee9a80526e9242646b0), but because `tox` filters `HOMEPATH`, the setting of `USERPROFILE` actually works. If I were to instruct tox to pass those variables, the flaw (in the environment patching) is [revealed](https://github.com/jaraco/pytest-home/actions/runs/6412917981/job/17411008575).

Therefore, the [code that maps](https://github.com/git-for-windows/git/blob/49aad3ca5264d9b543a8849ee6cf7d3231ebf025/compat/mingw.c#L3488-L3511) from legacy environment vars should prefer USERPROFILE and possibly even drop support for HOMEPATH.

**Comment by dscho** [comment]
@jaraco unfortunately, what you desire is not as easy as waving a wand and changing the default behavior, not by a long stretch. Not unless you want to send mobs with pitchforks after me: The behavior was changed (_away_ from what you propose here) in 2009: https://github.com/msysgit/msysgit/commit/6b096c9651da0d032a0e611d5edee7256e0da3c1 (and yes, the change was first made in msysGit's `/etc/profile`, then ported to `/cmd/git.cmd` in https://github.com/msysgit/msysgit/commit/53e5b4faac83b8c503014612927e167968217854, then reimplemented in C as `git-wrapper.c` in https://github.com/msysgit/msysgit/commit/893b221982321303e1a31b2098cd115c65ca49ab, then moved to `compat/win32/git-wrapper.c` in 9e7db4976e7a4d8e15180598186b6d46ac757270, then moved to the `mingw-w64-git` package's extra source files in git-for-windows/MINGW-packages@3e74d5db25f0cfe74c23560f6deeef55d7c213f6).

The original commit making that behavior change, to prefer `HOMEDRIVE`/`HOMEPATH` over `USERPROFILE`, mentions "msysGit issue 108" as reason. Sadly, that issue has gone to the Google Graveyard, joining so many other dearly missed things. It was originally available as https://code.google.com/archive/p/msysgit/issues/108 but that no longer resolves to the issue; Instead it says that msysGit moved to GitHub (which it did, and in 2015 it was retired in favor of a new project structure that now lives in https://github.com/git-for-windows). The only hint as to what issue 108 was about that we still have is this mail: https://groups.google.com/g/msysgit/c/AykB5L4Of6c/m/s-32wQnmxYYJ. And I seem to remember that the issue was a typical corporate setup where `USERPROFILE` pointed somewhere else than `HOMEDRIVE`/`HOMEPATH`, namely to a network share instead of a local directory and hence was frequently unreachable where the local directory (that `HOMEDRIVE`/`HOMEPATH` references) was reachable instead. Hence that change of behavior.

In any case, even if there was no established reason for Git for Windows' current behavior, after ~24 years it is way too late to make a fundamental change like this.

If you want to tell Git what home directory to use, you can easily do that by setting the `HOME` variable. That's what Git (and not only Git _for Windows_) is documented to use, anyways.

**Comment by jaraco** [comment]
Thanks for the thoughtful response and research. I understand the project is sticky and sometimes even improper behavior must be maintained. I'll trust your judgement.

> you can easily do that by setting the `HOME` variable

That's a great suggestion, and superior to deleting the HOMEDRIVE/HOMEPATH variables. Thanks for the suggestion.

**Comment by jrn** [comment]
> The original commit making that behavior change, to prefer HOMEDRIVE/HOMEPATH over USERPROFILE, mentions "msysGit issue 108" as reason.

That's https://github.com/git-for-windows/git/issues/108, right?

**Comment by rimrul** [comment]
> > The original commit making that behavior change, to prefer HOMEDRIVE/HOMEPATH over USERPROFILE, mentions "msysGit issue 108" as reason.
> 
> That's https://github.com/git-for-windows/git/issues/108, right?

No. #108 is from 2015, while https://github.com/msysgit/msysgit/commit/6b096c9651da0d032a0e611d5edee7256e0da3c1 is from 2009 and explicitly talks about "msysGit issue 108".

**Comment by dscho** [comment]
> #108 is from 2015

And in case somebody suspects this to be a clone that was created only years later: no, that ticket talks about the MSYS2 runtime, which Git for Windows started using in 2015 and no earlier.

**Comment by hickford** [comment]
> If you want to tell Git what home directory to use, you can easily do that by setting the HOME variable.

Is HOME an environment variable or Git variable? I can't find any documentation at https://git-scm.com/docs/git

**Comment by rimrul** [comment]
> > If you want to tell Git what home directory to use, you can easily do that by setting the HOME variable.
> 
> Is HOME an environment variable or Git config variable? I can't find any documentation at https://git-scm.com/docs/git or https://git-scm.com/docs/git-config

It is an environment variable defined in 

https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html

**Comment by dscho** [comment]
The rationale detailed [here](https://github.com/git-for-windows/git/issues/4625#issuecomment-1748458748) still stands: we cannot change this behavior _now_.

**Comment by jaraco** [comment]
@dscho What do you think about this approach:

- Acknowledge that USERPROFILE should be preferred and HOMEDRIVE+HOMEPATH is discouraged if not deprecated.
- Add a warning when HOMEDRIVE+HOMEPATH differs from USERPROFILE letting users know that USERPROFILE will be preferred in future release.
- Solicit an environment setting (environment variable) that (a) suppresses the warning and (b) retains the legacy behavior. Something like GIT_FOR_WIN_PREFER_HOMEPATH.
- In a future release as the release cycle allows, change to USERPROFILE by default.
- (optionally) Eventually, drop support for the legacy behavior.

This approach should provide a smooth transition and likely avoid the pitchforks for the (presumably) small number of users still reliant on those variables.

This approach wouldn't fix things for users like myself today, but it would at least lead to a world where Windows users are not bound to this decision 20 years from now.

**Comment by dscho** [comment]
> Acknowledge that USERPROFILE should be preferred and HOMEDRIVE+HOMEPATH is discouraged if not deprecated.

I fear that it is not quite as simple as that. The latter [can be configured via Active Directory](https://learn.microsoft.com/en-us/archive/msdn-technet-forums/e9d9cd4d-6882-459e-b7a8-7091cfa031d2) while the former cannot be.

At this stage, I am not really interested in burdening myself with an effort I deem not to be relevant for most users anyway.
