### ISSUE TITLE
Chinese char show twin chars

### ISSUE THREAD

**Issue by liaosankai** [git-for-windows/git#463]
test char.js  by `Git-2.6.0-64-bit for windows 7/10` with `node.js v4.0.0`

    console.log('中文字');
    console.log('ABC');
    console.log('123');
    console.log('中A1文B2字c3');

output:

![sample](https://cloud.githubusercontent.com/assets/82476/10260696/d7088614-69ad-11e5-9b53-01a87110accc.png)

**Comment by linquize** [comment]
What encoding do you use in `char.js`? UTF-8 with / without BOM?

**Comment by gisphm** [comment]
@liaosankai @linquize  I test the js file with `Git 2.6.0 bit for Windows` installed on my windows machine.
First, I create the file with encoding `utf-8`(without bom). After executing `node char.js`, it showed up as follows:
![charjs](https://cloud.githubusercontent.com/assets/3512120/10262977/8b9a50f0-6a10-11e5-9951-ce2d7af02974.png)
Then, I create another file with encoding `utf-8+bom`. But I get the same output as shown above.

**Comment by dscho** [comment]
The screenshot in [this comment](https://github.com/git-for-windows/git/issues/463#issuecomment-145246117) seems to contradict what [that comment](https://github.com/git-for-windows/git/issues/463#issue-109595418) claims.

Besides, there is pretty much no description of the chosen installer options, where to get *that precise* node version, etc.  Also, there are instructions how to make those test files instead of a public Git repository to clone. In effect, it is made more cumbersome than necessary to reproduce. Usually, I would try to reproduce locally nevertheless, but unfortunately, I am pretty busy on other fronts, so I have to decline.

**Comment by liaosankai** [comment]
Sorry, I'm try to describe in more detail.

###  Operating System
Windows7(x64) zh-TW Lang

### Git 2.6.0(x64) Setup Options
+ Use Git from Git bash only
+ Checkout Windows-style, commit Unix-style line endings
+ Use MinTTY(the default terminal of MSys2)
+ (No checked)Enable file system caching

### Test
I make three test file have the same code but with different encode 
+ ansi.js
+ utf-8-with-bom.js
+ utf-8-without-bom.js

The code content:

    console.log('中文字');
    console.log('ABC');
    console.log('123');
    console.log('中A1文B2字c3');

Run on `MS-DOS` and `MINGW64`

![ms-cmd](https://cloud.githubusercontent.com/assets/82476/10268510/b87ffd1c-6aed-11e5-9439-309f7214127d.jpg)
![git-64](https://cloud.githubusercontent.com/assets/82476/10268512/c4066d6a-6aed-11e5-9644-14007f14484d.jpg)

**Comment by hkdennis2k** [comment]
I am unable to reproduce on git version 2.6.0.windows.1(portable) with node(v0.10.26)
It produce expected result on my machine.


Do you have issue with `cat` or you have issue with nodejs only?

**Comment by gisphm** [comment]
I am also using node(v4.1.1 x64) on my windows 10(x64 pro zh-CN) machine. It also shows expected result.

**Comment by dscho** [comment]
@glsphm and you also are not telling anybody from where you downloaded node and how you installed it. And you also do not make a public repository available with test files. Do you really want to make it harder than necessary for me to help you?

**Comment by dscho** [comment]
What a pity.
