### ISSUE TITLE
Copying path are incomplete (linked to mintty to 3.6.4)

### ISSUE THREAD

**Issue by Sildra** [git-for-windows/git#4634]
- Path issue : https://github.com/mintty/mintty/releases/tag/3.6.5

### Setup

```
$ git --version

git version 2.42.0.windows.2
```

### Details

The current version of mintty (3.6.4) has an issue with copying from paths which is a huge pain when copying paths from git status commands. Can you re-release git-for-windos with the latest version of mintty (3.6.5) ?

**Comment by dscho** [comment]
> * Path issue : https://github.com/mintty/mintty/releases/tag/3.6.5

@Sildra that is not an issue, that is a released version.

> ### Details
> 
> The current version of mintty (3.6.4) has an issue with copying from paths which is a huge pain when copying paths from git status commands.

Those details are a bit... _concise_? In other words, I do not at all understand what the problem is.



> Can you re-release git-for-windos with the latest version of mintty (3.6.5) ?

As @rimrul pointed out, you can always install the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html). As it were, [the Git roadmap](https://gh.io/gitCal) starts the release candidate phase for v2.43.0 on November 3rd, which means that it is a bit late in the release cycle for out-of-band releases addressing non-critical issues.
