### ISSUE TITLE
Unable to identify ProxyCommand after entering ssh

### ISSUE THREAD

**Issue by aogg** [git-for-windows/git#4642]
The cmd command window of logging in to windows through ssh in windows

**Comment by dscho** [comment]
@aogg umm. Are you 100% certain that there is no way you could provide anything close to a complete bug report? In the current shape and form, this is a joke and not a bug report.

There was a issue reporting template that you deleted instead of filling it out. That was probably not the wisest course of action, as a lot of care has been put into providing that template with the aim of helping users to include enough information to make sense of their report.

Simply deleting this template and replacing it with an obscure half-sentence demonstrates a level of care that suggests that you are disinterested in receiving any help, or at least that you expect others to put much more effort into helping you than you did yourself when reporting the issue.

I choose to draw the curtain of charity over this ticket. If you can bring yourself to muster an effort worthy of attention into reporting this bug, please open a new ticket, and do spend the time and attention to fill in all the information you can think of, by way of showing respect to the people you _are asking to help you_, after all.
