### ISSUE TITLE
‘fatal: Unable to read current directory: No error’ for every local Git repository I have

### ISSUE THREAD

**Issue by rexcfnghk** [git-for-windows/git#473]
Background
---
I currently have two git programs installed on my computer:
  - **GitHub Desktop**
  - **Git For Windows**

I use Git Bash most of the time and I use GitHub Desktop when I need a bigger picture of my repository.

Issue
---
The problem is I can no longer run any Git commands on Git Bash. This happens when I try to run `git status`:

    rex@MyPC MINGW64 ~/My Documents/Source/FooRepository
    $ git status
    fatal: Unable to read current working directory: No error

The strange thing is it works perfectly fine in the Git shell that comes with GitHub desktop (which I believe is PowerShell based):

    C:\Users\rex\My Documents\Source\FooRepository [master]> git status
    On branch master
    Your branch is up-to-date with 'origin/master'.

    nothing to commit, working directory clean

**Comment by Radrik5** [comment]
Could you try a Git repo that doesn't have spaces in the path?

**Comment by dscho** [comment]
@rexcfnghk I will need substantially more information than that, and preferably a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve). Please study https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines and then provide the missing information.

**Comment by rexcfnghk** [comment]
I have successfully reproduced this issue. I am using the following environment:

- Windows 7 64-bit
- Git For Windows 64-bit v2.6.1
    - All commands are run inside Git Bash

When I try to `git clone` a remote repository into a directory **with spaces in the path** (or run any git commands in an existing repository as shown above), it fails as shown in the follwing output:

    rex@MyPC MINGW64 ~/My Documents/Source
    $ git clone http://www.abcd.com/FooRepository.git
    fatal: Could not get current working directory: No such file or directory

The other example is shown above when running `git status` in an existing repository, also **with spaces in the file path**.

When I try cloning into another directory **without spaces in the file path**, it clones successfully:

    rex@MyPC MINGW64 ~/Source
    $ git clone http://www.abcd.com/FooRepository.git
    Cloning into 'FooRepository'
    ...

**Comment by rexcfnghk** [comment]
Sorry it seems that I accidentally created the symlink `My Documents` that was creating this issue. Reverting to `~/Documents` seems to solve the issue (even with spaces). Closing the issue.

**Comment by dscho** [comment]
Hmpf. That is really too scarce information, causing quite a bit of lost time on my end.

This is [what I tried](http://whathaveyoutried.com):

1. I created a symbolic link to an existing directory via `mklink /d symbolic-link existing-directory` in an elevated `cmd` in my home directory.
2. I started *Git Bash* and called `cd symbolic-link`
3. Then I cloned a local repository via `git clone ../existing-repository`

This worked.

Then I tried the same with a junction point: `mklink /j junction-point existing-directory` as step 1., the other steps as above. And the same result: It worked.

So I guess that we will really not be able to fix this issue, unless you, @rexcfnghk, put in a little bit of an effort to come up with a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve).

**Comment by giacomocerquone** [comment]
I've the exact same problem and the only way I figured it out to get it to work is to give a cd to a repo with the full documents path (C:\Users\username\Documents\Gitrepo).
This happened to me, as you can see from the other post, when I updated Github and, more important, with the new windows 10 major update.

In fact now if I start a new powershell session and I go to the document folder without padding him the full path (just cd documents) it doesn't work!
So could be some new configuration in powershell I think!

**Comment by dscho** [comment]
@giacomocerquone I get the distinct impression that there is a ton of really vital information that has been left out. You report that you have the exact same problem, but fail to mention which version and particular settings you use. Then PowerShell is mentioned briefly. How did you set Git up to be used from PowerShell? And then there is talk about a symlink in an *update* of the comment?

Seriously, it is a bit much to ask me to cobble back together a clear picture from these scattered bits and pieces. Please do not make my life so hard. You can do [better](http://whathaveyoutried.com) than that.

**Comment by giacomocerquone** [comment]
Hi @dscho, I thought some of you would have opened the other issue, when I ask for help I'm always very specific. As I said:

>  Hi, I'm working in windows 10. I updated github for windows right yesterday (actual version 3.0.9.0, don't know if it means something) and git --version returns git version 2.5.3.windows.1
Now my problem is that every command I try to execute with git it returns: git unable to read current working directory no error (obviously the working directory isn't absolutely empty, and I also tried to create a new directory and initialize a new repo wit git init but it returns always the same error).

>To use git I edited the profile.ps1 of powershell in this way:
. (Resolve-Path "$env:LOCALAPPDATA\GitHub\shell.ps1")
. $env:github_posh_git\profile.example.ps1

**Comment by dscho** [comment]
This is a precise report: I downloaded [Git for Windows 2.6.3 (64-bit)](https://github.com/git-for-windows/git/releases/tag/v2.6.3.windows.1), installed it with the "Windows default terminal" option, then I cloned a repository into my home directory and XYZ happened (I expected ABC instead). If I clone the same repository into `C:\blub`, it works.

With such a precise report, I would have a chance to reproduce your issue.

**Comment by giacomocerquone** [comment]
I don't know if you're doing just an example or you really didn't understand what I said. Anyway this seems hilarious to me, you're again seeking clarification from me but everything has been already written (just in an inconvenient order).
Let's organize it so:

I downloaded [Github Desktop](https://desktop.github.com/) 8 months ago and for 4 months I always used the GUI version (never touched powershell or git directly). So 4 months ago I started using git from powershell (<b>without installing anything</b>) I just did what's written in [this guide](https://git-scm.com/book/it/v2/Git-in-Other-Environments-Git-in-Powershell) (basically it links posh-git used by Github Desktop <b>that was already installed</b> to the PATH environment variable editing the powershell profile).

I have always had my repos inside this folder: C:\Users\username\Documenti\Github\ ("Documenti" is the italian version of "Documents"... just to be precise).

## When everything was working
Until a few days ago I've always worked with git giving this commands (and never a problem):
> C:\Users\username>cd documenti\github\name-of-the-repo
C:\Users\Giacomo\documenti\github\name-of-the-repo> git status
On branch master
Your branch is up-to-date with 'origin/maste
nothing to commit, working directory clean

## After windows 10 and github desktop update this doesn't work
But since I installed both the new Windows 10 major update and the new Github Desktop version this is what happened:

> C:\Users\username>cd documenti\github\name-of-the-repo
C:\Users\Giacomo\documenti\github\name-of-the-repo [(master)]> git status
fatal: Unable to read current working directory: No error

## After windows 10 and github desktop update this works (note the "documents" is that that make it works):
> C:\Users\username>cd documents\github\name-of-the-repo
C:\Users\Giacomo\documents\github\name-of-the-repo [master]> git status
On branch master
Your branch is up-to-date with 'origin/maste
nothing to commit, working directory clean

## These are the actual version of the software in question
#### Git
`git --version`
`git version 2.5.3.windows.1`

#### Github Desktop
`Never Gonna Git You Up (3.0.9.0) dd3b7aa`

#### Windows
`Windows 10 Pro Threshold 2 version 1511`

## Conclusion
You said you're "getting the distinct impression..." and you were right, it's just an impression, we already said everything we could. I think that everyone here, included me, doesn't know which way to turn. Man I hope it is enough now, if it isn't I know what else I can tell you.

**Comment by dscho** [comment]
@giacomocerquone you do realize that

1. this is the *Git* for Windows project, not the *GitHub* for Windows one?
2. being testy makes it less likely that I even want to help you?

**Comment by giacomocerquone** [comment]
dahlbyk linked the issue I opened on posh-git here and so here we are and anyway doesn't matter that this is git for Windows because:
1. we have the same problem apparently
2. it's most likely an OS problem that we're trying to solve. Windows damaged some symbolic link during the update I think.

I don't want to be testy, but you're asking questions that more and more people already answered, but if you felt offended, I ask you sorry.

**Comment by happycollision** [comment]
Incidentally, for those who run into this problem in the future, the cause of the problem on my end was an intermediate folder permissions issue. For example, if the path is `C:\folderA\folderB\myGitRepo`, and there is a permission change to `folderA` or `folderB`, that might cause the problem. In my case, I needed to remove and then re-add my user to `folderB`. FYI.

**Comment by dscho** [comment]
@happycollision thank you for reporting this, and congratulations for the successful investigation!

**Comment by awatasoftsys** [comment]
/var/www/html/ERP$ git branch
fatal: Unable to read current working directory: No such file or directory

why this problem occuring

**Comment by dscho** [comment]
@awatasoftsys as you can see from the error message, this is a different problem than the one described in this ticket. In any case, it would make a lot of sense to try to come up with an [MCVE](http://stackoverflow.com/help/mcve) and then to open a separate ticket.
