### ISSUE TITLE
git-svn: Inconsistent file:// URL schemes between git and svn

### ISSUE THREAD

**Issue by vvs31415** [git-for-windows/git#4769]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 bit

```
$ git --version --build-options

git version 2.43.0.windows.1
cpu: x86_64
built from commit: 4b968f3ea3b32a7bc50846bab49f3f381841d297
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3930]
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
svn, version 1.12.0 (r1857323)
   compiled Apr 26 2019, 02:13:45 on x86_64-microsoft-windows6.2.9200
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cd F:\tmp
F:

svnadmin create buzz

mkdir import
cd import
echo hello>hello.txt
svn import -m "initial import" . file:///F:/tmp/buzz
del hello.txt
cd ..
rmdir import

git svn init file:///F/tmp/buzz
git svn fetch
type hello.txt
git log
```
 - What did you expect to occur after running these commands?

Script fails if we try to use the obvious URL scheme: file://F:/tmp/buzz

 - What actually happened instead?

The script succeeds if we are using different URLs to address the same repo.
They are expected to be the same.

**Comment by vvs31415** [comment]
https://github.com/git-for-windows/git/issues/1593

**Comment by dscho** [comment]
As mentioned in https://github.com/git-for-windows/git/issues/1593, interest has died down in trying to address this, and quite frankly, at this point I am considering to drop `git svn` from Git for Windows a better option than trying to address this here issue: `git svn` is inherently less of a native Windows command than `git.exe` due to its reliance on the POSIX emulation layer provided by the MSYS2 runtime.

@vvs31415 if you find the time to look into patching `subversion` to support native Windows paths when cloning from a local filesystem, please go ahead. Alternatively, I suspect that this here ticket will have the same outcome as https://github.com/git-for-windows/git/issues/1593 had.

**Comment by vvs31415** [comment]
I agree, this would be too much pain fo fix this on both ends. The more radical solution would be to rewrite git-svn altogether, in a language like Rust.
Closing the issue

**Comment by dscho** [comment]
> The more radical solution would be to rewrite git-svn altogether

To be honest, I consider `git svn` close to its end-of-life, given how few remaining Subversion instances are still out there, and those that _are_ there are more likely to be used with the Subversion client than with the `git svn` adapter.
