### ISSUE TITLE
git difftool in MinGit?

### ISSUE THREAD

**Issue by mversluys** [git-for-windows/git#4806]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 
2.39.3.windows.1 (as this is what's used by dugite). 
I've checked more recent versions including v2.44.0-rc0.windows.1

- Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options
git version 2.39.3.windows.1
cpu: x86_64
built from commit: 469fcac0990381aa6d656f5b02924482b91e0ce5
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.22631.3007]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

This was using an official release

dugite-native uses the prebuilt release as per here
https://github.com/desktop/dugite-native/blob/master/dependencies.json#L9

which is referring to 
https://github.com/git-for-windows/git/releases/download/v2.39.3.windows.1/MinGit-2.39.3.windows.1-64-bit.zip

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Occurs with any shell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Launch a shell that has MinGit tools in the path and then run

```
git difftool
```
 - What did you expect to occur after running these commands?

It results in an error
```
error: cannot spawn git-difftool--helper: No such file or directory
```

 - What actually happened instead?

It wasn't able to find the `git-difftool--helper` script which is normally found in `mingw64/libexec/git-core`
It doesn't appear that the script is included with MinGit.

My use case is to launch `git difftool` from an electron Git GUI which is using dugite which is using MinGit.
`git mergetool` does work with MinGit as all of the necessary support files are included with MinGit.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/git-for-windows/git

**Comment by dscho** [comment]
`git difftool` is a user-facing tool. Whatever it can do for third-party applications, low-level tooling can do better.

Maybe you can describe in a bit more detail what your tool does? I am sure we can figure out a better approach together that uses `git diff-index` and/or `git diff-files` instead of `git difftool`.

**Comment by mversluys** [comment]
I'm making good use of `git diff` to display diffs within my application to show changes inline, but would like users to be able to open the diff in an external tool like Araxis Merge and Beyond Compare.

`git mergetool` is working great in MinGit and allows to resolve merge conflicts in external tools.

I was able to verify that `git difftool` does work by copying `git-difftool--helper` from a full install of git-for-windows into `git/mingw64/libexec/git-core` in my packaged application.

**Comment by dscho** [comment]
Hmm. I hoped that we could reduce the number of Unix Shell scripts in MinGit rather than increase it again, but I guess that's the price we have to pay.

Please open a PR that removes the relevant part of https://github.com/git-for-windows/build-extra/blob/e85444a225764d80b35c3f817062d014d310b41b/make-file-list.sh#L294 (and please verify that it works as intended by running `sdk cd build-extra && ./mingit/release.sh 0-test`.

I would accept this change into Git for Windows v2.44.0 (scheduled two days from now) if the PR makes it in time.

**Comment by mversluys** [comment]
Thanks for the guidance. I'll try the changes and see how the testing goes this week.
