### ISSUE TITLE
vim bug

### ISSUE THREAD

**Issue by anmikf** [git-for-windows/git#4929]
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.41.0.windows.1
cpu: x86_64
built from commit: ff94e79c4724635915dbb3d4ba38f6bb91528260
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.19044.1288]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

nothing

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git-bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
vim
```
-----------------------------------------------
username@MMMMMM MINGW64 /e/foo
$ ls
bar  bar.exe*

username@MMMMMM MINGW64 /e/foo
$ cat bar
bar aaaaaaaaaaaaa
username@MMMMMM MINGW64 /e/foo
$ cat bar.exe
bar.exe bbbbbbbbbbbbb
username@MMMMMM MINGW64 /e/foo
$ vi bar              # modify bar then save

username@MMMMMM MINGW64 /e/foo
$ ls                  # bar lost
bar.exe*

username@MMMMMM MINGW64 /e/foo
$ cat bar.exe         # bar.exe changed
bar aaaaaaaaaaaaa add something
------------------------------

**Comment by dscho** [comment]
Does this also happen with regular [MSYS2](https://msys2.org)? Git for Windows [is based, in part, on MSYS2](https://github.com/git-for-windows/git/blob/v2.44.0.windows.1/ARCHITECTURE.md#a-software-distribution-really) and hence its `vim` inherits the behavior from that project.

**Comment by anmikf** [comment]
Yes, MSYS2 also has this bug.

**Comment by anmikf** [comment]
I don't know where to submit the bug, could you please submit it up?

**Comment by k-takata** [comment]
This is coming from the behavior of Cygwin and MSYS2.
If there is only `aaa.exe` in the directory, trying to open a file `aaa` results in opening `aaa.exe`.
If there are both `aaa` and `aaa.exe` in the directory, opening `aaa` actually opens `aaa`.
Because of this strange behavior, you don't need to add the `.exe` extension when you run a command from bash.
I don't know if there is a way to disable this.

To work around the original issue, you can add `set backupcopy=yes` in your `.vimrc`.
When `backupcopy` is "auto" (default) or "no", Vim saves a file in the following steps:

1. Move `aaa` to a backup file (e.g. `aaa~`).
2. Create a new file with the name `aaa`.
   Actually, this opens `aaa.exe` because of the strange Cygwin behavior.
3. Write the new contents to `aaa` (actually, `aaa.exe`).
4. Remove the backup file (`aaa~`) if the `backup` option is off.

When `backupcopy` is "yes":

1. Copy the contents of `aaa` to a backup file e.g. `aaa~`.
2. Open `aaa` and erase the contents.
3. Write the new contents to `aaa`.
4. Remove the backup file (`aaa~`) if the `backup` option is off.

**Comment by dscho** [comment]
Thank you @k-takata for identifying this as an upstream issue. I'll close this here ticket.
