### ISSUE TITLE
git-credential-wincred is missing from the preview installer

### ISSUE THREAD

**Issue by kevin-david** [git-for-windows/git#50]
I'm running the [developer's preview release](https://github.com/git-for-windows/git/releases/tag/v2.3.4.windows.2) and the wincred helper seems to be missing:
`git: 'credential-wincred' is not a git command. See 'git --help'`

Not a big problem since it can be easily worked around using something like [git-credential-winstore](https://gitcredentialstore.codeplex.com/), but figured it should be fixed before a real release.

**Comment by dscho** [comment]
Since this is a developers preview and you seem to be a good developer, how about giving it a try?

First you need to install the net installer: https://github.com/git-for-windows/git/releases/download/v2.3.4.windows.2/git-sdk-64-installer-dev-preview.7z.exe This will install all you need to build Git, then build Git from our current `master` and give you an interactive shell to play with.

The necessary change is actually in the `MINGW-packages` project which you need to initialize once before you can work on it:

```bash
cd /usr/src/MINGW-packages
git fetch
git checkout master
```

The file in want of fixing is `mingw-w64-git/PKGBUILD`, where you need to build the `.exe` in the `build()` function and then install it in the `package()` function; from the surrounding code it should be easy to copy-edit the necessary statements.

Here is the information how this executable is built in Git for Windows 1.x: https://github.com/msysgit/msysgit/blob/70f24b4b0f5f86a5e85f7264a4ee2c0fec2d4391/share/WinGit/release.sh#L84-L85

To test it, build the `mingw-w64-git` package by calling `makepkg-mingw -s` inside the `/usr/src/MINGW-packages/mingw-w64-git/` directory.

**Comment by kevin-david** [comment]
Have a fix for this in git-for-windows/MINGW-packages#5

**Comment by dscho** [comment]
Awesome! I commented on that PR and have no doubt that we can release a new `mingw-w64-git` package soon that fixes this here issue!
