### ISSUE TITLE
The PATH variable is very strange.

### ISSUE THREAD

**Issue by liyu34** [git-for-windows/git#503]
I clicked right mouse button on my project's root folder,chose the "Git Bash Here", then I typed "$PATH",and the PATH will be like this  

`
$ $PATH  
bash:/d/MyProject/ModBus/%USERPROFILE%/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:%USERPROFILE%/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program: No such file or directory
`  

Why git create an %USERPROFILE% in my project's dir?
And every time when I want to save a file which is edited by vi, after ":wq" the bash will show
`E138: Can't write viminfo file /d/MyProject/test/%USERPROFILE%/.viminfo!  
Press ENTER or type command to continue
`

**Comment by dscho** [comment]
> I click right button on my project file, and the PATH

Wha., whaaat? You click the right button on, wait, where are you clicking the right button? And what project file? Do you really talk about a project file, such as a Visual Studio `.sln` file, or do you talk about a regular file in your project? And how do you get a `PATH` from right-clicking?

Please clarify. Do not hesitate to restate the question as if you are talking to a three-year old, because that's sure how confused I feel right now.

**Comment by liyu34** [comment]
I click right mouse button on my project's root folder,and chose "Git Bash Here".
Then I typed "$PATH" on git-bash.
