### ISSUE TITLE
git-bash.exe not working when git installed in root (e.g. D:\Git)

### ISSUE THREAD

**Issue by tavrez** [git-for-windows/git#509]
I tested this only with default terminal emulator being command prompt. Git-bash.exe will says "cannot find the file"

**Comment by linquize** [comment]
which version?

**Comment by tavrez** [comment]
2.6.2 64-bit
I also notified that this file is working fine during installation, but post-installation process will do something to this file resulting on not openning bash properly

**Comment by ketiketa** [comment]
This problem is also present when doing a "classic" install for Git-2.6.2-32-bit (problem exists also in Git-2.6.1-32-bit).

During installation, git-bash.exe (63439d2b6980835d1f67e8ac7260dd050ffdbb87) is copied to "C:\Program Files (x86)\Git" and then at the end of the installation process, git-bash.exe is truncated to a 27kB file (596b198418a97437718d26ef920b9c5a4a964aee).

The resulting truncated git-bash.exe is considered malware for some AV (https://www.virustotal.com/fr/file/9f9b2f190b5bd91a42a3e8ee09f0edc12254ba7c18ede54cb4382d512a55c1f8/analysis/1445947552/).

The truncation is mainly the removal of end data starting at :
```xml
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">.
```

**Comment by dscho** [comment]
@ketiketa you are reporting a completely unrelated "bug" here. Please do not do that. Open a different ticket, or even better: try your hand at a solution and open a Pull Request (you need to look [here](https://github.com/git-for-windows/build-extra/blob/master/installer/edit-git-bash.c) to see what is "truncating" `git-bash.exe`).

**Comment by dscho** [comment]
@tavrez I cannot reproduce here. Installing with `Git-2.6.2-64-bit.exe /dir=c:\issue-509` and selecting the default Windows console for use with Git Bash works here:

![issue-509](https://cloud.githubusercontent.com/assets/127790/10794087/cb4936c6-7d93-11e5-9d40-43f83c405da4.png)

**Comment by tavrez** [comment]
I've tested installation process near 8 times after this, as I got it's related to length of the folder, all this folders failed when I tested:
c:\iss
c:\isss
c:\issss
c:\isssss
that's up to 6 letters, when I go on 7, it will become correct, like your test example, or this:
c:\issssss
I should also say that the only exe which become corrupted is git-bash.exe, not bin\bash.exe or anything else, but because they are not setting all env variables and context menu is using git-bash.exe, this is little important to be fixed.
Another thing is git-bash.exe should not be open in the post installation process, if it was, nothing can touch it and it will work perfectly :)
I should also say that this git-bash.exe has an icon at beggining, and it will gone after post-install process :(

**Comment by dscho** [comment]
Finally got it...
