### ISSUE TITLE
Could not open a connection to ssh authentication agent.

### ISSUE THREAD

**Issue by Freemmy-new** [git-for-windows/git#514]
Hello!

I followed this article 'Generating SSH keys' (https://help.github.com/articles/generating-ssh-keys/) to generate and add my SSH key to the ssh-agent. Everything was 'ok' until I had stuck on 3.2 step where I need to add my SSH key to the ssh-agent.

There's what I've got:
> $ ssh-agent -s
> SSH_AUTH_SOCK=/tmp/ssh-HdV5V0HDEkh4/agent.5536; export SSH_AUTH_SOCK;
> SSH_AGENT_PID=8068; export SSH_AGENT_PID;
> echo Agent pid 8068;

I constantly receive this message: 'Could not open a connection to your authentication agent.' while trying to add my SSH key to the ssh-agent:
> $ ssh-add
> Could not open a connection to your authentication agent.

The ssh-agent is run:
> $ ps x | grep ssh-agent
>      8068       1    8068       8068  ?        1125603 14:56:06 /usr/bin/ssh-agent

And one more trouble is that I cannot kill it via 'ssh-agent -k':
> $ ssh-agent -k
> SSH_AGENT_PID not set, cannot kill agent

Thanks for any help in advance.

Best regards
Dmitry

**Comment by kgybels** [comment]
@Freemmy-new Try the alternative suggested in step 3.1 `eval $(ssh-agent -s)` instead of just `ssh-agent -s`. This will allow you to continue along with the article.

The following will also be of interest to you:
[Running SSH Agent when starting Git Bash on Windows](http://stackoverflow.com/questions/18404272/running-ssh-agent-when-starting-git-bash-on-windows)

However, this is not the right place for this kind of support, so please close this issue.

**Comment by Siarhei-Yarkavy** [comment]
I see it like an issue, not support request. Freemmy-new tries many way, nothing helps. sh-add doesn't work with message "Could not open a connection to your authentication agent". This looks like an issue in git2 for windows.

**Comment by Freemmy-new** [comment]
Thank you, kgybels. It helped.
But I don't know what was wrong, because I had tried to use 'eval $(ssh-agent -s)' before open this issue and that didn't help me.

After reboot I run 'eval $(ssh-agent -s)' again and then 'ssh-add' completed successfully.

Thanks.
