### ISSUE TITLE
Cannot run Node, Error 0x2

### ISSUE THREAD

**Issue by PaulBGD** [git-for-windows/git#527]
```
Paul@Paul-PC:~/Documents/Coding/Fourums> node
Error 0x2 starting node.exe
```
Then if I try to run it in bash:
```
Paul@Paul-PC:~/Documents/Coding/Fourums> bash -e "node"
/c/Program Files (x86)/nodejs/node: /c/Program Files (x86)/nodejs/node: cannot execute binary file
```

My Node binary is x86 and I'm running bash on a 64 bit system.

**Comment by shiftkey** [comment]
What version of Git for Windows do you have installed?

**Comment by PaulBGD** [comment]
Here's the output of git --version, not sure if this is the version of git for windows sorry:
```
$ git --version
git version 2.6.3.windows.1
```
I just downloaded it about 20 minutes ago.

**Comment by shiftkey** [comment]
And how did you source node? From nodejs.org?

**Comment by PaulBGD** [comment]
Yes, I tried installing both x86 and x64.

**Comment by dscho** [comment]
@PaulBGD could you run `unalias node` and then try again?

**Comment by PaulBGD** [comment]
That worked, thanks! Any reason why this could have happened?

**Comment by kmelia** [comment]
> Any reason why this could have happened?

Hi @PaulBGD, I think the reason is the commit [build-extra/44ed99b4](https://github.com/git-for-windows/build-extra/commit/44ed99b47f564d0b89784ae8008627f5c3d06d69) who add:
```sh
alias node="winpty node.exe"
```
But there is no ``node.exe`` on your binaries.

Could you run ``unalias node && alias node="winpty node"`` and then try again? To see if ``winpty`` is needed or not?

**Comment by dscho** [comment]
@kmelia I think the proper solution would be to test whether `type node` succeeds and points to a `.exe` file. If that is the case, we should set the alias. Otherwise not.

**Comment by kmelia** [comment]
@dscho your solution seems good!

**Comment by PaulBGD** [comment]
```
Paul@Paul-PC / $ unalias node && alias node="winpty node"
bash: unalias: node: not found
```
@kmelia 
```
Paul@Paul-PC / $ type -p node
/c/Program Files (x86)/nodejs/node
```
@dscho

**Comment by PaulBGD** [comment]
Node seems to be working fine now.

**Comment by dscho** [comment]
> /c/Program Files (x86)/nodejs/node

@PaulBGD 

The question is: what are the two first bytes of that file? IOW what does

```sh
dd if=/c/Program Files (x86)/nodejs/node bs=2 count=1 | od -t x1
```

print?

**Comment by PaulBGD** [comment]
@dscho 
```
Paul@Paul-PC / $ dd if="/c/Program Files (x86)/nodejs/node" bs=2 count=1 | od -t x1
1+0 records in
1+0 records out
2 bytes (2 B) copied, 0.000426667 s, 4.7 kB/s
0000000 4d 5a
0000002
```

**Comment by dscho** [comment]
> ```
> Paul@Paul-PC / $ dd if="/c/Program Files (x86)/nodejs/node" bs=2 count=1 | od -t x1
> 1+0 records in
> 1+0 records out
> 2 bytes (2 B) copied, 0.000426667 s, 4.7 kB/s
> 0000000 4d 5a
> 0000002
> ```

Hmm. So it is not a Bash script as I had thought...

Oh, I guess I misunderstood the culprit completely (my only defense is that I am a bit sleep deprived these days): the issue seems to be that 64-bit `winpty` cannot call 32-bit executables?

/me tests that

*clicketyclick*

Nope, 64-bit `winpty` runs 32-bit `git,exe` just fine. Color me stumped.

**Comment by Saturn2888** [comment]
`unalias node` fixed it for me as well. I reinstalled Git from the git-scm website and had to unalias again to run Node.

**Comment by kmelia** [comment]
> and had to unalias again to run Node.

Hi @Saturn2888 you could add these lines to your ``.bashrc`` to automatically remove the unwanted aliases:
```sh
##### Git Bash for Windows >= 2.x
 
# remove the winpty Node aliases
unalias $(alias | grep winpty | grep node | cut -d"=" -f1 | cut -d" " -f2)
```
*ref: http://blog.kmelia.net/testing/coloration-dans-git-bash/123*

**Comment by dscho** [comment]
I invite everybody to investigate why `winpty` seems to be unable to run the 32-bit node, and also to work on the `/etc/profile.d/alias.sh` script to detect when to alias (and simply not alias otherwise).

**Comment by Saturn2888** [comment]
@kmelia I'd love to, but somehow after installing Heroku w/ Git Bash and reinstalling Git from SCM, I lost the Git Bash prompt.

Using SourceTree's embedded Git Bash, I got this error after creating a `.bashrc` and putting that line in it:
```shell
WARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.
```

**Comment by kmelia** [comment]
> WARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.

Check what do you have now on your home directory. Git Bash creates for you a profile file to use the ``.bashrc`` file.

> The node command is working now without having to unalias node each time.

You can also check if you have the node alias with the command ``alias``.

**Comment by Saturn2888** [comment]
Yeah, it created those other files and that warning went away the second time I loaded up Git Bash.

```shell
alias ipython='winpty ipython.exe'
alias ll='ls -l'
alias ls='ls -F --color=auto --show-control-chars'
alias php='winpty php.exe'
alias php5='winpty php5.exe'
alias psql='winpty psql.exe'
alias python2.7='winpty python2.7.exe'
```

**Comment by kmelia** [comment]
So:

> The node command is working now without having to unalias node each time.

This is not correct ;) The unalias is done on the ``.bashrc``.
So your ``node`` command is now working without the ``winpty``

**Comment by dscho** [comment]
If you need to run node *non-interactively*, you can always call it directly with the `.exe` suffix.

Back to this ticket: between all the comments, [my suggestion](https://github.com/git-for-windows/git/issues/527#issuecomment-164753707) is running the danger of getting lost. So here it is again, in all its glory:

> I invite everybody to investigate why `winpty` seems to be unable to run the 32-bit node, and also to work on the `/etc/profile.d/alias.sh` script to detect when to alias (and simply not alias otherwise).

**Comment by kachenjr** [comment]
This cost me some time today, and searching let me here.  The error symptom is a little confusing, but the issue is that the bash command can't find the exe that is being aliased.  Given the hint about the alias file and with a little searching of the intertubes, I found a post on stackoverflow that says to use command -v <program> to verify that bash (or whatever shell) can find the executable via the PATH variable.
I set up a test

$ cat ./testCommands.sh
#!/bin/bash
if ! command -v php.exe 2>&1 > /dev/null
then
  echo "php.exe not found"
else
  echo "php.exe found"
fi

$ ./testCommands.sh
php.exe not found
$ export PATH=$PATH:$PATH_TO_PHP
$ ./testCommands.sh
php.exe found

So changing the alias.sh file as suggested should at least stop the odd error and fail with the more obvious not found..

alias.sh
...
        for name in node ipython php php5 psql python2.7
        do
                if command -v ${name}.exe 2>&1 > /dev/null
                then
                        alias $name="winpty $name.exe"
                else
                        "Warning, ${name}.exe not found in path!"
                fi
        done
...
new login
bash: Warning, node.exe not found in path!: command not found
bash: Warning, ipython.exe not found in path!: command not found
bash: Warning, php.exe not found in path!: command not found
bash: Warning, php5.exe not found in path!: command not found
bash: Warning, psql.exe not found in path!: command not found
bash: Warning, python2.7.exe not found in path!: command not found

That and getting all these things in my path and I'm ready to rock and roll.
Thanks!

**Comment by kachenjr** [comment]
Actually.. to make this work, users are going to have to drop a shell script in /etc/profile.d/ that sets the path to all these things, if they aren't in the PATH setup by /etc/profile  .  To that end, I would recommend renaming the aliases.sh file to xaliases.sh (these are executed in alpha order), and tell users where to create the system path scripts.
Or, generate the .bash_profile for them, with this alias helper there.  That way the user has the chance to set PATH in .bashrc before .bash_profile gets sourced.  My $0.02.

**Comment by dscho** [comment]
The proper way is to use `type` to figure out whether the respective `.exe` is on the `PATH`.

**Comment by dscho** [comment]
You can find a good example [here](https://github.com/git-for-windows/git/blob/78ce6bc19e6b7ce9433b889b2a67d53b8fbeb557/mergetools/winmerge#L17-L21).
