### ISSUE TITLE
Git 2.6.3 installer error

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#528]
Previously, I installed Git 2.6.2 x64 on Win 7

1. Launch Git 2.6.3 installer
2. Confirm to install
3. Uninstaller shows
4. UAC prompt
5. Git 2.6.2 is uninstalled
6. Git 2.6.3 installing (creating directories)
7. Error
8. Quit, installation failed

```
---------------------------
Git 2.6.3 Setup
---------------------------
Setup was unable to create the directory "C:\Program Files\Git\tmp".
Error 5: Access is denied.
---------------------------
OK   
---------------------------

---------------------------
Error
---------------------------
Setup was not completed.



Please correct the problem and run Setup again.
---------------------------
OK   
---------------------------

```

UAC prompt is for the uninstaller 2.6.2.
But UAC prompt is not for the installer 2.6.3.

In 2.6.2, UAC prompt starts immediately when starting the installer.
But 2.6.3 does not.

In the meantime, I have to click `Run as administrator` on 2.6.3 installer as workaround.

**Comment by linquize** [comment]
Is it related to https://github.com/git-for-windows/build-extra/pull/86 ?

**Comment by dscho** [comment]
I believe this is now the third ticket describing the very same issue: `C:\Program Files\Git\tmp` cannot be created after upgrading from 2.6.2:

* https://github.com/git-for-windows/git/issues/526
* https://github.com/git-for-windows/git/issues/523

Please note that the time I spend pointing out duplicates is time I cannot spend on fixing the issue (and I ran out of time today to actually fix bugs because of tending to issues).
