### ISSUE TITLE
Configure http.sslcainfo in Git for Windows' own system-wide config

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#531]
At the moment, we configure this in `C:\ProgramData\Git\config` which is wrong because
1. other Git applications might not be able to handle our ca certs
2. when Git for Windows is uninstalled, the path would naturally become invalid
3. when upgrading from a 32-bit to a 64-bit Git for Windows, we leave an existing `C:\ProgramData\Git\config` mostly alone

**Comment by fourpastmidnight** [comment]
@dscho I know the issue still says its open, but is it really open? As I continue to work on the MSI installer on #682, if this is still an issue, I'd like to keep this issue in mind. There's no sense in creating an installer that doesn't resolve some of these long outstanding issues from the outset.

I'm familiar with the "system-wide" git config in `C:\ProgramData\Git`, as well as the user's global git config and the local repository git config, but where would the Git for Windows' "own system-wide config" reside, and how would you modify it via `git config --???configtype??` since the only legal options are `system`, `global`, and `local`?

**Comment by fourpastmidnight** [comment]
@dscho: Ah, I found the Git for Windows' "own system-wide config" reading through other installer issues, specifically, you mentioned it in #104. But my second question still stands--how do you modify it via `git config`, or is it something you can only modify via your favorite text editor?

**Comment by dscho** [comment]
> how do you modify it via git config

`git config -f C:/ProgramData/Git/config ...`

**Comment by dscho** [comment]
Oh, and yes: this issue is still open and awaits patiently the time when I can take care of it.

**Comment by fourpastmidnight** [comment]
@dscho: Thanks for the info!

**Comment by fourpastmidnight** [comment]
@dscho: I did some work on this with respect to the MSI installer on #682. The MSI installer now installs `mingw$BITNESS\etc\gitconfig` to `%ProgramData%\Git\config`. It will then eventually run the command `git config -f /$ProgramData/Git/config http.SslCAInfo "/C:\Program Files\Git\mingw$BITNESS\ssl\certs\ca-bundle.crt"`. (The path to the certs gets converted correctly via MinGW POSIX path conversion since I run this command from the Bash shell.)

Also, because the installer is actually installing the `%ProgramData%\Git\config`, upon uninstall, this file is removed. So I think that resolves the issue of an "invalid path" that you were talking about in point 2 above. Also, point 3 becomes irrelevant because the MSI handles it all, regardless of architecture. I have no idea about point 1 above.

I have one more lingering concern: I noticed in the original InnoSetup installer that when setting the option to enable the Git Credential Manager for Windows, the command `git config --system` is used. If I run this on my machine, this returns an error:

```
fatal: unable to read config file 'C:\Program Files\Git\mingw64/etc/gitconfig': No such file or directory
```

I am only running Git for Windows 2.7.1.windows.2, so maybe that has something to do with it? If not, how is it possible to configure Git such that running `git config --system` should look for the configuration file at `%ProgramData%\Git\config`?

**Comment by dscho** [comment]
> how is it possible to configure Git such that running git config --system should look for the configuration file at %ProgramData%\Git\config?

It should not... As far as Git for Windows is concerned, the "system" is really the MSYS2 environment. ProgramData is *another* level, one that core Git does not know (yet).
