### ISSUE TITLE
Git Bash does not handle arguments with curly braces correctly

### ISSUE THREAD

**Issue by sigoden** [git-for-windows/git#5310]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.47.1.windows.1
cpu: x86_64
built from commit: 2cd22437f64229935dc564db969cbcbfed5e9045
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.11.0
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.5247]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable FSMonitor: Disabled
```

### Details

Here are examples running in Windows Terminal PowerShell.
```
PS> & 'C:\Program Files\Git\bin\bash.exe' dump.sh '{}'
{}
PS> & 'C:\Program Files\Git\bin\bash.exe' dump.sh '{foo}'
foo
PS> & 'C:\Program Files\Git\bin\bash.exe' dump.sh '{"foo"}'
{"foo"}
PS> & 'C:\Program Files\Git\bin\bash.exe' dump.sh '{"foo":"a\\c"}'
{"foo":"a\c"}
PS> & 'C:\Program Files\Git\bin\bash.exe' dump.sh 'a\\c'
a\\c
PS> & 'C:\Program Files\Git\bin\bash.exe' dump.sh '{a\\c}'
a\c
PS> & 'C:\Program Files\Git\bin\bash.exe' dump.sh '{"a\\c"}'
{"a\c"}
```

The content for `dump.sh` is:
```
printf "%s\n" "$@"
```

<details>
<summary>
In case the terminal escapes the arguments, I also wrote a node.js script to reproduce the above example.
</summary>

1. create `test.js`:

```js
const { spawnSync } = require('child_process');

const PROG = 'C:\\Program Files\\Git\\bin\\bash.exe';

const ARGS = [
    `{}`,
    `{foo}`,
    `{"foo"}`,
    `{"foo":"a\\\\c"}`,
    `a\\\\c`,
    `{a\\\\c}`,
    `{"a\\\\c"}`,
]

for (const arg of ARGS) {
    console.log(`> dump.sh '${arg}'`)
    spawnSync(PROG, ["dump.sh", arg], { stdio: 'inherit' });
}
```
2. Run `test.js`
```
> dump.sh '{}'
{}
> dump.sh '{foo}'
foo
> dump.sh '{"foo"}'
{"foo"}
> dump.sh '{"foo":"a\\c"}'
{"foo":"a\c"}
> dump.sh 'a\\c'
a\\c
> dump.sh '{a\\c}'
a\c
> dump.sh '{"a\\c"}'
{"a\c"}
```

The execution results are consistent.

</details>

Summary:
- If the text inside `{}` has no quotes, `{` and `}` will be removed.
- If the text inside `{}` contains double backslashs, the double backslashs will be replaced with single backslash.

**Comment by dscho** [comment]
It gets worse: if you put all of those arguments onto the same command-line, it changes behavior, and I just verified that Cygwin exposes the same results:

```console
PS> & 'C:\Program Files\Git\bin\bash.exe' .\dump-args.sh '{}' '{foo}' '{"foo"}' '{"foo":"a\\c"}' 'a\\c' '{a\\c}' '{"a\\c"}'
{}
foo
foo
foo:a\c
a\\c
a\c
a\c
PS> & 'D:\cygwin64\bin\bash.exe' .\dump-args.sh '{}' '{foo}' '{"foo"}' '{"foo":"a\\c"}' 'a\\c' '{a\\c}' '{"a\\c"}'
{}
foo
foo
foo:a\c
a\\c
a\c
a\c
```

I brought up Cygwin because Git for Windows inherits the Bash and this behavior from Cygwin (indirectly, through MSYS2).

Most likely, the actual problem is that Windows does not actually pass the command-line parameters individually, but only passes a complete command-line, and programs have to parse that command-line themselves. Cygwin seems to use a slightly different strategy to split the command-line parameters than PowerShell (or for that matter, [the Win32 API function `CommandLineToArgvW()`](https://learn.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw)). Therefore, it might get arbitrarily tricky trying to pass parameters containing curly braces and/or quotes to the Bash.

Since this is already a problem in Cygwin, it might be best to bring it up with that project, see https://cygwin.com/problems.html for details how to do that.
