### ISSUE TITLE
Figure out why edit-git-bash messes with the icon

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#534]
When editing `git-bash.exe` via `edit-git-bash.dll` (or `.exe`), it loses its icon. Try to figure out why.

**Comment by daviesj** [comment]
It is not just the icon that is getting removed. edit-git-bash removes all resources including the entire String Table, Icon, and Manifest. I think it is because of the call to BeginUpdateResource. I think you need to pass FALSE as the bDeleteExistingResources parameter rather than TRUE. According to MSDN, if that parameter is TRUE, all existing resources will be deleted. If you pass FALSE, existing resources are kept unless they are specifically deleted or replaced by calls to UpdateResource. https://msdn.microsoft.com/en-us/library/windows/desktop/ms648030(v=vs.85).aspx

**Comment by dscho** [comment]
@daviesj thanks!
