### ISSUE TITLE
curl sspi ntlm

### ISSUE THREAD

**Issue by educhana** [git-for-windows/git#555]
There are two curl binaries in git-for-windows located into:

> usr/bin/curl.exe
> nimgw64/bin/curl.exe

But compiled with different features. The one in usr/bin misses the SSPI feature, which means that can not use proxy NTLM auth using the windows login credentials.

Details:
> usr/bin/curl.exe -V
> curl 7.45.0 (x86_64-pc-msys) libcurl/7.45.0 OpenSSL/1.0.2d zlib/1.2.8 libidn/1.32 
> libssh2/1.6.0
> Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp s
> ftp smb smbs smtp smtps telnet tftp
> Features: Debug IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets Met
>alink

> nimgw64/bin/curl.exe -V
> curl 7.45.0 (x86_64-w64-mingw32) libcurl/7.45.0 OpenSSL/1.0.2d zlib/1.2.8 libidn/1.32
> libssh2/1.6.0 librtmp/2.3
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s
> rtmp rtsp scp sftp smtp smtps telnet tftp
> Features: IDN IPv6 Largefile **SSPI** Kerberos SPNEGO NTLM SSL libz TLS-SRP

Git works OK with NTLM+SSPI auth. But Git Bash puts first in the path the usr/bin version,

**Comment by dscho** [comment]
> Git Bash puts first in the path the usr/bin version,

This is not correct; Starting *Git Bash* from the Start Menu results in this `PATH`:

```sh
me@work MINGW64 ~
$ echo $PATH
/c/Users/me/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:[...]
```

As you can clearly see, `/mingw64/bin` is in the `PATH` *before* `/usr/bin`.

But maybe you started Git Bash differently and wanted to describe [what you tried, precisely](http://whathaveyoutried.com)?

**Comment by ismail** [comment]
PATH problem aside it doesn't make sense to ship two curl binaries.

**Comment by dscho** [comment]
@ismail patches welcome.

**Comment by educhana** [comment]
You are rigth. Starting with git-bash.exe puts /migw64 first. 

My fault. I was starting this using [cmder](http://cmder.net/) which packages git-for-windows inside, and puts /usr/bin path first. My fault. 

Just out of curiosity, what is the reason of shipping two binaries? Is it an error or is needed for something?

**Comment by dscho** [comment]
> Just out of curiosity, what is the reason of shipping two binaries? Is it an error or is needed for something?

(For background regarding MSys2 vs MinGW, the short version is that for some functionality, we rely on the POSIX emulation layer provided by MSys2, a slimmed down Cygwin. Whenever we can get away without using POSIX functionality, we try to rely on *MinGW* instead, which targets the Win32 API directly.)
 
The `curl` package (which is the MSys2 package) is required by Perl. Perl needs MSys2 because it requires the `fork()` call. And we need Perl because `git-svn` is implemented as a Perl script that relies on Subversion bindings (and Subversion bindings is another thing that is really hard to do without POSIX functionality).

The `mingw-w64-curl` package (which is the MinGW package) is required by the HTTP(S) support of `git.exe` itself.

These packages *both* include also the executables `curl.exe` you found. Therefore, it is actually *more* work to ship with only one `curl.exe` because we have to *filter out* one of them.

Feel free to patch [our exclusion filter](https://github.com/git-for-windows/build-extra/blob/20de70504286eceddcc6b44d33f2221705428efe/make-file-list.sh#L47-L76), make sure to test that your patch works by [making and running an installer](https://github.com/git-for-windows/git/wiki/Making-an-installer) and then open a Pull Request.

If I did not have a couple of *really* pressing other things to do, I would make that change myself, but as it is, I have to rely on your participation.
