### ISSUE TITLE
Local git repository does not exist after sucessfull clone when used from cygwin ssh/bash

### ISSUE THREAD

**Issue by olivergondza** [git-for-windows/git#568]
`git clone` fail to create the target directory silently (more details in [1]). I am not sure if this use-case is supported, though. It works correctly from git bash shipped with Git for Windows.

[1] http://stackoverflow.com/questions/34266571/local-git-repository-does-not-exist-after-sucessfull-clone

**Comment by olivergondza** [comment]
For the sake of completeness, I tried to reproduce in powershell and it (had the same problem as cygwin bash and) revealed the culprit a bit. Absolute paths like `/cygdrive/c/User/x` cause git to actually manipulate the content of `C:\cygdrive\c\User\x`.

**Comment by kostix** [comment]
I'm not quie sure what this bug report is about.

You mean you're trying to clone *on Windows* into `/tmp/targetDirectory`, and it

1. Works in Git Bash;
1. Does not work in other shells (like PowerShell).

Is my summary correct?

My take on this would be that having Git somehow interpret `/tmp` on Windows would be utterly strange.  Having special treatment for names like `/c/foo/bar` is sensible but what `/tmp/foo` would be mapped to? `C:\WINDOWS\TEMP`?  I'm afraid that would be wrong due to peculiarities of the default ACLs set on this folder.

**Comment by olivergondza** [comment]
I come across this problem in cygwin where `/tmp/foo` is a valid, frequently used path. It seems that all the paths starting with `/` have that problem (`/cygdrive/c/`). I was not able to find out if cygwin (and its paths) is supported or not.

**Comment by kostix** [comment]
@olivergondza, Git for Windows has nothing to do with Cygwin: it uses no part of its runtime and is generally unaware about the very Cygwin existence.

GfW uses MinGW for building, and some bits of it (notably some tools, ported from Unix -- such as `bash` and `perl`) use the MSYS2 runtime which is a fork of MSYS which is a fork of Cygwin. Note that that latter fork happened very very long time ago and MSYS had (and has) very different goals from those of Cygwin.

You might check [this](http://sourceforge.net/p/msys2/wiki/How%20does%20MSYS2%20differ%20from%20Cygwin/) -- especially see the point 6 in the "Runtime" section.

**Comment by dscho** [comment]
While Git for Windows ships with a modified version of Cygwin, it is *not* expected to interact well with software that records paths other than Windows ones (i.e. Cygwin's POSIX paths).

**Comment by olivergondza** [comment]
@dscho, @kostix, thanks for clarification.
