### ISSUE TITLE
selecting content with mouse do not work in git 2.0.3 version

### ISSUE THREAD

**Issue by sukia** [git-for-windows/git#578]
install git bash for windows by default install guide.
in git console, use mouse select text, it always input a CTRL-C char,
how to avoid the behavior?

**Comment by rimrul** [comment]
__How and where the fuck__ did you even find anything that points to that version on Windows? It certainly isn't an official release, since the last Git for Windows 1 version was  1.9.5, the first tag of Git for Windows 2 was v2.1.2, and the first developers preview was v2.3.4. That even stated 
>This is the developers' preview to show what Git for Windows 2.x looks like. Please note that it is not intended for use in production.

This warning definitly includes installing it 9 months later, after multiple official releases. 

This means, that you somehow compiled your own outdated version of Git for Windows, that probably never was stable or even meant for any public use. Please grab an __official__ copy of Git for Windows 2.6.4, do a __clean__  reinstall and test your usecase again. If your problem still persists give us some details about what you did, what setup options you chose and what environment you use.

**Comment by dscho** [comment]
@sukia sorry for the bumpy start. But it is true that the information is pretty incomplete: from where did you get your copy of Git for Windows? What guide are you talking about? What "git console" (we have "Git Bash" and "Git CMD" but not "git console"...)? What Ctrl+C *character* is this (or do you mean that pressing Ctrl+C does not insert the clipboard's contents)?

As it is, the report is very sparse on information and it is quite frustrating for anybody who is trying to help (and yes, we really do try to help). Maybe you want to fill in the blanks after studying our [bug reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines)?
