### ISSUE TITLE
Bash colorization

### ISSUE THREAD

**Issue by boxfoot** [git-for-windows/git#590]
Hi,

I'm having an issue with colorized output in my bash shell, and noticing differences when I run `\Program Files\Git\bin\bash.exe` versus `\Program Files\Git\git-bash.exe`

In BOTH of these shells, my basic shells and prompts colorize properly.  However, when I run commands in the shell, the are correctly colorized in `Git\bin\bash.exe` and not colorized in `Git\git-bash.exe`

`bin\bash.exe`:
![image](https://cloud.githubusercontent.com/assets/487130/12145590/bffc90e0-b454-11e5-8fc8-3434903a76aa.png)

`git-bash.exe`:
![image](https://cloud.githubusercontent.com/assets/487130/12145596/c99f00f6-b454-11e5-88e8-f04ac4d9650a.png)

I'm running Git for Windows v2.6.3.

Any idea what's going on or how I can fully colorize `git-bash.exe` (which is an otherwise more feature-complete shell)?

**Comment by kgybels** [comment]
[Mocha uses node](https://github.com/mochajs/mocha/blob/2.3.4/bin/mocha#L1) which is not [mintty](https://github.com/mintty/mintty) aware.
This is also mentioned as a known issue in [Git for Windows' release notes](https://github.com/git-for-windows/build-extra/blob/17c1640749aa46e73400b4f18e3580d998108eda/installer/ReleaseNotes.md#known-issues)

@boxfoot Can you try running your command through winpty to see if it works?
Assuming node is in your path:
`$ winpty node ./node_modules/.bin/mocha --require babel-core/register --require app/scripts/test/setup app/scripts/test --recursive`

Or just `node` instead of `winpty node` because Git for Windows is already setting an [alias](https://github.com/git-for-windows/build-extra/blob/17c1640749aa46e73400b4f18e3580d998108eda/git-extra/aliases.sh#L13-L16) for it.

**Comment by boxfoot** [comment]
@kgybels that makes sense, and I missed this in the known issues list.

The following worked for me: `winpty bash ./node_modules/.bin/mocha`.  Note that I had to use `bash`, not `node` as the interpreter b/c I was actually referencing a launch script.
