### ISSUE TITLE
Dual-sign the installers with SHA-1 and SHA-2

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#592]
SHA-1 is deprecated, we should use SHA-2 (and several browsers now consider SHA-1 signed executables as if they were unsigned). But Vista and pre-2008 only accept SHA-1.

Pointed out by Sunny Gakhar.

**Comment by PhilipOakley** [comment]
I understand that getting a sha-2 cert for signing is costly, so it may be some time before a full sha-2 signing can happen. 

I was thinking that it may be worth having a note about the issue "Newer browers may issue a signature warning; check using our sha1 certificate" on the download web site(s).

While the main G4W site [git-for-windows.github.io](https://git-for-windows.github.io/) is under local control, the more commonly used site for download is [git-scm.com](https://git-scm.com/downloads).

Would it be worth (me) attempting to add a note to the G4W site, and perhaps a more involved change to git-scm? Or does the hassle of updating the git-scm mean that the effort would be largely nugatory.

**Comment by shiftkey** [comment]
I'm not sure how this is progressing @dscho but I'll drop some notes in here about our recent adventures with this and GitHub Desktop:

- we had an uptick in reports mid-January when Smartscreen (and IE11 where SmartScreen isn't available) reported that our installer was "invalid or corrupt"
- the changes are documented [here](http://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-authenticode-code-signing-and-timestamping.aspx) and this came into effect from January 1 as the relevant Windows Update propagated out to users - I don't see a mention of timestamping in [the release script](https://github.com/git-for-windows/build-extra/blob/b74dc5f177a67970b3384f2c4bef7a19aacc61d5/please.sh#L636) but maybe you're doing this already.
- an installer signed with a SHA-1 certificate and timestamped before 2016-01-01 will be trusted for a bit longer, but because we didn't timestamp our files we got caught up in this.
- as mentioned about, dual-signing the installer is necessary for pre-Windows 7 releases as they won't get SHA-2 support through Windows Update

**Comment by dscho** [comment]
I am pretty confident that I addressed this ticket through https://github.com/git-for-windows/build-extra/commit/5f321a4d6778744cbae773c0758816ebcc82f958 and the next release will show that it is fixed.

**Comment by dscho** [comment]
Just as a follow-up: Git 2.7.0(2) is dual-signed and therefore closes this ticket.
