### ISSUE TITLE
Uninstaller deletes extra git plugins in mingw64\libexec\git-core

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#597]
Very often the user upgrades Git for Windows when a new version is released.
However, the uninstaller deletes extra git plugins (`git-xxx.exe`) in `mingw64\libexec\git-core`.

If it cannot preserve the plugins, please show a warning message to tell user to re-install their own plugins.

**Comment by dscho** [comment]
No, the warning is the wrong solution. The uninstaller should know about the files it installed, and remove them afterwards, and nothing else. AFAICT we already do that with pretty much all the files other than `mingw64\bin` and `mingw64\libexec\git-core`.

I actually thought that we handled the files in `mingw64\libexec\git-core` properly, too.

@linquize feel free to work on https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss (using the instructions in the [Making an installer](https://github.com/git-for-windows/git/wiki/Making-an-installer) wiki page) to solve this problem.

**Comment by linquize** [comment]
ping

**Comment by dscho** [comment]
pong:

> @linquize feel free to work on https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss (using the instructions in the Making an installer wiki page) to solve this problem.

**Comment by fourpastmidnight** [comment]
This should be resolved once the MSI installer is the primary installer in use once #682 is completed.

**Comment by whoisj** [comment]
There are other locations besides `mingw64\libexec\git-core` that plugins can place their binaries and Git will find. They should likely live there. The `%programfiles/Git% belongs to Git and it is well within its right to modify/remove any files located there.

**Comment by fourpastmidnight** [comment]
@whoisj Ordinarily, I would agree with you. Unfortunately, as @dscho has made clear to me, this just isn't the case for Git For Windows. One case in point is the recent integration with the Git Credentials Manager for Windows--but I won't go into the details because the point is moot anyway.

Once the MSI is completed (per #682), the Windows Installer will only remove those files which it itself installed out of the MSI database. So users who create their own git hooks, templates, scripts, or anything else and place them in the Git program installation directory will not have those files removed when reinstalling, uninstalling, upgrading, or repairing Git For Windows.

Having said that, if users _customize_ any of the existing files (e.g. change an existing script installed by the MSI installer), those changes _will_ be lost on reinstall, uninstall, repair, and upgrade.

**Comment by whoisj** [comment]
> if users customize any of the existing files (e.g. change an existing script installed by the MSI installer), those changes will be lost on reinstall, uninstall, repair, and upgrade.

I do believe that is considered correct behavior. If I re-install an application, I do expect it to be in pristine condition and not drag state from a previous installation with it.

**Comment by fourpastmidnight** [comment]
@whoisj Yes, you are right, that's the correct behavior for a MSI.
