### ISSUE TITLE
git send-email not working anymore

### ISSUE THREAD

**Issue by sawong** [git-for-windows/git#621]
In git version 2.7.0.windows.1, I had send-email working with the following settings in my .gitconfig file:

[sendemail]
	smtpserver = mail.somecompany.com
	smtpuser = firstname.lastname
	from = Firstname Lastname

However, today when I typed the command:

git send-email --to someone@somecompany.com --suppress-cc=all HEAD~3

I received the following spew:

...OK. Log says:
Server: mail.somecompany.com
Use of uninitialized value $raw_from in concatenation (.) or string at C:\Program Files\Git\mingw64/libexec/git-core\git-send-email line 1404.
MAIL FROM:<>
RCPT TO:<someone@somecompany.com>
From: Firstname Lastname
To: someone@somecompany.com
Subject: [PATCH 1/3] ...
Date: Thu, 21 Jan 2016 13:39:50 -0800
Message-Id: <1453412392-2764-1-git-send-email-firstname.lastname@somecompany.com>
X-Mailer: git-send-email 2.7.0.windows.1

Result: 250

Before getting this error, I did uninstall and re-install git 2.7.0 for windows since the time send-email was working, and the installation froze on the re-install.  So I had to kill it and install again.

Any help would be much appreciated.

**Comment by PhilipOakley** [comment]
Doesn't 'from' need a proper email address. 

Your example doesn't have the < first @ last.com > part of the email. Did you trim that?

The message says to look at the git-send-email shell script (looks: it's a perl script) and see which part of the code is failing...



There may be other variables not yet defined in your .gitconfig for this case

Philip

----- Original Message ----- 
  From: sawong 
  To: git-for-windows/git 
  Sent: Thursday, January 21, 2016 10:34 PM
  Subject: [git] git send-email not working anymore (#621)


  In git version 270windows1, I had send-email working with the following settings in my gitconfig file:

  [sendemail]
  smtpserver = mailsomecompanycom
  smtpuser = firstnamelastname
  from = Firstname Lastname

  However, today when I typed the command:

  git send-email --to someone@somecompanycom --suppress-cc=all HEAD~3

  I received the following spew:

  OK Log says:
  Server: mailsomecompanycom
  Use of uninitialized value $raw_from in concatenation () or string at C:\Program Files\Git\mingw64/libexec/git-core\git-send-email line 1404
  MAIL FROM:<>
  RCPT TO:someone@somecompanycom
  From: Firstname Lastname
  To: someone@somecompanycom
  Subject: [PATCH 1/3] 
  Date: Thu, 21 Jan 2016 13:39:50 -0800
  Message-Id: 1453412392-2764-1-git-send-email-firstnamelastname@somecompanycom
  X-Mailer: git-send-email 270windows1

  Result: 250

  Before getting this error, I did uninstall and re-install git 270 for windows since the time send-email was working, and the installation froze on the re-install So I had to kill it and install again

  Any help would be much appreciated

**Comment by sawong** [comment]
Brilliant, Philip!

It works with:

from = firstname.lastname@somecompany.com

But then I noticed that the 'From' field in the received e-mail says: firstname.lastname@somecompany.com

It also works when I delete the 'from' line in .gitconfig altoghether, in which case the 'From' field in the received e-mail says: Firstname Lastname

This is exactly what I wanted.

Many thanks!
