### ISSUE TITLE
fatal: 'remote-https' appears to be a git command, but we were not able to execute it. Maybe git-remote-https is broken?

### ISSUE THREAD

**Issue by 810** [git-for-windows/git#646]
@dscho see the log from Dependency Walker 
https://justpaste.it/r50w

**Comment by dscho** [comment]
No need to worry, this label just indicates that *this ticket* is missing all the relevant info.

**Comment by dscho** [comment]
Oh, and the log also misses the relevant info.

**Comment by dscho** [comment]
For lurkers, this ticket started in an unrelated ticket: https://github.com/git-for-windows/git/issues/627#issuecomment-179568268

**Comment by 810** [comment]
whats missing in the log, i exported it from DW

**Comment by dscho** [comment]
> Oh, and the log also misses the relevant info.

@810 just so you know *what* is missing: [I asked *specifically* for full paths](https://github.com/git-for-windows/git/issues/627#issuecomment-179693314) but the log only contains basenames.

But since I have your attention, I would like you to copy `curl.exe` from `/mingw64/bin/` to `/mingw64/libexec/git-core/` and rename it to something that does not yet exist in your PATH, then execute it. If it still launches, something is rotten with your `git-remote-https.exe`.

In any case, it would be good to stop doing those tests with the PortableGit embedded in GitHub and start testing with PortableGit as of https://github.com/git-for-windows/git/releases/latest

**Comment by dscho** [comment]
> whats missing in the log, i exported it from DW

BTW you want me to continue complete sentences, you do same...

**Comment by 810** [comment]
> @810 just so you know what is missing: I asked specifically for full paths but the log only contains basenames.

I have updated the log

**Comment by 810** [comment]
Ok got it working again.

1) I added environment variables on top:
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\system32\Wbem
C:\WINDOWS\system32\WindowsPowerShell\v1.0\
2) removed the git, and installed again
3) Restarted the computer
