### ISSUE TITLE
 wish.exe doesn't exist in Git release package.

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#66]

**Comment by dscho** [comment]
@lygstate please put a little bit more effort into this. You *know* that this is a developers' preview, so you *know* that you are supposed to try to fix problems you experience.

Even if you do not see fit to contribute Pull Requests, an empty description is just poor form. The *least* you should do is to provide precise information what you tested, i.e. what file you downloaded, what is the MD5 (or SHA1). It cannot have taken more than ten seconds to write this bug report. *I* already spent ten times as much, just to reply. You might want to reconsider how much time you are willing to ask others to spend and how much you are willing to spend as well.

**Comment by lygstate** [comment]
Sorry for the unclear description, it's comes from
cmd/gitk.cmd
This script will calling to wish.exe
But wish.exe doesn't exist in msys2 package.

**Comment by dscho** [comment]
Step 1: download and install the SDK: https://git-for-windows.github.io/#download-sdk

Step 2: build a portable application: `cd /usr/src/build-extra && git fetch && git checkout master && ./portable/release.sh 2.3.5-lygstate`

Step 3: test the portable application

You will see that the bug you described has been fixed *before* you described it. There just has not been any other preview in the meantime because the assumption was that a *developers' preview*'s target audience consists of developers who would go through the above steps and find out that things have been fixed already.

So feel free to join the ranks of developers who work on Git for Windows. So far, both of us had to spend time on a bug that was already fixed (more of my time, too).
