### ISSUE TITLE
Bash not auto completing file names anymore

### ISSUE THREAD

**Issue by pflannery** [git-for-windows/git#672]
Just installed git version 2.7.2.windows.1 on Windows 10 64bit

Bash has stopped showing and auto completing file names when pressing tab after typing `./`
It shows and auto complete's folders.

Bash also no longer pastes text when using  context menu or ctrl+v.

**Comment by yaras** [comment]
> Bash has stopped showing and auto completing file names when pressing tab after typing ./
> It shows and auto complete's folders.

I just tried to check auto completion and it seems to work. My test:

```
git init .
touch afile
touch bfile
```

after that I type:

```
git add [TAB] [TAB]
```

and I get:

```
afile  bfile
```

I tried also:

```
git add a[TAB]
```

and I get:

```
$ git add afile
```

My git version:

```
$ git version
git version 2.7.2.windows.1
```

Could you provide [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of your issue?

> Bash also no longer pastes text when using context menu or ctrl+v.

It seems to be a separate problem, so you should report this in separate issue, but as far as I remember, on git bash I used Shift+Ins instead of Ctrl+V to paste text. Moreover, when I press right mouse button on console and select *Paste* the text in my clipboard gets pasted.

**Comment by yaras** [comment]
And also to be precise I tried auto completion with `./`: `git add ./[TAB][TAB]`

and I get:

```
afile  bfile
```

and after typying `git add ./a[TAB]` i get:

```
git add ./afile
```

**Comment by pflannery** [comment]
@yaras what about trying without the git cmd

```
$ touch afile.sh
$ ./a[TAB]
```

This used to work for me with the bash supplied in git for windows.

**Comment by pflannery** [comment]
Just to add, when not specifying `./` its happy to find files

```shell
$[TAB]
$ a
Display all 247 possibilities? (y or n)
AboveLockAppHost.dll
accessibilitycpl.dll
AccountsControlInternal.dll
ACCTRES.dll
acledit.dll
...etc....
```

**Comment by yaras** [comment]
@pflannery,

> what about trying without the git cmd [...]

I've run your code and it indeed does not show autocomplete options, so it is an issue.

> This used to work for me with the bash supplied in git for windows.

On which version did it work?

**Comment by pflannery** [comment]
> On which version did it work?

Good question, I'm not sure what it was.

@yaras thanks for your assist here

**Comment by yaras** [comment]
>> On which version did it work?

> Good question, I'm not sure what it was.

I'm afraid that without this answer it will be hard to trace this regression bug (assuming it worked in any previous version).

There are plenty of old versions of *Git for windows* on [Release page](https://github.com/git-for-windows/git/releases). Could you try some of them to check on which version it worked?

**Comment by dmsul** [comment]
Just to help out, I have autocomplete and `ctrl+v` pasting with version:

```bash
$ git --version
git version 2.6.3.windows.1
```
I'm in Win 10, 64-bit.

Note that autocomplete only works on files when appropriate. For example, if I have:

```bash
$ ls -l
total 3.8K
-rw-r--r-- 1 Daniel 197121 1.3K Feb 27 11:30 nonex_script.py
-rwxr-xr-x 1 Daniel 197121 2.5K Feb 25 21:08 executable_script.sh
```

Then `./ex[TAB]` autocompletes to `./executable_script.sh`, but `./non[TAB]` does not autocomplete because `nonex_script.py` cannot be called directly (note the different `x` permissions). However, if I try `python ./nonex[TAB]` or `vim nonex[TAB]`, we get autocompletion as expected. @pflannery, can you try your autocomplete under these different scenarios?

**Comment by pflannery** [comment]
@dmsul 

The following was running bash with admin rights.

```
$ touch ./run.sh

$ ls -l ./run.sh
-rw-r--r-- 1 Peter 197121 0 Feb 28 18:09 ./run.sh

$ chmod +x ./run.sh

$ ls -l ./run.sh
-rw-r--r-- 1 Peter 197121 0 Feb 28 18:09 ./run.sh
```

I've also tried `chmod 777 ./run.sh` but not able to get execute rights on a file.

**Comment by dscho** [comment]
> I've also tried chmod 777 ./run.sh but not able to get execute rights on a file.

This will never work, as the permission system expected by the POSIX tool chmod is incompatible with Windows' ACLs.

You will find that adding a shebang line (`#!/bin/sh` or some such as first line of the script) will make it auto-complete. And it will make the script executable to begin with.

For future record: the MCVE section is *really* about helping others to reproduce your problem, *not* to sneak in an unrelated bug report.

**Comment by pflannery** [comment]
I just tried putting a shebang `#!/bin/sh` in to ./run.sh and it worked

**Comment by pflannery** [comment]
thanks for you help @yaras @dmsul @dscho
