### ISSUE TITLE
ssh-add: Error connecting to agent: Connection timed out

### ISSUE THREAD

**Issue by cztomczak** [git-for-windows/git#674]
I've tried lots of things by googling, but no luck. I always get this error.
```
.. started ssh-agent OK
$ ssh-add
Error connecting to agent: Connection timed out
```

My .ssh/config:
```
Host github.com
  HostName github.com-cztomczak
  User git
  IdentityFile <...>
  IdentitiesOnly yes
```

Env variables:
```
GIT_SSH c:\bin\PuTTY\plink.exe 
```

I have __a passphrase set__ for my identitiy file. Pageant startups with my OS and asks for passphrase.

When I do ssh `git@github.com` or plink.exe `git@github.com` it authenticates fine.

git clone fails using both SSH and HTTPS:

```
$ git clone git@github.com:cztomczak/pycef.git
Cloning into 'pycef'...
FATAL ERROR: Disconnected: No supported authentication methods available (server sent: publickey)
fatal: Could not read from remote repository.
```

```
$ git clone https://github.com/cztomczak/pycef.git
Cloning into 'pycef'...
fatal: I don't handle protocol 'https'
```

I can clone repos fine using Github Desktop or SourceTree.

Btw. in Git-Bash on 32-bit an icon is missing in taskbar. On 64-bit the icon is OK. Been reinstalling it a few times and the icon is always missing in 32-bit. This was happening in 2.7.0, 2.7.1 and still in 2.7.2.

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

Tried both 32-bit and 64-bit, issue occurs in both.

```
$ git --version
git version 2.7.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

Win7 Pro 64-bit SP1.

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults.

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash from context menu.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
ssh-agent
or
eval `ssh-agent -s` 
```
 - What did you expect to occur after running these commands?

Starting ssh-agent to succeed.

 - What actually happened instead?

It failed. Connection timed out.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/cztomczak/pycef

**Comment by dscho** [comment]
PLink does not use ssh-agent but PuTTY's internal method to save connections.

**Comment by dscho** [comment]
I guess that this answered the question. It is a bit sad to get no feedback.

**Comment by cztomczak** [comment]
@dscho Still the problem persists. What was the solution?

**Comment by landstander668** [comment]
@cztomczak, it looks like you're using a mix of OpenSSH (ssh-add and .ssh/config) and PuTTY (Pageant and Plink) components. Any particular reason why? Neither knows of (or interacts with) the other, so I'm not surprised there are issues in that area.

The main thing which stands out is that Plink uses PuTTY's mechanism for saving settings, and won't even look at your .ssh/config file. You should be able to create a saved session (via putty.exe) named "github.com" with equivalent options (such as username) instead. This might actually be all you need, since Plink should be able to use the key stored in Pageant without any additional configuration (unless explicitly disabled).

The ssh-add command lacks the ability to communicate with Pageant, so unless I'm misunderstanding (and you're trying to leverage the OpenSSH authentication agent as well) that simply won't work. Now OpenSSH can be made to authenticate against keys **already stored** in Pageant, via the msys2 build of [ssh-pageant](https://github.com/cuviper/ssh-pageant)... this isn't currently built into Git for Windows, but is pretty easy to download and drop into place.

**Comment by cztomczak** [comment]
@landstander668 Just trying to make it work. Thanks for explaining, will try the suggestions.

**Comment by landstander668** [comment]
@cztomczak Only partially related, but I've added a Wiki page explaining how to [manually configure ssh-pageant](https://github.com/git-for-windows/git/wiki/OpenSSH-Integration-with-Pageant) under Git for Windows. This would allow Git to use OpenSSH instead of PuTTY for remote access, which might simplify your configuration, while still leveraging Pageant for agent key-based authentication.

Basically, it's a drop-in replacement for *ssh-agent* which simply forwards request to *pageant*.
