### ISSUE TITLE
Not possible to set GIT_SSH to a path with spaces

### ISSUE THREAD

**Issue by klikh** [git-for-windows/git#692]
Windows 7 64-bit
git version 2.7.2.windows.1
Git Bash

I have an executable script located in a folder with spaces, and what to use it for git over SSH. However, it seems that it is simply not possible to define GIT_SSH so that it points to a path with spaces.

Neither of the following works:

    $ export GIT_SSH=C:\\Users\\John\ Smith\\git-ssh-.bat
    $ export GIT_SSH=/c/Users/John\ Smith/git-ssh-.bat
        
    $ git fetch
    'C:\Users\John' is not recognized as an internal or external command,
    operable program or batch file.
    fatal: Could not read from remote repository.

Quoting gives another error but still doesn't work:

    $ export GIT_SSH="/c/Users/John\ Smith/git-ssh-.bat"
    $ export GIT_SSH=\"/c/Users/John\ Smith/git-ssh-.bat\"
    $ export GIT_SSH="C:\\Users\\John\ Smith\\git-ssh-.bat"
    $ export GIT_SSH="C:\Users\John Smith\git-ssh-.bat"

    $ git fetch
    error: cannot spawn C:/Users/John/ Smith/git-ssh-.bat: No such file or directory
    fatal: unable to fork

I would appreciate if you give me a workaround (if there is any workaround except "use path without spaces") until the issue is fixed.

**Comment by klikh** [comment]
Googling shows that the issue exists for a long time, and [was already reported](https://groups.google.com/forum/#!searchin/msysgit/GIT_SSH$20space/msysgit/ePVSH9ZC-74/WYflvp__foEJ) but was not ported to this bugtracker.

**Comment by dscho** [comment]
@klikh the quoted approach is the correct one, but I suspect that we never supported calling `.bat` scripts, only `.sh` ones.

**Comment by klikh** [comment]
> the quoted approach is the correct one
Which one exactly?

>  I suspect that we never supported calling .bat scripts, only .sh ones.
bat scripts are perfectly supported unless the path to the script contains a space. 

However, I'll check sh as well, thanks.

**Comment by dscho** [comment]
> the quoted approach is the correct one
> 
> Which one exactly?

Sorry. I meant this one:

> ```sh
> $ export GIT_SSH="C:\\Users\\John\ Smith\\git-ssh-.bat"
> ```

However, you are correct:

> .bat scripts are perfectly supported

Whoa, you're right! I did not know...

And I did verify that it works without spaces in the path and does not work with spaces. The easiest workaround for you is to use the short names (for backwards-compatibility, every file name has an alternate 8.3 compliant name, in your case it *might* be `C:\Users\JOHNSM~1\GIT-SS~1.BAT`).

It appears that something spooky is going on in the [`CreateProcessW()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425%28v=vs.85%29.aspx) call: it simply does not work for `.bat` files if the  the `lpApplicationName` parameter contains spaces, and even if it is replaced by the short path (using the [`GetShortPathName()` function](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364989%28v=vs.85%29.aspx)), if the `lpCommandLine` does not match the short path, it still will fail.

It *does* work, however, if quoting the first argument in `lpCommandLine` and passing `NULL` as `lpApplicationName`.

**Comment by dscho** [comment]
Fixed via 8086988cd73ab0044a797d7edd60b6d5d56b59d2

**Comment by klikh** [comment]
Wow. Thanks for the quick fix!

> The easiest workaround for you is to use the short names (for backwards-compatibility, every file name has an alternate 8.3 compliant nam

Yep, the workaround is clear, but the problem is how to identify this short name. E.g. in my Java program there is no straightforward method to do it, only by making a native system call.

**Comment by avih** [comment]
> every file name has an alternate 8.3 compliant name

AFAIK, on windows 8 and later, 8.3 names are only enabled by default on drive C (try `dir /X`)

**Comment by dscho** [comment]
> on windows 8 and later, 8.3 names are only enabled by default on drive C

Would you have a reference for this?

**Comment by avih** [comment]
> Would you have a reference for this?

Nothing too concrete, but that's my recollection from some time ago when I checked the subject, and when I search now I also see people who don't have 8.3 names and how to enable them (`fsutil` apparently).

Also, on few win7 systems which I checked just now they have short names on non C drives, and on win8/10 which I checked there are no 8.3 names on non-C drives.

So so far, I can't find evidence to contradict this.

**Comment by dscho** [comment]
> So so far, I can't find evidence to contradict this.

Hmm. I hoped for some link to an official statement that positively verifies this, not for the absence of contradicting evidence.

**Comment by avih** [comment]
Same, but I couldn't find one.

**Comment by SyntevoAlex** [comment]
Came across this issue by accident. We also had problems with it.

The problem here is not with `CreateProcessW` and also not related to Windows 7.

1. In OP's case, git is trying to run `git-ssh-.bat`
2. But `.bat` file is not an executable, so it can't be started directly.
3. `CreateProcessW` seems to have a dedicated code path for that, which eventually starts `cmd.exe /c` instead.
4. `cmd.exe` has non-standard commandline parsing rules.
   The most interesting part to us is that it won't accept *two* quoted arguments.
    
    Try it yourself:
   `cmd.exe /c "notepad.exe" 1.txt`
   `OK`
   
   `cmd.exe /c "notepad.exe" "1.txt"`
   `'notepad.exe" "1.txt' is not recognized as an internal or external command, operable program or batch file.`
5. So if both SSH helper has spaces and also one of its arguments has spaces, then:
   a. `CreateProcessW` will _succeed_.
   b. `cmd.exe` will exit with error `is not recognized...`.
   c. Notice that in OP's sample output we actually see `is not recognized...`.

Now regarding the fix applied. This is also rather curious.

1. If you use `CreateProcessW` with both arguments, it ends up starting like
   `C:\WINDOWS\system32\cmd.exe /c "C:\Temp\ssh helper.bat" user@server.com "git-upload-pack '/repo 1'"`
2. If you only use `lpCommandLine`
   `C:\WINDOWS\system32\cmd.exe /c ""C:\Temp\ssh helper.bat" user@server.com "git-upload-pack '/repo 1'""`

You can see it using Process Monitor.

Notice additional surrounding quotes. That's the "correct" way in terms of `cmd.exe` special parsing rules.
