### ISSUE TITLE
Unable to clone repository: No such file or directory

### ISSUE THREAD

**Issue by McDepp** [git-for-windows/git#700]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.
  
   Windows <=2.7.4 32-bit/64-bit 
   The issue is for all git version till the newest release 2.7.4.
   I try to install it on default and "c:\git" folder. Checkout out folder is at toplevel like directly on top of drive path (i.e. "e:\" ).

```
$ git --version
git version 2.7.4.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

 Windows 7/10 Professional  (all SPs) 32-bit and 64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

 Choose default setup except: "checkout as-is, commit as-is"

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 Bash and tortoisegit

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

For example cloning linux-kernel
```
$ git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git 
```
 The same issue happens with "core.symlinks=true" and"core.longpaths=true".
 I have same issue at company. I am not the only one with this issue.

 - What did you expect to occur after running these commands?

 Successfully cloned. git status says no changes at all

 - What actually happened instead?

 ```
$ git clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
Cloning into 'linux-stable'...
remote: Counting objects: 4992096, done.
remote: Compressing objects: 100% (410280/410280), done.
remote: Total 4992096 (delta 332056), reused 0 (delta 0)
Receiving objects: 100% (4992096/4992096), 950.52 MiB | 2.61 MiB/s, done.
Resolving deltas: 100% (4176496/4176496), done.
Checking connectivity... done.
error: unable to create file drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c (No such file or directory)
error: unable to create file drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.h (No such file or directory)
Checking out files: 100% (52916/52916), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c
        deleted:    drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.h
        modified:   include/uapi/linux/netfilter/xt_CONNMARK.h
        modified:   include/uapi/linux/netfilter/xt_DSCP.h
        modified:   include/uapi/linux/netfilter/xt_MARK.h
        modified:   include/uapi/linux/netfilter/xt_RATEEST.h
        modified:   include/uapi/linux/netfilter/xt_TCPMSS.h
        modified:   include/uapi/linux/netfilter_ipv4/ipt_ECN.h
        modified:   include/uapi/linux/netfilter_ipv4/ipt_TTL.h
        modified:   include/uapi/linux/netfilter_ipv6/ip6t_HL.h
        modified:   net/netfilter/xt_DSCP.c
        modified:   net/netfilter/xt_HL.c
        modified:   net/netfilter/xt_RATEEST.c
        modified:   net/netfilter/xt_TCPMSS
```
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

For example use theese repositories:
git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git

**Comment by dscho** [comment]
This is a known problem with the Linux kernel repository. Unfortunately, they believe that it makes sense to have files whose name differ only in case. This cannot work on a file system that is case-insensitive, such as NTFS in Windows' default mode.

**Comment by dscho** [comment]
Please note that I am very sympathetic to your situation, I just believe that the best course of action would be to talk sense into the Linux kernel developers. (Frankly, I have no idea how we could support this use case in Git for Windows...)

**Comment by Dirk1966** [comment]
The link below explains nicely, how to deal with POSIX case sensitive file names under Windows:
[http://superuser.com/questions/266110/how-do-you-make-windows-7-fully-case-sensitive-with-respect-to-the-filesystem](url)
I would try if this helps, but you also have special files in Windows "con", ... which may cause problems.

**Comment by dscho** [comment]
@Dirk1966 why not summarize it here? And ideally, this summary would end up in our FAQ...

**Comment by Dirk1966** [comment]
Willco, but this takes time!

**Comment by McDepp** [comment]
Thank you. Personally, I don't like windows. Not POSIX compatible and old crappy stuff like case-insensitive filenames or max-path-filenames (260 Byte), no softlink support without administration rights etc.

**Comment by Dirk1966** [comment]
At home, my system is LinUX, at work, I am mostly working under LinUX (AIX, HP-UX, Solaris, DEC OSF Unix, but this is just history, it is nearly no more).  The Windows API supports more than 32000 characters path length and even my office laptop boots Windows.
The more than 32000 characters path length - since Windows 8 you can use reasonable long path lengths - and the registry entry obcaseinsensitive were encourageing enough to perform some tests, which I documented above.
Unfortunately, there were too much obstacles around to continue without a group and a plan, what to do in future.

**Comment by sschuberth** [comment]
I don't think this issue is (only) about case-sensitivity of file systems. I've found this issue because I have a similar issue if I simply try to add a file named `aux.java` to a Git repository:

    $ git --version
    git version 2.8.1.windows.1
    $ mkdir test
    $ cd test
    $ git init
    Initialized empty Git repository in [...]/test/.git/
	$ touch aux.java
	$ git add .
	fatal: unable to stat 'aux.java': Permission denied
	$ stat aux.java
	  File: 'aux.java'
	  Size: 0               Blocks: 0          IO Block: 65536  regular empty file
	Device: 84b03637h/2226140727d   Inode: 2814749768165600  Links: 1
	Access: (0644/-rw-r--r--)  Uid: (1063636/[...])   Gid: (1049089/ UNKNOWN)
	Access: 2016-04-20 17:46:15.570252000 +0200
	Modify: 2016-04-20 17:46:15.570252000 +0200
	Change: 2016-04-20 17:46:15.569772200 +0200
	 Birth: 2016-04-20 17:46:15.569772200 +0200

Originally, I saw the issue with `aux.java` when cloning an existing repository that contains a file named like this, and the file appeared to be deleted.

I realize `aux` is a reserved device name on Windows, but `aux.<ext>` is not, and IMO it should "just work" to track these files.

**Comment by Dirk1966** [comment]
I did not write something into the FAQ, because of lack of knowledge and lack of time, but `aux.<ext>` is also handled differently by Windows and is something like "reserved".  Here is a session trace of `cmd.exe` in Windows 10-32:
`C:\Users\WinUser>echo "Test" >> auxt`
`C:\Users\WinUser>more auxt`
`"Test"`
`C:\Users\WinUser>echo "Test" >> aux`
`The system cannot find the file specified.`
`C:\Users\WinUser>echo "Test" >> aux.java`
`The system cannot find the file specified.`
`C:\Users\WinUser>`
As you can see, `aux.java` is handled in the same way as `aux`.

**Comment by sschuberth** [comment]
> As you can see, `aux.java` is handled in the same way as `aux` also in pure Windows.

You're right. What confused me is that `echo "test" > aux` and `echo "test" > aux.java` both actually *do* work in Git Bash. With MSYS being a Cygwin fork, I guess this is because [Cygwin can handle these special file names](https://cygwin.com/cygwin-ug-net/using-specialnames.html#pathnames-dosdevices), but `git.exe`, being a native Windows executable, can not. The question is whether `git.exe` *could* be made to handle these special file names, and whether that's desirable.

**Comment by Dirk1966** [comment]
> The question is whether git.exe could be made to handle these special file names via namespaces and the \\?\ prefix for file I/O, and whether that's desirable.

Of course it would be nice to handle this, but this will require massive effort.  Windows offered POSIX compatibility in some old programs (nfs server) and the "Ubuntu bash for Windows" for Windows 10-64 seems to use this or something similar too.
In the latter, in path C:/Users/UserName/AppData/... even two different files with name "t" and "T" in one directory are supported.  But then you touch the system very deeply and you may want to cover nearly all of the problems arising in the file space naming area.

**Comment by dscho** [comment]
The question is not whether it can be made to handle these file names, but
1. who is gonna do it, and
2. what to do about *other* software that *still* cannot handle these file names?

I guess everybody agrees that the answer to 1. is: "We still have to find somebody who would be willing" and to 2. "*elaborate shrug*".
