### ISSUE TITLE
How can I use localisation files in Git for Windows

### ISSUE THREAD

**Issue by charlesmilette** [git-for-windows/git#724]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing

64-bits Git 2.7.1.windows.2 on Windows 10 build 14925, but also appeared on 10586.  

Whenever I run a git command, in any shell, I get this:

```
C:\Users\Charles\Git\APNGViewer>git push
sh: warning: setlocale: LC_ALL: cannot change locale (fr): No such file or directory
sh: warning: setlocale: LC_ALL: cannot change locale (fr): No such file or directory
Everything up-to-date
```

Because the environement variable `LC_ALL` is set to `fr`, but Git or `sh` (not sure which one) was not able to find it's appropriate localisation files. [I know that some exists](https://github.com/msysgit/git/tree/master/po), but they don't seem to be bundled with a Git for Windows setup. 

For example, `make`:

```
C:\Users\Charles\Git\APNGViewer>make
make: *** Pas de cibles spécifiées et aucun makefile n'a été trouvé. Arrêt.
```

It has the appropriate localisation files, and thus shows content in French.  

**How can I use the localisation files to get French translations and fix this error?**

**Comment by PhilipOakley** [comment]
----- Original Message ----- 
  From: Charles Milette 
  To: git-for-windows/git 
  Sent: Sunday, April 10, 2016 1:08 AM
  Subject: [git-for-windows/git] How can I use localisation files in Git for Windows (#724)


    a..  I was not able to find an open or closed issue matching what I'm seeing 
  64-bits Git 2.7.1.windows.2 on Windows 10 build 14925, but also appeared on 10586. 

  Whenever I run a git command, in any shell, I get this:

C:\Users\Charles\Git\APNGViewer>git push
sh: warning: setlocale: LC_ALL: cannot change locale (fr): No such file or directory
sh: warning: setlocale: LC_ALL: cannot change locale (fr): No such file or directory
Everything up-to-date
Because the environement variable LC_ALL is set to fr, but Git or sh (not sure which one) was not able to find it's appropriate localisation files. I know that some exists, but they don't seem to be bundled with a Git for Windows setup. 

  For example, make:

C:\Users\Charles\Git\APNGViewer>make
make: *** Pas de cibles spécifiées et aucun makefile n'a été trouvé. Arrêt.
It has the appropriate localisation files, and thus shows content in French. 

  How can I use the localisation files to get French translations and fix this error?

IIRC the full set of translations is not bundled into the release (see Release notes) as most users have been using the default 'US English'. 

The solution would be to download the french translation files.
--
Philip

**Comment by charlesmilette** [comment]
It seems that they are in the `.po` format, while `make`'s translations files are in `.mo`. How can I convert them to `.mo` and where do I need to put them?

**Comment by charlesmilette** [comment]
I tried `C:\Program Files\Git\mingw64\share\locale\fr\LC_MESSAGES\git.mo` and `C:\Program Files\Git\share\locale\fr\LC_MESSAGES\git.mo`, but none works.

**Comment by dscho** [comment]
The localization files are properly built and installed when you use Git for Windows' [SDK](http://git-for-windows.github.io/#download-sdk). However, they are excluded from the installer because

1. they would increase the size of the installer substantially, and
2. many users made their wish known to keep Git for Windows unlocalized.

**Comment by PhilipOakley** [comment]
----- Original Message -----

**Comment by charlesmilette** [comment]
I didn't find any. Maybe a separate installer for the translation, as [TortoiseGit](https://tortoisegit.org/), so that the user could install the language if needed.

**Comment by charlesmilette** [comment]
I haven't been able to fully compile git, but enough to get the translations. I copied them into `C:\Program Files\Git\mingw64\share\locale` and they worked. I won't closed this issue for now, to see if we can implement something to get the translation files for the end user.

**Comment by charlesmilette** [comment]
Notice: git is now translated, but I still get `sh: warning: setlocale: LC_ALL: cannot change locale (fr): No such file or directory`

**Comment by dscho** [comment]
> Is there a documented mechanism for regular users to pick up the localisation if they want it?

@PhilipOakley only via the SDK (there is [a switch](https://github.com/git-for-windows/build-extra/blob/0ab6af6c70528bf7e0b323c45945e0ce40c6a94c/make-file-list.sh#L79) you can use to generate installers with localization).

> I haven't been able to fully compile git

Please [file a proper bug report](https://git-for-windows.github.io/#contribute).

> I still get sh: warning: setlocale: LC_ALL: cannot change locale (fr): No such file or directory.
> Putting the bash translation files the same way than with git didn't worked.

You need to copy *all* localization files, not just git's and bash's.

**Comment by zhchch** [comment]
Solution？

**Comment by dscho** [comment]
> Solution？

Build Git for Windows manually, including the localization.
