### ISSUE TITLE
Impossible to add files without recursion from git-cmd.exe

### ISSUE THREAD

**Issue by Maximus5** [git-for-windows/git#730]
I want to add new files by mask from current directory only. But when `git add *.cpp` is called from cmd.exe (terminal is initialized with `git-cmd.exe`) files from subdirectories are always added to the index.

----

 - [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using?

    git version 2.8.0.windows.1 64-bit

 - Which version of Windows are you running?

 Windows 8.1 64-bit

 - What options did you set as part of the installation?

 Unpacked portable

### Details

 - Which terminal/shell are you running Git from?

 git-cmd.exe with cmd.exe as shell

 - What commands did you run to trigger this issue?

```
git add *.cpp
```
 - What did you expect to occur after running these commands?

 Due to examples from <https://git-scm.com/docs/git-add> only files from current directory are expected to be added to the index. That is true, when the shell is bash.exe, because (seems like) the bash expands the mask into the files list.

 - What actually happened instead?

 But cmd passes the mask to git.exe and files from subdirectories are added to the index as well.

**Comment by dscho** [comment]
This is by design. Git relies on the shell to perform wildcard expansion, Git itself has a *different* form of wildcard expansion.

So in Git Bash, if you execute `git add *.cpp` it is the *Bash* that expands the `*.cpp` to all the matching file names.

If you execute `git add \*.cpp` instead, the Bash knows that it should leave the `*` alone (removing the backslash before passing the argument, because it is the "escape character"), and *Git* will expand the wildcard instead, and Git's idea of wildcard expansion is: every file in every subdirectory that matches and is not excluded by `.gitignore` and friends.

Your problem now is that you do not have any program that performs the wildcard expansion you would want, because you replaced the Bash with `cmd.exe` which *never* expands wildcards.

This issue is incurred by your using CMD instead of a shell, and I do not think we can do anything in Git to accommodate your use case.

Having said that, you can *work around* CMD's lack of wildcard expansion by calling

```cmd
echo */*.cpp >.git/tmpexcl
git -c core.excludesFile=.git/tmpexcl add *.cpp
```
