### ISSUE TITLE
Drive letter case-sensitive

### ISSUE THREAD

**Issue by midlan** [git-for-windows/git#735]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

64-bit

```
git version 2.8.0.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

Windows 10 Pro 64-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

yes, defaults, git in %PATH%
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

no
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

windows native cmd.exe
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
1. mkdir "c:\repo"
2. cmd /K "cd c:\repo\"
3. git init
4. echo "content" > file.txt
5. git add C:\repo\file.txt
```

**When your drive letter in step 2 is lower-case (in this example `c:`) and in step 5 is upper-case it will cause fatal.** I think it's a bug, because windows path is case-insensitive.
- What did you expect to occur after running these commands?

Adding a file.txt to future commit.
- What actually happened instead?

```
fatal: C:\repo\file.txt: 'C:\repo\file.txt' is outside repository
```
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

no, it's global problem

**Comment by fourpastmidnight** [comment]
Hmm, can you try something for me, I have a hunch:

```shell
C:\> git add /C:\repo\file.txt
```

**Comment by midlan** [comment]
It returns this:
```
c:\repo>git add /C:\repo\file.txt
fatal: Could not switch to '/C:/': Invalid argument
```

**Comment by fourpastmidnight** [comment]
@midlan: OK, thanks. I'm trying to determine if this has anything to do with MSYS POSIX path conversion or not, or maybe something with `git-add` itself and the path separators being used. Let's try these variations, too, for thoroughness:

```shell
C:\> git add C:/repo/file.txt
REM If this doesn't work, maybe also try:
C:\> git add /C:/repo/file.txt
```

**Comment by midlan** [comment]
`c:\repo>git add C:/repo/file.txt
fatal: C:/repo/file.txt: 'C:/repo/file.txt' is outside repository`

`c:\repo>git add /C:/repo/file.txt
fatal: Could not switch to '/C:/': Invalid argument`

**Comment by dscho** [comment]
> But I don't understand why you're not trying it on your PC.

@midlan Traditionally, the Git for Windows project suffers no shortage of bug reporters, but a shortage of contributors who dive into the code and fix bugs (keep in mind that Git for Windows is downloaded ~1.5 *million* times, yet there are fewer active Git for Windows contributors than you have fingers on your right hand).

That means that people in the latter category invariably have to pick and choose which fraction of the bug reports they work on. One easy way to triage the tickets is to assess how much the bug reporters are willing to work on the problem themselves: it is much more fun to work on those tickets, and they also have a much better chance of being resolved quickly.

Hence I encourage you to consider adding a test to Git's regression test suite, and contributing this as a Pull Request. See [the test suite documentation](https://github.com/git/git/blob/v2.8.3/t/README#L325-L364) and [a good example of a test](https://github.com/git/git/blob/v2.8.3/t/t3006-ls-files-long.sh).

Let's take a look at your MCVE (thanks BTW for making one that works! You'd be surprised how surprising that is to frequent readers of this here bug tracker):

```sh
mkdir "c:\repo"
cmd /K "cd c:\repo\"
git init
echo "content" > file.txt
git add C:\repo\file.txt
```

The first thing to notice is that we cannot go and create top-level directories in `C:\`. But that is not even necessary: *any* repository will have a drive letter. And we can use an absolute path that mismatches Git's idea of the current directory.

And then we do not even need the interactive `cmd` any longer: we can pass the absolute path to Git directly.

Inside a shell script, we can get at the absolute *Windows* path with: `pwd -W`.

So here is a sketch how to get the absolute path to the current directory with a drive letter that has the opposite case of what Git expects it to be:

```sh
dir="$(pwd -W)" &&
case "$dir" in
[A-Za-z]:*)
        # change case of the drive letter only
        drive_letter="$(echo "${dir%%:*}" | tr "A-Za-z" "a-zA-Z")" &&
        dir2="$drive_letter${dir#?}"
        ;;
*)
        [... skip test...]
esac
```

Another thing to note: we will want to guard the test so that it only runs on Windows because it makes little sense to run it on, say, Linux (and Git's source code is kept adamantly cross-platform). So it should look somewhat like this:

```sh
test_expect_failure MINGW 'drive letter is case-insensitive' '
        ...
'
```

(I say "failure" here because it is a known breakage.)
