### ISSUE TITLE
Unexpected behavior with git-bash terminal 2.8.2

### ISSUE THREAD

**Issue by ss005** [git-for-windows/git#747]
I'm facing two issues with git-bash 2.8.2 terminal, which are working correct in 1.9.5.msysgit.1 which is deprecated as of now.

Consider the following script : 
``` shell
#!/bin/bash
#git_2.8.2_test.sh
echo "This is first line..."
cat ./anyFile.txt | less
echo "This line should be after the content of anyFile.txt, but it is not...... why ???"
exit 0
```

I have ./anyFile.txt which has approx 200 lines in it, that's why I used `less` command in above script.
Now when executing the script.....
Problem 1 : 
>When `cat` command is executed with `less `, I can't scroll upwards to see how I run this script.. until the (END) is reached.

Problem 2 : 
>After reaching (END), I pressed q to come out of `less` and continue with script execution flow, but content of "anyFile.txt" is not there on terminal anymore.

Please see these images for more clarification : 
*Image 1*
![problem_1](https://cloud.githubusercontent.com/assets/8335298/15065436/3dbe0d56-137d-11e6-8997-89e4f591d7bd.png)
*Image 2*
![problem_2](https://cloud.githubusercontent.com/assets/8335298/15065437/4092302a-137d-11e6-830c-8422990b7926.png)

Maybe I'm missing something... but these things work fine in 1.9.5.msysgit.1

### Setup
Windows 10
git version 2.8.2.windows.1 64-bit
I've simply extracted the Git for windows 7z file.

**Comment by landstander668** [comment]
Both of these would be MSYS2 items (the runtime environment which Git builds upon), rather than issues with Git itself. That being said, for problem 2 all you should need to do is pass the `-X` option to _less_. Screen clearing behaviour varies by terminal type (and likely the specific version of _less_ as well), so this isn't really all that unexpected.

The updated test script would look like:

```
#!/bin/bash
#git_2.8.2_test.sh
echo "This is first line..."
cat ./anyFile.txt | less -X
echo "This line should be after the content of anyFile.txt"
exit 0
```

I'd also suggest dropping the _cat_ command entirely, replacing it with `less -X anyfile.txt`, as it's unnecessary (and slightly more resource intensive). Unless, of course,  you're using that as a test analogue for some other command, which would more naturally provide data through a pipe.

I can't seem to reproduce problem 1 (using Windows 7 Professional SP1 64-bit and Git 2.8.2 64-bit), so I don't really have any suggestions for that portion.

**Comment by ss005** [comment]
@landstander668 
Indeed these are related to MSYS2 items.
And yes, actually I was using cat with less (`cat -n ..... | less`) in my original script also :disappointed: 
Thanks for suggestion. :heart_eyes: 
I think I should spend more time to learn basic unix commands.
Now I can use `less -NX anyFile.txt`.

Using `less -X` solves my *problem 1* too. Now,  I can scroll up.
So I am closing the issue, since both problem have been resolved using `less -X`, and also you saved me from using unnecessarily extra commands..
Thank you again . :smile:
