### ISSUE TITLE
Update vim to 7.4.691

### ISSUE THREAD

**Issue by KamranMackey** [git-for-windows/git#75]
I think it would be nice if the default Vim installation when installing Git for Windows could be updated to 7.4.691, as patches past 7.4.674 fixes some issues, and also changes some things.

**Comment by dscho** [comment]
It would be nice, I agree. So: why not give it a try? You answered the call to the *developers*' preview, after all. The following steps should get you into a position to start:

```bash
cd /usr/src/MSYS2-packages
git fetch
git checkout master
```

(this is needed only once, subsequent updates should be performed using `git pull`)

Then, start an *MSys2* shell by double-clicking the `msys2_shell.bat` icon in the top-level directory of the Git SDK and run:

```bash
cd vim
vi PKGBUILD
<adjust>
makepkg -s
```

Please note:
- it *needs* to be an *MSys2* shell, the standard *MINGW64* shell will not be good enough because it uses the wrong compiler (the MinGW instead of the MSys2 one)
- you probably need to call `pacman -S base-devel` before you can compile the vim package, this needs to be done only once
- there is a good chance that upstream (https://github.com/Alexpux/MSYS2-packages) already worked on this, you might want to add that as remote (I typically give it the name "upstream") and work from there.
- Seeing as the vim package is just used by us, but is really not all that core a part of Git (:smiley:), it would probably make sense to send a PR directly to upstream. @Alexpux would most likely merge it, build new vim packages and upload them to the MSys2 repositories directly, and not only Git for Windows would benefit, but really every user of MSys2.

**Comment by KamranMackey** [comment]
Odd, I'm doing the "makepkg -s" command, but it keeps throwing up this error: "==> ERROR: Cannot find the strip binary required for object file stripping". Any idea on how I can fix this? I installed the base-devel package like you told me to install, but it's not working.

**Comment by dscho** [comment]
> "==> ERROR: Cannot find the strip binary required for object file stripping"

That's why...

> > you probably need to call `pacman -S base-devel` before you can compile the vim package, this needs to be done only once

**Comment by KamranMackey** [comment]
@dscho I did that command already.

**Comment by KamranMackey** [comment]
@dscho Alright, so I fixed it, but now I'm getting this error when building. "==> ERROR: Integrity checks (md5) differ in size from the source array." How do I fix that?

**Comment by dscho** [comment]
How did you fix it? Which package was missing from `base-devel`?

**Comment by dscho** [comment]
> ERROR: Integrity checks (md5) differ in size from the source array.

That means that you changed one entry in the [`sources`](https://github.com/git-for-windows/MSYS2-packages/blob/f1ae860aa99f3c3c7f32c63508adc2a5aac4d443/vim/PKGBUILD#L16-L24) array, but the [`md5sums`](https://github.com/git-for-windows/MSYS2-packages/blob/f1ae860aa99f3c3c7f32c63508adc2a5aac4d443/vim/PKGBUILD#L25-L32) array is still unchanged.

However, the `md5sums` entries are expected to match the MD5 checksums of the respective `sources` entries...

The simple workaround is to replace the respective `md5sums` entry with `SKIP`, the proper fix is to use `md5sum.exe <file>` to obtain the correct MD5 of the new version and then replace the entry in `md5sums`.

**Comment by KamranMackey** [comment]
Alright, but which file should I be md5sum'ing?

**Comment by KamranMackey** [comment]
Actually, I'm gonna say f it and build vim manually without the PKGBUILD since MSYS has the ability to do so.

**Comment by dscho** [comment]
> Alright, but which file should I be md5sum'ing?

Doesn't it say which one is not matching the provided checksum?

> I'm gonna say f it and build vim manually without the PKGBUILD since MSYS has the ability to do so.

But then we cannot package it easily nor upgrade it.

**Comment by KamranMackey** [comment]
@dscho Alright, so I tried building it again with "makepkg" and it gave me an error when trying to cd into a directory, which I fixed, and now it seemed to have built properly this time. And the answer to your question "Doesn't it say which one is not matching the provided checksum?" is no. No it does not.

**Comment by Alexpux** [comment]
To properly build "vim" from MSYS2-packages you need:
1. Modify PKGBUILD and fix version and commit ID
2. Run "source PKGBUILD && mksource" to fetch sources and create archive
3. Run "updpkgsums"
4. makepkg

**Comment by dscho** [comment]
Thanks, @Alexpux!

**Comment by KamranMackey** [comment]
@Alexpux Alright, thanks!

**Comment by KamranMackey** [comment]
Alright, pushed a PR to @Alexpux's repo which he merged in. :smiley:

On Tue, Apr 7, 2015 at 10:07 AM, dscho <notifications@github.com> wrote:

> Thanks, @Alexpux <https://github.com/Alexpux>!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/git-for-windows/git/issues/75#issuecomment-90623024>.
>



-- 
- Kamran Mackey

**Comment by dscho** [comment]
Awesome!

**Comment by dscho** [comment]
For lurkers: it was this PR https://github.com/Alexpux/MSYS2-packages/pull/212
