### ISSUE TITLE
ssh agent need id_rsa keyword every time when i push my code

### ISSUE THREAD

**Issue by stanhe** [git-for-windows/git#757]
```
$ git --version
 the  latest version for windows
```

i use ssh to connect to my repository ,but every time needs id_rsa key when i push my code.

**Comment by dscho** [comment]
> ```
> $ git --version
> the latest version for windows
> ```

If this is truly the output, you have a corrupt version.

> i use ssh to connect to my repository ,but every time needs id_rsa key when i push my code

By deleting the issue reporting template instead of going through it and diligently filling in the information, you really did yourself a disservice.

If you truly wish to receive help to resolve your problem, you will try to provide a report that exceeds the quality of the help you would hope for. See https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines for advice to go about that.

I will reopen this ticket when substantially more information was provided in a respectful form, than just a sloppy, hasty, incomplete one-liner.
