### ISSUE TITLE
The 2 “open bash” commands act differently

### ISSUE THREAD

**Issue by Brondahl** [git-for-windows/git#758]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

True

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

 64-bit (I believe)

```
$ git --version
git version 1.9.5.msysgit.1
```
Apologies if the answer is "this has been fixed in msysgit 2.x"

 - Which version of Windows are you running? 32-bit or 64-bit?

64-bit Win10

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Don't recall

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not to my knowledge

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

http://stackoverflow.com/questions/37143828/msysgit-why-are-the-2-open-bash-commands-acting-differently

 - What did you expect to occur after running these commands?

That these 2 different ways of opening the bash environment would be the same.

 - What actually happened instead?

See SO post.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Pass

**Comment by dscho** [comment]
> $ git --version git version 1.9.5.msysgit.1

Git for Windows 1.x (and its SDK called "msysGit") are no longer supported.

> > What options did you set as part of the installation? Or did you choose the defaults?
> 
> Don't recall

Okay. I'll just put as much effort into helping you as you did in crafting this report.

**Comment by Brondahl** [comment]
/sigh

As you can see in the discussion of the iss on the SO post, the purpose of raising this ticket is to ask the question "Is this known; Is this expected; Is this a concern?" If the answers are "No; I don't know; Not really" then that's fine, but I don't feel that your response is warranted.

The MCVE is clearly stated in the SO posts.

And regarding info I'm not really sure what you wanted me to do more ... 
I don't recall which options I used ... I installed git 4+ years ago ... do you wish me to go back in time to check? I don't even know which options are prompted for, so it's not like I can check those settings. If you can indicate what information is needed and where I can acquire it from (e.g. as you did with the version prompt).

Regarding 1.x vs 2.x, I agree but I raised the ticket because it seems fairly likely that the same issue is (or was at some point in the past) still applicable to v2.

**Comment by dscho** [comment]
> The MCVE is clearly stated in the SO posts.

Sure. And what did the good SO folks say? Did they solve your problem?

You clearly expect others to do click on that link. You clearly expect others to figure out what in that post is relevant and what is not. And you clearly expect other to *then* do *even more*.

This is not how it works.

If you expect others to put in a lot of effort, you put in an effort first.

If you do a really shoddy job at reporting an issue, it should come as no surprise if you will not be receiving any kind of high quality feedback.

And please do not shoot the messenger. @dscho out.

**Comment by Brondahl** [comment]
Ummm ... yes I did expect you guys to be capable of clicking on a link and reading 2 paragraphs of text. Doesn't seem like a major ask to me. If you'd like me to copy paste the question and the response then I can, but it seems like a massive waste of time ....

My original SO question:

I have 2 ways to open the bash prompt:

    Open it from the Windows Explorer context menu ("Right Click" > "Git Bash")
    Open it from Git Gui ("Repository" Menu > "Git Bash")

The two windows that open when I do this appear identical, but they get grouped separately by windows, and only one of the two gets a Git Icon (context menu version)

What's going on here, and is there any easy way to fix this, or have I identified a bug that I should raise on the msysgit project?


=-=-=-=-=-=-=-=-=-=-=-=
Response:


It looks like the bash window that is opened from the 'Git Gui' is an instance of "sh.exe" and the window that is opened when you open 'Git Bash' is an instance of "bash.exe" these are two separate .exe files in the git bin directory.

As a test, If you rename/remove the sh.exe file, the git gui, on opening will throw an error, but when you chose to open bash from it, it will now open bash.exe.

Furthermore, both files have the exact same size, 584kb.

I would at least raise an issue on the project to see if there is a good reason to do this.

**Comment by Brondahl** [comment]
To avoid any doubt, if my SO link had been a 5 screen long collection of questions, failed answers and discussions.
Then I would have had no issue with you having opened it, seen that it was going to take ages to decipher the thread and requested that I summarise the link.

That's not what happened. You evidently didn't even bother to open the link since if you had you would have seen that it contained nothing other than the "issue" description and some initial investigation thoughts.

**Comment by fourpastmidnight** [comment]
@Brondahl: Please update to the latest version of Git for Windows. This is not an issue in the latest version of Git for Windows. If updating to the latest version of Git for Windows is not possible, then I'm afraid you're stuck with the current behavior, because v1.x of Git for Windows isn't supported anymore and isn't likely to see a fix for purely a cosmetic change.

@dscho: Maybe you could come back over here to close this issue as "won't fix". :wink:

**Comment by Brondahl** [comment]
Ah, fair enough, certainly agree that it's not worth backdating in v1.

Is there any sort of guide for that upgrade (major differences between the two versions? settings files that I should backup and then restore after install? will v2 recognise and cleanup the existing v1 installation appropriately?)

Many Thanks,
Brondahl

**Comment by Brondahl** [comment]
Incidentally, I have a "Close" button here, so if you'd like me to do that then I can.
Saves @dscho spending further time here if he'd prefer not to do so.

**Comment by fourpastmidnight** [comment]
@Brondahl: Sounds good; please close the issue. 

As for changes, I would suggest looking at the Release Notes for v2.x of Git for Windows. It'll be a long read because there have been _many_ changes since v1.95. 

I'm not familiar with the upgrade from 1.x to 2.x, as 1.x (_I believe_) was only 32-bit, and there's now a 64-bit install in 2.x. So I just performed a fresh install (especially since I didn't have many customizations).

If you've customized your shell environment (e.g. created your own `bash.rc` in your home directory, that will remain and should be "inherited" by the updated version of Git for Windows). If you've added custom git scripts, you should copy those elsewhere so you can copy those to your new installation of Git for Windows 2.x appropriately. (Alternatively, I would create a custom directory _outside_ of the Git for Windows installation for your custom Git scripts and modify your `PATH` environment variable to add the location of this new directory. Then, Git BASH will pick up the updated `PATH` and your custom Git scripts should be available to Git. This seems to work well for me.)
