### ISSUE TITLE
sdk net-installer retrieve git-for-windows mirror result error

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#76]
```
:: Synchronizing package databases...
 git-for-windows                                                                                  0.0   B  0.00B/s 00:00 [------------------------------------------------------------------------]   0%
 git-for-windows                                                                               1872.0   B   914K/s 00:00 [########################################################################] 100%

error: could not open file /var/lib/pacman/sync/1cb4ed32f5db94fc7c0f9ffa6b315f92fe2d50e3?response-content-disposition=attachment%3Bfilename%3D%22git-for-windows.db%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZX
NvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMWNiNGVkMzJmNWRiOTRmYzdjMGY5ZmZhNmIzMTVmOTJmZTJkNTBlMz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmdpdC1mb3
Itd2luZG93cy5kYiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTQyODQxOTE5NX0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=Dnkpi2dSSS5ZZYf-bQA143~aYDAPFrU
UrNnuWX7qCam72CCwfL2VT86JzQA8F8GaLtGz5pv-mvsS~8lV0UFjEqBHfSEiW-~vEwP9YcuKCtx5OmdYP9g0H5P4Qc5XXYdZuWP8rY2xCYwe2v3aUrpS0Nk9eRKbYXf0f9rc1YQj6MzqW4ab5T1yUEJbDWXJiNpBEHPElGD-McTtufFSU~3y5czbNJOg3mK8v6wZFTf
Iz2WM-anWrcikR0~IsWmg~aEsznMDKZ9XukCkKoa-d-SHWZZHljuFQPjQFK~dSe09JTV1zssZWPN~DmrYZCCGgnsOcFuUKkw3ls06n4EPceIvgA__&Key-Pair-Id=APKAIQIOJCQ5764M5VTQ.sig.part: File name too long
 mingw32                                                                                          0.0   B  0.00B/s 00:00 [------------------------------------------------------------------------]   0%
 mingw32                                                                                         21.6 KiB  13.2K/s 00:15 [######------------------------------------------------------------------]   9%
 mingw32                                                                                         53.6 KiB  38.2K/s 00:04 [################--------------------------------------------------------]  23%
 mingw32                                                                                        101.6 KiB  66.5K/s 00:01 [##############################------------------------------------------]  43%
 mingw32                                                                                        133.6 KiB  97.1K/s 00:01 

```

It's seems git-mirror doesn't compat with pacman

**Comment by dscho** [comment]
Can you find out how to trigger this warning reliably?

**Comment by lygstate** [comment]
run setup-git-sdk.bat always result this error.

**Comment by lygstate** [comment]
@dscho  refer to https://github.com/Alexpux/MSYS2-packages/issues/210

**Comment by lygstate** [comment]
It's possible because of lack of .sig file.

**Comment by dscho** [comment]
@lygstate it was most likely premature to bump this upstream because you haven't analyzed anything yet.

The first thing is to find out which URL `pacman` tries to access.

At the same time, you will find out what part of `pacman`'s code is responsible for fetching from this URL.

Most likely, you will find that the filename is just set to the *basename* of the URL *after* following a redirect. And after that redirect, the basename has a `?[...]` suffix, and besides, the basename of the *original* URL should be used, not of the redirected URL.

So you see, there is a lot of work to be done yet. And you cannot ask other people to do it for you.

**Comment by lygstate** [comment]
@dscho  I do not familiar with pacman, so I ask other people, this is the best option for me. I've already located the problem comes from pacman, that's already provide enough information.

**Comment by dscho** [comment]
> that's already provide enough information.

That is where we agree. You basically treat other people as if they had to do the work for you. But it is *your* problem, not theirs.

**Comment by lygstate** [comment]
@dscho  Please to be clear, you and other people have nothing to do for ME, and I create this issue is not asking you People do works for me, I just do contribution to make those apps to be better, In fact, I was also the one do the work, please take a little back about the https, you always think you do the right thing without test anything, but I test and verify it, good commit log doesn't means good commit, I hope you understand that.

**Comment by dscho** [comment]
> you and other people have nothing to do for ME

That contradicts your earlier statement: 

> I ask other people, this is the best option for me.

**Comment by lygstate** [comment]
@dscho There is no contradicts, I report this issue doesn't means have to be answered, I am not looking for answer, just report a issue.

**Comment by dscho** [comment]
> There is no contradicts, I report this issue doesn't means have to be answered, I am not looking for answer, just report a issue.

You report an issue without even understanding whether it is a bug in Bintray, in Pacman, or in the script I use to populate our Pacman repository. It would have made sense to report it to MSys2 if you were *sure* that it was a bug in Pacman. But you have no idea whether that is the case. Even *I* have no idea at this point. That is why the bug report was way too premature, and that is why a lot of questions have to be answered, still, and by not answering them before opening that bug report with MSys2, you essentially made it very clear that you expect others to do your homework.

And homework there is still a lot to do:

- using curl (with `-i`, `-L`, `-D` and possibly other options), you need to find out whether the culprit is indeed the missing signature, as the MSys2 maintainer has suggested
- if it is, you need to find out whether Bintray reports this correctly as a 404 (if it does not, the bug lies with Bintray, not with Pacman)
- if it is correctly reported as 404, you need to find the source code in Pacman that is supposed to handle this and investigate whether there is something to fix. If you have no idea yet where to find the source code for Pacman, note that it is an *MSys2* program (i.e. `ldd.exe /usr/bin/pacman.exe` lists `msys-2.0.dll` as a dependency), read up on our page [how to build MSys2 packages](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages), note that you can easily do that by starting the `msys2_shell.bat` in Git SDK's top-level directory, and calling

```sh
cd /usr/src/MSYS2-packages
git fetch
git checkout master
cd pacman
makepkg -s
```

There is just really no alternative to diligent, in-depth analysis.

**Comment by nalla** [comment]
Have a look at [be_sync.c#L231](https://github.com/Alexpux/MSYS2-pacman/blob/e0d06d167fadf4bf70d5eab84e7985dbe91ef162/lib/libalpm/be_sync.c#L231) and [be_sync.c#L258](https://github.com/Alexpux/MSYS2-pacman/blob/e0d06d167fadf4bf70d5eab84e7985dbe91ef162/lib/libalpm/be_sync.c#L258). It seems when using the *internal* downloader, then the returned (and redirected to cloudfront.net from the bintray call) `final_db_url` is appended by the `.sig` extension. This results in that long filename that is then tried to be opened here [dload.c#L443](https://github.com/Alexpux/MSYS2-pacman/blob/e0d06d167fadf4bf70d5eab84e7985dbe91ef162/lib/libalpm/dload.c#L443) and produces that error some people are complaining about.

This analysis goes in line with the fact that when using `XferCommand = /usr/bin/curl -i -d -C - -f %u > %o` does not results in an error.

**Comment by dscho** [comment]
@nalla first of all, thank you so much for the thorough research, and for a clear description of your findings, which is truly refreshing.

> So one possible solution would be to revert this change for Git for Windows?

I think we should not do that because it would reintroduce a problem that would rear its ugly head later when we might be forced to add mirror repositories.

On the other hand, if we were to fix [`get_filename()`](https://github.com/Alexpux/MSYS2-pacman/blob/9d96bed9d6b57c1f3cfb4220e80f6dd473d86683/lib/libalpm/dload.c#L52-L59) so that it would ensure that the file name is extracted *correctly* from the URL (i.e. stripping the `?...` parameters), it would still not work because Bintray redirects 

https://dl.bintray.com/git-for-windows/pacman/i686/git-for-windows.db

to

https://d29vzk4ow07wi7.cloudfront.net/0f343f99927a16d7b7373abdb83b150e174164f2?response-content-disposition=attachment%3Bfilename%3D%22git-for-windows.db%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMGYzNDNmOTk5MjdhMTZkN2I3MzczYWJkYjgzYjE1MGUxNzQxNjRmMj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmdpdC1mb3Itd2luZG93cy5kYiUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTQyODkzNTU1N30sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=G0GJRZJ0fN487fdu8PWoXSB7qk9HSaw6P1WMPMXzbJQNLG-sPC3uwv-jY-yNZ9pvvdzAClEk14IaBEyzjQxx19PqaQVWalL~3rm5jTV3HoaUCxE3v98xvXjqvUkT2hZ15KDgJI4Bfb-7SJe9QZrkqCcgSSAPRZJSeKBSXLLoSGePcIRYW6UUI-d~FS-AJQWKYOqRJN7BHq1i0DOf-T~G2iGOKU~a4lV~CA9HXxGXu~qxuPc8lbKk7xB9QjTTL2V9RatP3koTbxpQ1gWyRaxUoFRjlMYOtIAYfMjY8VUO7hzptByEoxcbGdcJhhJbbL5IGF0YNOyZuXMtDUCi3JaE7A__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA

i.e. Pacman would incorrectly look for https://d29vzk4ow07wi7.cloudfront.net/0f343f99927a16d7b7373abdb83b150e174164f2.sig which is *completely* bogus.

So it appears that the underlying issue is that Pacman assumes by mistake that any HTTP redirection implies that we are connecting to a dynamic mirror. 

I am thinking about something like this:

```diff
diff --git a/lib/libalpm/alpm.h b/lib/libalpm/alpm.h
index 06e080b..701cb77 100644
--- a/lib/libalpm/alpm.h
+++ b/lib/libalpm/alpm.h
@@ -201,6 +201,7 @@ typedef enum _alpm_siglevel_t {
 	ALPM_SIG_DATABASE_OPTIONAL = (1 << 11),
 	ALPM_SIG_DATABASE_MARGINAL_OK = (1 << 12),
 	ALPM_SIG_DATABASE_UNKNOWN_OK = (1 << 13),
+	ALPM_SIG_DATABASE_BOGUS_REDIRECT = (1 << 14),
 
 	ALPM_SIG_USE_DEFAULT = (1 << 31)
 } alpm_siglevel_t;
diff --git a/lib/libalpm/be_sync.c b/lib/libalpm/be_sync.c
index 20130dc..2413b55 100644
--- a/lib/libalpm/be_sync.c
+++ b/lib/libalpm/be_sync.c
@@ -243,7 +243,7 @@ int SYMEXPORT alpm_db_update(int force, alpm_db_t *db)
 
 			/* if we downloaded a DB, we want the .sig from the same server -
 			   this information is only available from the internal downloader */
-			if(handle->fetchcb == NULL) {
+			if(handle->fetchcb == NULL && !(level & ALPM_SIG_DATABASE_BOGUS_REDIRECT)) {
 				/* print final_db_url into a buffer (leave space for .sig) */
 				len = strlen(final_db_url) + 5;
 			} else {
@@ -254,7 +254,7 @@ int SYMEXPORT alpm_db_update(int force, alpm_db_t *db)
 			/* TODO fix leak syncpath and umask unset */
 			MALLOC(payload.fileurl, len, RET_ERR(handle, ALPM_ERR_MEMORY, -1));
 
-			if(handle->fetchcb == NULL) {
+			if(handle->fetchcb == NULL && !(level & ALPM_SIG_DATABASE_BOGUS_REDIRECT)) {
 				snprintf(payload.fileurl, len, "%s.sig", final_db_url);
 			} else {
 				snprintf(payload.fileurl, len, "%s/%s.db.sig", server, db->treename);
diff --git a/src/pacman/conf.c b/src/pacman/conf.c
index ccf8183..e1797ac 100644
--- a/src/pacman/conf.c
+++ b/src/pacman/conf.c
@@ -389,6 +389,13 @@ static int process_siglevel(alpm_list_t *values, alpm_siglevel_t *storage,
 			if(database) {
 				SLSET(ALPM_SIG_DATABASE_MARGINAL_OK | ALPM_SIG_DATABASE_UNKNOWN_OK);
 			}
+		} else if(strcmp(value, "BogusRedirect") == 0) {
+			if(package) {
+				SLSET(ALPM_SIG_DATABASE_BOGUS_REDIRECT);
+			}
+			if(database) {
+				SLSET(ALPM_SIG_DATABASE_BOGUS_REDIRECT);
+			}
 		} else {
 			pm_printf(ALPM_LOG_ERROR,
 					_("config file %s, line %d: invalid value for '%s' : '%s'\n"),
```

and then adding `BogusRedirect` to the `SigLevel = ` line in our `/etc/pacman.conf`, but I have unfortunately no time to test (and most likely improve) this patch.

**Comment by dscho** [comment]
@nalla I forked the pacman repository and put my patch [here](https://github.com/Alexpux/MSYS2-pacman/compare/master...dscho:bogus-redirect), just in case you want to play with it.

**Comment by nalla** [comment]
@dscho I tried compiling `pacman` using your patch and using @elieux patch (I added a branch that will apply the patch [here](https://github.com/git-for-windows/MSYS2-packages/compare/master...nalla:sanity-check)).

But I had no luck creating the package because the `pacman` test-suite seems to fail. So far I have no clue why.

**Comment by dscho** [comment]
@nalla I *think* those test failures are known and upstream builds with a `makepkg` option that skips the tests.

**Comment by dscho** [comment]
Also, @nalla good find on that patch. Much better than mine!

**Comment by nalla** [comment]
I'm happy to report that it *seems* to work.

```bash
nalla@dev MINGW64 ~
$ rm /var/lib/pacman/sync/git-for-windows.db

nalla@dev MINGW64 ~
$ pacman -Syu
:: Synchronizing package databases...
 git-for-windows                               1884.0   B  0.00B/s 00:00 [########################################] 100%
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting full system upgrade...
warning: pacman: local (4.2.0.6125.274527d-1) is newer than msys (4.2.0.6106.9b2114c-1)
 there is nothing to do
```

**Comment by nalla** [comment]
I opened https://github.com/git-for-windows/MSYS2-packages/pull/14 for fixing this issue.

**Comment by dscho** [comment]
@nalla :+1: Thank you very, very much!

**Comment by dscho** [comment]
The pacman packages have been updated to contain @nalla's patch.
