### ISSUE TITLE
Norton is flagging Trojan.Gen.SMH in Git-2.8.3-32-bit.exe

### ISSUE THREAD

**Issue by KDCA** [git-for-windows/git#769]
I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Windows are you running? 32-bit or 64-bit?
A: Win 7 32-bit with recent updates.  Along with Norton Anti Virus with recent updates.

- What options did you set as part of the installation? Or did you choose the defaults?
A: Selected Defaults

### Details

1) Downloaded Git-2.8.3-32-bit.exe, confirmed the SHA256 checksum, and started the installer as Windows Administrator.

2) Norton flagged the following files as containing "Trojan.Gen.SMH"
- git-gui.exe
- git-bash.exe
- gitk.exe

Can anyone confirm this is yet another Norton Anti Virus false positive ?

**Comment by dscho** [comment]
> Downloaded Git-2.8.3-32-bit.exe, confirmed the SHA256 checksum

Might be an idea to actually spell out the checksum here. For the record, the correct SHA-256 checksum is 428a1765cfbadd88b767b779823dfeae134dcbe43170740b088ffad2cdb4be4b

> Norton flagged the following files as containing "Trojan.Gen.SMH"

VirusTotal does not: https://www.virustotal.com/en/file/428a1765cfbadd88b767b779823dfeae134dcbe43170740b088ffad2cdb4be4b/analysis/1463759770/

> I was not able to find an open or closed issue matching what I'm seeing

That is surprising: [this search](https://github.com/git-for-windows/git/issues?q=is%3Aissue+virus+is%3Aclosed) produces a list containing

- #444 
- #384 
- #350 
- #136 
- #113 

Note: *all* of these reports have turned out false in the past. And this is not surprising. The installers are prepared in a dedicated VM that is used exclusively to prepare the Git for Windows installers, nothing else.

I assume you are a customer of Norton's? Then you are in the best solution to tell them about their problem.
