### ISSUE TITLE
HOWTO for building a simple custom installer

### ISSUE THREAD

**Issue by zaps** [git-for-windows/git#771]
I'm trying to wrap my head around building a customized Windows installer for my team but unfortunately getting a bit lost in the docs. 

My requirements are pretty simple, I just want the standard Git for Windows installation experience plus a few additional packages-- ruby, python2/3, etc, and a minimal gcc toolchain for building cpan modules/ruby gems. 

Following the [Technical overview](https://github.com/git-for-windows/git/wiki/Technical-overview) I was able to get the SDK and build an installer but when it came to specifying what additional packages I wanted to add to the custom installer I hit a wall. I presume it involves modifying the `build-extra/make-file-list.sh` in some way but I could not find anywhere in the documentation where this is clearly outlined. 

What would be really helpful would be a one-page HOWTO providing a super-high-level procedure on building a simple custom Git for Windows installation package, something like:

1. Install the SDK
2. Run this command to see what packages are available: `<command>`
3. Edit some stuff
4. Edit this file to add/remove packages in the generated installer: `/path/to/file`
5. Edit some more stuff
6. Generate the installer with `release.sh`

Thanks!

**Comment by fourpastmidnight** [comment]
@zaps: It's pretty simple and well described in the Technical Overview you linked to, which is the one-page "HOWTO" you're looking for. Also check out the [package management](https://github.com/git-for-windows/git/wiki/Package-management#technical-details) link at the bottom of the overview. You do not need to mess with `make-file-list.sh`.

It looks like the InnoSetup installer doesn't support "out of the box", as it's currently written, the packaging of optional components. (The portable "installer", which is really just a 7-zip self-extracting archive file, does support this, as does creating a NuGet package. Also, please don't use the MSI, as it is under active development and not ready for general use--not all options presented in the UI wizard actually work yet!!) With respect to the NuGet package, I'm not sure whether the resulting NuGet package could be used for installing via Chocolatey. I'm just not that familiar with Chocolatey; but if it would work, then that's a possible other route for you to go.

The usage of `release.sh` for the portable installer is:

```shell
release.sh <version> [[optional_package_name]...]
```

To package using NuGet would be similar. Just see the `nuget/release.sh` file in the SDK. (NOTE: the first time I tried creating a NuGet package by running `release.sh`, it didn't seem to work. I got an error. But re-running the same command a second time, it worked (and every time thereafter). I think there's a slight bug in the NuGet `release.sh` script; when you don't have NuGet.exe, it goes out to get it, but then it fails to actually create the NuGet package. But, now that you have NuGet.exe, running `release.sh` again to create the package succeeds. I probably should make an issue for this....)

So, if you wanted to package Ruby and (full) GCC, after following the guidance in the Technical Overview and Package Management pages, you would only need to run:

```shell
sdk_location/usr/src/build-extra/portable $  release.sh 2.8.3 mingw-w64-ruby mingw-w64-gcc
```

You should then have in your home directory (`C:\users\<username>`) a file called `PortableGit-2.8.3-64-bit.7z.exe` (if building on a 64-bit machine).

You can find the list of available packages in both the `MINGW-packages` and `MSYS2-packages` repositories. You should try to use the MinGW packages over the MSYS2 packages when possible.

**Comment by zaps** [comment]
Ah ok the specifying the package names on the command line was the bit I was missing-- thank you! :thumbsup:

That didn't quiiite get me where I wanted-- at the beginning of the package process I got errors indicating `mingw-w64-ruby` and `mingw-w64-gcc` were not found. But, thanks to your helpful pointer to the [Package Management](https://github.com/git-for-windows/git/wiki/Package-management#technical-details) page I was able to get them built, installed, and included in the generated installer. 

I'm curious, for extra packages such as these, is there a way to avoid having to compile them from source if one does not intend on making any local changes? Does there exist a binary repository where all these MSYS2/mingw PKGBUILDs are pre-built? That way pacman could be configured to pull from that location instead of having to compile. I see that this is the case for the core git stuff which is on Bintray.

I have experience with installers on Windows (including WiX/MSI but as you mentioned it's still in the early stages) so I'd be happy to look into getting the optional component thing working for InnoSetup.

**Comment by fourpastmidnight** [comment]
I'm glad that worked out for you. At this point, since you have the SDK installed, the only time you would need to retrieve/compile the extra packages again is if you wanted to upgrade them, and that's only a `git pull` away.

As for modifying the InnoSetup to accept extra packages, I was going to look into it tonight; I'm a newer Git For Windows member, so I'm surprised this isn't supported in that vehicle when it is supported in all the others. I think I should be able to add support for this, so I'll give it a try tonight. I'll reference this issue when I make a pull request.

**Comment by zaps** [comment]
Very good thanks again for the help!

**Comment by fourpastmidnight** [comment]
I made a first crack at adding optional package support to the InnoSetup release process, but since for a long time this was the only release vehicle, it makes lots of assumptions about the release process. This isn't bad, it's just a reflection of the time when this script was first written. But, because of that, this will require careful consideration of any changes made to the InnoSetup release script.

Let's see what feedback I get, if any. I don't want to spend too much time on this, as I'm actively working on the MSI installer which already supports "optional packages"--but the MSI is just not ready for prime-time yet. And as mentioned above, the Portable and NuGet vehicles also currently support this "feature", the obvious disadvantage being they aren't really installers in the Windows sense of the word.
