### ISSUE TITLE
Git Bash in MinTTY ludicrously slow on Windows 10

### ISSUE THREAD

**Issue by Nathan2055** [git-for-windows/git#786]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

2.9.0.windows.1, 64-bit

 - Which version of Windows are you running? 32-bit or 64-bit?

64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults, though I enabled support for Git from default cmd.exe (not the full Unix toolset, though)

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I installed GitHub Desktop a few minutes before installing Git Bash, but uninstalled it because it was acting slow as well.

I also copied in a .gitconfig file as well as .ssh and .gnupg folders from my previous Windows install (Windows 7, I clean installed with 10 recently).

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash, AKA MinTTY

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Launching Git Bash

 - What did you expect to occur after running these commands?

Git Bash to open

 - What actually happened instead?

It sits on a black screen for a very long time, apparently executing "/usr/bin/bash --login -i". When it finally loads, running any Git command takes a very long time.

Git from within stock cmd.exe runs fine and fast.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by dscho** [comment]
Please have a look here: https://github.com/git-for-windows/git/wiki/Diagnosing-performance-issues

**Comment by linquize** [comment]
Anti virus installed?

**Comment by Nathan2055** [comment]
@linquize - Yes, Trend Micro. I'll try adding an exception.

@dscho - Thanks, I'll test that and see if I can figure out what's causing the bottleneck.

**Comment by fourpastmidnight** [comment]
FWIW, I also use TrendMicro MaximumSecurity 2016 and I do not exclude the directory (or sub-directories) containing my local git repositories.

**Comment by emahfoud** [comment]
I'm having exactly the same issue. I also have Trend Micros Internet Security and while it was enabled, even the installer halted at 100%, and wouldn't finish until I disabled Trend. 

Now starting Git Bash, or running any Git command takes several seconds whenever Trend is enabled.

**Comment by dscho** [comment]
@emahfoud any chance you can use the information in https://github.com/git-for-windows/git/wiki/Diagnosing-performance-issues to diagnose further?

**Comment by shytikov** [comment]
I have similar problems. Git v2 is so much slower than git v1. Using Windows 8/10 64 bit. Tried both git2 32 and 64 versions. Always ending up installing git1 and sticking with it. Otherwise very uncomfortable to work in command line interface.

Tried all optimizations. Just cannot get HOW c++ implantation could be slower than based on sh/perl and tcl...

Does anyone else has the same experience? How do you live this it? I'm ready do switch to `fossil` for personal use. It looks now it's faster than `git`...

**Comment by kostix** [comment]
@shytikov, supposedly because it spends time (busy-)waiting on some resource rather than burning CPU cycles.

Say, it might be something like #193 (which I experienced even on Windows XP which usually does not have all these bizzare performance issues like Windows 8+ do).

**Comment by kostix** [comment]
@shytikov, as to Fossil, it's a nice DVCS with interesting ideas.  But if you're used to staging, `git $whatever --patch` and rebasing, you'll quickly find it to be a toy system.

It's also has prettly horrible CLI interface: it's web UI is awesome but if you want to not leave your console window for inspecting the history, your experience will be suboptimal at best.

(The community is nice and responsive but such is that of Git, too.) ;-)

**Comment by shytikov** [comment]
For me `git` is the best, but I need to do something with the speed. With v2 command line interface become uncomfortable even on newly created repositories!

**Comment by dscho** [comment]
@shytikov ranting does not fix the issue. If you are truly interested in fixing it, try to follow [my earlier advice on diagnosing the slowness](https://github.com/git-for-windows/git/issues/786#issuecomment-229653610). Vague descriptions of some kind of perceived slow-down will achieve nothing good.

**Comment by shytikov** [comment]
@dscho, you're right. I'm working on proceeding with your earlier advice. And I will come back to you soon with more details.

So far I can share with you my other findings. It seems that `cmder` ships with portable version of git that on the same PC and with same configuration runs significantly faster! You can check my figures by following my link below: 

https://github.com/cmderdev/cmder/issues/1048

I don't know why difference is so dramatic! Once again, same PC, same `cmd`. Same user configuration file. I don't know what gives major part of the performance gain in this case...

**Comment by shytikov** [comment]
@dscho, unfortunately, nothing interesting in all these performance diagnostic steps. 

I cannot tell where from that delay comes. I've tried to disable network drives, since have found when I move to office my home folder maps to network drive... Didn't helped at all. 

Portable version delivered with `Cmder` started being slow for me. So I think it's something to do with my PC among other things.

But `git1.9.5` works like lightnings... 

For example when I run `gogs` server on my local machine with `git2` webpages with repository information opens with 12 seconds delay. When I switch to `git1` delays about 0.1 second...

Do you have any vision WHY delays on Windows is encountered? Even for such a simple command as get git version, for example?

**Comment by shytikov** [comment]
Here is my simple `test.cmd`

```
@echo off
echo %time% < nul
git --version
echo %time% < nul
```

Here is results from `git2` (with trace enabled):

```
16:07:37.68
16:07:38.279806 git.c:350               trace: built-in: git 'version'
git version 2.9.0.windows.1
16:07:38.28
```

Here is results from `git1` (with trace enabled):

```
16:07:30.33
trace: built-in: git 'version'
git version 1.9.5.msysgit.1
16:07:30.35
```

`Git1` is times faster!

**Comment by kostix** [comment]
@shytikov, you could try to somehow profile (I mean, with a suitable profiler application) your Git to try to figure out what and where is spending time.

As I've already mentioned, in the context of #193, even `cat.exe` bundled with GfW exhibited the offending behaviour, so may be you could start right there.

Now, if that would be a GNU/Linux- or *BSD-based platform, I'd reach for `strace` or the equivalent tool. AFAIK, there exist a 3rd-party tool for Windows which intercepts syscalls made by a process.  So may be you could explore the matters there.

**Comment by kostix** [comment]
@shytikov, looks like [it's doable with the stock MS tools](https://blogs.msdn.microsoft.com/debuggingtoolbox/2007/04/13/windbg-script-tracing-api-calls/).

**Comment by shytikov** [comment]
Will be tracing `git` soon...

I was also thinking about network drive, but after I disconnected it — nothing changed. I also put my laptop into flight mode, results almost the same (trace was disabled):

```
18:27:54.09
git version 2.9.0.windows.1
18:27:54.81

18:27:48.05
git version 1.9.5.msysgit.1
18:27:48.08
```

I was setting `HOME` variable earlier, it had no effect, but I will try once again now.

**Comment by fourpastmidnight** [comment]
I can confirm that MinTTY is _ridiculously_ slow on Windows 10. Unfortunately, I cannot pinpoint exactly when this slowness started occurring.

My computer completely locked up on me yesterday, so I had to give it the "one-finger salute". Since I was forced to reboot (I usually hibernate every night), I decided it was time to install all the updates that were available since the last time I rebooted. This included the Windows 10 Anniversary Update. I also took the time to upgrade from Git for Windows 2.7.1 to the latest Git for Windows 2,9,3.

Now that I've upgraded from Git 2.7.1, I'm noticing this slowness that's being described. I haven't gone through diagnosing performance issues according to the linked-to Wiki articles as of yet. I plan on doing this later today. When I've run through that, I'll report on my findings. I just wanted to be able to confirm that something has changed with respect to Windows 10 and/or MinTTY that has in fact caused MinTTY to become _much_ slower.

**Comment by dscho** [comment]
@fourpastmidnight thanks for the thorough analysis! I look forward to see how it develops from here. For the record, my Git Bash here (Windows 10 + Anniversary Update) is fast.

**Comment by kostix** [comment]
@fourpastmidnight, executing programs on Windows always was known to be slow (slower than on a Linux-based system running on the same hardware) so yes, I'd try to stick with escape sequences to send ANSI colour controls to the terminal driver.

**Comment by shytikov** [comment]
I think it has something to do with the network... It's closest where I could get in my investigation.

Right now ti works fine for me, and I haven't noticed what I've done to make it work. 

But check do you have `.gitconfig` and `.vimrc` on network drive, if yes, can you copy them to local drive and try to restart? Maybe it's also SSH keys?

**Comment by fourpastmidnight** [comment]
**ANOTHER UPDATE**
So, I'm running Git for Windows v2.9.2 x64 on my work computer. AND, I'm also using my custom git prompt on my work computer. **I do not** experience any slowness on this computer as I do on my home computer.

I am running Windows 7 Pro on my work computer, whereas my home computer is Win 10 Pro + AU. It doesn't appear that my prompt is the root issue of the slowness on my home computer afterall. (YAY! But it still is a bit slow for my liking, so one day I'm going to look into that. Thanks @kostix for the tip on using straight up ANSI terminal codes over `tput`.) So it is definitely something environmental--some difference between Windows 7 and Windows 10

@dscho: To be clear, I'm not saying that this issue has anything to do with the Win10 AU in particular, as this issue was filed months in advance of that update being available (however, that's not to say that @Nathan2055 isn't a Fast Ring Windows Insider, in which case, it _could_ be Win10 AU-specific. @Nathan2055, are you a Fast Ring Windows Insider and did you have preview bits of the AU update installed when you filed this issue?) In order to rule out more possibilites, can you tell me @dscho, did you enable the Windows Subsystem for Linux feature of the Win 10 AU? That's one thing I enabled straight after installing this update.

**Comment by fourpastmidnight** [comment]
**LAST UPDATE FOR NOW**
So, I've needed to take some time to learn some stuff at home. As such, I've been using Git for Windows 2.9.3 on my home PC for a few days now as I commit changes to the project that's being used as the sample for what I'm learning. I don't know what's changed with my environment (as I haven't done anything explicit to help improve anything, I figured I'd just live with it for a while), but my prompt is now not as slow as it was when I first reported here. It's almost back to it's "normal" speed. In case you're wondering, I use a local GPO to disable Windows updates because they annoy me too frequently--I only reboot when I need to, and when I do, I install all required updates then. So no new Windows update has been installed that would've changed anything (at least, no update I'm aware of...:wink:).

Anyway, since this hasn't seen much other traffic since I posted my updates here and no response from @Nathan2055, I can't say that this is an "active" issue--for me anyway.

**Comment by fourpastmidnight** [comment]
I've been running Git For Windows 2.9.x on my home machine on Windows 10 Pro x64 w/ AU for a few months now. I experienced slowness initially after the installation--but it mysteriously went away a day later. I haven't heard anything back from anyone on this issue about whether or not they are still experiencing the sluggishness I also initially experienced, or whether or not they've tried going through the Diagnosing Performance Issues wiki page, especially from the OP.

In light of that, I'm closing this issue. If anyone can definitively show that Git for Windows v2.9+ _is actually_ and _significantly_ slower than it's predecessors, please reopen this issue with the evidence.

**Comment by ToMakeSense** [comment]
Found a workaround in here [Solution to Git Bash is very slow in Windows!](https://blog.praveen.science/solution-to-git-bash-is-very-slow-in-windows/), it works!
```bash
git config --global core.preloadindex true  
git config --global core.fscache true  
git config --global gc.auto 256  
```

**Comment by linquize** [comment]
How do preloadindex and fscache relate to mintty?

**Comment by elieux** [comment]
> How do preloadindex and fscache relate to mintty?

In that for most people MinTTY equals Bash equals Git prompt. When every command in the shell is followed by a delay from executing PS1, it's easy to misdiagnose what's actually slow. I assume this is the case.
