### ISSUE TITLE
git-sh-i18n--envsubst.exe Hang

### ISSUE THREAD

**Issue by vbjay** [git-for-windows/git#796]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

64 bit
```
$ git --version
git version 2.9.0.windows.1
```
 - Which version of Windows are you running? 32-bit or 64-bit?

 
![image](https://cloud.githubusercontent.com/assets/3629489/16280863/a2a74246-388f-11e6-98ff-c0c905791307.png)

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults + truetype font

![image](https://cloud.githubusercontent.com/assets/3629489/16281117/d2e4ebec-3890-11e6-9eb5-cefab464a5d1.png)

![image](https://cloud.githubusercontent.com/assets/3629489/16281247/72bbb538-3891-11e6-9319-640d8138af38.png)

![image](https://cloud.githubusercontent.com/assets/3629489/16281274/95f78b26-3891-11e6-8cb8-f112b8f44285.png)

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git submodule foreach --recursive git gc --aggressive

git submodule foreach --recursive git remote -v update
```
I have tried other git submodule foreach commands and get the same result

 - What did you expect to occur after running these commands?

 The entered command to run for all submodules

 - What actually happened instead?

 The git-sh-i18n--envsubst.exe process hasn't ended.  

![image](https://cloud.githubusercontent.com/assets/3629489/16281195/2ced4788-3891-11e6-8356-9603d5adc4a5.png)

![image](https://cloud.githubusercontent.com/assets/3629489/16281338/f5d8efd0-3891-11e6-8e05-4c9fd9db9202.png)

If I kill the process the git command processes and works as expected.  
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

 https://github.com/gitextensions/gitextensions

**Comment by dscho** [comment]
Sorry, I meant to comment on this ticket earlier. I cannot reproduce here:

```sh
me@work MINGW64 /usr/src/git/3rdparty ((5359b48...))
$ git clone https://github.com/gitextensions/gitextensions
Cloning into 'gitextensions'...
remote: Counting objects: 59756, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 59756 (delta 1), reused 0 (delta 0), pack-reused 59745
Receiving objects: 100% (59756/59756), 46.30 MiB | 1.89 MiB/s, done.
Resolving deltas: 100% (46537/46537), done.
Checking connectivity... done.

me@work MINGW64 /usr/src/git/3rdparty ((5359b48...))
$ cd gitextensions/

me@work MINGW64 /usr/src/git/3rdparty/gitextensions (master)
$ git submodule foreach --recursive git remote -v update
```

And surely 46.3 megabyte does not constitute a minimal example.

**Comment by vbjay** [comment]
Try git submodule update --init --recursive first to make sure all
submodules are cloned.  I don't know if it is a gitextensions bug on how it
ran the commands or not.

**Comment by vbjay** [comment]
I ran the command in a script from gitextensions.  
![image](https://cloud.githubusercontent.com/assets/3629489/16714053/126681ba-4686-11e6-9fb4-b02d608c68a4.png)

I got 
![image](https://cloud.githubusercontent.com/assets/3629489/16714054/3540766e-4686-11e6-83ec-1836f05b5437.png)

When I open the shell and run the same command I get 
![image](https://cloud.githubusercontent.com/assets/3629489/16714068/7c5b7396-4686-11e6-9c22-d7126df16b75.png)

**Comment by dscho** [comment]
On Sun, 10 Jul 2016, Jay Asbury wrote:

> Try git submodule update --init --recursive first to make sure all
> submodules are cloned.  I don't know if it is a gitextensions bug on how it
> ran the commands or not.

I am terribly sorry, but I won't be able to spend that amount of time on
this issue.

If you would like me to have a look at this problem again, you need to
create a minimal example that I can easily clone to verify that I can
reproduce the problem here.

This is not me trying to be mean or nasty or something. I really try to
help, even on a lovely Sunday afternoon that I should probably spend with
my family instead.

I just know that reproducing the issue is but the first, tiny step of
resolving the problem. Most of the time will be spent hunting the bug,
then resolving it, and getting a fix integrated upstream, in this case
probably something between 3-15 hours,given the complexity and
heterogenity of the involved code (Git's submodule handling is implemented
in an odd mixture of C and shell code, with some processes spawned in a
manner that does not lend itself to be run in a debugger).

And while you cannot help me with the debugging (otherwise you would
already have done that and opened a Pull Request ready to merge), you
*can* help quite a bit with allowing me to reproduce the problem here.

**Comment by dscho** [comment]
I am sorry, I cannot do anything for you, it seems.
