### ISSUE TITLE
git-for-windows console help / msys2 / perl

### ISSUE THREAD

**Issue by damnedkluev** [git-for-windows/git#805]
Could you provide the man.exe from msys2 into git-for-windows for open help in console?
Because using browser for help has additional latency, opens unneeded browser window and cli help make available this simple usage as "git help pull | grep recur -A .. -B .." for little consult about partly known options.
Or (just better) provide the way or instruction how to combine git-for-windows and full msys2 installations without duplicates and collisions.
And (more better) - provide the way or instruction how to setup git-for-windows using system perl such as strawberry perl or Active Perl. I tried to do any of this but did not succeeded but you may be know (must be know :)) yours project much better to do it.

**Comment by PhilipOakley** [comment]
----- Original Message ----- 
  From: damnedkluev 
  To: git-for-windows/git 
  Sent: Monday, June 27, 2016 2:54 PM
  Subject: [git-for-windows/git] git-for-windows console help / msys2 / perl (#805)


  Could you provide the man.exe from msys2 into git-for-windows for open help in console?
  Because using browser for help has additional latency, opens unneeded browser window and cli help make available this simple usage as "git help pull | grep recur -A .. -B .." for little consult about partly known options.
  Or (just better) provide the way or instruction how to combine git-for-windows and full msys2 installations without duplicates and collisions.
  And (more better) - provide the way or instruction how to setup git-for-windows using system perl such as strawberry perl or Active Perl. I tried to do any of this but did not succeeded but you may be know (must be know :)) yours project much better to do it.

Just go to the G4W page https://git-for-windows.github.io/, scroll to the bottom, and there you will find the SDK with links to the wiki on creating your own release.

Check what the new release size would be to see if it is worth a pull request, (with careful and well explained commit message) and then be ready to resolve the niggles, such as the other help source options, compatability with pagers and terminals...

If you find there are missing wiki pages (e.g. about steps to include new packages), then please do fill in the blanks, to make it easier for everyone to help each other.
-

Philip

**Comment by dscho** [comment]
The purpose of [Git for Windows](https://git-for-windows.github.io/) is really to bring *Git* to Windows.

While that implies that we have to ship quite a few Unix-like tools, it does not mean that we will include such tools unless they are needed for Git's own operations, or at least for historical reasons (needs of active contributors are sometimes a factor in deciding whether to include a tool or not).

Having said that, what you really are looking for is [MSYS2](https://msys2.github.io/). Git for Windows leverages MSYS2 and ships with a subset of its files. MSYS2 even sports a package management system called "pacman" to install more tools (including Git...), so why don't you give it a whirl?

> And (more better) - provide the way or instruction how to setup git-for-windows using system perl such as strawberry perl or Active Perl.

If you get `git svn` to work with Strawberry Perl or Active Perl, please do let us know!
