### ISSUE TITLE
Could not execute git commands written in shell script if outside bash

### ISSUE THREAD

**Issue by linquize** [git-for-windows/git#81]
If I run `C:\Program Files\Git\mingw64\bin\git.exe` instead of `C:\Program Files\Git\cmd\git.exe` outside bash, git commands written in shell script will fail.
e.g. `git submodule`, `git rebase`
```
fatal: 'submodule' appears to be a git command, but we were not able to execute it. Maybe git-submodule is broken?
```

**Comment by dscho** [comment]
Running `git.exe` directly is simply not supported. That's why we have the Git wrapper in `cmd/`...

Why don't you stay on the recommended path? ;-)

**Comment by YueLinHo** [comment]
@dscho e.g. TortoiseGit call git.exe
ref: [Comment #9 of TortoiseGit issue 2426](https://code.google.com/p/tortoisegit/issues/detail?id=2426#c9)

**Comment by dscho** [comment]
Again, why don't you (or TortoiseGit) stay on the recommended path?

**Comment by lygstate** [comment]
@YueLinHo I was point the target path to `C:\Program Files\Git\cmd\git.exe` in TortoiseGit, and it's works fine, I think you could have a try.

**Comment by dscho** [comment]
@YueLinHo just for the record, this ticket requires your response before it can go *any* further.

**Comment by YueLinHo** [comment]
> Why don't you stay on the recommended path? ;-)

In the past(```GfW 1.*```), the ```\cmd\git.exe``` does not work, so that TortoiseGit usually takes/locates ```\bin\git.exe``` automatically for user.

Now, rule changed: ```\cmd\git.exe``` is the recommended path, instead of ```\bin\git.exe```. Right?
If so, suppose a *compatible* way for ```Gfw 1.*``` and ```2.*``` is needed.

BTW, could you please tell me why ```C:\Program Files\Git\mingw64\bin\git.exe``` exist?
come fomr msys2?
or could you direct me to some reference?
Thank you. :)

**Comment by dscho** [comment]
> In the past(GfW 1.*), the \cmd\git.exe does not work, so that TortoiseGit usually takes/locates \bin\git.exe automatically for user.

This should have been reported, and preferably fixed, then.

> Now, rule changed: \cmd\git.exe is the recommended path

No, the rule did not change. This was always the recommended path to use, even when it was still a batch file.

It is definitely *possible* to fix the `\bin\git.exe` so that you should be able to call it directly. That would require more work from your side, though, than simply editing the path.

> BTW, could you please tell me why C:\Program Files\Git\mingw64\bin\git.exe exist?

This is the Git executable itself. The executable in `\cmd\` (which we call the "Git wrapper") just sets up some environment variables and then hands off to the Git executable.

**Comment by YueLinHo** [comment]
@dscho 
Thank you for lots of information. ^_^

**Comment by dscho** [comment]
@linquize @YueLinHo do you plan to work on this, or can we close the ticket?

**Comment by YueLinHo** [comment]
@dscho 
I am done here. :)
Thanks for your help.
