### ISSUE TITLE
The commit message box is not maximized when the main window is maximized.

### ISSUE THREAD

**Issue by CNMan** [git-for-windows/git#814]
![2016-07-10_141201](https://cloud.githubusercontent.com/assets/8692234/16711989/41a8df94-46aa-11e6-8425-4576f9443ab7.png)
it seems the commit message box is a fixed size now.

**Comment by dscho** [comment]
Is this Windows-specific? Version?

**Comment by CNMan** [comment]
yes.
git-gui version 0.20.GITGUI
git version 2.9.0.windows.1

Tcl/Tk version 8.6.5

**Comment by PhilipOakley** [comment]
> yes.
> git-gui version 0.20.GITGUI
> git version 2.9.0.windows.1
> Tcl/Tk version 8.6.5

I've always found the commit message box (as displayed on screen) to be 
fixed max size, so if the overall gui window is streched wide, the commit 
message box stofs expanding when the display area reaches ~80 char width.

However it does then gain a horizontal scroll bar (IIRC) is you type a too 
long sentence, or paste a long link into the message.

It does help ensure that we users follow the general guidance about 
formatting our commit messages, old school style. Given that many users 
still use a tty style interface with fixed widths (each to their own as they 
say), it can help.

It also forces you to read, and re-read the message just to make it fit 
neatly in the box. This has some nice side effects 
http://academia.stackexchange.com/a/72366/30739


Philip

**Comment by dscho** [comment]
> yes.

@CNMan if that was supposed to be an answer to my question whether this issue is Windows-specific, then I am afraid that the home work was not done properly.

I set up a Linux VM and tested this, and here is the screenshot:
![git-gui-commit-panel](https://cloud.githubusercontent.com/assets/127790/16713206/1cd62fd2-46a0-11e6-8107-6977b712f647.png)

Therefore it is now clear that this is not a Windows-specific issue. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).
