### ISSUE TITLE
MINGW64 does not display unicode

### ISSUE THREAD

**Issue by drozzy** [git-for-windows/git#837]
Here is what I see in MINGW64 when I run anything that uses unicode (erlang's dialyzer in this case).
![unicode](https://cloud.githubusercontent.com/assets/140710/17272934/063d274e-5672-11e6-901e-79a56d5198db.png)

I am using Windows 10, with 2.9.2 install of git for windows: https://git-scm.com/
Any tips?

**Comment by fourpastmidnight** [comment]
CMD is known to have problems displaying Unicode. Here are a couple of things you can try to see if it resolves your issue:

1. Make sure your command prompt code page is set to 65001 by issuing the command:
    ```batch
    C:\> chcp 65001
    ```

2. Change the command prompt font to a font which contains Unicode characters, such as **Lucida Console** or **Consolas**. (**NOTE:** I know that Consolas does not have a wide range of the Unicode character code points defined. IIRC, Lucida Console doesn't either.)

This may be enough to solve your problem, but if not, it's an issue with Command Prompt and not Git for Windows. For more information, see [this StackOverflow.com Q&A](http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how) regarding this issue.

If you are unhappy with the result, or it just doesn't work, I recommend that you reinstall Git for Windows and use the MinTTY console instead, which fully supports UTF-8.

**Comment by fourpastmidnight** [comment]
Apparently you ignored the issue template. Have you searched the issues list to see if someone else has had a similar issue with UTF-8 when using Git for Windows? Can you please answer the questions in the issue template to give us a better idea of how you installed Git for Windows?

You may find that once you search the issues list, there are others who have reported a similar problem and resolved it. Otherwise, answering the questions will give us a better idea of how we might be able to help you.

**Comment by drozzy** [comment]
Sorry for ignoring the template, I'll re-file this with full info when I get the chance.

**Comment by dscho** [comment]
@drozzy please do not use the bug tracker to ask usage questions. And to fend off a misunderstanding already: You are seeing ANSI escape sequences, which has nothing to do with Unicode.
