### ISSUE TITLE
Please consider upgrading mintty to v2.4.2 (available via msys2)

### ISSUE THREAD

**Issue by tomreyn** [git-for-windows/git#842]
msys2 now uses mintty 2.4.2 as per 
https://github.com/Alexpux/MSYS2-packages/blob/master/mintty/PKGBUILD

Git for Windows 2.9.2 comes with mintty which was released more than a year ago:
https://github.com/mintty/mintty/releases/tag/2.0.3
(mintty has apparently since moved from now defunct - despite archives - Google Code to GitHub)

Could you consider upgrading to the latest msys2 / mintty?

An earlier upgrade request for (a then current version of) embedded mysys2 can be found in #232 .

Thanks for your much appreciated work.

**Comment by PhilipOakley** [comment]
msys2 now uses mintty 2.4.2 as per 
  https://github.com/Alexpux/MSYS2-packages/blob/master/mintty/PKGBUILD

  Git for Windows 2.9.2 comes with mintty which was released more than a year ago:
  https://github.com/mintty/mintty/releases/tag/2.0.3
  (mintty has apparently since moved from now defunct - despite archives - Google Code to GitHub)

  Could you consider upgrading to the latest msys2 / mintty?

The easiest way is via the 'how to contribute' link at the bottom of the main G4W page, links to https://github.com/git-for-windows/git/wiki/Technical-overview

It's fairly easy to to prepare the data and do the pull request (even if you feel not quite ready for a big time contribution - this is 'just' the swapping out of the old and import of the new)

Philip

**Comment by kgybels** [comment]
@dscho I think the mintty package needs to be removed from the git-for-windows pacman repository. It is taking precedence over the msys one because it is listed first in pacman.conf.

From /etc/pacman.conf:

    [git-for-windows]
    Server = https://dl.bintray.com/$repo/pacman/$arch
    SigLevel = Optional
    
    [mingw32]
    Include = /etc/pacman.d/mirrorlist.mingw32
    
    [mingw64]
    Include = /etc/pacman.d/mirrorlist.mingw64
    
    [msys]
    Include = /etc/pacman.d/mirrorlist.msys

Using the Git for Windows SDK:

    KGybels@PC-KIM MINGW64 /
    $ pacman -S -i mintty
    Repository      : git-for-windows
    Name            : mintty
    Version         : 1~2.0.3-2
    Description     : Terminal emulator with native Windows look and feel
    Architecture    : x86_64
    URL             : https://mintty.github.io
    Licenses        : GPL3
    Groups          : base
    Provides        : None
    Depends On      : sh
    Optional Deps   : None
    Conflicts With  : None
    Replaces        : None
    Download Size   : 115.15 KiB
    Installed Size  : 240.00 KiB
    Packager        : Unknown Packager
    Build Date      : Mon, Aug 17, 2015 11:34:27 AM
    Validated By    : MD5 Sum  SHA-256 Sum
    
    Repository      : msys
    Name            : mintty
    Version         : 1~2.4.0-1
    Description     : Terminal emulator with native Windows look and feel
    Architecture    : x86_64
    URL             : https://mintty.github.io
    Licenses        : GPL3
    Groups          : base
    Provides        : None
    Depends On      : sh
    Optional Deps   : None
    Conflicts With  : None
    Replaces        : None
    Download Size   : 150.21 KiB
    Installed Size  : 302.00 KiB
    Packager        : Alexey Pavlov <alexpux@gmail.com>
    Build Date      : Tue, Jul 19, 2016 7:05:59 AM
    Validated By    : MD5 Sum  SHA-256 Sum  Signature

If I swap the order of the repositories in pacman.conf, I can successfully install the newer version:

    KGybels@PC-KIM MINGW64 /
    $ pacman -S mintty
    resolving dependencies...
    looking for conflicting packages...
    
    Packages (1) mintty-1~2.4.0-1
    
    Total Download Size:   0.15 MiB
    Total Installed Size:  0.29 MiB
    Net Upgrade Size:      0.06 MiB
    
    :: Proceed with installation? [Y/n] Y
    :: Retrieving packages...
     mintty-1~2.4.0-1-x86_64                           150.2 KiB   839K/s 00:00 [#########################################] 100%
    (1/1) checking keys in keyring                                              [#########################################] 100%
    (1/1) checking package integrity                                            [#########################################] 100%
    (1/1) loading package files                                                 [#########################################] 100%
    (1/1) checking for file conflicts                                           [#########################################] 100%
    (1/1) checking available disk space                                         [#########################################] 100%
    :: Processing package changes...
    (1/1) upgrading mintty                                                      [#########################################] 100%

**Comment by dscho** [comment]
@kgybels I appreciate that you want to help, I really do.

Please understand, though, that there is a good reason for `mintty` in Git for Windows' Pacman repository overriding the one from the MSYS2 repository: *Git Bash* was enhanced to make it pinnable to the taskbar last year. This support relies on the command-line options that were implemented in a Pull Request that was ultimately rejected by MinTTY and implemented differently. I do not have the time right now to figure out what patches are needed to make the "Pin to taskbar" function work with the new MinTTY (if it works out of the box, that is, which I doubt, quite frankly).

If you have time to do that, I would very much appreciate your opening a Pull Request with the necessary changes, where I would like to ask you to describe what sort of testing you performed (I had to kill the Explorer and restart it from the Task Manager a couple of times after removing `%USERPROFILE%\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\ImplicitAppShortcuts\<hex-string>\Git Bash.lnk` when I tested it, because things would miraculously continue working with a broken setup otherwise).

**Comment by kgybels** [comment]
@dscho These different versions of mintty are causing problems in the Git for Windows SDK, when I try to run `msys2.exe`, I get `/usr/bin/mintty: unknown option '--store-taskbar-properties'`, because msys2 launcher relies on the official mintty options. I created Alexpux/MSYS2-packages#673 to set the correct mintty dependency.

    KGybels@PC-KIM MSYS /usr/src/MSYS2-packages/msys2-launcher-git (mintty-epoch)
    $ pacman -U msys2-launcher-git-0.3.32.56c2ba7-2-x86_64.pkg.tar.xz
    loading packages...
    resolving dependencies...
    looking for conflicting packages...
    
    Packages (2) mintty-1~2.4.2-1  msys2-launcher-git-0.3.32.56c2ba7-2
    
    Total Installed Size:  0.45 MiB
    
    :: Proceed with installation? [Y/n] Y
    (2/2) checking keys in keyring                                                                         [###########################################################] 100%
    (1/2) checking package integrity                                                                       [###########################################################] 100%
    (1/2) loading package files                                                                            [###########################################################] 100%
    (2/2) checking for file conflicts                                                                      [###########################################################] 100%
    (2/2) checking available disk space                                                                    [###########################################################] 100%
    :: Processing package changes...
    (1/2) installing mintty                                                                                [###########################################################] 100%
    (2/2) installing msys2-launcher-git                                                                    [###########################################################] 100%

You can see that it installs `mintty-1~2.4.2-1` from msys repository. However, that breaks `git-bash.exe`, because it relies on `mintty-1~2.0.3-2` from git-for-windows repository.
