### ISSUE TITLE
"git add -p" results in "Can't locate Git.pm in @INC" when Perl is in PATH

### ISSUE THREAD

**Issue by cchan** [git-for-windows/git#845]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

64-bit

```
$ git --version
git version 2.9.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

64-bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

```
$ perl --version
This is perl, v5.8.8 built for msys-64int
... irrelevant license info ...
```

This particular Perl was installed as part of Ruby DevKit, and for better or worse I need it in the PATH.

### Details

In Git Bash:

```
$ cd any/git/repository
$ git add -p
Can't locate Git.pm in @INC (@INC contains: /mingw64/share/perl5/site_perl /usr/lib/perl5/5.8/msys /usr/lib/perl5/5.8 /usr/lib/perl5/site_perl/5.8/msys /usr/lib/perl5/site_perl/5.8 /usr/lib/perl5/vendor_perl/5.8/msys /usr/lib/perl5/vendor_perl/5.8 .) at C:\Users\Clive\AppData\Local\Programs\Git\mingw64/libexec/git-core\git-add--interactive line 7.
BEGIN failed--compilation aborted at C:\Users\Clive\AppData\Local\Programs\Git\mingw64/libexec/git-core\git-add--interactive line 7.
```

When Perl is removed from the PATH by renaming the executable `perl.exe` to something else, no such error is produced and it works as expected.

[One interesting and probably unrelated thing to note is that the path-separator slashes are going in both directions in the error message]

**Comment by dscho** [comment]
It seems not only to be in the `PATH`, but also *before* `/usr/bin/`!

You might be able to work around that by prefixing `PATH` with `/cmd/:`.

**Comment by dscho** [comment]
I *guess* that my suggestions helped, as there has been radio silence ever since.

**Comment by niklasholm** [comment]
I have a very similar issue when running git in a MSYS2 proper environment (setup per the instructions [here](https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper)) and the mingw64 port of perl installed (`/mingw64/bin/perl`).

```shell
$ git --version
git version 2.15.1.windows.2

$ perl --version
This is perl 5, version 22, subversion 0 (v5.22.0) built for MSWin32-x64-multi-thread
...

$ git add -p
Can't locate Git.pm in @INC (you may need to install the Git module) (@INC contains: /mingw64/share/perl5/site_perl C:/msys64/mingw64/lib/perl5/site_perl/MSWin32-x64-multi-thread C:/msys64/mingw64/lib/perl5/site_perl C:/msys64/mingw64/lib/perl5/vendor_perl C:/msys64/mingw64/lib/perl5/core_perl .) at C:\msys64\mingw64/libexec/git-core\git-add--interactive line 7.
BEGIN failed--compilation aborted at C:\msys64\mingw64/libexec/git-core\git-add--interactive line 7.
```

Evidently, there is some compatibility issues with perl versions other than the msys2-linked one located in `/usr/bin/perl`. `/mingw64` is located before `/usr/bin` on the `PATH`.

A viable workaround is to put `alias git='PATH="/usr/local/bin:/usr/bin/:/bin:$PATH" git'` in `~/.bashrc` to have git find the "right" perl version.

However, a proper solution would have git work regardless of different perl versions on the path. Therefore, I believe that this issue should be reopened.

**Comment by dscho** [comment]
> However, a proper solution would have git work regardless of different perl versions on the path. Therefore, I believe that this issue should be reopened.

How would that work?

Remember, my primary concern is the end-user facing Git for Windows installer.

You are using a very different setup: obviously, you use an MSYS2 setup that is enhanced by using Git for Windows' packages.

More than that, you are using a MINGW version of Perl, and nothing guarantees that that works with Git for Windows' Perl scripts. That would put quite a bit of a burden onto the shoulders of an already over-burdened OSS maintainer, which is quite the bit unfair.

I am sympathetic to your situation, though. So if you are willing to get your peculiar setup to work, I am here to assist you. That is a far cry from supporting your setup, and it is several universes away from solving your problem for you, of course.

**Comment by niklasholm** [comment]
Well to me it seems that if a script depends on a specific version of an interpreter to work correctly it should reference the path of that version directly rather than looking it up on the more general PATH variable. `git-add--interactive` actually has a shebang that references the correct version, but for some reason, it isn't used, probably because of the way the program is called.

I understand you cannot support every possible environment, but in this case, it seems the problem is triggered by the modified PATH, not the fact that I'm using MSYS2 proper. Adding stuff to the PATH isn't exactly unusual, even on a Windows system, and something that I think the user should be able to do (reasonably) without breaking functionality.

**Comment by dscho** [comment]
Git for Windows *prepends* its directories to the `PATH`. That's why it works in the intended use case.

You could of course try your hand at "fixing" the way Git's Perl scripts are called. Keep in mind, though, that the shebang line refers to a Unix-like path. `git.exe` is a Windows executable, though, not an MSYS2 one, therefore cannot handle pseudo-Unix paths.

It looks more and more as if you don't actually want to spend time on fixing your use case, and might be better served with using MSYS2's own `git` (I.e. *not* `mingw-w64-git`) package.
