### ISSUE TITLE
"git bash here"  not working 

### ISSUE THREAD

**Issue by prathyushr** [git-for-windows/git#851]
"git bash here"  not working .It lands on home folder

**Comment by dscho** [comment]
I *guess* that you meant the Explorer integration? It is sad that I have to guess, you could have done a better job of reporting the issue.

In any case, I cannot reproduce the issue. If I right-click on the *Desktop* in Explorer and then click *Git Bash Here*, it opens exactly where it is supposed to open: in `~/Desktop`.

Feel free to provide much, much more context so that other people have a chance to help you. Until then, I will close the ticket.
