### ISSUE TITLE
Ubuntu on Windows Compatability?

### ISSUE THREAD

**Issue by md-5** [git-for-windows/git#855]
Have not actually seen this bug myself, but making thread per request anyway.
Ref: https://twitter.com/JSchindelin/status/765801767418331136

**Comment by dscho** [comment]
@md-5 we have a beautiful issue reporting template. There are quite a bit of useful questions in there to help you come up with a good report.

Simply linking to Twitter is unfortunately not a good bug report.

So here a summary of the scarce information that *is* available: apparently, some `BuildTools.jar` of some "Spigot MC" assumes quite a bit about Git for Windows (which might have held true for 1.x but not for 2.x). In particular, it was reported that:

```sh
$ java -jar BuildTools.jar
Loading BuildTools version: git-BuildTools-afc7566-52 (#52)
-- Beta feature --

This will install Ubuntu on Windows, distributed by Canonical

and licensed under its terms available here:

https://aka.ms/uowterms



In order to use this feature you must have Developer Mode enabled.


You must run this jar through bash (msysgit)
```

Typing out the screenshot here unfortunately depleted the time I was willing to spend on this today.

**Comment by dscho** [comment]
So: more information. It appears that for some reason those tools launch `bash.exe` where Git for Windows' `bash.exe` is *not* in the `PATH`, and Windows 10 (with Anniversary Update) has a `bash.exe` in `C:\Windows\System32`.

How can that be, since *Git Bash* automatically puts `bash.exe` into the `PATH`, and quite early?

The most likely explanation is that the tools *edit* the `PATH`, and make assumptions about Git for Windows that held true in the 1.x days (where all the executables were in `C:\Program Files (x86)\Git\bin`, whether they require the MSYS POSIX emulation layer or not), but no longer in 2.x days.

Any developer/user with this problem is welcome to instrument the code of those build tools to figure out where the `PATH` is invalidated. That should be relatively easy, given somebody with enough interest in the issue.

**Comment by fourpastmidnight** [comment]
Since this is a tooling problem with some software the OP is using, should this really be an open bug here? The way I have read this issue, this is not a problem with Git for Windows in and of itself. Rather, the tool being used by the OP made some assumptions about the current user's operating environment. I don't see that there's anything we can do to "fix" anything. The OP, on the other hand, has several options they could use to work around their issue that has nothing to do with Git for Windows.

**Comment by dscho** [comment]
I agree. I also think that no response whatsoever, let alone some digging on their own, makes this a ticket so low priority that it is better closed (we do not have the resources to take care of such tickets).
