### ISSUE TITLE
Portable installer doesn't seem to honor environment variables

### ISSUE THREAD

**Issue by nulltoken** [git-for-windows/git#87]
- Using `%LOCALAPPDATA%\git-for-windows` doesn't extract anything in the provided location
- Using `C:\Users\Em\AppData\Local\git-for-windows` however works (on my machine :wink:)

**Comment by dscho** [comment]
Do you say you type `%LOCALDATA%\git-for-windows` in portable installer's dialog asking for the installation location? If so, that is unfortunately nothing we can tackle anytime soon because that dialog is part of the 7z sfx module we are using (for which we have no source; @sschuberth is looking at replacing it with a module that is actually Open Source and *might* handle environment variables in the file dialog, but 1) it might not, and 2) don't hold your breath for it :-)

**Comment by nulltoken** [comment]
>Do you say you type %LOCALDATA%\git-for-windows in portable installer's dialog asking for the installation location?

I was indeed unclear. You perfectly reworded my statement. Thanks!

> that is unfortunately nothing we can tackle anytime soon because that dialog is part of the 7z sfx module

Makes sense. Thanks for the feedback and the amazing work!

@shiftkey I think you can safely drop the %LOCALAPPDATA% note from the gist.

**Comment by shiftkey** [comment]
> @shiftkey I think you can safely drop the %LOCALAPPDATA% note from the gist.

:thumbsup: i updated it earlier but I'll remove the whole section

**Comment by dscho** [comment]
okay, this is resolved... Thanks!

**Comment by sschuberth** [comment]
> @sschuberth is looking at replacing it with a module that is actually Open Source and might handle environment variables in the file dialog

For the record, I was looking at using the [official SFX modules](http://7-zip.org/download.html) instead of the dated ones from [here](http://7zsfx.info/en/download.html) that we currently use, but the official modules are still way too limited. For example, there is still no way to prompt the user for a path to extract to. So I believe we should stick to the current SFX modules.
