### ISSUE TITLE
update-ca-trust fails due to p11-kit and spaces in directory path

### ISSUE THREAD

**Issue by jblaine** [git-for-windows/git#878]
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup

git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64

Microsoft Windows [Version 10.0.10586]

Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
### Details

Git being run from "Git Bash"

It appears the `update-ca-trust` script is calling p11-kit and p11-kit is not properly quoting the full path to the `trust` command (and perhaps others...):

```
~:MY-PC> update-ca-trust
p11-kit: 'Files/Git/mingw64/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Files/Git/mingw64/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Files/Git/mingw64/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Files/Git/mingw64/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
p11-kit: 'Files/Git/mingw64/bin/trust' is not a valid command. See 'Program --help'
p11-kit: couldn't run trust tool: No error
~:MY-PC>
```

**Comment by dscho** [comment]
According to `pacman -Qo $(which update-ca-trust)` in a Git for Windows SDK, the file is owned by the `mingw-w64-x86_64-ca-certificates` package, which is in turn owned by the MSYS2 project (i.e. not Git for Windows).

How about [installing the SDK](https://git-for-windows.github.io/#download-sdk) and following the advice in https://github.com/git-for-windows/git/wiki/Package-management to rebuild the package, and then patch the sources to fix the problem?

**Comment by jan-hudec** [comment]
I found a workaround. If you execute git-bash using a dos path, i.e.

    C:\PROGRA~1\Git\git-cmd.exe --no-cd --command=usr/bin/bash.exe -l -i

MSys will keep using that form when converting paths back to native form and there will be no space to split on.

On a side-note, keep in mind that (the shell from which you run) `update-ca-trust` has to be run As Administrator if installed under Program Files.

**Comment by jan-hudec** [comment]
There is more problems with the `update-ca-trust` though:

1. There is both `/etc/pki/ca-trust` and `/mignw64/etc/pki/ca-trust`, the `source` subdirectory only exists in the former. There are two copies of `update-ca-trust`, one in `/usr/bin` that updates the former and one in `/mingw64/bin` that updates the later. The new certificate has to be added to corresponding `source` directory for each.
2. `git-remote-https` looks somewhere else altogether anyway, because when I get both scripts to run (using the workaround above) and verify both `ca-bundle.trust.crt` contain the new certificate, `git fetch` still does not accept it. However, both `GIT_SSL_CAINFO=/mingw64/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt git fetch` and `GIT_SSL_CAINFO=/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt git fetch` **do** accept it.
3. And that somewhere does not seem to be system either, because I did add the certificate to the “Trusted Root Certification Authorities” store and browsers accept it because of that.

So

1. Is both packages (`msys/ca-certificates` and `mingw64/mingw-w64-x86_64-ca-certificates`) needed? In my separate MSys2 installation I only have the first.
2. Where does git look for the certificates by default then? I couldn't find it documented anywhere, don't see any configuration file that might specify it and couldn't get `strace` to tell me what files it opens.

**Comment by jan-hudec** [comment]
However, I don't think `update-ca-trust` is of any use, because that, neither the msys one in `/usr/bin/update-ca-trust` that updates `/etc/pki/ca-trust/extracted` nor the mingw64 one in `/mingw64/bin/update-ca-trust` that updates `/mingw64/etc/pki/ca-trust/extracted`, is not where Git reads the certificates. Instead, the special configuration file in `/c/ProgramData/Git/config` sets `http.sslCAinfo` to `/mingw64/ssl/certs/ca-bundle.crt`.

I couldn't find any script that would manage that, but the bundle is just concatenated certificates anyway.

**Comment by kschoenf** [comment]
I think that's the point. You need the `update-ca-trust` tool (including the p11-kit) to generate such a new `ca-bundle.crt` file if you use a private CA infrastructure, e.g. an own root CA, to add your own CA certificates to this bundle. In the Msys part this works as expected but Git use the `curl` from the mingw* part and so it will rely on the OpenSSL installation and its data files like the `ca-bundle.crt` file from mingw* part. Hmm :-(
Maybe as a solution... is it possible to configure the mingw* OpenSSL installation to use the data files, e.g. `/mingw*/etc/pki/...`, `/mingw64/ssl/...` and `/mingw64/share/pki/...` from the Msys part? E.g. via symbolic links? Currently we have these files in different versions in the Msys and mingw* world and this is really confusing :-( if you have to add your own CA certificates.

**Comment by dscho** [comment]
My attempt to [assist the reporter with actually fixing the problem](https://github.com/git-for-windows/git/issues/878#issuecomment-246099207) failed, so I will close this ticket.
