### ISSUE TITLE
Cancelling installation removes old vrsion aswell

### ISSUE THREAD

**Issue by techtonik** [git-for-windows/git#886]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - 32-bit Vista 6.0.6002

 - What options did you set as part of the installation? Or did you choose the
   defaults?

![image](https://cloud.githubusercontent.com/assets/515889/18540202/d3351e00-7b25-11e6-8af3-dc08402b4667.png)

### Details

When cancelling upgrade from 2.9 to 2.10, I ended without Git at all.

 - What did you expect to occur after running these commands?

Expected old version to be restored.

 - What actually happened instead?

Old version was removed.

**Comment by fourpastmidnight** [comment]
The current installer is an InnoSetup-based installer. When installing a new version of Git for Windows, if it detects a previously installed version, it uninstalls it before installing the new one. I reported a similar issue on #682 where the installer failed to update Git for Windows (due to Visual Studio) which led to me picking up an effort to create an MSI installer. (Of late, I haven't had as much time to work on it, but that will change after this weekend.) Please hold on while the MSI installer is being developed. Until then, please reinstall the old version; your Git settings in your home directory are still there.

Since this is unlikely to be fixed until an option to install via MSI is available, I'm going to close this issue for now. You can follow the progress of the MSI on #682. Thank you for reporting this issue.
