### ISSUE TITLE
[Portable] Maybe link  /tmp to %TMP%

### ISSUE THREAD

**Issue by nulltoken** [git-for-windows/git#89]
Currently the portable version

- can access the global/system config from the current system
- allows accessing local drives (through `/c/`...)
- correctly honors "~"  (eg. `cd ~&& ls`)

However, `/tmp` points to a folder within the portable directory. Could it be possible to rather make it unwrap to `%TMP%`? What would be the potential issues with that approach?

/cc @shiftkey

**Comment by dscho** [comment]
Oh bummer. I really thought I had solved this. @nulltoken could you verify that your `/etc/profile` has its `TMP=` line commented out?

**Comment by nulltoken** [comment]
@dscho 

Below an excerpt of it.

```
#TMP="/tmp"
#TEMP="/tmp"
```

Do you need a full dump of it?

**Comment by dscho** [comment]
No, that is sufficient. But now I'd like to know the output of `env | grep -i tmp` (translated into: is it `/tmp/` or `$TMPDIR`?)...

**Comment by nulltoken** [comment]
```
$ env | grep -i tmp
tmp=C:\Users\Em\AppData\Local\Temp
```

**Comment by nulltoken** [comment]
```
$ echo $tmpdir

```

**Comment by nulltoken** [comment]
```
$ ls $tmp
117A.tmp*
12F2.tmp*
1351.tmp*
1390.tmp*
21D6.tmp*
2283.tmp*
22E2.tmp*
2563.tmp*
25A3.tmp*
4925.tmp*
4AAC.tmp*
4B4A.tmp*
4BC8.tmp*
...
```

```
ls /tmp

```

**Comment by dscho** [comment]
Ah, sorry, I get it now... The `tmp` environment variable is set correctly (Win32 environment is case insensitive if memory serves correctly, so Git won't have any problems with it), but the `/tmp` directory is not a mounted directory.

It is certainly possible to mount it, but I am not quite sure how that would pan out:
- it might be too hard to teach `/etc/fstab` to mount the *user*'s temporary directory, and
- multiple Git installations' temporary directories might interfere when mapped to the *same* directory, and
- it might add another startup cost to the shell (it would have to be done for every shell call, interactive or not, because sometimes users call `git.exe` directly from `cmd.exe` and the call might require a shell script to be executed, and
- Git -- being a Win32 program that has no clue about MSys2's POSIX emulation has no idea of a `/tmp/` directory anyway: it uses the environment variable instead.

So I am not sure that we need to fix anything here, or even that we can... @nulltoken thoughts?

**Comment by shiftkey** [comment]
Yeah, I'm not sure of what the value here is of making `/tmp` point to the `%TEMP%` directory. Perhaps because I'm using this from PowerShell rather than git-bash, but I find myself going straight to '%TEMP%' out of habit.

Sounds like there's a bit of unknowns here around the work involved (and potential impact). Do we consider this urgent to address for v2.3 @nulltoken @dscho?

**Comment by nulltoken** [comment]
Things tend to pile under `/tmp` and I'm not sure how the isolated one will get cleaned up... Not a blocking topic on my side, though.

**Comment by dscho** [comment]
Okay, let's leave it as-is for now, until we encounter something like a "permission denied" in which case I'll have to think about some solution that does not impact shell scripts too badly.

**Comment by dscho** [comment]
@nulltoken do you agree that we can let this ticket take a vacation until the time when we see that `/tmp/` causes something serious such as "permission denied" problems? I would like to close it in that case so I do not get distracted when looking at the issue list...

**Comment by nulltoken** [comment]
@dscho :+1: Every ticket deserves a vacation from time to time :wink:

**Comment by nulltoken** [comment]
@dscho I've installed today the portable 64 bits version at $DAYJOB and eventually hit a "permission denied" while accessing `/tmp`. If you could think of some commands you'd like me to run, I'd be happy to do this on Monday.

**Comment by dscho** [comment]
@nulltoken do you remember what steps triggered the "permission denied"? If so, could you try with a new portable Git (if you have no time to build one with a current `git-extra`, I will try to set aside some time to build one over the weekend)?
