### ISSUE TITLE
pre-commit is not installed by default

### ISSUE THREAD

**Issue by dscho** [git-for-windows/git#9]
When installing SDK 0.4, `/packages/.git/hooks/` does not contain the `pre-commit` hook.

**Comment by sschuberth** [comment]
@dscho Could you please check whether https://github.com/git-for-windows/sdk-packages/pull/36 fixes the rebase use-case?

**Comment by dscho** [comment]
@sschuberth Sorry for lagging so long; I see you verified the fix already!

**Comment by sschuberth** [comment]
To be precise, I did not verify my change, but just re-reviewed it before manually merging it. So it should work ok now when amending / rebasing. Still, this issue is about the pre-commit hook not being installed by default, and that's still the case. I intend to not spend any more time on this and keep it that way as the MSYS- / mgwport-based toolchain is more or less abandoned now in favor of MSYS2 and pacman.
