### ISSUE TITLE
post-install.bat missing

### ISSUE THREAD

**Issue by kingces95** [git-for-windows/git#901]
After installing, `README.portable` references `post-install.bat` which is missing. 

I'm trying to check the portable version into source control and noticed that `rebase.db.i386` is different depending on how I unpack the archive. If I double click from the shell I get one version and and if run `PortableGit-2.10.0-32-bit.7z.exe -y -gm2` I get another. Given that the contents change depending on how I unpack I'm unsure which version I should check in. Can anyone advise?

**Comment by kingces95** [comment]
@bastianeicher I noticed you did some work to ensure that the extraction of the portable zip would be repeatable -- that the contents would be immutable. Given your experience, could tell me why I get different versions of `rebase.db.i386` depending on how I extract the archive and maybe let me know which version I should check in? Hopefully the version I extract from the command line..

**Comment by PhilipOakley** [comment]
----- Original Message ----- 
  From: kingces95 
  After installing, README.portable references post-install.bat which is missing. 

  I'm trying to check the portable version into source control and noticed that rebase.db.i386 is different depending on how I unpack the archive. If I double click from the shell I get one version and and if run PortableGit-2.10.0-32-bit.7z.exe -y -gm2 I get another. Given that the contents change depending on how I unpack I'm unsure which version I should check in. Can anyone advise?

If you use 7zip itself (I go via the 7zip gui for this), you can see the extraction script that the exe uses, so you can see what it does.

IIRC the script is buried in the the wider GfW release script that is on the GfW Github web repos.

Philip

**Comment by dscho** [comment]
> After installing, README.portable references post-install.bat which is missing.

To be precise, [it says:](https://github.com/git-for-windows/build-extra/blob/4e5fff3d0bfb482b08edfd0d3cf5079caf095f4e/portable/root/README.portable#L21-L23):

> *NOTE*: if you decide to unpack the archive using 7-Zip manually, you must
> run the `post-install.bat` script. Git will not run correctly
> otherwise.

In other words: if you run the self-extracting `.exe` as a program (instead of manually extracting the archive using 7-Zip), you have to run the `post-install.bat`.

Corollary: if you *do* run the self-extracting `.exe`, you *do not* have to run the `post-install.bat` (you can't, really, because it will delete itself once run).

> I'm trying to check the portable version into source control

To do that, either accept rebased `.exe` files, or simply do not run the `.exe`, but extract the archive as if it were a `.7z` file (which it is).

> IIRC the script is buried in the the wider GfW release script that is on the GfW Github web repos.

It lives here: https://github.com/git-for-windows/build-extra/blob/4e5fff3d0bfb482b08edfd0d3cf5079caf095f4e/post-install.bat
