### ISSUE TITLE
Double icons - Search mode Windows 8.1

### ISSUE THREAD

**Issue by mraph21** [git-for-windows/git#905]
Hello,

Under windows 8.1, when we search “Git cmd”, we have 2 shortcuts like below 

![image](https://cloud.githubusercontent.com/assets/22635733/19109836/6c09a548-8af7-11e6-8c31-2d27c6669aca.png)

“git cmd” doesn’t work
“Git CMD” works

Same problem with the other 2 shortcuts (green works, the other not)
  
![image](https://cloud.githubusercontent.com/assets/22635733/19109851/79270fcc-8af7-11e6-8bbc-080715ae8d6b.png)

Users launch sometime the wrong shortcut…..

How can we have just 1 shortcut displayed please ?

Thanks a lot

Regards

**Comment by dscho** [comment]
What you see as "double icon" is actually not a shortcut, but a command. It is more obvious in Windows 10's version of the start menu:

![git-cmd-double-icons](https://cloud.githubusercontent.com/assets/127790/19148810/cb278190-8bbe-11e6-888f-0388ad6e8e25.png)

Therefore, it is not quite correct to say that "the other" icon "does nothing". What it does is to open a Windows console, executing `git.exe` therein with the parameter `cmd`, Git then looks for the subcommand "cmd", finding nothing, it reports that error into the console window, and then exits, which unfortunately closes the console and you see nothing (unless you are a *very* fast reader).

A valid workaround may be to install aliases that launch the appropriate `.exe` files. Could you try that? Simply add these lines to your `C:\Program Files\Git\mingw64\etc\gitconfig` (I trust you to adjust the paths as necessary, of course):

```ini
[alias]
        cmd = !\"C:/Program Files/Git/git-cmd.exe\"
        bash = !\"C:/Program Files/Git/git-bash.exe\"
        gui = !\"C:/Program Files/Git/cmd/git-gui.exe\"
```

This will always execute the Bash in a Windows console, and it will also open a console window with `git gui` (because the `git.exe` program *is* a console command), but it would at least work as you expect instead of showing nothing.

Looking forward to your feedback.

**Comment by mraph21** [comment]
Thanks you very much for your explanations, it's interesting.
I applied the workaround, works well.

Many thanks
