### ISSUE TITLE
Procedure entry point CancelSynchronousIo could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by ajstadlin** [git-for-windows/git#906]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup
 - PortableGit-2.10.1-32-bit.7z.exe
AND
 - Git-2.10.1-32-bit.exe

 - Windows Server 2003 R2, Standard Edition, Service Pack 2 - 32bit operating system.
Running as a hyper-v virtual machine in Windows Server 2012 R2 host, Intel Xeon CPU E5-1650.

 - Default Git Portable and regular Git Installation Options

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Was previously running Git 2.9 portable and earlier versions without problems.  I did not try Git 2.10.0 on this machine.  I have been using Git successfully on that machine for several years.

 - What actually happened instead?  Screenshot attached.  There are 3 of these errors.  1 each for "rebase.exe - Entry Point Not Found", "Dash.exe - Entry Point Not Found", and "bash.exe - Entry Point Not Found"

![gib-2101-bug-01](https://cloud.githubusercontent.com/assets/14024430/19121438/818b6d8c-8af4-11e6-94a5-89990c49a3a5.png)

//AJ

**Comment by ajstadlin** [comment]
I just regression tested:  PortableGit-2.10.0-32-bit.7z.exe works OK.

This issue is a new problem specific to PortableGit-2.10.1-32-bit.7z.exe.

**Comment by nalla** [comment]
Here is your root issue https://github.com/Alexpux/MSYS2-packages/issues/687

**Comment by dscho** [comment]
> should we also put this information somewhere?

Yeah. At *least* in the FAQ, I would guess. (I see you already did that.)

> Maybe you rather want to maintain two msys2-runtime packages and release a special back ported XP version?

From https://www.microsoft.com/en-us/cloud-platform/windows-server-2003:

> Windows Server 2003 extended support ended on July 14, 2015

Given that W2k3's end of life already celebrated its first birthday, I am not really willing to put in the time and effort to maintain a second line of MSYS2 runtimes.

Having said that, if any contributor is interested enough to put in the work to start a branch off of our `master` and willing to test future updates to said branch, I would certainly do my part to keep things working for users stuck on no-longer-supported Windows versions.

**Comment by ajstadlin** [comment]
Windows Server 2003 is a legacy platform I have to "keep alive" for legacy software maintenance reasons.  As long as I know that I have reached the highest version I can go with git on that platform, I can deal with it OK - especially since it is a Portable version I am able to use.  If I really need features in future releases of git for my 2003 platforms, I'll just mirror copies of my projects to storage on a modern servers and use git on the mirrors on the modern servers.

As long as this issue is not a bug affecting relatively current platforms, it is OK to close.

Thanks for your great work!
//AJ

**Comment by dscho** [comment]
@ajstadlin please note that I previously had some success at times by copying `msys-2.0.dll` from some older Git for Windows' `usr\bin` into a newer one. It *may* work for v2.10.0 and v2.10.1 (I have no way to test on legacy platforms right now.)

**Comment by Eli-Zaretskii** [comment]
Would it work if I kept the entire usr/bin/ and bin/ directories from an older Git for Windows, and only updated the MinGW-compiled parts?

**Comment by Arnie97** [comment]
@dscho Tested your idea on Windows XP but got no luck :sob: 
Mintty complains that `__locate_ctype_ptr()` could not be located in `msys-2.0.dll`.

**Comment by Eli-Zaretskii** [comment]
Thanks for following-up on my idea.
Mintty is AFAIK an MSYS2 program, so it doesn't come as a surprise that it didn't work.  But just to understand: was that the new Mintty, the one which came with Git for Windows version later than 2.10?  And if so, what if you used the older Mintty instead?

In any case, I don't use Mintty, I use the standard Windows cmd prompt window.  So maybe my idea is workable in that case?  The problem is I couldn't easily test the idea myself, because I couldn't find which parts of the distribution are the MinGW compiled programs and their support files, and which parts are MSYS programs which need the newer msys-2.0.dll.

Thanks again for your followup.  I still hope some day it could be possible to run newer Git on Windows XP.

**Comment by PhilipOakley** [comment]
@Eli-Zaretskii said:

> I still hope some day it could be possible to run newer Git on Windows XP.

I hope so too, but I think it will need those of us who still have XP (no doubt for many and varied reasons) to help together to provide a suitable backward compatibility shim. As @dscho has noted elsewhere (FAQs etc), as maintainer, the main GfW project needed to leave behind the XP compatibility issues (which were based on cygwin's work IIRC) as the Microsoft OS progressed to Win 10 and beyond.

I expect that even coordinating the "XP" compatibility issues would be an ever growing task.

**Comment by Eli-Zaretskii** [comment]
I'm okay with helping with this as much as I can, but for now I was unable to find a way to upgrade beyond v2.10.0 and have a working Git.  One reason is that I don't really understand the differences between the 3 different distribution formats, and cannot find the documentation about that anywhere.  I asked a question about that on the forum, but got no responses.

My attempt to upgrade the MinGW parts of Git by unpacking the .tar.bz2 distribution of Git on top of the 2.10.0 tree, hoping that the MSYS compiled parts will work, was unsuccessful: the result was that Git started in a Mintty, not in the normal cmd window I use here.  Which tells me that some configuration file overwrote my local config, and I couldn't identify that file.  Do you perhaps know where this is recorded?

Once again, I never before used the .tar.bz2 distribution, so I don't know the correct procedure for installing it.  Perhaps someone could point me to some relevant docs or explain how to install .tar.bz2 distro, then maybe I could take it from there.  I still think that this is a promising direction, since most of Git is compiled with MinGW, which still supports XP.

TIA

**Comment by PhilipOakley** [comment]
Hi @Eli-Zaretskii 

> don't really understand the differences between the 3 different distribution formats

I'm not quite sure which three you mean, maybe those on [the releases page](https://github.com/git-for-windows/git/releases/)?

For doing actual work on the GfW with the [Software Developers Kit (SDK)](https://git-for-windows.github.io/#contribute) then download the SDK (you may need to scroll down to find the button depending on your display size), and do have a read of the [technical overview](https://github.com/git-for-windows/git/wiki/Technical-overview). The technical overview is part of the wiki, so do add in or correct any learning points to the various wiki pages (things do change ;-) 

The wiki has additional pages, so use the show more button to extend the side bar. 

The other place to look for the XP stuff is the commits immediately after last XP release (by date, given that there are a number of repos that are part of the GfW build process stack). Its in those commits that the compatibility code will be removed (especially in the upstream stacks).

The one problem is there is no search button for the Wiki (as far as I can tell), so we can't quickly find pages that mention "XP" !

**Comment by Eli-Zaretskii** [comment]
By "the three" I meant the .tar.bz2, the MinGit, and the PortableGit, and also the differences between those and the .exe installer.  What is the purpose of each one, and how each one of these should be installed when one upgrades to a newer version?

Thanks for the pointers, but the answer to the above questions doesn't seem to be there.

As for the XP-incompatible stuff: AFAIK it is in the MSYS2 DLL, which took it from the upstream Cygwin DLL.  I'm not aware of any changes in the MinGW-compiled parts of GfW that would make those parts refuse to run on XP.  Maybe I'm wrong, I don't know.  I will know for sure if and when I succeed to update the MinGW parts of GfW leaving the MSYS2 parts intact at their Git 2.10.0 versions, and then try to use the result.  For now, I failed to get to that point, probably due to lack of knowledge both on GfW packaging and Git internals (configuration files etc.).

**Comment by PhilipOakley** [comment]
> one problem is there is no search button for the Wiki (as far as I can tell)

I was wrong. It (the search box) is just to the right of the Github logo in the top left banner line. There is the word 'search' in a very soft grey font.

The use of soft grey fonts is one of the significant failings of modern 'design' for those without perfect teenage eyes ;-)

**Comment by PhilipOakley** [comment]
> By "the three" I meant the .tar.bz2, the MinGit, and the PortableGit, and also the differences between those and the .exe installer.

The distinction is not quite the one suggested. There is the .exe vs .tar.bz distinction, which is between formats, and then there is the distinction between the three products (MinGit, Portable Git, and installed Git) and then there is the SDK.

Below is a general statement of how I see it.

The distribution formats are:

1. The .exe is a self extracting 'zip' archive of the .7z variety ([see wiki](https://github.com/git-for-windows/git/wiki/Zip-Archives---extracting-the-released-archives) )

2. The .tar.bz2 is a zipped archive that needs a reader to unpack the .bz2 and .tar formats to extract the _same data_ (I believe).

The User 'products' are (possibly in reverse order):

1. [MinGit](https://github.com/git-for-windows/git/wiki/MinGit) : is an intentionally minimal, non-interactive distribution of Git for Windows, with third-party applications as its intended audience. 

2. Portable Git is a full set of all the files needed to run Git portably (needs a wiki description page ;- but [see Making-a-portable-Git](https://github.com/git-for-windows/git/wiki/Making-a-portable-Git))

3. Regular installed Git : the interactive [Git for Windows](https://git-for-windows.github.io/) installed in the usual Windows way, with menu icons, alternate terminal windows (mintty), etc.

The Developer / Contributor product is the Software development kit (SDK) see '[how to participate](https://github.com/git-for-windows/git/wiki/How-to-participate)'.

1. The [SDK installer](https://github.com/git-for-windows/build-extra/releases/latest) provides (will fetch) the source code, documentation, compilers, etc. During install this will do the first compile of you personal local version of Git setting you up to delve into the parts that suit your capability.

**Comment by Eli-Zaretskii** [comment]
Thanks, that's useful info.

I still feel that I'm missing something, since as I wrote earlier, unpacking the .tar.bz2 tarball of a newer GfW, excluding the MSYS2 parts, seemed to overwrite some of my configuration, because the updated Git came up in Mintty, whereas the previous version used the Windows cmd window.  When I install from the .exe installer, my configuration and all the options I've chosen during previous installations are preserved.  Do you know where are those options recorded?  I mean the selections I make during installation on the few dialogs I'm shown where I select whether to use Git from Git Bash, how to handle the CR-LF EOLs, etc.

**Comment by PhilipOakley** [comment]
I've updated the entry. As you note the .tar.bz2 tarball is simply everything (as far as I understand), without using the installer which is run by the exe.

I can't remember where the options are stored, but I have seen them mentioned in reply to other issues, so a bit of searching may help there.

**Comment by PhilipOakley** [comment]
(doh, from the Issues template): The install options are found via:
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
```

**Comment by Eli-Zaretskii** [comment]
Great, thanks.  Found it.
Will try to do that upgrade dance again when I have time.
