### ISSUE TITLE
Git status says that there are no changes after file rename

### ISSUE THREAD

**Issue by astro75** [git-for-windows/git#939]
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Path Option: Cmd
Plink Path: d:\putty\plink.exe
SSH Option: Plink
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Tried Bash and GitExtensions GUI

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
```
echo "1" > A.txt
echo "2" > B.txt
git init .
git add *
git commit -m First
rm A.txt
rm B.txt
git reset --hard
mv A.txt C.txt
mv B.txt A.txt
mv C.txt B.txt
git status
```

 - What did you expect to occur after running these commands?

 See file modifications

 - What actually happened instead?

 Git shows no modifications

**Comment by dscho** [comment]
This is an unfortunate shortcoming of Git for Windows: if the file times have not changed (renaming files does not change the times), and if the file sizes have not changed (both of your files have the *exact* same size), a change is not detected.

The way non-Windows Git detects those renames is by inspecting the so-called "inode". There *is* an equivalent on Windows, but emulating the inodes would slow down Git *dramatically*. We are talking about orders of magnitudes slower.

So we weighed the performance penalty versus detecting the case where a tracked file was replaced by renaming a file with *the exact same file modification time* and *the exact same size* (i.e. with no other changes than that rename), and performance was just more important than that rare case, in particular since that rare case is usually detected very easily and quickly by the user.

Workaround: `touch A.txt B.txt && git status`.

**Comment by PhilipOakley** [comment]
Maybe a documentation patch for the git extra might be an option that notes this condition and workaround, though deciding _where_ the note should be added could be an issue.

 @astro75 - was there a particular man page you looked at (that should there for contain a GfW note) when you first hit the problem? - Would the `git help status` stages be the right place for a simple note?

**Comment by astro75** [comment]
When I hit the problem I searched for answers with google. I did not look at the man pages for this problem so I can't recommend where to put that.

We use Unity game engine and there are many file changes at once so it is not easily detected by the user in our case. Luckily Unity has callbacks for asset file renaming. We can just update file modification time automatically once that happens.

**Comment by dscho** [comment]
> We can just update file modification time automatically once that happens.

Great!
