### ISSUE TITLE
Explorer integration gives: application not found

### ISSUE THREAD

**Issue by abergmeier-dsfishlabs** [git-for-windows/git#957]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.2.windows.1.895.g8126884
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.3.9600]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things?

This seems to happen to multiple people. See http://www.hoverdroids.com/errors/git/git-gui-here-and-git-bash-here-doesnt-work-resolved/
Am not willing to potentially cripple my registry though.

### Details

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Right click on explorer - `Git Bash Here`

 - What did you expect to occur after running these commands?

 Git bash should open

 - What actually happened instead?

An explorer error message: `application not found`

Would expect the uninstaller for _2.10.1_ not cleaning up properly.

**Comment by abergmeier-dsfishlabs** [comment]
Seems to be for some reason starting with _2.10.2_ Git gets installed in `C:\Program Files\Git` again instead of `C:\Users\<user>` again.

**Comment by fourpastmidnight** [comment]
When performing a standard installation of Git for Windows, it's installed to `C:\Program Files\Git`. If you don't have appropriate permissions on your machine, you may not be able to elevate your credentials with the required Administrator permissions (via UAC), and so Git for Windows will install per-user, in `C:\Users`. Either way, the Windows Explorer context menu item should work. 

So now I'm left wondering what series of events actually took place on your machine. For example, did you install the previous version with elevated permissions, and then upgrade using a non-elevated, per-user install? In this scenario, since the upgrade was run unelevated, its possible the previous installation of the context menu item could not be uninstalled during upgrade because it lives in an area of the registry that requires Administrator access to write/delete from.

Where is your ` install-options.txt` located (or, what command did you run to display its contents for this issue)? Was it working before? Did you recently upgrade? Do you have Admin permissions on the machine on which you installed Git For Windows?

**Comment by abergmeier-dsfishlabs** [comment]
_Personally I would prefer to have it installed to `C:\Users` because there are surprisingly lots of tools out there that still do not handle spaces in paths correctly._

So I installed 2.10.1 before (installed "over" a previous Git version). I do not remember doing anything special. AFAIR _Git_ began installing into `Users` a few versions back. Remember that this also broke quite a few apps back then.
Then yesterday I uninstalled 2.10.1 and installed 2.10.2 (getting the elevated rights dialog). I guess that is why it was using the default `C:\Program Files\` because it no longer found the previous installation location.

I think I ran all installations with elevated rights. That being said to me it sounds like a installer bug that it does not fail if it cannot update the Context entries.

But even if - that should only be a problem if the uninstall did not clean up properly, right?

> Where is your install-options.txt located (or, what command did you run to display its contents for this issue)?

`install-options.txt` is located in `C:\Program Files\Git\etc\install-options.txt`.

> Was it working before?

Before uninstalling and installing 2.10.2? Yes.

> Did you recently upgrade?

Upgrade what from what exactly?

> Do you have Admin permissions on the machine on which you installed Git For Windows?

Yes

**Comment by dscho** [comment]
I cannot reproduce the "application not found" problem.

What do your registry entries `HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Directory\shell\git_shell` and `HKEY_CURRENT_USER\SOFTWARE\Classes\Directory\shell\git_shell` contain?

**Comment by abergmeier-dsfishlabs** [comment]
@dscho All of them contained the old paths under `C:\Users\`. Changed them manually to `C:\Program Files` now.

**Comment by dscho** [comment]
@abergmeier-dsfishlabs it looks as if the uninstaller is stupid and takes the *current* user as indicator which registry keys to delete. And apparently your most recent upgrade was run elevated, so it probably tried to remove the `HKEY_LOCAL_MACHINE` entries rather than the `HKEY_CURRENT_USER` ones.

This is only a guess, though, as it is not clear to me from your response which keys you found, and what they contained exactly, and how you changed them.

In any case, it seems that you fixed your problem (although there is no explicit "yay, it works now", either).

**Comment by abergmeier-dsfishlabs** [comment]
@dscho And is there any way of making the uninstaller more intelligent. Or at least check at the end whether there are dangling shell values that lead to nowhere?

**Comment by dscho** [comment]
@abergmeier-dsfishlabs the installer can learn all kinds of new tricks. But I do not have enough information to act. For now, all I know is that the installer installs the registry keys correctly in my hands.

**Comment by abergmeier-dsfishlabs** [comment]
@dscho 

> But I do not have enough information to act.

And I do not seem to provide enough information for you to really understand/analyze the problem. So lets perhaps rather try to narrow it down by teaching the uninstaller to at least issue an error if after uninstalling there are still shell registry entries which are not backed by a existing binary. This way people in the future might be able to tell where something went wrong.

**Comment by dscho** [comment]
@abergmeier-dsfishlabs rather than issuing an error when such a registry entry exists, it would be better to simply remove it. But from my reading, that is exactly [what the code does](https://github.com/git-for-windows/build-extra/blob/0f9136b497b1dbe1a1058637054e08d0a3232935/installer/install.iss#L384-L413).

More eyes welcome, of course.

**Comment by fourpastmidnight** [comment]
@dscho 

> ...it looks as if the uninstaller is stupid...

I don't think that's true at all. In fact, I would totally expect this behavior if installing/uninstalling using different methods (e.g. Admin vs. non-Admin (un)install). There are two morals to this story:

1. Always (un)install Git for Windows elevated or non-elevated, but never a mixture of the two.
2. Installers shouldn't implement both per-user and per-machine installs
.   - Granted, this is sub-par for the Git for Windows audience, so we're left with number 1.

Perhaps the best course of action would be to be able to detect the method of installation used on an existing installation during upgrade and take appropriate action:

1. If the previous installation is per-machine, and the upgrade installation will be per-user, error: You need Administrative rights to uninstall the previous installation of Git for Windows.
2. If the previous installation was per-user and the upgrade wil be per-machine: Proceed, but the installer must remove the previous installation from the per-user locations.

All other scenarios are already covered.
