### ISSUE TITLE
Static Download URLs

### ISSUE THREAD

**Issue by if-kenn** [git-for-windows/git#962]
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I am wanting to be able to script a download of the latest stable release of Git for Windows and not tie it to a specific version.

Are there static URLs so you don't have to use URL that use the version number like:

https://github.com/git-for-windows/git/releases/download/v2.10.2.windows.1/Git-2.10.2-64-bit.exe

Possibly along the lines of:

https://github.com/git-for-windows/git/releases/download/latest/Git-latest-64-bit.exe

Thanks

**Comment by dscho** [comment]
You could help.

I already have a script that updates the version number on the home page automatically: https://github.com/git-for-windows/git-for-windows.github.io/blob/master/bump-version.js

You could easily teach it to update a static file that contains the correct link.

OTOH you could also direct your script to https://git-scm.com/download/win and parse out the correct download URL.

**Comment by OverlordQ** [comment]
Yeah, if you're scripting it, it's already pretty available using the GitHub API.

    curl -u username:pw https://api.github.com/repos/git-for-windows/git/releases/latest  | jq '[.assets[] | {key: .name, value: .browser_download_url}] | from_entries'

```
{
  "Git-2.10.2-32-bit.exe": "https://github.com/git-for-windows/git/releases/download/v2.10.2.windows.1/Git-2.10.2-32-bit.exe",
  "Git-2.10.2-32-bit.tar.bz2": "https://github.com/git-for-windows/git/releases/download/v2.10.2.windows.1/Git-2.10.2-32-bit.tar.bz2",
  "Git-2.10.2-64-bit.exe": "https://github.com/git-for-windows/git/releases/download/v2.10.2.windows.1/Git-2.10.2-64-bit.exe",
  "Git-2.10.2-64-bit.tar.bz2": "https://github.com/git-for-windows/git/releases/download/v2.10.2.windows.1/Git-2.10.2-64-bit.tar.bz2",
  "MinGit-2.10.2-32-bit.zip": "https://github.com/git-for-windows/git/releases/download/v2.10.2.windows.1/MinGit-2.10.2-32-bit.zip",
  "MinGit-2.10.2-64-bit.zip": "https://github.com/git-for-windows/git/releases/download/v2.10.2.windows.1/MinGit-2.10.2-64-bit.zip",
  "PortableGit-2.10.2-32-bit.7z.exe": "https://github.com/git-for-windows/git/releases/download/v2.10.2.windows.1/PortableGit-2.10.2-32-bit.7z.exe",
  "PortableGit-2.10.2-64-bit.7z.exe": "https://github.com/git-for-windows/git/releases/download/v2.10.2.windows.1/PortableGit-2.10.2-64-bit.7z.exe"
}
```

**Comment by if-kenn** [comment]
Well, the problem with that is while I am scripting, I am intending to use the bash shell included with Git for most of my logic so it become a bootstrap issue for fresh systems. I will be shortly making a pull request that will make the following files:

```
static/Git-latest-32-bit.exe.txt
static/Git-latest-32-bit.tar.bz2.txt
static/Git-latest-64-bit.exe.txt
static/Git-latest-64-bit.tar.bz2.txt
static/MinGit-latest-32-bit.zip.txt
static/MinGit-latest-64-bit.zip.txt
static/PortableGit-latest-32-bit.7z.exe.txt
static/PortableGit-latest-64-bit.7z.exe.txt
```

**Comment by if-kenn** [comment]
Pull Request:

https://github.com/git-for-windows/git-for-windows.github.io/pull/12

**Comment by if-kenn** [comment]
I am a little surprised by the tone of the response here https://github.com/git-for-windows/git-for-windows.github.io/pull/12#issuecomment-261586440

Maybe I misunderstood the "help wanted" label in that you were looking for community help instead of me asking for help. In the spirit of the open source community, I thought I would do something that could benefit others who find themselves having to bootstrap before they have Bash that is provided from Git for Windows. I could of easily misinterpreted the spirit and this might not of been the intention. Either way, I will take the time to address the points raised, but might not waste my time standardizing something that is not wanted.

1. In doing my work, I wanted to make sure that it did not break any previous functionality, so I tested it with both:
`node bump-version.js 2.10.2 "Wed, 02 Nov 2016 19:43:32 UTC" https://github.com/git-for-windows/git/releases/tag/v2.10.2.windows.1`
and
`node bump-version.js --auto`
The explicit call worked, while the --auto one did not on node 6.9.1, screenshot attached.
<img width="555" alt="screen shot 2016-11-18 at 9 25 27 am" src="https://cloud.githubusercontent.com/assets/5553161/20442983/c48009e2-ad7f-11e6-8d60-99cd82259fe9.png">

2. Best practices of dealing with JSON highly discourage regex parsing since it is so fraught with edge cases. Since this is being done via node which has native JSON parsing it is even more surprising. Since it is broken for me, I cannot state which is faster, but doing a timing showed that the one that works is 0.1 seconds slower than the one that is broken and did not have a chance to complete, screenshot attached. If performance is the desired result (for a very light weight build script?), then it is further confusing why the original would https://api.github.com/repos/git-for-windows/git/releases and not https://api.github.com/repos/git-for-windows/git/releases/latest since currently it is 22 times the size.
<img width="522" alt="screen shot 2016-11-18 at 10 07 18 am" src="https://cloud.githubusercontent.com/assets/5553161/20443002/d4d00220-ad7f-11e6-9a0f-3a7262788645.png">

3. Apologies for not using camel case in the var name, that was an oversight on my part and can be easily changed. As for the "new parameter", I have looked for Git for Windows version convention did not easily find anything. The original code actually does not clarify what it is, but addresses it as "match[3]". I only see it being used in things such as 2.11.0-rc0.windows.1 vs v2.11.0-rc0.windows.2 which in theory shouldn't be even used for the release page. If the intention is to explicitly state things, then the usage section is missing the --auto ability.

4. Yes, you are right this does increase the script by 30%, what is most valued; performance, best practices, script size, readability? The change of the mode was by accident when creating a new file, that is not intended and can be easily addressed.

5. The change of the extension .txt to .url is very easy to change, but again would not follow standard practices since technically it is not a .url file and implementing that would need much more information and defeat the intention of the static file. An example can be seen here: http://www.lyberty.com/encyc/articles/tech/dot_url_format_-_an_unofficial_guide.html

6. Assuming the file names is a good one and should be fixed, I have not dug into the depths of the GitHub API and am a bit of a neophyte. This could be improved but would then be at odds with the concern of the script size.

7. If I decide to resubmit this, then I will make a note in the commit as I did on the issue.

8. In the initial issue, it was not stated if you wanted this to be submitted via a pull request or not so that is the method I used. I have not used a force-push in the past so it is something new to me, again if I resubmit this then I will try to follow this advice.

In light of the bar of entry that has been put forth, at this point I am feeling like my time would be better spent just writing a bootstrap kludge for my own project instead of trying to help anyone else out there that might be in the boat.

**Comment by dscho** [comment]
> I am a little surprised by the tone of the response here

I am sorry if I offended you.

> Maybe I misunderstood the "help wanted" label in that you were looking for community help instead of me asking for help.

But we are in this together, right? I am reviewing changes in order for the end result to become as good as we can make it. And I think that the PR is a good start, and after addressing my concerns it will be even better.

> node bump-version.js --auto
> The explicit call worked, while the --auto one did not on node 6.9.1, screenshot attached.

Whoa. That's a bug. And since you fixed that bug, there should be at least one commit message talking about this. That is important lest anybody revert a change without knowing what it fixed.

> Best practices of dealing with JSON highly discourage regex parsing since it is so fraught with edge cases.

I agree. And to make it easy to review, that change needs to be in its own commit, with its own explanation (another best practice).

> it is further confusing why the original would https://api.github.com/repos/git-for-windows/git/releases and not https://api.github.com/repos/git-for-windows/git/releases/latest since currently it is 22 times the size.

Oh. I did not even realize that this was the case, let alone that the PR fixes this.

Yes, this is a good change. But my missing it is a very, very strong indicator that a separate commit with a beautiful commit message explaining the issue would have helped tremendously. I would really like to see that come about before merging the PR.

> Apologies for not using camel case in the var name

My apologies for not making clear that apologies are not required. My comment simply tries to encourage consistency, as it is much easier on the eyes of anybody looking at the code when the code style is uniform and does not distract from the actual logic.

> As for the "new parameter", I have looked for Git for Windows version convention did not easily find anything.

This PR being about the home page of Git for Windows, and furthermore using Javascript (which Git's source code does not use), there is no documentation as to the convention apart from the code itself. The existing function name already uses camelCase, so I would strongly prefer the new parameter to use the same style, and the existing parameters use full words as explanation, not half-words, so I would also like to stay with that convention.

> The change of the extension .txt to .url is very easy to change, but again would not follow standard practices since technically it is not a .url file and implementing that would need much more information and defeat the intention of the static file.

That standard practice is not what I saw in the wild. My suggestion was based on encountering `.url` files before that simply contained a single URL.

> I have not used a force-push in the past so it is something new to me, again if I resubmit this then I will try to follow this advice.

Updating PRs by force-pushing is the recommended practice (it is even written at the bottom of every PR when viewed by a user who can push to the associated branch).

> In light of the bar of entry that has been put forth, at this point I am feeling like my time would be better spent just writing a bootstrap kludge for my own project instead of trying to help anyone else out there that might be in the boat.

Since you are talking about a different bootstrap solution: personally, I would simply write a Powershell script. Powershell is available on all current Windows versions (i.e. Windows Vista and later), and it has really beautiful functions to interact with REST APIs as well as parsing JSON into proper objects. I recently implemented a Powershell script myself to access a different REST API, based on the advice given here: http://stackoverflow.com/questions/3574723/call-rest-api-from-powershell-script#13261170

And please do not take this as saying that the PR is bad and should be abandoned. I will gladly take it once all concerns are addressed (and I do not necessarily mean that you do everything exactly the way I suggested; you can convince me with good arguments, I am always eager to learn).

**Comment by if-kenn** [comment]
Thank you for the thoughtful response. I am still a bit confused by how to do update the PR by force-pushing. Can you direct me to somewhere that describes it? My Googling has found some stuff, but I want to understand it more in the abstract so I don't start using it wrong.

**Comment by dscho** [comment]
> I am still a bit confused by how to update the PR by force-pushing. Can you direct me to somewhere that describes it?

@if-kenn once upon a time, in a previous Open Source project I was maintaining, I wrote [this article](https://github.com/maven-nar/nar-maven-plugin/wiki/How-to-contribute#incorporating-fixes-into-the-pull-request-ie-rewriting-the-topic-branch) about it, hopefully it is clear enough?

**Comment by sxlijin** [comment]
@if-kenn GitHub PRs always reference the current state of the branch pointers they are merging, so if you force-push to a branch, that automatically updates the PR (with a slight delay for back-end DB updates)

**Comment by dscho** [comment]
Let's move the discussion to https://github.com/git-for-windows/git-for-windows.github.io/pull/12 which will be reopened as soon as there is discussion/progress again.
