### ISSUE TITLE
Differentiate between git and portablegit

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#99]
I can't file issues against the website so I'm filing this here.

It's not obvious to me looking on the website what the difference is between ```Git-2.3.5.8-dev-preview-64-bit.exe``` and ```PortableGit-2.3.5.8-dev-preview-64-bit.7z.exe``` from the downloads page.

I think it should be clear on the website so users know which one to download.

**Comment by nalla** [comment]
Can you provide information on *what* exactly do you have in mind? Like a text for each download *or* another naming of the files?

**Comment by kjeremy** [comment]
If I knew what the difference was between the two files I would tell you :)

**Comment by nalla** [comment]
But you *know* the meaning of the word "portable"?

**Comment by kjeremy** [comment]
Sure: you can carry it around or perhaps it can be used in multiple
situations or architectures (though the filename suggests that it's
architecture dependent).  I'm saying the use of the word portable alone
isn't enough to figure out which version a user would want to download.

**Comment by nalla** [comment]
What about `Git-2.3.5.8-dev-preview-64-bit-setup.exe` and `PortableGit-2.3.5.8-dev-preview-64-bit-portable.exe` which would eventually result in `Git-2.3.5.8-64-bit-setup.exe` and `Git-2.3.5.8-64-bit-portable.exe`. @dscho what do you think?

**Comment by kjeremy** [comment]
I think you just need to state somewhere what the difference between the
files are. IE why would I want to download one over the other?

**Comment by dscho** [comment]
We probably just need to link to http://en.wikipedia.org/wiki/Portable_application, most likely in the bottom part of each and every release.

@kjeremy please note, though, that it is still just a developers' preview, i.e. a preview for power users who are likely to fix bugs and open PRs. In your case, a PR would have been appreciated, and since you did not know what a portable application is, you could have just Googled.

**Comment by dscho** [comment]
So I will leave this open, as a low-priority ticket, because it is not clear what to do exactly (or if anything really needs to be done at all; users seemed to find the Git for Windows 1.x installers alright, even if there was the choice between Git-*, PortableGit-*, msysGit-net-* and msysGit-full-* files).

**Comment by kjeremy** [comment]
Ahhh that's the definition of 'portable' you were using.  I was assuming it was more of a 'portable across platforms'.  The term 'portable' means many different things.  Typically on windows you can choose at install time whether a program is for all users or the current one.  I wonder if that would be possible further on down the road.

I think the big reason people find the correct 1.x installers is because there's one installer that pops up on git-scm.com.

I'll try to come up with some wording for the site that makes this distinction clear.  Thanks for clarifying.

**Comment by dscho** [comment]
> The term 'portable' means many different things.

Yeah, but the combination of "portable" and an `.exe` extension kind of gives it away that this is a Windows installer ;-)

> Typically on windows you can choose at install time whether a program is for all users or the current one. I wonder if that would be possible further on down the road.

It sure is possible... it just will require a person driving the project. Like... maybe... you? :smile_cat: 

> I think the big reason people find the correct 1.x installers is because there's one installer that pops up on git-scm.com

And that won't change, except that we'll have to put in a PR that switches them over to the Git for Windows 2.x line (I am already in contact with the GitHub for Windows people, so if I run into a road block I am sure I'll get help) and make sure that it detects whether it should go for the 64-bit or the 32-bit version. Most likely we will have to touch [this](https://github.com/git/git-scm.com/blob/master/app/assets/javascripts/site.js#L40-L48) and [that](https://github.com/git/git-scm.com/blob/0e8dfa92ca1d0b47e6b66adecc0c149f191c97d5/app/controllers/downloads_controller.rb#L29-L32) code. Help very welcome (I am no Rubist, and it will show if I have to take care of that).

**Comment by nalla** [comment]
@dscho I adressed this issue by some changes to the `git-scm.com` website https://github.com/git/git-scm.com/compare/master...nalla:git-for-windows-url.

Those changes could easily be adjusted so that the releases are parsed for portables too and saved into the database by postfixing the platform string. E.g. `windows32portable` Then a new portable section on the download page could be added to offer the portable release right off the `git-scm.com` website.

Before going any further and before opening a PR on the *git-scm.com* website, I'd appreciate some feedback.

**Comment by dscho** [comment]
@nalla wow, this is excellent! With that change, we probably do not have to worry about portable vs non-portable anymore because most users download from `git-scm.com` anyway.

**Comment by nalla** [comment]
https://github.com/git/git-scm.com/pull/535

**Comment by nalla** [comment]
I *think* this can be closed.

**Comment by dscho** [comment]
Yeah, I agree, the issue did move to https://github.com/git/git-scm.com/pull/535. Thanks!
