### ISSUE TITLE
Changing file length limit when cloning

### ISSUE THREAD

**Issue by alexanderwhatley** [git-for-windows/git#999]
See http://stackoverflow.com/questions/41177019/trying-to-set-file-name-length-limit-with-git-permission-denied/41177526#41177526. Essentially, I believe that there should be a more intuitive error message given when git config is trying to set a system wide command.

**Comment by PhilipOakley** [comment]
It is advantageous to fully populate the issue template, and in this case add in any UAC status. 

Do say what you were trying to do and why the particular cammand sequence was chosen (compared to others)

Having to go to even such an august site as SO still takes time and effort.

> I am trying to clone a GitHub repository containing files with long path names, and I am trying to get around Git's file length restriction using the command

`git config --system core.longpaths true`

```
error: could not lock config file C:\Program Files\Git\mingw64/etc/gitconfig: Permission denied
error: could not lock config file C:\Program Files\Git\mingw64/etc/gitconfig: Invalid argument
```

The error is low level, so deciding programatically, what the 'friendly' message should be is a problem.

Do you have UAC access there.
What UAC access did you have during install of Git.
Any reason why you particularly need --system rather than --global.

what other tools do you have running that could also have access to the gitconfig file (and other versions of Git from other providers) - Windows has different access semantics to Unix/Linux.

**Comment by dscho** [comment]
The title of this bug report is very misleading.

> It is advantageous to fully populate the issue template, and in this case add in any UAC status.

Indeed.

> See http://stackoverflow.com/questions/41177019/trying-to-set-file-name-length-limit-with-git-permission-denied/41177526#41177526. 

Please note that I do not appreciate being sent to a random website to figure out whatever you might want me to do. Not one bit. It shows how little you think my time is worth, and I am tempted to mirror that.

As to the `--system` flag: it affects the installation and is not per-user, therefore requires administrator's privileges.

The error message could be more friendly, and if this report would have been, too, I would have tried to find some time to make it, too, instead of spending the same time on collecting the necessary information.

Instead I will point to the code location that would need to be improved, and punt this squarely back into the original reporter's court: https://github.com/git-for-windows/git/blob/v2.11.1.windows-prerelease.1/builtin/config.c#L623-L627
